### ISSUE TITLE
MessageFormat plug-in and pre-compiled messages

### ISSUE THREAD

**Issue by glen-84** [ngneat/transloco#102]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

Please clarify whether or not the MessageFormat plug-in supports build-time compilation of messages / reading from pre-compiled messages (functions).

The [messageformat documentation](https://messageformat.github.io/messageformat/page-build) recommends using messageformat as a compile-time tool, to avoid having to download the compiler to the client and compile messages at run-time. It also solves a potential CSP issue.

Is there any way to use pre-compiled messages with this library?

**Comment by itayod** [comment]
Hi @glen-84,

The plugin we provide does not support build-time since most of the time the transpilation of the message includes variables that we need to resolve, that could happen only during runtime.

example:
```
{
  "message": "Can replace {{value}} and also give parse messageformat: The {gender, select, male {boy won his} female {girl won her} other {person won their}} race - english",
}
```

```html
      <span>{{ t.message | translocoParams: { value: dynamic } }}</span>
```


Therefore it doesn't make sense for our case to support precompilation for message format.

**Comment by glen-84** [comment]
@itayod,

I'm referring to pre-compilation from ICU message to JS function, not to the resulting string.

Example:

greeting: `Hello {name}` -> `function greeting(name) { return ``Hello ${name}``; }`

(the above is just an example, it doesn't look exactly like that)

**Comment by fxck** [comment]
https://github.com/ngneat/transloco/issues/47#issuecomment-525872345

**Comment by itayod** [comment]
Hi @glen-84.

I see what you meant here, but unfortunately, we are currently not going to support that soon.
