### ISSUE TITLE
Empty keys are rendering the key instead of the empty value

### ISSUE THREAD

**Issue by shakedSetoo** [ngneat/transloco#103]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Key with empty value is not rendered empty but displays its key instead of the empty value.
If I have an empty value for specific key
{
"KEY": ""
}
then in the displayed component the text on the element will be KEY and not ""

## Expected behavior
Empty values should be rendered empty

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, for that you could use our [stackblitz example](https://stackblitz.com/edit/transloco-example)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by shaharkazaz** [comment]
You need to pass config the following option:

```js
missingHandler: {
 allowEmpty: true
}
```

**Comment by shakedSetoo** [comment]
@shaharkazaz Its not working...

I have a key "LANDING_PAGE.BUY_NOW_BTN2" and its value is empty in my french translation file.

the key is rendered to the view and not the empty string...

too bad...

**Comment by shaharkazaz** [comment]
Can you create a reproduction in stackblitz?

**Comment by artuska** [comment]
+1 for this issue
