### ISSUE TITLE
Library and SharedModule that both uses Transloco

### ISSUE THREAD

**Issue by Kzamikaze** [ngneat/transloco#104]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X] Support request
[ ] Other... Please describe:
</code></pre>

This issue may have been brought up in the past but i have not a found a true solution.
I am trying to use Transloco in a library and a SharedModule that are both used by my main application.

The library's TRANSLOCO_LOADER uses translations files from its assets so that it can be used in other projects:
<pre><code>
const en = require("../i18n/en.json");
export class i18nLibraryLoader implements TranslocoLoader {
  constructor() {}

  getTranslation(): Promise<Translation> {
    return new Promise((res, err) => {
      res(en);
    });
  }
}</pre></code>

Library module:
<pre><code>
@NgModule({
  imports: [
 ...
TranslocoModule,
...
 ],
providers: [
    {
      provide: TRANSLOCO_LOADER,
      useClass: i18nLibraryLoader
    }
  ]
})
export class LibraryModule {}
</pre></code>

My SharedModule uses an HttpClient and do more configuration for Transloco:
<pre><code>
export class HttpLoader implements TranslocoLoader {
  constructor(private http: HttpClient) {}

  getTranslation(langPath: string): Observable<HashMap<Translation>> {
    return this.http.get<Translation>(
      `shared/assets/i18n/${langPath}.json`
    );
  }
}

export class ApplicationMissingTranslationHandler
  implements TranslocoMissingHandler {
  handle(key: string, params: HashMap, config: TranslocoConfig): string {
    return "Missing translation for " + key;
  }
}

export class CustomFallbackStrategy implements TranslocoFallbackStrategy {
  getNextLangs(failedLang: string): string[] {
    return ["en"];
  }
}

export function preloadUser(transloco: TranslocoService): Function {
  return function(): Promise<HashMap<any>> {
    let language = localStorage.getItem("language");
    if (language) transloco.setActiveLang(language);
    else {
      language = getBrowserLang();
      transloco.setActiveLang(language);
      localStorage.setItem("language", language);
    }
    return transloco.load(language).toPromise();
  };
}
</pre></code>
SharedModule:
<pre><code>
@NgModule({
  imports: [
    ...
    TranslocoModule,
    ...
  ],  
  providers: [
    {
      provide: APP_INITIALIZER,
      multi: true,
      useFactory: preloadUser,
      deps: [TranslocoService]
    },
    {
      provide: TRANSLOCO_CONFIG,
      useValue: {
        prodMode: environment.production,
        listenToLangChange: true,
        defaultLang: "en"
      }
    },
    {
      provide: TRANSLOCO_LOADER,
      useClass: HttpLoader,
      deps: [HttpClient]
    },
    {
      provide: TRANSLOCO_MISSING_HANDLER,
      useClass: ApplicationMissingTranslationHandler
    },
    {
      provide: TRANSLOCO_FALLBACK_STRATEGY,
      useClass: CustomFallbackStrategy
    },
  ]
})
export class SharedModule {}
</pre></code>

Finally my main application Module :
<pre><code>
@NgModule({
  imports: [
    ...
    SharedModule,
    LibraryModule,
    ...
  ],
 exports: [
  ...
  TranslocoModule,
  ...
]
})
export class AppModule
</pre></code>

Compilation goes well but when my app initialize, only the Library TRANSLOCO_LOADER  gets used.
The other providers like APP_INITIALIZER/TRANSLOCO_CONFIG/TRANSLOCO_MISSING_HANDLER/TRANSLOCO_FALLBACK_STRATEGY from the SharedModule gets used but not TRANSLOCO_LOADER from the SharedModule.

The result is only my library's components are translated. All other translations are caught by the TRANSLOCO_MISSING_HANDLER.

I could move the SharedModule service to my main application but that SharedModule is used by multiple other applications and that would mean duplicating the code to all the other applications and i would rather avoid that.

I am looking for a way to isolate the TranslocoService form the Library and the one from the SharedModule, ideally with a way to propagate language change events from one service to the other.

Please let me know if you need more context/code.

**Comment by itayod** [comment]
Hi @Kzamikaze,

In your case,  I would recommend you to use `TRANSLOCO_LOADER` only once in your `SHARED_MODULES`.

SharedModule stays the same:

```ts

@NgModule({
  imports: [
    ...
    TranslocoModule,
    ...
  ],  
  providers: [
    {
      provide: APP_INITIALIZER,
      multi: true,
      useFactory: preloadUser,
      deps: [TranslocoService]
    },
    {
      provide: TRANSLOCO_CONFIG,
      useValue: {
        prodMode: environment.production,
        listenToLangChange: true,
        defaultLang: "en"
      }
    },
    {
      provide: TRANSLOCO_LOADER,
      useClass: HttpLoader,
      deps: [HttpClient]
    },
    {
      provide: TRANSLOCO_MISSING_HANDLER,
      useClass: ApplicationMissingTranslationHandler
    },
    {
      provide: TRANSLOCO_FALLBACK_STRATEGY,
      useClass: CustomFallbackStrategy
    },
  ]
})
export class SharedModule {}
```

Library module uses the SharedModule:
```ts
@NgModule({
  imports: [
 ...
TranslocoModule,
SharedModule
...
 ],
providers: [
    {
      provide: TRANSLOCO_LOADER,
      useClass: i18nLibraryLoader
    }
  ]
})
export class LibraryModule {}
```

Please let me know if that's works for you.

**Comment by Kzamikaze** [comment]
Thanks for the quick reply.
I've managed to get it working with your suggestion, but i did it in reverse, importing the <code>LibraryModule</code> in the <code>SharedModule</code>.

At least it's working now, but isn't there a way to import both my <code>SharedModule</code> and the <code>LibraryModule</code> in my main <code>AppModule</code> with each one having its own service instance ?
Most of my apps use the SharedModule but not all of them use the library and my plan is to use that library is other applications without the SharedModule.

I guess my main design flow here is having to declare Transloco in my <code>SharedModule</code> when it should be in the <code>AppModule</code> but the current approach allows me to have only one translation file for all my applications which is convenient for my translators.

**Comment by itayod** [comment]
I am glad that it works for you now :)

What I can recommend you do in that case is to keep using only one `TRANSLOCO_LOADER` in your main application, and create [scope](https://github.com/ngneat/transloco#scope-configuration) for each library, this way you could split the translations between multiple files.

P.S
I have seen that you save the active language to `localstorage` did you see we have a [plugin](https://github.com/ngneat/transloco/tree/master/projects/ngneat/transloco-persist-lang) for that?

Also, about your "fallback lang" you could simply pass is as an `array` or `string` in the config, see in  the [example app](https://github.com/ngneat/transloco/blob/master/src/app/app.module.ts#L52)

**Comment by Kzamikaze** [comment]
I will look into scopes and see if i can find a solution.
Thank you for the feedback
