### ISSUE TITLE
Bug: availableLangs array not matching type declaration

### ISSUE THREAD

**Issue by jurgh1** [ngneat/transloco#106]
## I'm submitting a...

<pre><code>
[ x ] Bug report  
</code></pre>

## Current behavior

In app.module.ts, the useValue.availableLangs array, in the TranslocoConfig section, is not compatible with its type declaration after running

> $ ng add @ngneat/transloco

E.g when selecting 

> en, no

as desired languages during installation, the TranslocoConfig looks like this afterwords.

``
{
      provide: TRANSLOCO_CONFIG,
      useValue: {
        availableLangs: [en,no],
        defaultLang: 'en',
        prodMode: environment.production,
      } as TranslocoConfig
    },
``

## Expected behavior

The expected behavior would be an array compatible with the type declaration.

> export declare type AvailableLangs = string[] | {
    id: string;
    label: string;
}[];

## Minimal reproduction of the problem with instructions

Run

> $ ng add @ngneat/transloco

and select your desired languages. Eg. 

> en, no

## Environment

<pre><code>
Angular version: 8.2.7
Transloco : 2.0.0-rc.3

 
For Tooling issues:
- Node version: 12.10.0  
- Platform:  Windows 10

Others:

</code></pre>

**Comment by itayod** [comment]
Thanks for taking the time and opening this issue, we already fixed that in an internal branch. 

Anyhow we are still working on version 2 so for now I would recommend you to use version 1 until we will officially release the new version.
