### ISSUE TITLE
TypeError: Cannot read property 'completeScopeWithLang' of undefined at translate

### ISSUE THREAD

**Issue by maxime1992** [ngneat/transloco#107]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

(not sure whether actual bug or something I'm missing...)

## Current behavior

I'm trying to use `translate` method from a service.
I'm aware that I need to guarantee that translation file is loaded before I use it, which is the case. To make sure of it, I'm displaying the following:

```
console.log('getDefaultLang', translocoService.getDefaultLang());
console.log('getActiveLang', translocoService.getActiveLang());
console.log(translocoService.getTranslation(translocoService.getActiveLang()));
```

Which outputs:

```
getDefaultLang fr
getActiveLang fr
{ editionNumber: "4ème édition", ... }
```

But, if I run:

```
translocoService.translate('editionNumber')
```

It throws an error:

```
TypeError: Cannot read property 'completeScopeWithLang' of undefined
    at translate (ngneat-transloco.js:593)
```

## Expected behavior

I should be able to translate from a service?

## Minimal reproduction of the problem with instructions

Unfortunately... None. I tried to repro with your stackblitz and it's working. I'm using `"@ngneat/transloco": "1.8.0"` and I do not understand why it's not working within my project. I might be missing something obvious here :man_shrugging: 

## Environment

<pre><code>
Angular version: 8.2.1

Browser:
- [x] Chrome (desktop) version 76
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
Others:

</code></pre>

**Comment by shaharkazaz** [comment]
@maxime1992 Hi! we need more information in order to figure out what's wrong since you can't reproduce it in stackblitz.
can you try adding a debugger and maybe share some insights?

**Comment by shaharkazaz** [comment]
@maxime1992 Feel free to reopen this with further information in case this is still relevant.

**Comment by maxime1992** [comment]
@shaharkazaz I finally figured it out :) 

The error change slightly with v2 and it helped me to understand better.

I was trying to use the translate method within a validator. The context is not the correct one anymore and therefore it was breaking all the `this` within transloco.

What I did to solve it:

```
translocoService.translate.bind(translocoService)(`myKey`)
```

Instead of just 

```
translocoService.translate(`myKey`)
```
