### ISSUE TITLE
transloco v2: flatten at runtime does not work with arrays?

### ISSUE THREAD

**Issue by maxime1992** [ngneat/transloco#114]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

After upgrading to v2, I'm not able to work with arrays anymore.

My JSON file containing the translations is generated on the server, half for static needs, half from a CMS and I merge the 2 so that I can access to all that from one endpoint. 

With v1 I was really happy as I could do things like:

```html
<div *transloco="let t">
  <h1>{{ t.static.title }} - {{ t.dynamic.values }} values available</h1>
  <ul>
    <li *ngFor="let value of t.dynamic.values">{{ value }}</li>
  </ul>
</div>
```

But now that ["Each translation file is now flatten in runtime"](https://github.com/ngneat/transloco/blob/master/BREAKING_CHANGES.md#features) it doesn't work anymore. Is there any way to achieve this in v2?

## Expected behavior

Be able to use dynamic data and arrays.

## Minimal reproduction of the problem with instructions

See above.

## What is the motivation / use case for changing the behavior?

Be able to use dynamic data and arrays.

## Environment

<pre><code>
Angular version: 8.2

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by shaharkazaz** [comment]
@maxime1992 what version are you using?

**Comment by ArielGueta** [comment]
@maxime1992 they have added the array support in the latest version. In your case, you should do:

```html
<div *transloco="let t">
  <h1>{{ t('static.title) }} - {{ t('dynamic.values') }} values available</h1>
  <ul>
    <li *ngFor="let value of t('dynamic.values')">{{ value }}</li>
  </ul>
</div>
```

**Comment by maxime1992** [comment]
Oh cool @ArielGueta thanks for letting me know! I'll give it a go tonight or this we.
Cheers

**Comment by shaharkazaz** [comment]
@maxime1992 I'm closing this for now. 
Feel free to reopen if something isn't working as expected 🙂

**Comment by maxime1992** [comment]
All working as stated by @ArielGueta!

Thanks :)
