### ISSUE TITLE
Upgrading from ~1.7.9 to the latest guide

### ISSUE THREAD

**Issue by Beerbossa** [ngneat/transloco#115]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Having a hard time upgrading, I tried uninstalling and reinstalling, setting up the app.module just like in the tutorial, etc. But I still get a vscode linting error anytime I try to `{{ t('key.to.something') }}`. It's like if my IDE doesn't understand that this is callable with this version, I may have missed this part from the documentation ?

> transloco Member 't' is not callable

## Expected behavior

To be able to keep up to date with the latest versions 😢 

## Minimal reproduction of the problem with instructions
- Project that used an earlier version of transloco
- Upgrading with npm install @ngneat/transloco@2.0.3 (or uninstall and ng add @ngneat/transloco)
- Trying to change the old approach 
```{{ t.authentication.forgot_pass_card_title }}```
to
```{{ t('authentication.forgot_pass_card_title') }}```

## Environment

<pre><code>
Angular version: 8.2.4

 
For Tooling issues:
- Node version: v12.3.1  
- Platform:  Windows 10
- Ide: Visual studio code

Others:
"tslint": "~5.15.0",
"typescript": "~3.5.3"
"codelyzer": "^5.0.0",
</code></pre>

**Comment by shaharkazaz** [comment]
@Beerbossa it's fixed in v2.0.4 can you please verify?

**Comment by Beerbossa** [comment]
Yes it worked after upgrading then closing / re-opening vsCode 😃 Thanks a lot !

Also worth noticing for some people that I had to go in `Settings (ctrl + ,) -> search prettier quote -> Prettier: Single Quote to true` to be able to auto reformat without prettier changing the interpolated ```t('key.to.entry')``` to ```t("key.to.entry")``` automatically.

**Comment by shaharkazaz** [comment]
@Beerbossa Great to hear :slightly_smiling_face:
