### ISSUE TITLE
[v2.1.1] Error TranslocoTestingModule : _v.parent.context.$implicit is not a function

### ISSUE THREAD

**Issue by vincentjdc** [ngneat/transloco#117]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When using `TranslocoTestingModule` I get the following error (even for a dummy component test) :

> TypeError: _v.parent.context.$implicit is not a function

## Expected behavior

No error

## Minimal reproduction of the problem with instructions

1. Create a dummy component :
```
ng g c dummy
```
2. Run the tests : all tests pass
3.  Edit the spec for DummyComponent to look like this :
```ts
import { async, ComponentFixture, TestBed } from '@angular/core/testing';

import { DummyComponent } from './dummy.component';
import { TranslocoTestingModule } from '@ngneat/transloco';

describe('DummyComponent', () => {
  let component: DummyComponent;
  let fixture: ComponentFixture<DummyComponent>;

  const fr = {
    "hello_message": "Bonjour à tous"
  };

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [
        TranslocoTestingModule.withLangs({ fr: fr }, { defaultLang: 'fr' })
      ],
      declarations: [ DummyComponent ]
    })
    .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(DummyComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
```
4. Run the tests : all tests pass
5. Edit DummyComponent template to look like this :
```html
<ng-container *transloco="let t;">
    <p>{{ t('hello_message') }}</p>
</ng-container>
```
6. Run the tests : the DummyComponent test fails :
![transloco-test-fail](https://user-images.githubusercontent.com/50613035/66254314-e6728c00-e774-11e9-8c94-314f27fe8cb7.png)

## Environment

<pre><code>
Angular version: 8.

Browser:
- [x] Chrome (desktop) version Chrome 77.0.3865
- [] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.9.0
- Platform:  Docker container node:latest running on Linux Mint 19.1 

Others:
- Angular Version : 
    "@angular/animations": "^8.0.2",
    "@angular/common": "^8.0.2",
    "@angular/compiler": "^8.0.2",
    "@angular/core": "^8.2.6",
    "@angular/forms": "^8.0.2",
    "@angular/http": "^8.0.0-beta.10",
    "@angular/platform-browser": "^8.0.2",
    "@angular/platform-browser-dynamic": "^8.0.2",
    "@angular/router": "^8.0.2",
    "@coreui/angular": "^2.5.2",
    "@coreui/coreui": "^2.1.12",
    "@coreui/coreui-plugin-chartjs-custom-tooltips": "^1.3.1",
    "@coreui/icons": "0.3.0",
    "@fortawesome/fontawesome-free": "^5.11.1",
    "@ngneat/transloco": "^2.1.0",
</code></pre>

## Additionnal notes

- Replacing `t('hello_message')` with `'hello_message' | transloco` make the test to pass.
- The above Dummy component works fine in the "real" app (just need to set a route and set the "hello_message" translation)

**Comment by itayod** [comment]
Hi @vincentjdc seems strange, I couldn't reproduce it.

Could you please add a reproduction?

**Comment by vincentjdc** [comment]
Hi @itayod,

I couldn't reproduce in a fresh new project neither.
I deleted node_modules and run "npm install" and everything works.

Thanks for your help :)
