### ISSUE TITLE
Question: markup in parameters

### ISSUE THREAD

**Issue by zygimantas** [ngneat/transloco#118]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I need to translate text: "You have ❤︎9 lives"
Now the markup is:
```html
<p>
  {{t('part1')}}
  <span custom-heart-component [value]="9"></span>
  {{t('part2')}}
</p>
```

Translations:
```text
part1: "You have"
part2: "lives"
```

## Expected behavior

Is there any more elegant way to do this, without splitting the translation into 2 parts?

**Comment by shaharkazaz** [comment]
@zygimantas 
You can achieve that by passing a param to the translation.
Your translation file:
```
{
  ...
  "lives-left": You have {{lives}}♥️ lives
}
```
Your component:
```html
<p>{{ t('lives-left', { lives: 9 } ) }}</p>
```
Of course you can also put the translation insisde your custom heart component.

You can join our [gitter channel](https://gitter.im/ngneat-transloco/lobby#) in case you need further guidance and questions 🙂
