### ISSUE TITLE
Structural directive with fullTemplateTypeCheck Ivy Issue

### ISSUE THREAD

**Issue by mickz18** [ngneat/transloco#119]
## I'm submitting a...

<pre><code>
[*] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

    ERROR in src/app/app.component.html(332,6): error TS2339: Property 't' does not exist on type 'AppComponent'.

## Expected behavior

Compiling successfully

## Minimal reproduction of the problem with instructions

create new project with --enable-ivy or with ng@next
ng add @ngneat/transloco
change html template

`... <div class="content" role="main" *transloco="let t">
  {{ t("title") }} ...
`

## Environment
since v2
Transloco 2.1.1 
<pre><code>
Angular CLI: 8.3.8
Node: 11.15.0
OS: linux x64
Angular: 8.2.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.8
@angular-devkit/build-angular     0.803.8
@angular-devkit/build-optimizer   0.803.8
@angular-devkit/build-webpack     0.803.8
@angular-devkit/core              8.3.8
@angular-devkit/schematics        8.3.8
@angular/cli                      8.3.8
@ngtools/webpack                  8.3.8
@schematics/angular               8.3.8
@schematics/update                0.803.8
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

also with cli@next

</code></pre>

**Comment by shaharkazaz** [comment]
@mickz18 
Hey, it's not a Transloco issue. It seems like Ivy isn't ready and has some problems with backward compatibility. 
We already open an [issue in the official repository](https://github.com/angular/angular/issues/32900) so that you can track it.

It's worth mention that it only happens when using the structural directive with "fullTemplateTypeCheck" in tsconfig.

**Comment by mickz18** [comment]
Thanks for the clarification!

**Comment by julianpoemp** [comment]
> Possible workarounds:
> 
> * Remove the `fullTemplateTypeCheck` flag from the tsconfig.
> * Use the pipe/attribute directive
> 
> Anyway, I would avoid using Ivy for the time being as it's not ready.

Angular 9 will be released in January 2020. How long would it take to make transloco compatible with ivy?

**Comment by itayod** [comment]
Hi @julianpoemp this should work fine now, as it was fixed by angular.
You could see the original issue [here](https://github.com/angular/angular/issues/32900)
