### ISSUE TITLE
[Feature] Provide mechanism for remembering selected language

### ISSUE THREAD

**Issue by DmitryEfimenko** [ngneat/transloco#12]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Proposal
Based on the documentation I didn't see a way to specify a mechanism for remembering the language that user selects. I'd expect something similar to what [ngx-translate-cache](https://github.com/jgpacheco/ngx-translate-cache) provides.

## Current behavior
Proposed behavior does not exist

## Expected behavior
Pending design

## What is the motivation / use case for changing the behavior?
There is no need to ask the consumer of this library to write all the boilerplate needed to store the selected language in LocalStorage or Cookies

**Comment by shaharkazaz** [comment]
@DmitryEfimenko It's on its way 🙂 
we are planning to start work next week.

**Comment by agugan** [comment]
@shaharkazaz 
I am not sure whether this is incorporated in the planning or already exists. But I would also like to add  a sub feature to it.

Our enterprise applications have multiple sub-projects to switch between. Sometimes we have language selection coming in from different source than the rest of project. 

Currently we have to store the selected language in cookie/LS and retrieve it the respective translation module initialization.

Future: I would like to see it integrated to translation store itself. 
Ex:
``` ts
{
      provide: TRANSLOCO_CONFIG,
      useValue: {
        prodMode: environment.production,
        listenToLangChange: true,
        defaultLang: 'en',
        persistLanguage: {  
         persistLanguageAcross: true,
         name: 'selected_lanaguage_transloco'
   }
      }
    }
```
So when these options enabled, we will store the selected language  also in cookie/Local/Session storage under the given name, and then we can first check for the persisted language in sub-projects else fallback to defaultLanguage. 

Though this look like a specific usecase, but its also one of the bigger pain points in translations.
If you like this feature, I would love to submit a PR with help.

**Comment by shaharkazaz** [comment]
@agugan Hey, we are working on something and a PR should be ready soon, you are welcome to track this 🙂

**Comment by itayod** [comment]
Hey @DmitryEfimenko, 
After reconsidering this feature, we have decided not to implement it as part of the library, as we try to keep it as clean and simple as possible.

Also implementing this feature is pretty easy and doesn't require a lot of code:
```javascript

  constructor(private transloco: TranslocoService) {}

  ngOnInit() {
    // set the saved language from local storage.
    this.transloco.setActiveLang(localStorage.getItem('lang'));

    // persist the current language in local storage.
    this.transloco.langChanges$.pipe(distinctUntilChanged())
        .subscribe(lang => localStorage.setItem('lang', lang));
  }
```

Does it satisfy your issue?

**Comment by DmitryEfimenko** [comment]
it's trivial to save it to the `localStorage`. It becomes more involved when saving it to the cookie which is a valid use-case if you want to have it working with SSR.

If worrying about the library size, make it a separate addon library just like in the case of *ngx-translate-cache*, which is separate from *ngx-translate*. It does not need to be a part of the *transloco* library itself.

As a matter of fact, a lot of the implementation could be straight copy-pasted [from ngx-translate-cache](https://github.com/jgpacheco/ngx-translate-cache/blob/master/src/translate-cache.service.ts).

**Comment by shaharkazaz** [comment]
@DmitryEfimenko 
I see what you mean. You're welcome to open a PR. Here are the requirements:
- It will be under the official library, so please create a new library with angular-cli under the `projects/ngneat` folder.
- The storage should be flexible, so the consumer should provide it. ( without a default value )

Good luck!

**Comment by NetanelBasal** [comment]
@DmitryEfimenko could you check if the following PR resolved this issue, please?

https://github.com/ngneat/transloco/pull/34/files

**Comment by NetanelBasal** [comment]
@DmitryEfimenko I rewrote it from scratch, the new implementation will be:

```ts
export function getLangFn({ cachedLang, browserLang, cultureLang, defaultLang }) {
  return whatYouWant;
}

@NgModule({
  imports: [
    TranslocoPersistLangModule.init({
      getLangFn,
      storage: {
        provide: TRANSLOCO_PERSIST_LANG_STROAGE,
        useValue: localStorage
      },
    })
  ],
})
class AppModule {}
```

**Comment by DmitryEfimenko** [comment]
That looks clean!
