### ISSUE TITLE
Change log documentation

### ISSUE THREAD

**Issue by mickz18** [ngneat/transloco#120]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[*] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

after upgrade from 2.0.1 to 2.1.1 no key was found anymore.
I had to add avaibleLang to fix it.
It's on the doc but not when I start using transloco.

## Expected behavior

More clear information about change

Others:

Just open issue to  smooth the experience that other may have with the lib. Love your work thank a lot !

**Comment by itayod** [comment]
@mickz18 Could you please farther explain the issue?

**Comment by mickz18** [comment]
yep sorry submit to fast by error

**Comment by itayod** [comment]
@mickz18 
It's pretty clear from the docs that you need to add it to `TRANSLOCO_CONFIG`.

If you have any farther questions, please feel free join our [gitter channel](https://gitter.im/ngneat-transloco/lobby#)
