### ISSUE TITLE
Not able to handle nested folder structure for namespaces

### ISSUE THREAD

**Issue by devKomban** [ngneat/transloco#122]
## Support Request

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Lazy loading module 

AccountModule.ts
```ts
@NgModule({
  declarations: [AccountCComponent,AccountPComponent],
  imports: [
    CommonModule,
    AccountRoutingModule,
    MaterialModule,
    FormsModule,
    ReactiveFormsModule,
    FormElementsModule,
    DirectivesModule,
    TranslocoModule
  ],
  providers: [{ provide: TRANSLOCO_SCOPE, useValue: { scope: 'master-services/temp-account', alias: 'account' } }],
  entryComponents: [AccountPComponent]
})
```

transloco.loader.ts
```ts
import { HttpClient } from '@angular/common/http';
import { Translation, TRANSLOCO_LOADER, TranslocoLoader } from '@ngneat/transloco';
import { Injectable } from '@angular/core';


@Injectable({ providedIn: 'root' })
export class HttpLoader implements TranslocoLoader {
  constructor(private http: HttpClient) {}

  getTranslation(langPath: string) {
    console.log(langPath);
    return this.http.get<Translation>(`/assets/i18n/${langPath}.json`);
  }
}

export const translocoLoader = { provide: TRANSLOCO_LOADER, useClass: HttpLoader };


```
output of console.log(langPath) is "[object Object]/ar"

## Expected behavior

output of console.log(langPath) is "master-services/temp-account/ar"

## What is the motivation / use case for changing the behavior?

Need to use nested folder structure

## Environment

<pre><code>
Angular version: 7

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version 70.0b11
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by itayod** [comment]
Hi @devKomban I could not reproduce this, could you upload a reproduction stackblitz of your problem?

**Comment by itayod** [comment]
Also, that might be a version problem, what Transloco version do you use?

**Comment by devKomban** [comment]
> Also, that might be a version problem, what Transloco version do you use?

I am currently using version 2.0.4

**Comment by itayod** [comment]
Could you try update to the newest? 
Until version 2.1.0 we didn’t accept object as scope value

**Comment by devKomban** [comment]
It worked Thanks a lot **itayod**
