### ISSUE TITLE
[Question] a way to access the key value from the typescript

### ISSUE THREAD

**Issue by SurendraR** [ngneat/transloco#124]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X] Support request
[ ] Other... Please describe:
</code></pre>

I'm unable to find a way to access the key value from the typescript.
My `en.json` file:
```json
{
  "test": {
    "child1": "child1Value",
    "child2": "child2Value"
  }
}
``` 
I want to access the value for child1 in typescript. How do I do that? 
I've already started using transloco in my application. Please help me with this.

**Comment by andreaslarssen** [comment]
Waht have you tried? How do you load your files and scopes?

**Comment by shaharkazaz** [comment]
@SurendraR Hey, please try to describe your issue ina more readable way (see my editing).

I'm trying to understand what you are trying to achieve, Are you trying to access the translation programmatically? if so, check the [programmatical translation](https://github.com/ngneat/transloco#programmatical-translation) section in the docs.

If I misunderstood you, please try to explain and create a stackblitz reproduction.

**Comment by shaharkazaz** [comment]
@SurendraR feel free to ask questions in [our gitter channel](https://gitter.im/ngneat-transloco/lobby#) if what I suggested didn't resolve your issue.
