### ISSUE TITLE
Should be able to pass an element in translation

### ISSUE THREAD

**Issue by Newbie012** [ngneat/transloco#126]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ x ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

```
{{ t('translationWithIcon', { icon: <fa-icon ...></fa-icon> }) }}
// Output: t('translationWithIcon', { icon: ❤️ })
```

## Expected behavior

```
{{ t('translationWithIcon', { icon: <fa-icon ...></fa-icon> }) }}
// Output: My translation with the following ❤️ icon.
```

## What is the motivation / use case for changing the behavior?

The current behavior is unexpected and IMHO not a solution for any kind of case.

## Environment

<pre><code>
Angular: 8.2.9

Browser:
- [ x ] Chrome (desktop) version 77
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
 - Node: 10.11.0
 - OS: win32 x64

Others:

</code></pre>

**Comment by itayod** [comment]
Hi @Newbie012, 

Thanks for your proposal, but we are not willing to support this feature.
You could try create a [custom transpiler](https://github.com/ngneat/transloco#transloco-transpiler) for that.
