### ISSUE TITLE
Translation works while using transloco pipe but same string using with service.translate is not working

### ISSUE THREAD

**Issue by devKomban** [ngneat/transloco#127]
##Help Request

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
<code>
this.objTranslationService.translate('cashAccount.LISTOFCASHACCOUNTS');
</code>
in class file
produces  "Missing translation for 'cashAccount.LISTOFCASHACCOUNTS'"
<code>
{{'cashAccount.LISTOFCASHACCOUNTS' | transloco}}
</code>
in template file is working.

## Environment

<pre><code>
Angular version: 7
@ngneat/transloco: 2.1.1

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by ArielGueta** [comment]
If you did not load the translation when you call translate in your component you should use selectTranslate. https://github.com/ngneat/transloco#programmatical-translation

**Comment by andreaslarssen** [comment]
If we could implement inline loaders (#121), the pipe (or anything else) wouldn't have to load the languages

**Comment by shaharkazaz** [comment]
@devKomban feel free to reopen if @ArielGueta's  suggestion didn't resolve the issue.
@andreaslarssen Thanks, but it's not related to the issue.
