### ISSUE TITLE
Features comparison table vs angular-i18n, ngx-translate, angular-l10n, ...

### ISSUE THREAD

**Issue by dsuwirya** [ngneat/transloco#13]
Hello,

Would be really great if you can add features comparison table like what the angular-l10n has, that will ease developers to make decision which library is best to use depending on their situations.

ref. https://github.com/robisim74/angular-l10n

Thanks.

**Comment by shaharkazaz** [comment]
Did you check out [this section](https://github.com/ngneat/transloco#comparison-to-other-libraries) of the README file?

**Comment by DanielHabenicht** [comment]
Can you add something like translation file support to the table? Would be good to know if it supports `xliff` or other formats on first look. 

Also translation of plurals should be added for comparison. 

And what about a comparison against the build in translation tool (+ the i18n Polyfill for components)? I think what @dsuwirya meant was adding those other tools/packages to the table.  
Keep up the good work. For me the features above are missing and there is no path for a migration to the official next gen internationalisation library from the angular team. But it should solve the problems of a good amount of people as it seems pretty easy to.use ;)

**Comment by shaharkazaz** [comment]
@DanielHabenicht 
A table is just a tool for a quick comparison, all the needed information is in the README,
but I see what you mean, I will talk to the team and we will decide what should be added.
We don't want to make it too big.

**Comment by shaharkazaz** [comment]
We have added Pluralization to the table but decided that it's the last thing we'll add to it.
A comparison with Angular's i18n will be added shortly 🎉

**Comment by MickL** [comment]
@shaharkazaz The link is outdated. Is there a comparison in the new docs website, too? I wonder what are the benifits of transloco over ngx-translate

**Comment by Andrew-Marks-Trisept** [comment]
@MickL I found the most recent version of the comparison chart before they redid the docs here: https://web.archive.org/web/20191004014440/https://github.com/ngneat/transloco/

**Comment by rala72** [comment]
Is it possible to add the current comparison table again somewhere?
I think the table in the link above might not be up-to-date.

**Comment by shaharkazaz** [comment]
@rala72 We decided to remove the comparison (due to several reasons). I'm sure that quick research will provide you with all the information needed.
