### ISSUE TITLE
How does Tranloco prevent translation glitching?

### ISSUE THREAD

**Issue by andreaslarssen** [ngneat/transloco#131]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x ] Other... Please describe: Question
</code></pre>

Right now, what loads a translation file is the usage of a translation key through a pipe or the directive (or the service, using the selectTranslate method (if the file isn't loaded another way)).

So let's say you use the pipe in a template, and that's what triggers the fetching of the file. What is that prevents translation/string glitching?

**Comment by shaharkazaz** [comment]
You can provide a loading template to be displayed while the translation is being loaded

**Comment by andreaslarssen** [comment]
Ok, so no prevention
