### ISSUE TITLE
Define scope using pipe syntax

### ISSUE THREAD

**Issue by shravansofts** [ngneat/transloco#134]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Define scope using pipe syntax

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, for that you could use our [stackblitz example](https://stackblitz.com/edit/transloco-example)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by shaharkazaz** [comment]
@shravansofts We are not going to support this, here is why:
1. This will always have to be the 3rd parameter.
2. What is the use case where you need a scope just on one pipe?
3. We recommend using the structural directive to avoid multiple subscriptions

**Comment by shravansofts** [comment]
We have a usecase to support multiple vendor(apple, samsung, nokia).
The same code could be used for all vendor cases. (imagine scope string comes from a APP level const)
