### ISSUE TITLE
camel cased folders don't work with scope

### ISSUE THREAD

**Issue by LPCmedia** [ngneat/transloco#136]
[X] Bug report
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
[X] Other... Please describe: Is this intended ? if so please close or document.

## Current behavior

use Scope with a file in a folder using kebab casing does not work. The translation keys ger camel cased and cannot be accessed.  

## Expected behavior

I can load the file in the folder and access my translations 
....i18n/name-of-folder/en.json

// in lazy module.ts
scope: 'name-of-folder'

{{ name-of-folder.title }}

## Minimal reproduction of the problem with instructions

Will provide repo if this is indeed a bug.

**Comment by shaharkazaz** [comment]
@LPCmedia 
From the [docs](https://netbasal.gitbook.io/transloco/lazy-load-translation-files/scope-configuration):

>By default, the namespace will be the scope name (camel cased)...

In your case, instead of `name-of-scope` you should use `nameOfFolder`.

**Comment by LPCmedia** [comment]
Thanks @shaharkazaz 

I got it to work using a scope + alias to the kebab case name. I failed to mention i'm migrating an existing app and needed to keep the name-of-folder in the html.

**Comment by shaharkazaz** [comment]
@LPCmedia did @ArielGueta solved your issue?

**Comment by LPCmedia** [comment]
Ill test this by wednesday.

**Comment by NetanelBasal** [comment]
@LPCmedia here's a working example. https://stackblitz.com/edit/ngneat-transloco-ybqnab

If you have any issue, let us know.
