### ISSUE TITLE
TranslocoPipe.ngOnDestroy: Cannot read property 'unsubscribe' of null

### ISSUE THREAD

**Issue by mstawick** [ngneat/transloco#137]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I'm getting `Cannot read property 'unsubscribe' of null`. I'm not sure why it exactly happens in my case, but it seems that checking if the subscription is set in ngOnDestroy would be a good idea anyway (for ex. if the key is falsy then subscription is never set).

<pre><code>
  ngOnDestroy() {
   >>> if (this.subscription != null)
    this.subscription.unsubscribe();
  }
</code></pre>

**Comment by shaharkazaz** [comment]
@mstawick Thanks for the report! fixed in b55bd59 and released in v2.2.1 🙂
