### ISSUE TITLE
Prefetch user language fails on Safari desktop

### ISSUE THREAD

**Issue by ld210** [ngneat/transloco#138]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Prefetching user language via APP_INITIALIZER doesn't work on Safari, prevent app to bootstrap.

<img width="1265" alt="Capture d’écran 2019-10-18 à 13 24 24" src="https://user-images.githubusercontent.com/16461928/67090834-69e7a080-f1ab-11e9-9d7b-d21735b9fcdf.png">

## Expected behavior

Works fine with Chrome. Expecting Safari to be able to fetch JSON file as well.

## Minimal reproduction of the problem with instructions

Here is the loader's code, nothing fancy : 
```
export function preLoadTranslations(transloco: TranslocoService) {
  return function () {
    const currentLang = (window.navigator as Navigator).language.split('-')[0];
    return transloco.load(currentLang).toPromise();
  };
}

export const preLoad = {
  provide: APP_INITIALIZER,
  multi: true,
  useFactory: preLoadTranslations,
  deps: [TranslocoService]
};
``` 

and my App.module : 

```
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    RouterModule,
    BrowserAnimationsModule,
    HttpClientModule,
    AppRoutingModule,
    MaterialModule,
    SharedModule,
    AuthModule,
    TranslocoModule,
  ],
  providers: [CampaignService, UserService, GroupService, ContentService, LanguageStoreService, AdministratorService, PaginationStoreService, {
      provide: TRANSLOCO_CONFIG,
      useValue: {
        availableLangs: [{id: 'fr', label: 'Français'}],
        defaultLang: 'fr',
        fallbackLang: 'fr',
        missingHandler: {
          allowEmpty: true
        },
        reRenderOnLangChange: false,
        prodMode: environment.production,
      } as TranslocoConfig
    },
    translocoLoader,
    TranslocoService,
    preLoad
  ],
  bootstrap: [AppComponent]
})
```

## Environment

<pre><code>
Angular CLI: 8.2.0
Node: 12.10.0
OS: darwin x64
Angular: 8.2.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x ] Safari (desktop) version 13.0.1
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.10.0
- Platform:  Mac OS 10.14.6

</code></pre>

**Comment by ArielGueta** [comment]
Where do you call `setActiveLang`?

```ts
export function preLoadTranslations(transloco: TranslocoService) {
  return function () {
    const currentLang = (window.navigator as Navigator).language.split('-')[0];
    transloco.setActiveLang(currentLang);
    return transloco.load(currentLang).toPromise();
  };
}
```

**Comment by ld210** [comment]
Hi,
i don't. I added it, but it doesn't change anything. Still not able to preload language.

**Comment by ld210** [comment]
Okay, i just found what happened. Entirely my fault. We have an interceptor, for authentication purposes, that inject a jwt token in the header. If there's no token, the request is dismissed.
Since i add an active token in the browser i use for dev, there was no issue with it. As soon i used another browser, the http request for the language file was dismissed.
I simply add json files in the interceptor white list.

Sorry for the inconvenience, i dun goofed.

**Comment by shaharkazaz** [comment]
@ld210 I was just going to  reply that it seems good to me.
Great to hear that it's resolved, close this issue if it's not relevant anymore :+1:
