### ISSUE TITLE
Support for angular >=8 without warnings

### ISSUE THREAD

**Issue by javix** [ngneat/transloco#140]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ x ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I use angular ^8.2.11. If I install transloco, I get the following warning:

> npm WARN @ngneat/transloco-utils@1.0.2 requires a peer of @angular/common@^7.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngneat/transloco-utils@1.0.2 requires a peer of @angular/core@^7.2.0 but none is installed. You must install peer dependencies yourself.

## Environment

<pre><code>
Angular version: 8.2.11
</code></pre>

**Comment by shaharkazaz** [comment]
@javix Thanks for the report, fixed in the latest version.
