### ISSUE TITLE
Allow translate custom provide in app.module.ts

### ISSUE THREAD

**Issue by DiV666** [ngneat/transloco#142]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ X ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I need to send translated texts to a library with an InjectionToken:
<pre><code>app.module.ts
{
  provide: LIBRARY_STRINGS,
  useFactory: (translocoService) => {
    return translocoService.translate('DASHBOARD');
  },
  deps: [TranslocoService]
}
</code></pre>

But translations is not ready and i can't return an observable or subscribe to `selectTranslate()`:
`Missing translation for 'DASHBOARD'`

Is it possible to load the translations to translate the InjectionToken?

I know this is more a question about angular behavior, but if you could help me with your library it would help me a lot.

Thank you

## Environment

<pre><code>
Angular version: 8.2.11

Browser:
- [ X ] Chrome (desktop) version 76
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by shaharkazaz** [comment]
@DiV666 I'm afraid the only way you can achieve that is by [preloading the language](https://netbasal.gitbook.io/transloco/recipes/prefetch-the-user-language)
I'm closing this since it's more of an Angular related issue than Transloco, if you need more assistance please refer to our [gitter channel](https://gitter.im/ngneat-transloco/lobby?source=orgpage)
