### ISSUE TITLE
Tool for extracting texts for translation

### ISSUE THREAD

**Issue by antontemchenko** [ngneat/transloco#143]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
There is no possibility to extract all keys from HTML & .ts

## Expected behavior
There should be a possibility to extract all keys to file (.json, .po) 

## What is the motivation / use case for changing the behavior?
This feature will speed up all the translation process

**Comment by shaharkazaz** [comment]
@antontemchenko We are currently in the process of building that tool. 
It should be ready by the end of next week, please track this [repo](https://github.com/ngneat/transloco-keys-manager)

**Comment by antontemchenko** [comment]
@shaharkazaz thanks for letting me know.
It would be great if it will be mentioned in docs ;)
