### ISSUE TITLE
Use of Inline Loaders when building a library with Ng-Packagr

### ISSUE THREAD

**Issue by SparkMonkey** [ngneat/transloco#144]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I just switched from ngx-translate to transloco in order to deal with lazy loading issues with my libraries. 

So I'm using the [Inline Loaders](https://netbasal.gitbook.io/transloco/lazy-load-translation-files/inline-loaders) feature.

My issue is not related to transloco itself, but how to use transloco when building a library with ng-packagr.

Here is the transloco Inline Loader example from the doc :

    export const loader = ['en', 'es'].reduce((acc, lang) => {
      acc[lang] = () => import(`../i18n/${lang}.json`);
      return acc;
    }, {});

It uses dynamic import. But ng-packagr does not support it for now. See this [this issue.](https://github.com/ng-packagr/ng-packagr/issues/1285)

My question is how to deal with this ? I believe Ng-packagr is used a lot and I wonder how you guys handle this situation. Inline Loaders seems to be meant to work with library, so I suppose this need is common.

Thank you

## Environment

<pre><code>
Angular version: 8.2.11

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 70
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.16.0  
- Platform:  Windows

Others:

ng-packagr: 5.7.0
</code></pre>

**Comment by shaharkazaz** [comment]
@SparkMonkey Hi,
As you mentioned, it's not a Transloco issue. It's an issue with ng-packager that we hope they will resolve in the future. 
The inline loaders were introduced to allow translations encapsulation of lazy load modules.
What I can suggest in your case is to use `setTranslation` and load them eagerly if someone uses the library:
```ts
import en from '....';
import es from '....';

export class YourModule {
  constructor(private translocoService: TranslocoService) {
    translocoService.setTranslation(en, 'en');
    translocoService.setTranslation(es, 'es');
  }
}

**Comment by SparkMonkey** [comment]
Thank you for your fast answer.

That is highlighting the fact that I do not understand how it works.

When you say eagerly, do you think of something like that 

    getTranslation(langPath: string) {
        return this.http.get<Translation>(`/assets/i18n/${langPath}.json`);
    }

Should the path to the json file be relative to the concerned library module ? Or absolute to the library's root ? 

When we used ngx-translate, we tried to tweak the application's angular.json's assets to point on i18n files packaged in the library npm package (manual copy).

Is this needed with Transloco ?

Thank you a lot

**Comment by SparkMonkey** [comment]
Ok I have found why I couldn't build since I added the eager import.

The i18n json file embedded in dist, thanks to the import, is sadly prefixed by the following : 

     /**
     * @fileoverview added by tsickle
     * @suppress {checkTypes,constantProperty,extraRequire,missingOverride,missingReturn,unusedPrivateMembers,use   lessCode} checked by tsc
     */

This is not a valid JSON file anymore since comments are not allowed in JSON. I'm searching how to avoid this.

Meanwhile I'm wondering something about your proposed solution : 

Will I be able to define an i18n file for each module of my library ? Since the scope is not involved in the solution, I understand that I will have to merge all my i18n files into one. Is that right ?

Thank you

**Comment by shaharkazaz** [comment]
I assume that the translation files are locally in the npm package. When you do this in your exposed module from the library:

```ts
import en from './en.json';
import es from './es.json';

export class YourNpmPackageModule {
  constructor(private translocoService: TranslocoService) {
    translocoService.setTranslation(en, 'en');
    translocoService.setTranslation(es, 'es');
  }
}
```


See how we use the `setTranslation` method. It will include both the `en` and the `es` translations (eagerly) in the library bundle. Now, when someone consumes the library, it can use its translations.

The second approach you mentioned can work too. You can copy the library translation files into your assets folder, put them under a scope name, and in your library root component providers set the scope.

**Comment by shaharkazaz** [comment]
@SparkMonkey Can you create a reproduction repo? I think this will advance us better towards a solution

**Comment by SparkMonkey** [comment]
I have tested your solution and it works for routed components !

I did the eager import in each modules of my library (that is packaged as npm), and called setTranslation in their constructors as you proposed.

Each modules's components of my library are effectively translated according to their own i18n file, when i route them.

I'm admitting that I do not understand how this works, because I expected setTranslation calls to override each others. I'm guessing there is a TranslationService instance for each module, so there is no override.

In order to help people who reads this issue, here some steps I have been through :

- I had to set "resolveJsonModule": true in compilerOptions to allow import * as en from './i18n/en.json' syntax.
- I had to set "annotateForClosureCompiler": false in angularCompilerOptions to disable tsickle annotations that made i18n JSON files invalid
- I used "module": "esnext" in compilerOptions
- I finally used Angular CLI to package the library (it use ngPackagr under the hood anyway)

------------------------------------------------------------------------------------------------

But it only works for routed components. See below :

**Works :**  Routed UsersComponent is translated translated properly.

    import { UsersModule, UsersComponent} from '@mylib';
    @NgModule({
        imports: [
            UsersModule,
            RouterModule.forChild([
            {
                path: '',
                component: UsersComponent,
            }
        ])
        ]
    })
    export class LazyUsersModule { }

**Doesn't work :** A call to a library's component from a template of the main application

    @Component({
        selector: 'ngx-dashboard',
        styleUrls: ['./dashboard.component.scss'],
        `
            <div>
                <component-of-my-lib></component-of-my-lib>
            </div>
        `
    })
    export class DashboardComponent {
    }

Am I doing something wrong on the second use case ?

Thank you for your support 👍

**Comment by NetanelBasal** [comment]
Thanks for your detailed summary. Transloco doesn't create new instance for each module. When you call `setTranslation` by default it merges the translations. We hope that `ng-packagr` will add the `import` support in the future, and when it does it will work out of the box. I'm closing this issue for now.
