### ISSUE TITLE
You're using an inline loader but didn't provide a loader for default/da

### ISSUE THREAD

**Issue by jamalsoueidan** [ngneat/transloco#146]
TRANSLOCO_SCOPE is not working properly when using a specific loader for the module translation.

I cannot get it to work, and I cannot find enough documentation about it.

```
  providers: [
    {
      provide: TRANSLOCO_SCOPE,
      useValue: {
        scope: 'default',
        loader: (lang) => of({anything: "ad"})
      },
    },
  ],
```

**Comment by ArielGueta** [comment]
It meant to work with Webpack `import` function, which creates a separate chunk for each file. What you are trying to do is not making sense.

Read the docs: https://netbasal.gitbook.io/transloco/lazy-load-translation-files/inline-loaders

**Comment by jamalsoueidan** [comment]
> It meant to work with Webpack `import` function, which creates a separate chunk for each file. What you are trying to do is not making sense.
> 
> Read the docs: https://netbasal.gitbook.io/transloco/lazy-load-translation-files/inline-loaders

I'm trying to make it work like the TRANSLOCO_LOADER.

```
@Injectable({ providedIn: 'root' })
export class HttpLoader implements TranslocoLoader {
  constructor() {}

  getTranslation(langPath: string) {
    return of({my translation object});
  }
}
```

**Comment by ArielGueta** [comment]
So call `setTranslation` in the constructor:

```ts
@NgModule({
 ...
})
export class TodosModule {
  constructor(private service: TranslocoService) {
     service.setTranslation(translationobject, lang);
  }
}
```

**Comment by jamalsoueidan** [comment]
> So call `setTranslation` in the constructor:
> 
> ```ts
> @NgModule({
>  ...
> })
> export class TodosModule {
>   constructor(private service: TranslocoService) {
>      service.setTranslation(translationobject, lang);
>   }
> }
> ```

I want to reuse my provider in all modules.

export const loader {
      provide: TRANSLOCO_SCOPE,
      useValue: {
        scope: 'default',
        loader: (lang) => of({anything: "ad"})
      },
    },

**Comment by zmoshansky** [comment]
Somewhere in your project (ideally a better variant of this is eventually shipped with transloco), define an inlineLoaderFactory.

```
/**
 * @param loader `(lang: string) => import(`./i18n/${lang}.json`)` to create a relative import to the correct dir
 */
export function InlineLoaderFactory(loader: Fn<Promise<JSON>>) {
  return SUPPORTED_LANGUAGES.reduce((acc, lang) => {
    acc[lang] = () => loader(lang);
    return acc;
  }, {});
}
```

Then in lazy loaded modules, use the following to trigger inline loading from the module's i18n folder:
```
  providers: [
    {
      provide: TRANSLOCO_SCOPE,
      useValue: {
        loader: InlineLoaderFactory((lang: string) => import(`./i18n/${lang}.json`)),
        scope: 'walkthrough',
      },
    },
  ],
```

Keep in mind, it seems possible that calling `transloco.translate` in a service may occur before the translation has loaded...

In our project, we've built a service that subscribes to `transloco.event$` and caches all of the loaded translation scopes.
```
public async translate(...) {
  await scopeLoaded(scope);
  return transloco.translate('foo');
}
```

**Comment by ArielGueta** [comment]
@jamalsoueidan I don't understand what you are trying to do. If you have the translation object and you want to set it manually for the whole app, call `setTranslation` in the `AppModule`:

```ts
@NgModule({
 ...
})
export class AppModule {
  constructor(private service: TranslocoService) {
     service.setTranslation(translationobject, lang);
  }
}
```

**Comment by ArielGueta** [comment]
@zmoshansky you can use `selectTranslate('key', params, 'scope/name').subscribe()`

**Comment by jamalsoueidan** [comment]
Thank you @ArielGueta  :)

**Comment by MarcosVRSDev** [comment]
> Somewhere in your project (ideally a better variant of this is eventually shipped with transloco), define an inlineLoaderFactory.
> 
> ```
> const SUPPORTED_LANGUAGES = ['en', 'de', 'es'];
> 
> /**
>  * @param loader `(lang: string) => import(`./i18n/${lang}.json`)` to create a relative import to the correct dir
>  */
> export function InlineLoaderFactory(loader: Fn<Promise<JSON>>) {
>   return SUPPORTED_LANGUAGES.reduce((acc, lang) => {
>     acc[lang] = () => loader(lang);
>     return acc;
>   }, {});
> }
> ```
> 
> Then in lazy loaded modules, use the following to trigger inline loading from the module's i18n folder:
> 
> ```
>   providers: [
>     {
>       provide: TRANSLOCO_SCOPE,
>       useValue: {
>         loader: InlineLoaderFactory((lang: string) => import(`./i18n/${lang}.json`)),
>         scope: 'example',
>       },
>     },
>   ],
> ```
> 
> Keep in mind, it seems possible that calling `transloco.translate` in a service may occur before the translation has loaded...
> 
> In our project, we've built a service that subscribes to `transloco.event$` and caches all of the loaded translation scopes. Otherwise lazy-loaded modules may not be quick enough to subscribe to `event$` to deterministically catch the loaded events. Again, hopefully this is eventually provided by transloco.
> 
> ```
> public async translate(...) {
>   await this.isScopeLoaded(scope);
>   return this.transloco.translate('foo');
> }
> ```

I know it's been a while, but can you share your "isScopeLoaded" function? I'm having the same problem in my project, but I'm having trouble getting it to work correctly.

**Comment by nhhockeyplayer** [comment]
this project is a disaster
javascript is unfit for commercial development
these KIND of libraries have invaded angular
and the field in general
and tarnished beautiful frameworks like NgRX
taken after react which has been a mess trying to and successfully sliming its way into everything
and setting back the semantics back to JAVASCRIPT

I had ngx-translate up in 5 mins with a core singleton load it once and forget it module

**Comment by shaharkazaz** [comment]
@nhhockeyplayer There is a way to leave feedback, but that's not the way. This is open-source, and if you have a suggestion to improve, you are welcome to open a PR or an issue instead of rage (I have no idea why, lol) commenting on an issue from 2019.
Nobody is forcing you to use Transloco.
