### ISSUE TITLE
Feature request: Loading i18n assets remotely

### ISSUE THREAD

**Issue by bjornharvold** [ngneat/transloco#147]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

My web components are located here:
https://mywebcomponents.com/scripts.js
https://mywebcomponents.com/assets/i18n/en.json

I have a user who wants to use my custom web component on another site. 
E.g. https://externalsite.com/

He imports my external JS Web Component but Transloco fails because it is looking for translation files on the remote site (https://externalsite.com/) instead of the site where the web component originated from.  

## Expected behavior

There should be a way to tell Transloco on which URL to append to find the external en.json.

## What is the motivation / use case for changing the behavior?

Web Components cannot be re-used at this time.

Cheers,
Bjorn

**Comment by NetanelBasal** [comment]
You can define what path you want in the loader.

**Comment by bjornharvold** [comment]
How do I do it in AppModule if I only use the global confit?

**Comment by NetanelBasal** [comment]
You have the loader at your disposal: 

```ts
@Injectable({ providedIn: 'root' })
export class HttpLoader implements TranslocoLoader {
  constructor(private http: HttpClient) {}

  getTranslation(langPath: string) {
    return this.http.get<Translation>(defineThePathHere);
  }
}
```

**Comment by bjornharvold** [comment]
Thank you Netanel :-)
