### ISSUE TITLE
StaticInjectorError - InjectionToken TRANSLOCO_TRANSPILER

### ISSUE THREAD

**Issue by wesleygrimes** [ngneat/transloco#152]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I am attempting to use Transloco with a custom loader. My providers array looks like this in my feature module:

```typescript
providers: [
   ...
    localizationLoader,
    {
      provide: TRANSLOCO_CONFIG,
      useValue: {
        availableLangs: ['en', 'es'],
        defaultLang: 'en'
      }
    }
  ],
```

`localizationLoader` is this:

```typescript
import { Injectable } from '@angular/core';
import { SomeService } from '../another/area';
import { TRANSLOCO_LOADER, TranslocoLoader } from '@ngneat/transloco';

@Injectable()
export class LocalizationLoader implements TranslocoLoader {
  constructor(private someService: SomeService) {}

  getTranslation(langPath: string) {
    return this.someService.geti18n();
  }
}

export const localizationLoader = { provide: TRANSLOCO_LOADER, useClass: LocalizationLoader };
```

When I attempt to use the `transloco` pipe in a template. The following error hits the console:

```
ERROR Error: StaticInjectorError(e)[InjectionToken TRANSLOCO_TRANSPILER]: 
  StaticInjectorError(Platform: core)[InjectionToken TRANSLOCO_TRANSPILER]: 
    NullInjectorError: No provider for InjectionToken TRANSLOCO_TRANSPILER!
```

## Expected behavior

Translations should load as expected
## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, for that you could use our [stackblitz example](https://stackblitz.com/edit/transloco-example)

## Environment

<pre><code>
Angular version: 7.2.5

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.12.0
- Platform:  Mac

Others:

</code></pre>

The code is loaded through Angular Elements. Not directly in App Module.

**Comment by wesleygrimes** [comment]
I was able to resolve this by moving the config provider up to the top-level, non-lazy loaded module. Thanks @itayod for your help!

**Comment by Azbesciak** [comment]
But what If I need it to be in lazy module?

**Comment by kenatwex** [comment]
Yes, this one is causing disruption in distributed MFE ecosystem. Im thinking ngx-translate was better choice. Issues are long and exhausting for transloco. It looks like there was lack thereof for documenting token injected sharing of this artifact amongst apps, hosts, remotes and libraries or even the main functionality to implement same. 

So we are attempting to roll our own token injection setup with environment.ts for config and loader to get this shared properly otherwise its a duplication issue that dont hold water with MFE
