### ISSUE TITLE
how to use scope more efficiently

### ISSUE THREAD

**Issue by huantaoliu** [ngneat/transloco#153]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I am migrating from ngx-translate, my translation files structure for example like this

```
i18n
  ---en.json
  ---es.json
   i18n /folder1
           ---en.json
           ---es.json
  i18n /folder2
          ---en.json
          ---es.json
```

In my lazy loaded module, I need translation files from both folder1 and foder2, How can I add scope for both folder1 and folder2 in my LazyModule ?
Currently I can only load one scope a time,
```
{ provide: TRANSLOCO_SCOPE,
  useValue: { scope: 'folder1', alias: 'folder1' } 
}

```
Also, when migrating from existing app, containing many folders under i18n, we have to load scope manully, and use **folder1**.EXISTING.KEY.EVENTHOUGH.UNIQUE | transloco accross the app. It became very easy to omit or make a mistake when migration.

## Expected behavior

1. idealy I can load more than 1 scope a time in my Module

2. it will be great if I dont need to append scopeName before my existing language key
 just use EXISTING.KEY.EVENTHOUGH.UNIQUE | transloco 

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, for that you could use our [stackblitz example](https://stackblitz.com/edit/transloco-example)

## Environment

<pre><code>
Angular version: 8.2.12
transloco: 2.1.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
1. Can you explain the i18n directory structure with a real-world example and the motivation behind it?
2. If you don't have a unique prefix for each scoped key, tools such as the Keys Manager will not be able to find it.

**Comment by huantaoliu** [comment]
For new app, I think it's manageable and reasonable, to put app global shared translation files under root folder, and lazy loaded module load their scope accordingly.

**Comment by NetanelBasal** [comment]
Please prepare a stackblitz example of what you're trying to do.
