### ISSUE TITLE
Transloco v2.5.2: Timing issue with lazy loaded modules 

### ISSUE THREAD

**Issue by bjornharvold** [ngneat/transloco#154]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

1. I'm loading a lazy loaded module and I have a lazy loaded json file
2. When the first component displays it need to convert an enum of strings to their localized values
3. I want to do that in the onNgInit() method
4. I loop through the enum keys and call this.transloco.selectTranslate for each key. 
5. At this point, I get a missing key error
6. If I try to display the key directly using the directive in HTML it works
7. If I add a button to the page and click the button after the page is loaded and call the same method i call in onNgInit() it works
8. If I load some data from the server before translating, giving Transloco some more time, it works
9. If I put the keys in the root json file, it works
9. If I try to translate on AfterViewChecked, it also does not work
10. If I print out the translation on the first line of onNgInit() like this: console.log(this.translate.getTranslation()); I can see the keys I am looking for are in fact already there and available... just not available even though I run selectTranslate directly below.

Not sure if this is a regression issue. I just started noticing it today. My lazy loaded json file is about 300 lines. 

Let me know if you have any other questions.

## Environment
Angular CLI: 8.3.17
Node: 12.12.0
OS: darwin x64
Angular: 8.2.13
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.17
@angular-devkit/build-angular      0.803.17
@angular-devkit/build-ng-packagr   0.803.17
@angular-devkit/build-optimizer    0.803.17
@angular-devkit/build-webpack      0.803.17
@angular-devkit/core               8.3.17
@angular-devkit/schematics         8.3.17
@angular/cdk                       8.2.3
@angular/cli                       8.3.17
@angular/flex-layout               8.0.0-beta.27
@angular/material                  8.2.3
@angular/pwa                       0.803.17
@ngtools/webpack                   8.3.17
@schematics/angular                8.3.17
@schematics/update                 0.803.17
ng-packagr                         5.7.1
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.2

**Comment by itayod** [comment]
@bjornharvold Hi, it is not an issue with Transloco since the translation files are loaded asynchronously.
for your case, I would recommend you to use the `selectTranslate` method which returns an `Observable` of the translation:

```ts
selectTranslate<string>('hello').subscribe(value => ...)
selectTranslate<string>('hello', {}, 'es').subscribe(value => ...)
```

**Comment by itayod** [comment]
@bjornharvold could you please provide us a small reproduction?

**Comment by bjornharvold** [comment]
Would love to but right now I have a bunch of crazy workloads with deadlines. Will revert back to this later. Provided all that I could of info right now before having to move on.

**Comment by itayod** [comment]
> Would love to but right now I have a bunch of crazy workloads with deadlines. Will revert back to this later. Provided all that I could of info right now before having to move on.

Could you at list update the issue with your code?

**Comment by huantaoliu** [comment]
@bjornharvold 
I guess your problem is `selectTranslate()` with lazy loaded scope, it's somewhere is the document but indeed not very discoverable.

for example if you have this i18n structure
```i18n
 i18n/lazy-folder
       --en.json
       --es.json
```

and you load scope in your LazyModule

```
providers: [
    { provide: TRANSLOCO_SCOPE,
      useValue:  {scope: 'lazy-folder', alis: 'lazyFolder'}
     }
  ],
```

Then when you use `selectTranslate()` in the component, you actually need put scopename as the third parameter, and use the original language key as the first param without appending scopeName.
```
this.translocoService.selectTranslate('MY.ORIGINAL.KEY', {}, 'lazy-folder');
```
THIS will have timing issue
`selectTranslate('lazyFolder.MY.ORIGINAL.KEY')`

**Comment by bjornharvold** [comment]
Thank you @huantaoliu. That works nicely :-)
