### ISSUE TITLE
selectTranslation should take alias

### ISSUE THREAD

**Issue by andreaslarssen** [ngneat/transloco#155]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

**Comment by ArielGueta** [comment]
Can you describe what do you mean?

**Comment by itayod** [comment]
@andreaslarssen I am sorry but we won't support alias in `selectTranslate` IMHO it should be only in the template, also we won't be able to know which scope to load.

**Comment by andreaslarssen** [comment]
When configuring a scope, you can add an alias:

```
{
  provide: TRANSLOCO_SCOPE,
  useValue: { scope: 'todos/todoos', alias: 'customName' }
}
```

But if you want to use the service to programmatically translate something, you need to use the setTranslation method. This method does not take an alias, which means that the translation key will be the scope.

On a side note: It seems that if you define a scope on component level, and translate something in the template, then you can use the provided alias when using the service. But if you don't translate anything in the template, you have to use the scope.
