### ISSUE TITLE
Possible to implement TranslocoLoader per scope?

### ISSUE THREAD

**Issue by wesleygrimes** [ngneat/transloco#156]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Is it possible to implement a scoped loader for each lazy loaded feature module I have? I realize you can do es6 `import` loaders, but I would like to implement a separate `TranslocoLoader` for each lazy loaded feature module. 

We are implementing Transloco on a massive mono-repo application where each feature module is managed by a separate team of developers with translations pulled from different backend systems.

## Expected behavior

To be able to implement a separate `TranslocoLoader` per provider scope.

In a perfect world I could do this:

```typescript
// my-feature.loader.ts
import { Injectable } from '@angular/core';
import { TRANSLOCO_LOADER, TranslocoLoader } from '@ngneat/transloco';
import { of } from 'rxjs';

@Injectable({ providedIn: 'root' })
export class MyFeatureLoader implements TranslocoLoader {
  constructor() {}

  getTranslation(langPath: string) {
    return of({ something: 'is' });
  }

}

export const myFeatureLoader = { provide: TRANSLOCO_LOADER, useClass: MyFeatureLoader };
```

```typescript
// my-feature.module.ts
...
@NgModule({
  imports: [CommonModule, TranslocoModule],
  providers: [{ provide: TRANSLOCO_SCOPE, useValue: { scope: 'myFeature', myFeatureLoader } }],
})
export class MyFeatureModule {}
```
## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, for that you could use our [stackblitz example](https://stackblitz.com/edit/transloco-example)

## Environment

<pre><code>
Angular version: 7.2.5

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.12.0
- Platform: Mac

Others:

</code></pre>

**Comment by wesleygrimes** [comment]
I'm currently having to manually load the translations within the `constructor`. Would prefer to have the ability to implement a `TranslocoLoader` per feature module. I tried the inline loader route but could never get it to work.

**Comment by itayod** [comment]
Hi @wesleygrimes you could did you try using the inline loader with `useFactory`?

```ts
export const scope = function(http: HttpClient) {
  const loader =  ['en', 'es'].reduce((acc, lang) => {
    acc[lang] = () => http.get(
      'path/to/translation',
      { params: { fromObject: { lang } } }
    );
    return acc;
  }, {});
  return {scope: 'my-scope', loader: loader}
}

@NgModule({
  imports: [TranslocoModule],
  providers: [
    {
      provide: TRANSLOCO_SCOPE,
      deps: [HttpClient],
      useFactory: loader
    }
  ],
  declarations: [YourComponent],
  exports: [YourComponent]
})
export class FeatureModule {}

```

**Comment by wesleygrimes** [comment]
This works, almost, but I have to return a `Promise` not an `Observable`. Thanks!
