### ISSUE TITLE
Console error when translating root key from lazy module that also load a scope file

### ISSUE THREAD

**Issue by huantaoliu** [ngneat/transloco#158]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
In a lazy loaded module, which also loads a scope file,

when I translate a language key from root en.json in component using `translocoService.translate()`

 I have Error message in console 
`Minsing translation for KEY`

## Expected behavior

should not have the mis-leading error message in my console

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, Here is the example repo [reproduce](https://stackblitz.com/edit/ngneat-transloco-awzlew?file=src%2Fapp%2Flazy%2Flazy%2Flazy.component.ts)

Step 1: click on Lazy button
Step 2: check console log
Step 3: refresh page
Step 4: check lazy.component.ts

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by itayod** [comment]
@huantaoliu That probably a problem of timing since the translation files haven't loaded yet.
Try to use `translocoService.select()` instead

**Comment by NetanelBasal** [comment]
The translations aren't loaded yet. Use `selectTranslate()` or [Prefetch the User Language](https://netbasal.gitbook.io/transloco/recipes/prefetch-the-user-language).

**Comment by huantaoliu** [comment]
Hi @NetanelBasal I have a follow up question, In the example, I tried to Prefetch the user language taking advantage of APP_INITIALIZER.

It solved the problem by using  **prefetch user language** . file directly under folder i18n is getting preloaded. 

The problem now is if I want to  use translate() inside lazy-loaded module( as shown in lazy.component.ts this.service.translate('title')).  Since the scoped file is not pre-loaded, when hard refresh in lazy module, I still have error of missing translation.

So my problem is when using Prefetch the User Language, can we pre-load all languge files including scopes files ?

I know we can use selectTranslate(), but In my case it will be too complicated with many nested subscriptions, it will be nice that we can safely use translate() under lazy loaded module components.

**Comment by NetanelBasal** [comment]
Yes, you can do this:

```ts
export function preloadUser(userService: UserService, transloco: TranslocoService) {
  return function() {
    return userService.getUser().then(({ lang }) => {
      transloco.setActiveLang(lang);
	  const langs = ['en', 'scope/en', 'scopeTwo/en'];
      return Promise.all(langs.map(l => transloco.load(l).toPromise()));
    }
  };
}
```
