### ISSUE TITLE
[transloco-messageformat] Should messageformat be a dependency?

### ISSUE THREAD

**Issue by MatthiasKunnen** [ngneat/transloco#161]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

`messageformat` is currently a peer dependency which means you need to explicitly install it.

## Expected behavior

`messageformat` should be a dependency and as such be installed alongside `@ngneat/transloco-messageformat` by default

## What is the motivation / use case for changing the behavior?

Since messageformat is required it should be a dependency rather than a peer dependency.

If this is intentional I'm interested in the reason behind it.

**Comment by NetanelBasal** [comment]
There is no right or wrong answer in this case. We prefer giving users the freedom to choose the exact version they want to use.

**Comment by MatthiasKunnen** [comment]
Why not use `"messageformat": "*"` in that case?

**Comment by NetanelBasal** [comment]
Because we follow the sem version convention, and we might not support the next major release yet.

**Comment by MatthiasKunnen** [comment]
You said freedom to install exact version so I made it as wide as possible. 

Say there is a dependency `^2.0.0`. By default the latest version with major 2 will be installed (currently 2.3.0). Now in case the user wants `2.1.0`, all they need to do is `yarn add messageformat@2.1.0`. `2.3.0` will no longer be installed as the dependency is satisfied by `2.1.0`. Alternatively [resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions) can be used.

In which scenario would a dependency obstruct the user? 

What I am saying is that you seem to have a specific use case in mind that I either don't grasp and/or that may not apply to most consumers of this package. Not having this as a dependency seems to be more of an obstruction than having it since you have to install `messageformat` manually as well as remove it manually.

**Comment by NetanelBasal** [comment]
In that specific case, you are right. But imagine that this was a wider range such as `>= 1.5.2 < 6`. In this case, maybe the user wants to use a different version from what we've installed by default.

**Comment by MatthiasKunnen** [comment]
That would work if the dependency was `>= 1.5.2 < 6` instead of `^2.0.0` in my example.

**Comment by NetanelBasal** [comment]
I see what you mean. @itayod will change it to dependency.

**Comment by MatthiasKunnen** [comment]
I can make a PR too if you'd like one

**Comment by NetanelBasal** [comment]
Go for it.

**Comment by itayod** [comment]
too late, already fixed that 😁
