### ISSUE TITLE
Support with Nrwl

### ISSUE THREAD

**Issue by M-Blobby** [ngneat/transloco#165]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I'm searching how to use transloco with a project built with Nrwl [https://nrwl.io/](url). I would like to have a folder i18n for my apps and for each libs., but not sure if it's possible.
I checked transloco-with-nx-libs [https://github.com/NetanelBasal/transloco-with-nx-libs](url), but transloco don't work in this project, labels are not displayed.

**Comment by itayod** [comment]
@M-Blobby it should work for you no problem, just use `TranslocoConfig` on the main application and save side project's translations on the assets directory of the main app. 
also for questions, we have a [gitter](https://gitter.im/ngneat-transloco/lobby) channel so for further questions feel free to enter and ask there.

**Comment by mattgek** [comment]
I'm trying to add transloco to our Nx monorepo, but get the following error while doing so. 

Any suggestion to what I'm doing wrong?

![Screen Shot 2021-09-15 at 11 27 12](https://user-images.githubusercontent.com/17617446/133408063-d9609c61-1228-46e2-ba00-144d6047b6be.png)
