### ISSUE TITLE
Code snippets are one-liners on "Installation" step of documentation

### ISSUE THREAD

**Issue by antontemchenko** [ngneat/transloco#166]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

All code snippets are one-liners

## Expected behavior

Code should be multilined

## Minimal reproduction of the problem with instructions

Go to [Installation](https://netbasal.gitbook.io/transloco/installation) step of documentation

## What is the motivation / use case for changing the behavior?

To make code readable

## Environment

Browser:
- [x] Chrome (desktop) version 78.0.3904.97
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 70.0.1
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version 18.17763

**Comment by itayod** [comment]
Hi @antontemchenko it is gitbook's issue, we will notify them about it.

**Comment by NetanelBasal** [comment]
Fixed, thanks.
