### ISSUE TITLE
It's not documented of how to use a scope with a "-" character in it's name

### ISSUE THREAD

**Issue by Dorrro** [ngneat/transloco#170]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

It's not directly possible to use a scope with a "-" character in it. The solution is somewhat not documented - you can use lower camel case notation, like "loginForm" (from "login-form")

## Expected behavior

It should be either possible to use "-" character in a scope name or it should be well documented what characters are allowed and what operations are being done with the scope name itself.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-eq17dy

## What is the motivation / use case for changing the behavior?

Let's say I do have a component called `LoginFormComponent`. By the book it is placed under `login-form` folder. Therefor I'd like to create a specific for that component scope translations. The first thought, at least for me, is that I do create a folder `login-form` and there I place all the translation files.

**Comment by NetanelBasal** [comment]
According to both of your issues, it seems you didn't bother to go through the documentation. We worked hard on it, [reread](https://netbasal.gitbook.io/transloco/lazy-load-translation-files/scope-configuration) it, please.
