### ISSUE TITLE
Scope providers overwrite each other when using shared libraries/modules

### ISSUE THREAD

**Issue by Ketec** [ngneat/transloco#172]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Let's say you have "main" module with "global" scope provider.
It imports a "demo-page" module - that has "demo" scope provider.

In this case, the main scope provider overwrites the "demo-page".

Angular uses the latest provider if the name is the same.

## What is the motivation / use case for changing the behavior?
Multiple, scoped reusable modules (that may come from a lib via npm).

**Comment by montella1507** [comment]
This is very common for angular.. angular provides only:
1) Compoment scoped providers 
2) Global providers (for eagerly loaded modules - aka imports:[]) 
3) module scoped providers (ONLY FOR LAZY LOADED MODULES)

there is really missing a way how to provide truly "ngmodule scoped" providers..

However, afaik this problem can be solved by rewriting transloco providers to be "multi:true" and register all to "singleton - service" which is consumed by pipe "translation selector"..

{
 scope: "x",
 loader:..,
multi:true
}.
{
 scope: "y",
 loader:..,
multi:true
}

...

all providers will register to singleton service and it will be okay...

**Comment by Ketec** [comment]
You mean rewritten in the transloco repository or whoever uses this library (if so, can you provide more details)?

**Comment by montella1507** [comment]
Well i mean:
1) Do not take Scope in pipes (etc.) from Dependency injector.. because there is ALWAYS 1 single value (1 value in eagerly loaded modules and 1 value per lazy loaded module - not usable for reusable libraries at all) 

2) Use Scope only as "lazy loading" and use only Read to select "subset" of finall translation object

**Comment by montella1507** [comment]
Or it may be possible to implement custom loading strategy + use translocoService.setTranslation() to manually combine all files.

**Comment by Ketec** [comment]
The use cases would be like:
MainApp -> lib demofeature -> lib sharedcomponents
MainApp -> lib demofeaturetwo  -> lib sharedcomponents

Each lib, main would need their own scoped translations.
The features themselves would be lazy loaded and used just once - so this works.
But shared is imported so you can use its components.

Also teams have different access - feature teams cannot access main or shared libs.

**Comment by shaharkazaz** [comment]
@Ketec as @montella1507 and the docs stated, scope providers can only be in either a component providers or a lazy-loaded module provider, that's how angular works.
If you need further assistance, please try our [gitter channel](https://gitter.im/ngneat-transloco/lobby?source=orgpage).
