### ISSUE TITLE
VSCode highlights transloco statement as an error

### ISSUE THREAD

**Issue by pnocera** [ngneat/transloco#177]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ x] Other... Please describe:
</code></pre>

## Current behavior

please see attached screenshot
![vscode](https://user-images.githubusercontent.com/118793/69788076-01cea600-11be-11ea-9ff8-9cf028772de1.jpg)

angular 8.2.14
typescript 3.5.3

Angular Language Service VSCode extension 0.900.0

**Comment by shaharkazaz** [comment]
What version are you using?

**Comment by pnocera** [comment]
2.8.0, let me try to upgrade...

**Comment by shaharkazaz** [comment]
@pnocera Seems like that Angular Language Service v0.8 is working fine, use that version (you can choose which version to install), and we will open a bug in their repo.

**Comment by pnocera** [comment]
Thanks !

**Comment by shaharkazaz** [comment]
@pnocera ok so I checked and they don't have a bug for it, feel free to open one so you could keep track.

**Comment by JustinPierce** [comment]
Solved this by reverting to that last 0.800 version of the Angular Language Service extension as suggested by @shaharkazaz. According to the output in VSCode, the 0.900 versions of the extension are using v9.0 release candidates of `@angular/language-service` and `typescript@3.6.3`, which I suspect may be the actual source of the problem.

**Comment by caipirginka** [comment]
There are a few workarounds for this bug inside the Angular Language Service for VSCode and I found this one to actually work:
https://github.com/angular/angular/issues/16643#issuecomment-380837685

To use it for Transloco, the HTML should be like this one:

```
<ng-template transloco let-fn="$implicit">
  <p>{{ trigger(fn,'SETTINGS.TITLE',{name: 'Sam'}) }}</p>
</ng-template>
```

and inside the Component's class:
```
    trigger(callback, ...args) {
        return callback(...args);
    }
```
Any arbitrary name can be used instead of "fn" and "trigger".
It's not very clean and I'm not sure I'd use it, but it may be of interest to somebody...

**Comment by billyjov** [comment]
> @pnocera Seems like that Angular Language Service v0.8 is working fine, use that version (you can choose which version to install), and we will open a bug in their repo.

Switching back to V0.8 solved this issue for me. It's seems like there is an problem using the newest version of the angular language service
