### ISSUE TITLE
VSCode feature request

### ISSUE THREAD

**Issue by pnocera** [ngneat/transloco#179]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ X ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:

</code></pre>

Would love to have a context menu in VSCode editor to add an entry in transloco json file.
That would add the current selection as a new entry in the default language json file and replace the current selection with {{t('<whichever_entry>')}}

I never created a VSCode extension, but if someone points me to a good direction to take...

![vscode1](https://user-images.githubusercontent.com/118793/69854554-ae298e80-1289-11ea-93da-c6ad5d8efd73.jpg)

**Comment by NetanelBasal** [comment]
I like the idea. I imagine something like this:

1. Users choose a text and open the context menu.
2. You display the available translation files.
3. They can select a specific one or all of them.
4. You create the key based on the text (`password-must-have`), and replace it with the pipe.

The implementation should be straightforward. You can start with this [tutorial](https://medium.com/@rmmmsy/your-first-visual-studio-code-extension-ce8e040ba8ca).

**Comment by pnocera** [comment]
ok let me give it a try...

**Comment by pnocera** [comment]
Here's a quick shot
https://marketplace.visualstudio.com/items?itemName=gcidev.translococtx

https://github.com/pnocera/translococtx

**Comment by NetanelBasal** [comment]
I made changes in the extension and added it to our repo. You can continue work on it here. 

- Add support to pass multiple entry points. (for scopes)
- Add the option to choose whether to unflat the key. (use the flat package from npm)

https://github.com/ngneat/transloco/tree/master/vscode/extractor

**Comment by pnocera** [comment]
great ! thanks

**Comment by NetanelBasal** [comment]
Ping

**Comment by NetanelBasal** [comment]
I'm closing the issue. Feel free to open a PR with the rest of the code.
