### ISSUE TITLE
'messageformat' module not found

### ISSUE THREAD

**Issue by mariojsnunes** [ngneat/transloco#18]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When I build my solution, I get these errors:

ERROR in error TS2307: Cannot find module 'messageformat'
ERROR in node_modules/@ngneat/transloco/lib/transpiler-strategies/messageformat.transpiler.d.ts(3,27): error TS2307: Cannot find module 'messageformat'

## How to solve :)
On messageformat.transpiler.ts

Change the MessageFormat  import from this:
> import MessageFormat from 'messageformat';

to this:
> import * as MessageFormat from 'messageformat';

I tried to create a pull request, but couldn't figure out how, sorry!

Thanks!
This package is awesome 👍

**Comment by Coly010** [comment]
Do you have a repo with this bug on it? 
Are you attempting to use the MessageFormatTranspiler?

If not, @shaharkazaz, is it worth re-adding `messageformat` to the list of `peerDependencies`

**Comment by itayod** [comment]
I fixed the issue and published new version :)
@mariojsnunes Thanks for letting us know!
