### ISSUE TITLE
Lazy load multiple JSON files in a component using TRANSLATE_SCOPE

### ISSUE THREAD

**Issue by mohamedaarab1994** [ngneat/transloco#181]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently when I try to lazy load multiple translation json files into one component the app breaks. I have the following situation:

Component A needs two translation json files to render properly, say for example: "TranslationA.json" and "TranslationB.json". For this I provide the file via the providers property in the component decorator using `{ provide: TRANSLOCO_SCOPE, useValue: { scope: 'TranslationA', alias: 'TranslationAlias'} }`. When I add the `multi: true` property, it doesn't seem to work.

## Expected behavior
When I use `multi: true` when providing TRANSLOCO_SCOPE I should be able to lazy load multiple translation json files.

## Minimal reproduction of the problem with instructions

`    {
      provide: TRANSLOCO_SCOPE,
      useValue: { scope: 'translationA', alias: 'translationAliasA' },
      multi: true
    },
    {
      provide: TRANSLOCO_SCOPE,
      useValue: { scope: 'translationB', alias: 'translationAliasB' },
      multi: true
    }`

This breaks.

## What is the motivation / use case for changing the behavior?

It would make the libary even better than it is if you can lazy load multiple files in one component.

## Environment

<pre><code>
Angular version: 7

Browser:
- [x] Chrome (desktop) version 78.0
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.16
- Platform:  Windows

Others:
</code></pre>

**Comment by itayod** [comment]
Hi @mohamedaarab1994 
basically there are two ways you can accomplish that depends on your use case:
1. if you are using inline loaders you could do that with `webpack` import's [magic comments](https://webpack.js.org/api/module-methods/#magic-comments)
2. you could use an inline scope in the component's template:
```html
<div *transloco="let t; scope: 'scope'">
  <h1> {{ t('scope.title') }} </h1>
</div>

<div *transloco="let t; scope: 'scope2'">
  <h1> {{ t('scope2.title') }} </h1>
</div>

```

**Comment by mohamedaarab1994** [comment]
@itayod I prefer the inline loader option you mentioned, however for that I still need to provide multiple values for TRANSLOCO_SCOPE token (correct me if I'm wrong). That seems to be giving me a heap of trouble. This is how I do it:

`{ provide: TRANSLOCO_SCOPE, useValue: { scope: 'translationA', loader: loadTranslationFile('translationA'), alias: 'translationAliasA' }, multi: true}, 
{ provide: TRANSLOCO_SCOPE, useValue: { scope: 'translationB', loader: loadTranslationFile('translationB'), alias: 'translationAliasB' }, multi: true}`

**Comment by itayod** [comment]
@mohamedaarab1994 we currently don't support that, would you like to open a pr for this?

**Comment by mohamedaarab1994** [comment]
@itayod If I get it working, I will submit a PR for this
