### ISSUE TITLE
Page animation with template loader seems broken

### ISSUE THREAD

**Issue by C0ZEN** [ngneat/transloco#182]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When switching page with a global Angular animation, the template loader is not static to the page.  
It is display outside it like if the template loader is absolute to the page and also slow down by the animation.

## Expected behavior

When switching page with a global Angular animation, the template loader should be static.

## Minimal reproduction of the problem with instructions

Seems hard to me to create a reproduction.
Nevertheless, you can checkout this video of the problem:

https://drive.google.com/file/d/1jAemWOVwwRmvUFfppCYQ86Q9LC-WnUqE/view?usp=sharing

## Environment

<pre><code>
Angular version: 8.2.14

Browser:
- [x] Chrome (desktop) version 78.0.3904.108
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.3.1
- Platform:  Windows

</code></pre>

## Others:

I am not sure that this is an issue from this library so this is the reason for the support request flag.  

## What I Tried

- Adding `transition: none !important` and `animation: none !important` to the `.transloco-loader-template` class.
- Changing a bit the animation code

## Code

animation.ts
```typescript
import {
  animate,
  animateChild,
  group,
  query,
  style
} from '@angular/animations';

export const ANIMATION = [
  style({
    position: 'relative'
  }),
  query(':enter', [
    style({
      height: '100vh',
      left: 0,
      overflow: 'hidden',
      position: 'fixed',
      top: 0,
      width: '100%'
    })
  ]),
  query(':leave', [
    style({
      height: '100vh',
      left: 0,
      overflow: 'hidden',
      position: 'absolute',
      top: 0,
      width: '100%'
    })
  ]),
  query(':leave', [
    style({
      transform: 'translateX(0%)'
    })
  ]),
  group([
    query(':enter', [
      style({
        'overflow-x': 'hidden',
        'overflow-y': 'hidden',
        'z-index': 0
      })
    ]),
    query(':leave', [
      style({
        'overflow-x': 'hidden',
        'overflow-y': 'hidden',
        'z-index': 1
      }),
      animate('350ms ease-out', style({
        transform: 'translateX(100%)'
      }))
    ])
  ]),
  query(':enter', animateChild())
];
```

app.component.html
```html
<div [@routeAnimations]="prepareRoute(outlet)">
  <router-outlet #outlet="outlet"></router-outlet>
</div>
```

app.component.ts
```typescript
public prepareRoute(routerOutlet: RouterOutlet): string {
    return routerOutlet && routerOutlet.activatedRouteData && routerOutlet.activatedRouteData[ 'animation' ];
  }
```

**Comment by itayod** [comment]
@C0ZEN sorry but it is not an issue that related to this library

**Comment by C0ZEN** [comment]
Just in case someone have the same problem.  

I found a solution by adding a class to the `body` which will hide all the loader templates only during the animation.

*class*
```css
.transloco-loader-template {
      display: none !important;
}
```

Then add some outputs to hide or show this class on the router outlet.

*app.component.html*
```html
(@routeAnimations.start)="animationStart()"
(@routeAnimations.done)="animationEnd()"
```

**Comment by C0ZEN** [comment]
A real fix is available.
