### ISSUE TITLE
getAvailableLangs() documentation & feature request

### ISSUE THREAD

**Issue by SansDK** [ngneat/transloco#183]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[X] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Calling `getAvailableLangs()` returns either a `string[]` or something like `[{ id: 'en', label: 'English' }, { id: 'es', label: 'Spanish' }]`. This makes it difficult to use this method to check if a saved language is available to use within the app (when persisting language outside of the `@ngneat/transloco-persist-translations`).

The documentation also lacks information about this method, only stating `Gets the available languages:`, without giving any information on the return type(s), and how to actually use it to check if a language is available for example.

## Expected behavior

First of all I expect better documentation on `getAvailableLangs()` than almost literally the method name with spaces. 

Secondly, I would like to see a method like `isAvailableLang(string)`, to check if a given string is included in the specified availableLangs (+ lowercase on both language abbreviations would be nice to have).

## What is the motivation / use case for changing the behavior?

When using a custom way of persisting a language, it doesn't seem right to just call `setActiveLang(...)` without knowing if the specified language is even an available language. To prevent all kind of errors it would be nice to have a solid way of checking the specified language.

## Environment

<pre><code>
Angular version: not applicable

Browser:
- [X] not applicable

**Comment by itayod** [comment]
Hi @SansDK 
As for the documentation, since we have types support thanks to typescript, we get this documentation out of the box.

About the function, we have a method `isLang` for this, but it currently private method, you are welcome to create a pr that expose this method if you like

**Comment by SansDK** [comment]
Hi,
Thanks for your response.

It's nice to get documentation like this out of the box, but that doesn't mean that you can't or shouldn't edit it to clarify the working or the usage of the method.

I will create a PR for exposing the `isLang` method if I have the time to do so.

Thanks.

**Comment by SansDK** [comment]
Hi @itayod @NetanelBasal,

if any one of you have the time to check out the pull request that would be greatly appreciated.
Thanks.

**Comment by SansDK** [comment]
@NetanelBasal, thanks for merging the PR.
I noticed that a new build hasn't been triggered after the merge. Could you trigger a new build manually? Or was it the intention to not release a new version for only this PR?

Thanks.

**Comment by itayod** [comment]
@SansDK we are waiting for https://github.com/ngneat/transloco/pull/184 to release the new version with your changes

**Comment by SansDK** [comment]
Ok that's fine!
Thanks for the update.
