### ISSUE TITLE
Resolved translations are not re-used when using different aliases

### ISSUE THREAD

**Issue by mohamedaarab1994** [ngneat/transloco#187]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Whenever you provide an alias in a component/module using `TRANSLOCO_SCOPE`, it causes the other pages that use the same translation file without an alias to break. After debugging I found out that you only have one scope key per translation file, meaning you have to always use `scope` or always use `alias` if you want your translations to be fine. In the video below you can see the behaviour:

https://www.youtube.com/watch?v=BX3WfFI7ZXg

## Expected behavior

You should be able to provide a different alias or ignore the alias in specific use-cases without breaking the translation file.

## Minimal reproduction of the problem with instructions

The video demonstrates it: https://www.youtube.com/watch?v=BX3WfFI7ZXg

## What is the motivation / use case for changing the behavior?

To make this library even better and get to use `aliasses` and `scopes` together in harmony :)

## Environment

<pre><code>
Angular version: 7.2.15

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.16.0
- Platform:  Windows

Others:

</code></pre>

**Comment by itayod** [comment]
@mohamedaarab1994 it seems like an odd usage of scopes, could you tell us what is your use case?

**Comment by mohamedaarab1994** [comment]
@itayod Right now we have a lot of translation files in our projects so we seperated these files into two folders: "Pages" and "Features". Our scopes look like this: "features/offer-information" which is inconveniant to use, so we give every translation an alias, however we have many people maintaining our project and not everybody uses the same alias and therefore they leave buggy or non-working code behind.

**Comment by ArielGueta** [comment]
That's does not make sense. Scopes and aliases are meant to be unique. If you have a problem sharing these, you can create an object and use it:

```ts
{
  offerInformation: { scope: '', alias: '' }
}
```

And let everyone use this one source of truth.

**Comment by mohamedaarab1994** [comment]
@ArielGueta You're missing the point. Perhaps I didn't make myself clear enough. Let me explain the behavior in a scenario:

There are two pages that are lazy loaded, we'll call them `GeneralInformationComponent` and `PriceInformationComponent`. We also have a translation file named `offer-information.json` that is shared among these two pages. 

In the page `GeneralInformationComponent` we want to define the scope like this:

`{ provide: TRANSLOCO_SCOPE, useValue: { scope: 'offer-information', alias: 'OfferInformationGeneral'}},` and use it in our view like this: `{{'OfferInformationGeneral.Content' | transloco}}`

in the page `PriceInformationComponent` we want to definte the scope like this:

`{ provide: TRANSLOCO_SCOPE, useValue: { scope: 'offer-information', alias: 'OfferInformationPrice'}},` and use it in our view like this: `{{'OfferInformationPrice.Content' | transloco}}`

If you were to navigate to these pages via router navigation (going from PriceInformationComponent to GeneralInformationComponent) Only one of these pages would load in the translation file while the other page would show you the translation key, because the translation file was registered by the first served component. There is a cache system that checks whether a file has loaded or not regardless of what scope or alias you assign to the file and prevents it from loading the file again. This causes the transloco library to assign the file to only one key (in this case to `OfferInformationPrice`, because you were visitting `PriceInformationComponent` first).

The video also demonstrates this behavior.

**Comment by ArielGueta** [comment]
To be honest, this is weird. You are using the same translation file in two places with a different alias?  If you load both, you will have a duplicate object in memory.

**Comment by mohamedaarab1994** [comment]
@ArielGueta That's right, we need to use the same translation file in two places with a different alias, because that's what aliases are for right? To distinguish one from the other. However, duplaticate objects in memory isn't cool either. It would be nice if there was one object in memory that has many aliases assigned to it. It isn't that weird if you think about it. A person can also have multiple names and while still having one body. Same concept can be applied to the translation files

OfferInformationGeneral -> offer-information.json
OfferInformationPrice ->offer-information.json

**Comment by itayod** [comment]
Hi @mohamedaarab1994 we decided that we won't support this feature.
Scope alias should be unique across the project

**Comment by chriszrc** [comment]
@itayod I'm running into a related issue. I'm started to use route resolves to preload translation files using `translocoService.load()`, but the translations stop working when I use that approach, because originally the components were just using translations in the templates, so adding:

`    {provide: TRANSLOCO_SCOPE, useValue: {scope: "upload/uploadForm", alias: "uploadForm}},`

and using:

`t(uploadForm.mykey)`

worked just fine. However if I try to preload the translations, the load() method apparently doesn't have the option of using a custom alias, and because the translations are already loaded now, the component doesn't also load the translations again under the custom alias, so all the template translations are broken. I could update the template translations to match the default "alias" you get when calling load():

`t(uploadUploadForm.mykey)`

but that's annoying. Is there any way to set an alias when using load()?
