### ISSUE TITLE
translate is undefined.  I want to use it as a pure function.

### ISSUE THREAD

**Issue by heecheolman** [ngneat/transloco#191]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

> [transloco DOC] You don't have to inject the service each time you need to translate a key. Transloco has an exported translate() function:

`translate` provided as a pure function does not work. Sometimes it works, but when I'm not sure, I refresh the browser and get an error.

```ts
let service: TranslocoService;

export function translate<T = any>(key: TranslateParams, params: HashMap = {}, lang?: string): T {
  // service is undefined
  return service.translate(key, params, lang);
}
```

## Expected behavior

I want to use it as a pure function.

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, for that you could use our [stackblitz example](https://stackblitz.com/edit/ngneat-transloco-5zqhv5?file=src/app/app.component.ts)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by itayod** [comment]
@heecheolman it doesn't suppose to happen, can you show us how do you use it?

**Comment by mohamedaarab1994** [comment]
I'm having the same issue. Sometimes it works and sometimes it doesn't. When refreshing the page, the value is always either undefined or the name of the key.

**Comment by ArielGueta** [comment]
@mohamedaarab1994 I don't think your issue is related to this one. The translate function works only if you already loaded the translation before calling it. It's sync function.

**Comment by heecheolman** [comment]
But the documentation says that it can be used as a pure function.

In the code below, the service variable is defined outside of the service class scope

```ts
let service: TranslocoService;

export function translate<T = any>(key: TranslateParams, params: HashMap = {}, lang?: string): T {
  // service is undefined
  return service.translate(key, params, lang);
}
```

**Comment by heecheolman** [comment]
> @heecheolman it doesn't suppose to happen, can you show us how do you use it?

stackblitz example code is being used in `app.module.ts.`

**Comment by ArielGueta** [comment]
From the docs: 

> Note that in order to safely use this method, you are responsible for ensuring that the translation files have been successfully loaded by the time it's called. If you aren't sure, you can use the selectTranslate() method instead:

**Comment by itayod** [comment]
From what I have saw in your StackBlitz, you try to use the translate before the service beed initialized.
You **must** wait until you initial the service in order to use this method
