### ISSUE TITLE
Feature Request: Implement provideTranslocoConfig

### ISSUE THREAD

**Issue by wesleygrimes** [ngneat/transloco#195]
I would be willing to submit a PR to implement the solution mentioned below. Curious to know your thoughts.

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently adding the `TRANSLOCO_CONFIG` is done by manually constructing a provide object.

```
providers: [
        {
          provide: TRANSLOCO_CONFIG,
          useValue: {
            availableLangs: ['en-us', 'es-us', 'fr-ca', 'en-ca'],
            defaultLang: 'en-us',
            fallbackLang: 'en-us',
            prodMode
          } as TranslocoConfig
        },
        ...
]
```

## Expected behavior

It would be nice to have a method like `provideTranslocoConfig({...config})` that is provided by the library. Similar to how NgRx has `provideMockStore`, etc...

## Minimal reproduction of the problem with instructions

Not a bug

## What is the motivation / use case for changing the behavior?

By providing a method we can avoid type coercion and potentially misconfigured config objects and instead do:

```
providers:[
  provideTranslocoConfig({
    availableLangs: ['en-us', 'es-us', 'fr-ca', 'en-ca'],
    defaultLang: 'en-us',
    fallbackLang: 'en-us',
    prodMode
  }),
  ...
]
```
## Environment
All

**Comment by itayod** [comment]
Hi @wesleygrimes thanks for the suggestion,

We like the idea 😃

Feel free to open a PR for this. We also would like to make that as default, so make sure to update the ng-add command too.

**Comment by wesleygrimes** [comment]
Awesome, I will work on a PR!
