### ISSUE TITLE
How could I wrap the transloco pipe or rename it?

### ISSUE THREAD

**Issue by cesalberca** [ngneat/transloco#199]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

To translate in templates I have to use the `transloco` pipe. Is there any possible way to rename or wrap it around my own pipe like as follows?

```ts
import { Pipe } from '@angular/core'
import { TranslocoPipe } from '@ngneat/transloco'

@Pipe({
  name: 'translate'
})
export class TranslatePipe extends TranslocoPipe {}
```

This is a way people found out to rename external pipes: https://stackoverflow.com/questions/52470434/using-a-pipe-under-a-different-name. However when I try it stops working.

Cheers on the library, best library for translations in Angular right now! ;)

## Expected behavior

I should be able to extend TranslocoPipe with a custom pipe and it should still work, or be able to wrap it.

**Comment by NetanelBasal** [comment]
```ts
@Pipe({
  name: 'translate',
  pure: false
})
export class TranslatePipe extends TranslocoPipe {}
```

I wouldn't recommend doing this. Some devtools rely on this name.

**Comment by cesalberca** [comment]
Thanks! That's what I was looking for.
