### ISSUE TITLE
Feature Request - add a fallback value when the translation path does not exists

### ISSUE THREAD

**Issue by Newbie012** [ngneat/transloco#201]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I have a set of strings that some of them needs to be translated, and if they don't exist in the translation path, I want to present a different value (in this case, the key itself).

## Expected behavior
Something like:
```
<ng-container *transloco="let t; read: 'keys'">
  <ng-container *ngFor="let key of ['knownKey', 'unkownKey']">
    {{ t(key, {fallback: 'Unknown Key'}) }}
  </ng-container>
</ng-container>
```

## Minimal reproduction of the problem with instructions
Shown in expected behavior.

## What is the motivation / use case for changing the behavior?
Sometimes I fetch the "keys" from my database and some of them are already "localized". So, in this case, I will write

```
{{ t(key, {fallback: key}) }}
```

## Environment

<pre><code>
Angular version: 9.0.0-RC4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by itayod** [comment]
see: https://app.gitbook.com/@netbasal/s/transloco/hack-the-library/transloco-missing-handler

**Comment by AmitMY** [comment]
@itayod That page you linked is 404

**Comment by itayod** [comment]
Try now

**Comment by AmitMY** [comment]
Thanks @itayod 
This solution is insufficient though - 

Given the code `t('organizations.organization.providers.dialogs.credentials.clientId', {fallback: "Client ID")`

with the following handler

```ts
export class CustomTranslocoMissingHandler extends DefaultHandler implements TranslocoMissingHandler {
  handle(key: string, config: TranslocoConfig) {
    console.error(key, config);
    return super.handle(key, config);
  }
}
export const customTranslocoMissingHandler = {
  provide: TRANSLOCO_MISSING_HANDLER,
  useClass: CustomTranslocoMissingHandler
};
```

I don't see the fallback passed anywhere, so I can't use it.


![image](https://user-images.githubusercontent.com/5757359/70987756-3a7ce380-20c9-11ea-9590-c995f922651c.png)

**Comment by itayod** [comment]
@AmitMY it doesn't work because you are using it wrong:
1: the second param of the function `t` is the parameters of the translations, so if the key is missing then the `params` are irrelevant.
2: from docs: **returns an empty string to use as a replacement for the missing key's value.**
and if you need to customize it you will need to return a replacement value:

```ts
export class CustomTranslocoMissingHandler extends DefaultHandler implements TranslocoMissingHandler {
  handle(key: string, config: TranslocoConfig) {
    return 'My replacement value for missing key';
  }
}
```

**Comment by AmitMY** [comment]
Thanks @itayod ,
I don't agree - design-wise - that the params should be discarded in this handler. It makes sense to get everything I sent to the function `t`.

In my case for example, I have a key, that is known, but I also have a fallback value, and passing this fallback value is currently not possible, therefore `TranslocoMissingHandler` is not a viable solution right now. 

This key/fallback value comes from a remote server, and I already have it in the context of that function.

**Comment by itayod** [comment]
@AmitMY by what you have described in the issue, this is the default behavior of Transloco (when Transloco doesn't find the translation `key` it simply returns the `key`).

If it is not the case, please provide a stackblitz example that illustrates your use case.

**Comment by Newbie012** [comment]
@itayod Not entirely correct. It returns the whole **path** (with the key) instead of just the key

**Comment by itayod** [comment]
@Newbie012 could you provide a stackblitz example of your use case?

**Comment by AmitMY** [comment]
Sure, stackblitz:
https://stackblitz.com/edit/transloco-example-hb9f94?embed=1&file=src/app/on-push/on-push.component.html

Relevant code in `on-push`:
```html
<ng-container *transloco="let t">
  <ul class="list-group">
    <li class="list-group-item" data-cy="regular"><b>Return `home english`: </b>{{ t('nested.home', {fallback: 'home spanish'} ) }}</li>
    <li class="list-group-item" data-cy="regular"><b>Return `house localized`: </b>{{ t('nested.house', {fallback: 'house localized'} ) }}</li>
  </ul>
</ng-container>
```

Output:
![image](https://user-images.githubusercontent.com/5757359/71073878-ea198a80-2189-11ea-9717-6bfbc0b3164f.png)

**Comment by itayod** [comment]
@AmitMY 
IMHO using `t('nested.house', {fallback: 'house localized'} )` would be an abuse usage for the translation parameters.

to solve your problem you could custom the missing keys to return `null` for missing values:
```ts
export class CustomHandler implements TranslocoMissingHandler {
  handle(key: string, config: TranslocoConfig) {
    return null;
  }
}
```
Then in the HTML:
```html
  t('nested.house') || 'house localized'}}
```

**Comment by AmitMY** [comment]
I accept your solution, even though it would be nice to know if a fallback exists or not (to show the default "key is missing error")

Thanks.

**Comment by itayod** [comment]
> I accept your solution, even though it would be nice to know if a fallback exists or not (to show the default "key is missing error")

You are welcome,
If you like to know if a key is missing, you could add `console.warn` before the `return`.

Let me know if you have any trouble with this solution going forward.

**Comment by depyronick** [comment]
> @AmitMY
> IMHO using `t('nested.house', {fallback: 'house localized'} )` would be an abuse usage for the translation parameters.
> 
> to solve your problem you could custom the missing keys to return `null` for missing values:
> 
> ```ts
> export class CustomHandler implements TranslocoMissingHandler {
>   handle(key: string, config: TranslocoConfig) {
>     return null;
>   }
> }
> ```
> 
> Then in the HTML:
> 
> ```
>   t('nested.house') || 'house localized'}}
> ```

maybe this should be the default behavior or maybe a simple boolean config option to return null for missing keys instead of key itself.
