### ISSUE TITLE
Scoped Library Extractor breaks build at CI (in docker container)

### ISSUE THREAD

**Issue by niklissad** [ngneat/transloco#204]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

At CI builds library extractor fails with error
```
> xxx@0.0.0 transloco:extract-scoped-libs /home/www
> transloco-scoped-libs

Starting Transloco Scoped Libs...
✅ Copy translation from file: /libs/core/src/lib/i18n/en.json to: /apps/panel/src/assets/i18n/core/en.json
internal/fs/utils.js:220
    throw err;
    ^
Error: ENOENT: no such file or directory, open '/home/www/.gitignore'
```

## Expected behavior

Library extractor didn't break build at CI

## Minimal reproduction of the problem with instructions

Setup GitLab CI and try to build application in Docker with PROD env

## What is the motivation / use case for changing the behavior?

Wee need a key to don't change gitignore or just warning/silent skip

## Environment

<pre><code>
Angular version: 8.2.14
@ngneat/transloco-scoped-libs: 1.1.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12
- Platform: node:alpine in Docker

</code></pre>

**Comment by itayod** [comment]
Hi @niklissad, I have fixed that and released a new version.
You are welcome to try and let us know if you run into another issue :)
