### ISSUE TITLE
setActiveLang not being applied to translations in component ts files

### ISSUE THREAD

**Issue by ygeelen-tb** [ngneat/transloco#205]
The setActiveLang method (language switching) is working for translations in views.
However, translations in the components (TypeScript) using translocoService.translate are not being translated when calling setActiveLang ?

I set the reRenderOnLangChange to true though, both in the app module bootstrapping and in the transloco.config.js

Am I missing something?

**Comment by shaharkazaz** [comment]
@ygeelen-tb the translate function is a synchronous function and after the execution, it will not change the value again. if you need your programmatically translations to listen to language changes you need to use observables and [selectTranslate](https://netbasal.gitbook.io/transloco/service-api/translation-api).
