### ISSUE TITLE
Git tags are missing for releases > 2.8.0

### ISSUE THREAD

**Issue by timbru31** [ngneat/transloco#208]
#15  I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x] Other... Please describe:
</code></pre>

## Current behavior

The most recent git tag is 2.8.0, while the most recent npm release is 2.12.1

## Expected behavior

The git tags for 2.12.1, 2.12.0, 2.11.2, 2.11.1, 2.11.0, 2.10.0 and future releases are provided, too.

## Minimal reproduction of the problem with instructions

n/a

## What is the motivation / use case for changing the behavior?

I'm using GitHub's "Watch releases" feature, but missing updates with this.

## Environment

n/a

**Comment by itayod** [comment]
Hi @timbru31 I have updated the tags, thanks for noticing

**Comment by timbru31** [comment]
Great, thanks for the quick fix!

Merry Christmas to all of you 🎁
