### ISSUE TITLE
translocoLang attribute ignored when switching language

### ISSUE THREAD

**Issue by rraziel** [ngneat/transloco#212]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The `translocoLang` attribute is not taken into account when switching language dynamically (but it does work properly for the "initial" language).

## Expected behavior

The `translocoLang` attribute should be taken into account after switching language.

## Minimal reproduction of the problem with instructions

1. Have 2 languages
2. Loop through available languages, using transloco and translocoLang attributes to display the language from its own translation file (take english from en.json, spanish from es.json)
3. Upon initialization English and Espanol are properly displayed
4. When clicking on either button, they both get translated to the new language, ignoring the `translocoLang` attribute

Demo available at https://transloco-example-bo5nz7.stackblitz.io/home (cf. language buttons in `application.component.html`)

## What is the motivation / use case for changing the behavior?

Displaying each available language in its own language is convenient from a UX point of view.

## Environment

<pre><code>
Angular version: 8.2.0

Browser:
- [x] Chrome (desktop) version 79.0.3945.88
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 11.8.0
- Platform: Windows

Others:
</code></pre>

Also: very nice library, had given up on Angular 2+ internationalization after leaving ng-i18next from Angularjs

**Comment by itayod** [comment]
@rraziel did you try to use `static`?
see in [docs](https://netbasal.gitbook.io/transloco/general/using-multiple-languages-simultaneously)

**Comment by rraziel** [comment]
Using `[translocoLang]="availableLanguage + '|static'"` seems to work, although I'm not quite sure I understand what `static` does (from the documentation page you linked to).

**Comment by itayod** [comment]
I am glad to hear that it is working for you now :)
