### ISSUE TITLE
Structural directive / pipe performance question

### ISSUE THREAD

**Issue by a-legrand** [ngneat/transloco#213]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x] Other... Please describe: performance question
</code></pre>

## Current behavior

Hello :)
Just a question: why is the structural directive recommended over the pipe?
And to be more precise: is the structural directive called everytime a change is triggered on a component? I can see that the transloco pipe is impure, and I don't know how the structural directive can overload my app or not (I need a solution with strong optimizations as my current custom impure pipe is now an issue)
Thanks!

**Comment by itayod** [comment]
You have all the answers in the [doc](https://netbasal.gitbook.io/transloco/translation-in-the-template/structural-directive).

✅ it is DRY as it creates **one** subscription per template
✅ it uses less memory from the same reason
✅  `t` function is memoized

For further questions, we have a [gitter channel](https://gitter.im/ngneat-transloco/lobby).
Or simply can ask in `stackoverflow`
