### ISSUE TITLE
transloco per module

### ISSUE THREAD

**Issue by jmo3300** [ngneat/transloco#214]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[x] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

An app has several (let's say) working modules.
These working modules should have their own i18n repository / services.
Despite using a separate transloco-root.module in each working module only the latter transloco is used for all modules.

## Expected behavior
transloco should be able to handle i18n per module at least to manage a repository per working module.

## Minimal reproduction of the problem with instructions

see https://github.com/jmo3300/ng01_i18n_tranloco02, there doc/dev_log.md.

## What is the motivation / use case for changing the behavior?

An i18n solution which can be applied per module.

For keeping the independance of the applications modules an i18n solution should be able to serve modules independant from the actual application they are used in. An i18n solution must not couple independant modules with a centralized i18n functionality / repository spanned over the whole application. Each (multilingual) module should have and should use its own translation repository / service. This keeps the modules decoupled. The modules can be developed and internationalized independently.

## Environment

-   Angular-CLI         8.3.14
-   node.js             12.13.0
-   npm                 6.12.0

Browser:
- [x] Chrome (desktop) version 79.0.3945.88
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v12.13.0
- Platform:  Windows 10

Others:

CLI input during installation does not work fine.
Documentation and actual result of  transloco installtion do not match.

see also dev-log.md at  https://github.com/jmo3300/ng01_i18n_tranloco02

**Comment by itayod** [comment]
@jmo3300 if I understand correctly what you are trying to do then you are doing it wrong, **You should not have more than one `transloco-root`.** (that is why it called **root**...).

Take the time to read the [documentation](https://netbasal.gitbook.io/transloco/lazy-load-translation-files/scope-configuration) of how it should be done, or read my [blog](https://medium.com/angular-in-depth/lazy-load-and-encapsulate-i18n-files-in-angular-with-transloco-55af44885797) that include a complete guide of managing the i18n files
