### ISSUE TITLE
Small IDE question

### ISSUE THREAD

**Issue by dertuerke** [ngneat/transloco#215]
Hello, is it normal that Webstorm returns this error message?

Unfortunately I don't understand why I get this error message

`"@ngneat/transloco": "~2.12.0"`

![image](https://user-images.githubusercontent.com/2199151/72059334-15e3e800-32d2-11ea-9a9e-0a4a6c674acf.png)

**Comment by NetanelBasal** [comment]
I guess it's related to your IDE version or something. It works fine in our projects.

**Comment by NetanelBasal** [comment]
Try to open an issue, and maybe they will help.
