### ISSUE TITLE
transloco-scoped-libs always adds an entry to the .gitignore file

### ISSUE THREAD

**Issue by Dorrro** [ngneat/transloco#216]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Running `transloco-scoped-libs` command always results with an entry in the `.gitignore` file. There's no option to omit that part of the process.
https://github.com/ngneat/transloco/blob/master/projects/ngneat/transloco-scoped-libs/index.js#L138

## Expected behavior

Since we do have our own `.gitignore` rules, we do not want to add unnecessary entries to the file. Having an option to skip adding entry to the `.gitignore` would be much appreciated

**Comment by itayod** [comment]
Would you like to create a pr for this?

**Comment by Dorrro** [comment]
I'll try, sure

**Comment by itayod** [comment]
I have published a new version `1.2.0`. You can now use the `--skip-gitignore` flag to unmodify the gitignore.
