### ISSUE TITLE
Lib with translation but app without

### ISSUE THREAD

**Issue by sidyes** [ngneat/transloco#218]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have a NX workspace with multiple apps and libs. 
Some of the libs got their own translations and are lazy loaded into the app (I followed **[this example](https://github.com/NetanelBasal/transloco-with-nx-libs)**).  
It is working fine but when I have an app without translation the lazy loaded translations cannot be loaded (receiving a 404 not found).

It seems that the lazy loaded lib wants to import the translation files into the translation files of the application (which do not exist).

Do you have an idea how I can use the translations of the lazy loaded file without having translation files in the main app?

## Expected behavior

Translations of libraries can be used even though the app itself does not contain any translations?

## Minimal reproduction of the problem with instructions

Setup a NX workspace like in the example above and remove the assets/i18n folder from it.

I hope you can help me.

**Comment by adgoncal** [comment]
As far as I understand, the issue is the translation files are fetched from your app's `assets/i18n`. If the translation files are not there, then it will 404. There are a few solutions:
1. Use [inline loader](https://netbasal.gitbook.io/transloco/lazy-load-translation-files/inline-loaders) - but then the translation files are bundled with the typescript during build.
2. Use [scopedLibs](https://netbasal.gitbook.io/transloco/tools/scoped-library-extractor) - but then you need to add a package.json to each lib, and run the scoped library extractor whenever a key is added/modified. This also adds many entries to `.gitignore`.
3. Keep all translations in your app's `assets/i18n` directory to begin with - but then they are not easily re-usable among different apps.

**Comment by sidyes** [comment]
> As far as I understand, the issue is the translation files are fetched from your app's `assets/i18n`. If the translation files are not there, then it will 404. There are a few solutions:
> 
> 1. Use [inline loader](https://netbasal.gitbook.io/transloco/lazy-load-translation-files/inline-loaders) - but then the translation files are bundled with the typescript during build.
> 2. Use [scopedLibs](https://netbasal.gitbook.io/transloco/tools/scoped-library-extractor) - but then you need to add a package.json to each lib, and run the scoped library extractor whenever a key is added/modified. This also adds many entries to `.gitignore`.
> 3. Keep all translations in your app's `assets/i18n` directory to begin with - but then they are not easily re-usable among different apps.

1. The thing is that I am using inline-loaders in my libs.  I lazy load a module from a local library into my app and have TRANSLOCO_SCOPE in my library provided with a loader. It does not work when I do not have a translation in my main ap...
2. By now, I am not really keen on in copying all that stuff since libs are working when the app that is using them also contains translations.
3. Not an option for us.

I am not sure why option 1 is not working for me.

**Comment by sidyes** [comment]
Update: nevermind it is working with inline loaders, I just need to preload the default language in the main app. 💯

**Comment by ArielGueta** [comment]
@adgoncal Use inline loader - but then the translation files are bundled with the typescript during build.

That's not true. It will lazy load them.

**Comment by adgoncal** [comment]
> @adgoncal Use inline loader - but then the translation files are bundled with the typescript during build.
> 
> That's not true. It will lazy load them.

@ArielGueta yes, it is lazy-loaded, but not from a json. It is part of the js file generated for that lazy-loaded lib bundle during build. This might be ok for others, but my workflow is to join all en translation files into one single file and send that to the translation agency, and then split the translated files and put them in the dist assets.
