### ISSUE TITLE
Test the library with AOT and SSR

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/transloco#22]

**Comment by NetanelBasal** [comment]
General:
- Check that this works: `{{ 'Hello {{ name }}' | translate: { name: 'Srinivas' } }}`
- https://github.com/ngx-translate/core/issues/1101
- https://github.com/ngx-translate/core/issues/1011
- https://github.com/ngx-translate/core/issues/374
- https://github.com/ngx-translate/core/issues/789
- https://github.com/ngx-translate/core/issues/520
- https://github.com/ngx-translate/core/issues/224

**Comment by NetanelBasal** [comment]
https://github.com/ngx-translate/core/issues/570

**Comment by NetanelBasal** [comment]
Get translation of multiple keys

**Comment by shaharkazaz** [comment]
@NetanelBasal you don't want to separate the issues here?

**Comment by NetanelBasal** [comment]
Yes. I need to check them first
