### ISSUE TITLE
Passing translated collection data to angular input attribute.

### ISSUE THREAD

**Issue by secabhi** [ngneat/transloco#220]
Hi I have a reusable component which generated key value pair
Like below
<img width="213" alt="Screen Shot 2020-01-20 at 2 22 45 PM" src="https://user-images.githubusercontent.com/3812742/72712170-81f70380-3b90-11ea-9ecd-d74f1eb8b34c.png">

My component is

`<app-component [data]="keyValue" />`

where keyValue is 
`[{key:'name',value:'one'},{key:'class',value:'nine'},{key:'age',value:'thirteen'}]`

How I can pass all keys in keyValue as translated value from app-component itself as I am using reusable keyValue component ?

**Comment by itayod** [comment]
have you considered using the [service](https://netbasal.gitbook.io/transloco/service-api/translation-api)?

**Comment by secabhi** [comment]
I can do that but the problem is there is too many places I am using this reusable component. Using Translation service is tedious task . Let me know if I can do without translation API.

**Comment by itayod** [comment]
then you could create a custom pipe that injects the TranslocoService and translate each of the keys

**Comment by itayod** [comment]
btw next time you have a question please don't open an issue, you could ask a question in stackoverflow or ask in our [gitter](https://gitter.im/ngneat-transloco/lobby) channel.
