### ISSUE TITLE
[Feature] Add translated nested object return in the template

### ISSUE THREAD

**Issue by nimesko** [ngneat/transloco#221]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

We cannot return a nested object translated based on a key in the template directly

## Expected behavior

We can receive a translated object by passing a key (and your parameters) on our template.

## What is the motivation / use case for changing the behavior?

If we are implementing a smart/dumb pattern, sometimes we need to pass a set of labels/placeholders to our dumb component. To have a clean dumb component (and follow the design pattern) we need to pass a value/object of values to our child

Imagine the following scenario:

**signin.component.html** (smart component) Today
```html
....
  <app-signin-form class="signin-form"
    [value]="valueSigninForm$ | async"
    [placeholders]="getTranslateProperty(t('signinForm.placeholders'))"
    [labels]="getTranslateProperty(t('signinForm.labels'))"
    [errors]="getTranslateProperty(t('signinForm.errors'))"
    (changed)="onChangedSigninForm($event)">
  </app-signin-form>
....
```

**signin.component.ts** (smart component) Today
```typescript
....
  getTranslateProperty(key: string) {
    return this.translocoService.translateObject(key, null, this.translocoService.getActiveLang());
  }
....
```

**signin-form.component.ts** (dumb component) Today
```typescript
....
  @Input() value: SigninForm;
  @Input() placeholders: SigninFormPlaceholders;
  @Input() labels: SigninFormLabels;
  @Input() errors: SigninFormFieldErrors;

  @Output() changed: EventEmitter<SigninForm>;
....
```

**signin-form.model.ts** Today

```typescript
import { FormFieldErrorMessage } from '@frontend/core/core.model';

export type SigninFormFields = 'email' | 'password';
export type SigninForm = Partial<Record<SigninFormFields, string>>;
export type SigninFormPlaceholders = Partial<Record<SigninFormFields, string>>;
export type SigninFormControls = 'submit';
export type SigninFormLabels = Record<(SigninFormFields & SigninFormControls), string>;
export type SigninFormFieldErrors = Partial<Record<SigninFormFields, FormFieldErrorMessage>>;
```

The desired implementation is that in **. Ts ** of the smart component, we do not need the `getTranslateProperty` method, replacing it with a direct reference in the template. So, we can modify the actual implementation with

**signin.component.html** (smart component) Desired
```html
....
  <app-signin-form class="signin-form"
    [value]="valueSigninForm$ | async"
    [placeholders]="t('signinForm.placeholders', true)"
    [labels]="t('signinForm.labels', true)"
    [errors]="t('signinForm.errors', true)"
    (changed)="onChangedSigninForm($event)">
  </app-signin-form>
....
```

**signin.component.ts** (smart component) Today
```typescript
....
// We remove this method because is not necessary anymore.
//  getTranslateProperty(key: string) {
//    return this.translocoService.translateObject(key, null, this.translocoService.getActiveLang());
//  }
....
```

**Comment by itayod** [comment]
Hi @nimesko does it work for you if you use `selectTranslateObject` from the service?

**Comment by nimesko** [comment]
Hi @itayod it works only if we use `async pipe`.

If we replace *translateObject* to *selectTranslateObject* inside a template who has a *ng-container* or *ng-template*, wouldn't we be doing a double subscription to the template?

Another issue is that, since the subscription is made to the template, we already have the language context, so the call for *translateObject* would make more sense, in my opinion.

**Comment by itayod** [comment]
You could use either, about supporting it from the directive, we decided that we don't want to support that for now...

So for your usecase, please use `translateObject` or `selectTranslateObject`.

**Comment by nimesko** [comment]
@itayod ok, thank you for your response 👍 

Have a good week o/
