### ISSUE TITLE
How to include HTML markups in translations

### ISSUE THREAD

**Issue by marchbox** [ngneat/transloco#226]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x] Other... Please describe: question
</code></pre>

For example, in the en.json file:

```
{
  "foo": "This is a <strong>bold</strong> message."
}
```

Currently when I use `transloco` pipe, it'll escape `<` and `>` characters. I tried to write my own transpiler, but it didn't work either. Seems there's some sanitizing happened after the transpiler, possibly even after the pipe.

Thank you!

**Comment by shaharkazaz** [comment]
@marchbox use the translation in `innerHTML` binding.
Issues in our GitHub repo are reserved for potential bugs or feature requests. If you have any questions relating to how to use the library, we recommend asking them either in Stackoverflow or in the dedicated [Gitter channel](https://gitter.im/ngneat-transloco/lobby).
This question was already raised in our gitter channel and answered there.

**Comment by marchbox** [comment]
Thank you!

**Comment by manikantag** [comment]
For follow up, below is how to do it:

    { "contact": "Contact <a href=\"mailto:support@example.com\">support@example.com</a> for assistance." }


And, in template:

    <p [innerHTML]="transLoco('contact')">

**Comment by shaharkazaz** [comment]
@scotch83 Actually, it's in the [doc's FAQ](https://jsverse.gitbook.io/transloco/resources/faqs#can-i-include-html-markup-inside-a-translation).
