### ISSUE TITLE
Unit tests did not work with Ivy

### ISSUE THREAD

**Issue by emzet** [ngneat/transloco#227]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When running unit tests with imported **TranslocoTestingModule** (wrapped in factory function) as written in [guide](https://netbasal.gitbook.io/transloco/general/unit-testing), with `"enableIvy": true` in `tsconfig.json`, gets an error `Error: Can't resolve all parameters for TestingLoader: (?)`. When `enableIvy` property is set to `false` then works properly, without errors.

## Expected behavior

Do not throw error, when compiling with enabled Ivy.

## Minimal reproduction of the problem with instructions

1. create new app with `ng new my-app`
2. add this library `ng add @ngneat/transloco`
3. add **TranslocoTestingModule** to some component e.g. **AppComponent** as written in [guide](https://netbasal.gitbook.io/transloco/general/unit-testing)
4. run unit tests `ng test`

## What is the motivation / use case for changing the behavior?

To work unit tests properly with Ivy i.e. Angular 9 as it has Ivy enabled by default.

## Environment

<pre><code>
Angular version: 9.0.0-rc.12

Browser:
- [X] Chrome (desktop) version 79.0.3945.130 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v13.7.0  
- Platform: Windows 10 

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
It is fixed in 2.13.1. Thanks for the report.
