### ISSUE TITLE
transloco-locale requires peer dependency of @ngneat/transloco@^1.7.9 although 2.x installed

### ISSUE THREAD

**Issue by Siedlerchr** [ngneat/transloco#229]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Have transloco and transloco-locale instaled.
npm update shows warning about missing peer dependency for transloco 1.x although version 2.x is already installed. 

## Expected behavior

No warnings.

## Minimal reproduction of the problem with instructions

Install transloco and tarnsloco-locale

## Environment

<pre><code>
Angular version:  8.1.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version:  v12.14.1
- Platform:  windows

Others:
    "@ngneat/transloco": "^2.13.2",
    "@ngneat/transloco-locale": "^1.0.0",

</code></pre>

**Comment by NetanelBasal** [comment]
Fixed in v1.0.1
