### ISSUE TITLE
.all-contributorsrc pointing to wrong project owner

### ISSUE THREAD

**Issue by Coly010** [ngneat/transloco#23]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x ] Other... Please describe:
The `.all-contributorsrc` file is pointing to `NetanelBasal` as project owner.
</code></pre>

## Current behavior

As the `.all-contributorsrc` Project Owner is pointing to NetanelBasal, the URL generated for the links for contributors point to `github.com/NetanelBasel/transloco`.

## Expected behavior

Generated URLs should point to `github.com/ngneat/transloco`.

## What is the motivation / use case for changing the behavior?

All links for current contributors contributions point to a 404 page.

**Comment by NetanelBasal** [comment]
Fixed, thanks.
