### ISSUE TITLE
Prefix all keys in a component via provider

### ISSUE THREAD

**Issue by xXKeyleXx** [ngneat/transloco#230]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

If I have a long key like `LONG_PATH.LONG_GROUP_NAME.LONG_COMPONENT_NAME.LONG_KEY_NAME` it can make you components look bloated. Especially when you use the pipe in attributes and they overflow you max line length.

## Expected behavior
A way to prefix all keys in a component without using scopes.

## What is the motivation / use case for changing the behavior?
Reducing the key length when used in a component

## Pipe example code ##
```typescript
export const TRANSLOCO_PREFIX = new InjectionToken<string>('TRANSLOCO_PREFIX');

@Pipe({
  name: 'translate',
  pure: false,
})
export class TranslatePipe implements PipeTransform, OnDestroy {

  ...

  constructor(
    private translocoService: TranslocoService,
    @Optional() @Inject(TRANSLOCO_SCOPE) private providerScope: MaybeArray<TranslocoScope>,
    @Optional() @Inject(TRANSLOCO_LANG) private providerLang: string | null,
    @Optional() @Inject(TRANSLOCO_PREFIX) private prefix: string | null,
    private cdr: ChangeDetectorRef,
  ) {
    this.listenToLangChange = shouldListenToLangChanges(this.translocoService, this.providerLang);
  }

  transform(key: string, params?: HashMap | undefined, inlineLang?: string | undefined, ignorePrefix?: boolean | undefined): string {
    if (!key) {
      return key;
    }
    if (!ignorePrefix && this.prefix) {
      key = `${this.prefix}.${key}`;
    }

    const keyName = params ? `${key}${JSON.stringify(params)}` : key;

    ...
```

**Comment by NetanelBasal** [comment]
https://netbasal.gitbook.io/transloco/translation-in-the-template/structural-directive#utilizing-the-read-input
