### ISSUE TITLE
No pipe found with name 'transloco' in Angular 9 lazy loaded module

### ISSUE THREAD

**Issue by micobarac** [ngneat/transloco#231]
I followed the manual:

`ng add @ngneat/transloco`

it imported `TranslocoRootModule` into `angular.module.ts`.

I imported `TranslocoModule` into a lazy loaded module, but I keep getting the error:

```html
<h1>{{ 'App.Title' | transloco }}</h1>
```

`error NG8004: No pipe found with name 'transloco'`.

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I cannot make it to work with Angular 9 and Ivy enabled

`error NG8004: No pipe found with name 'transloco'`
`
## Expected behavior

`transloco` pipe should work

## Minimal reproduction of the problem with instructions

It is a part of a huge commercial project, and cannot extract the example from it

## Environment

<pre><code>
Angular version: Angular: 9.0.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by Galleazzo** [comment]
Did you manage to fix this problem? I'm going through the same problem
