### ISSUE TITLE
TypeError: t_r307 is not a function

### ISSUE THREAD

**Issue by SvenBudak** [ngneat/transloco#234]
I tryed today to switch from l10n to transloco and i started with very basic stuff. I `ng add` the package, selected the http loader and json format.

Then i copied this from the docu:

```
<ng-container *transloco="let t">
	<h1>{{ t('hello') }}</h1>
</ng-container>
```

and i am wondering why i get this error:

```
ERROR TypeError: t_r307 is not a function
    at MenuComponent_ng_container_0_Template (template.html:6)
    at executeTemplate (core.js:11841)
    at refreshView (core.js:11688)
    at refreshDynamicEmbeddedViews (core.js:13053)
    at refreshView (core.js:11711)
    at refreshComponent (core.js:13128)
    at refreshChildComponents (core.js:11419)
    at refreshView (core.js:11740)
    at refreshComponent (core.js:13128)
    at refreshChildComponents (core.js:11419)
```

The first entry in console is `🍻 Translation Load Success: en` so i think that everything is well configured.

(I dont add any service or something else to the ts file. But if i understand the documentation correct, i dont need any else then to load the directive in the html file)

Before i start trying this package, i ng update the whole project from angular 8 to 9. But everything was working before i start changing translation stuff. So i think the update was working correct.

**Comment by shaharkazaz** [comment]
@SvenBudak What's your Transloco version?

**Comment by SvenBudak** [comment]
i used `ng add @ngneat/transloco` so i expected that its latest `2.13.2` ... but its `1.1.1` in my `package.json`... Sorry that i didnt checked this before i post. I didnt know that its possible that ng add install a old version :) But then this is maybe a thing that can be fixed.

**Comment by shaharkazaz** [comment]
@SvenBudak upgrade to the latest and see if you still have any issues and reopen 🙂

**Comment by itayod** [comment]
@SvenBudak for a cleaner start I would recommend you to revert what the `ng-add` changes install the new version and run then `ng g @ngneat/transloco:init` that should run the same procedure as `ng-add`

**Comment by SvenBudak** [comment]
Thanks @itayod it worked with `ng g @ngneat/transloco:init` much better :) I am just wondering why configs are splitted in 2 files... Some are in `transloco-root.module.ts` and some others are in `transolco.config.js`.. Some stuff seems to be duplicate, like `availableLangs: ['en', 'de']` and `langs: ['en', 'de']`.

**Comment by SvenBudak** [comment]
I am wondering why i get exactly the same problem in a new project after 6 Months :)
The ng add command is not updated?

I use `Angular 10.0.0` and `@ngneat/transloco": "^1.1.1` 

It works only when i use the pipe like: `{{ t('name', { name: 'Transloco' }) }}`

**Comment by shaharkazaz** [comment]
@SvenBudak why not use the latest version? 🙂

**Comment by SvenBudak** [comment]
i used ng add. i dont checked the version... ng add dont use the latest version?

**Comment by shaharkazaz** [comment]
@SvenBudak Should give you the latest... you can run `ng add @ngneat/transloco@latest`, maybe it's a cache thing.

**Comment by SvenBudak** [comment]
Oh wow 😁
I didn't know there was a cache for ng add.
Thanks for your quick answer!
I will bookmark this issue for future projects 😂

**Comment by timhecker** [comment]
Hi, I had the same @SvenBudak problem:

> I use Angular 10.0.0 and @ngneat/transloco": "^1.1.1

I found also weird questions during the config/installation process. I used an old version of transloco on my device, but it was the `2.13.2`.

Maybe some problem with the last version of angular?

Thanks in advance.

**Comment by shaharkazaz** [comment]
@timhecker Please update to the latest version of transloco and try

**Comment by timhecker** [comment]
> @timhecker Please update to the latest version of transloco and try

Yep, I solved with `ng add @ngneat/transloco@latest` and now I see the 2.17.3 on `package.json`.  Thanks

**Comment by eluchsinger** [comment]
I had similar problems. After running `ng add @ngneat/transloco` (like in the installation guide), my modules changed and some files were added, but transloco was not added to `package.json`.
