### ISSUE TITLE
TranslocoService.translate should support number type as a parameter

### ISSUE THREAD

**Issue by micobarac** [ngneat/transloco#236]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

`Type 'number' is not assignable to type 'string'.`

## Expected behavior

TranslocoService.translate should support number type as a parameter

## Minimal reproduction of the problem with instructions

```typescript
export class AppComponent {
  constructor(private translocoService: TranslocoService) {}

  ngOnInit() {
   // This throws an error
    this.translocoService.translate('hello', { value: 3});

   // This works
    this.translocoService.translate('hello', { value: '3'});
  }
}
```

`Type 'number' is not assignable to type 'string'.`

## What is the motivation / use case for changing the behavior?

Use `number` type as a translate parameter.

## Environment

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.0.1
Node: 13.8.0
OS: darwin x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@angular/flex-layout              9.0.0-beta.29
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Comment by itayod** [comment]
What version do you use?

**Comment by micobarac** [comment]
`"@ngneat/transloco": "1.1.1"`

**Comment by itayod** [comment]
see https://github.com/ngneat/transloco/issues/235#issuecomment-585189301
