### ISSUE TITLE
[Feature Request] - Current Lang in URL

### ISSUE THREAD

**Issue by SvenBudak** [ngneat/transloco#237]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

I cant find any solution to show the current selected language in the url. In the old package i used (angular l10n) it was just a setting in the config. Is a feature like this planed for this package?

**Comment by ArielGueta** [comment]
Can you please explain what it looks like, and why we need it?

**Comment by SvenBudak** [comment]
This will explain it better as I can: https://support.google.com/webmasters/answer/182192?hl=en

**Comment by ArielGueta** [comment]
Thanks. This is a really long article. I think the maintainers will appreciate a summary of how the feature should like.

**Comment by SvenBudak** [comment]
For example. I can't switch to transloco with some projects because all urls are listed on google with www.domain.com/en/

All entries will link to dead links

**Comment by ArielGueta** [comment]
Duplicate of #28

**Comment by itayod** [comment]
https://github.com/ngneat/transloco/issues/28#issuecomment-566464842
