### ISSUE TITLE
Expose key instead of value within transpile method

### ISSUE THREAD

**Issue by bevkoski** [ngneat/transloco#239]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The `transpile` method of the `TranslocoTranspiler` interface is declared as follows:
```typescript
transpile(value: any, params: HashMap<any>, translation: HashMap): any;
```

## Expected behavior

Instead, the `transpile` method of the `TranslocoTranspiler` interface is declared as follows:
```typescript
transpile(key: TranslateParams, params: HashMap<any>, translation: HashMap): any;
```

## Minimal reproduction of the problem with instructions

Create a custom transpiler as stated in the Transloco documentation: https://netbasal.gitbook.io/transloco/hack-the-library/transloco-transpiler.

## What is the motivation / use case for changing the behavior?

Exposing `key` instead of `value` would be more useful.

Example use case: I would like to do some custom processing (with the help of a custom service injected within the transpiler) to determine whether to add a prefix or suffix to the key and provide a different translation at the end. Currently, I am doing a workaround where I get the `key` based on the provided `value`, but this is not optimal and would lead to problems in case of duplicate values within a translation file.

As an additional argument, by knowing the `key` we can get to the value via `translation[key]`, but not vice versa (at least not directly and robustly).

**Comment by itayod** [comment]
@bevkoski maybe you could use the [interceptor](https://app.gitbook.com/@netbasal/s/transloco/hack-the-library/transloco-interceptor) for your usecase?

**Comment by bevkoski** [comment]
@itayod, thanks for the input. After a closer look at the interceptor, I can say that it is indeed applicable for my use case. Sorry for not checking more thoroughly earlier - I assumed that the timing of the interception would not work for me. In case you believe that exposing the key within the transpiler is not a good idea, feel free to close this issue.

**Comment by shaharkazaz** [comment]
@bevkoski I'm glad that solved your issue 🙂
