### ISSUE TITLE
Documentation about $events Observable

### ISSUE THREAD

**Issue by aboudard** [ngneat/transloco#240]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

In the current documentation (2.13.0), 
https://netbasal.gitbook.io/transloco/service-api/translation-api
we read :
```
// don't forget to unsubscribe
translocoService.events$.pipe(
 filter(e => e.type === 'translationLoadSuccess')
).subscribe(({ langName, scope }) => {
 ...
});
```
This gives an error : property langName does not exist on TranslocoEvents

## Expected behavior

The following works with version 2.13.0 :
```
this.translate.events$.pipe(
      filter(e => e.type === 'translationLoadSuccess')
    ).subscribe(({ payload }) => {
      console.log(payload.langName);
    });
```
This does match the declared types :
```
export declare type LoadedEvent = {
    type: 'translationLoadSuccess';
    wasFailure: boolean;
    payload: {
        scope: string | null;
        langName: string;
        /** @deprecated */
        lang: string;
    };
};
```

## Environment

<pre><code>
Angular version: 8.2.14

Browser:
- [x ] Chrome (desktop) version 77
 
For Tooling issues:
- Node version: 10.16.0  
- Platform:  Windows

**Comment by itayod** [comment]
updated the docs, thanks
