### ISSUE TITLE
404 link for migration document for ngx-translate

### ISSUE THREAD

**Issue by timbru31** [ngneat/transloco#241]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The link defined in https://github.com/ngneat/transloco/blob/7760f7e28e00e3d85b1cc5ac76a91eabed7c0599/schematics/src/migrate/ngx-translate-migration.ts#L169 points to https://github.com/ngneat/transloco/tree/v1/migration/migration.md which is a 404 site.

## Expected behavior

The link should point to https://github.com/ngneat/transloco/blob/master/schematics/src/migrate/ngx-translate-migration.md

## Minimal reproduction of the problem with instructions

None needed I guess ;)

## What is the motivation / use case for changing the behavior?

Users migrating from other libraries should be able to read the more detailed migration document.

## Environment

<pre><code>
Angular version: 8.2

 
For Tooling issues:
- Node version: 12.16.1
- Platform:  macOS

**Comment by itayod** [comment]
fixed, thanks.
