### ISSUE TITLE
Update peer dependency to Angular v9

### ISSUE THREAD

**Issue by micobarac** [ngneat/transloco#243]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

<pre><code>
@ngneat/transloco@2.13.3" has incorrect peer dependency "@angular/core@>=6.0.0 <9.0.0".
</code></pre>

## Expected behavior

Transloco should support Angular 9

## Minimal reproduction of the problem with instructions

Any Angular 9 project

## What is the motivation / use case for changing the behavior?

Angular 9 support

## Environment

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.0.3
Node: 13.8.0
OS: darwin x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.3
@angular/cdk                      9.1.0
@angular/cli                      9.0.3
@angular/flex-layout              9.0.0-beta.29
@angular/material                 9.1.0
@ngtools/webpack                  9.0.3
@schematics/angular               9.0.3
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Comment by itayod** [comment]
@micobarac would you like to create a pr for this?

**Comment by micobarac** [comment]
@itayod , does this include updating only peer dependencies to support Angular? If it does, I can do it. Just give me permission please to create PR.

**Comment by itayod** [comment]
> does this include updating only peer dependencies to support Angular 9

It does.

To create a PR you will have to fork the library, take a look at this [stackoverflow](https://stackoverflow.com/questions/14680711/how-to-do-a-github-pull-request) if you have never done it before.
