### ISSUE TITLE
Migration from ngx-translate does not replace translate pipes which contain a newline

### ISSUE THREAD

**Issue by timbru31** [ngneat/transloco#244]
I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The migration from `ngx-translate` does not replace `translate` pipes which block ends with a newline.
For example:

```html
<h1>{{
  'HELLO' | translate 
}}</h1>
```

won't be replaced, but `<h1>{{ 'HELLO' | translate }}</h1>` will be.

## Expected behavior

The migration from `ngx-translate` should correctly replace `translate` pipes which contain a newline.

## Minimal reproduction of the problem with instructions

You can find an MRE here: https://github.com/timbru31/ngx-translate-migration-repro.  
The `master` branch uses ngx-translate, if you run `npx ng add @ngneat/transloco && npx ng g @ngneat/transloco:migrate` only the first of the `| translate` pipes will be replaced in the `app.component.html`. The state after the migration has run can be viewed in the `bug` branch.

## What is the motivation / use case for changing the behavior?

The migration should also replace `translate` pipes with a newline before the closing brackets.

## Environment

<pre><code>
Angular version: 8.2.x
 
For Tooling issues:
- Node version: 12.16.1
- Platform:  macOS
</code></pre>

**Comment by shaharkazaz** [comment]
@timbru31  should work as expected in v2.13.5, LMK if you have any issues 🙂

**Comment by timbru31** [comment]
Thanks, I've confirmed v2.13.5 works as expected! 🎉
