### ISSUE TITLE
Transloco Date Pipe does not support all date formatting

### ISSUE THREAD

**Issue by tanepiper** [ngneat/transloco#245]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ x ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

This is both a bit of a bug, but also a request to support all date formatting options supported in `Date.toLocaleDateString`.

Currently the Transloco pipe only supports two date format options `dateStyle` and `timeStyle`.

This is in fact causing issues between Chrome, Firefox and Safari.

In Chrome, for the Dutch localisation for `{dateStyle: 'medium'}` the format for the date is `25 feb. 2020` but for Firefox and Safari it is `25-2-2020`.

## Expected behavior

I want to be able to pass custom date formats using all options, rather than rely on the browser settings for `dateStyle` and `timeStyle`

## What is the motivation / use case for changing the behavior?

Providing the `toLocaleDateString` a set of custom options provides a consistant output across browsers, in our case:

`d.toLocaleDateString('nl-NL', {year: 'numeric', month: 'short', day: '2-digit'})` provides the same output across all browsers

## Environment

<pre><code>
Angular version: 8.2.14

Browser:
- [ X ] Chrome (desktop) version 80
- [ X ] Firefox version 74
- [ X ] Safari (desktop) version 13.0.5
</code></pre>

**Comment by itayod** [comment]
@tanepiper looks like it just a matter of typing, would you like to create a pr for this?
