### ISSUE TITLE
Different behaviour between Angular number pipe and translocoDecimal pipe

### ISSUE THREAD

**Issue by SantiagoIlli** [ngneat/transloco#248]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
When i use translocoDecimal pipe with number 1000 the result is 1000 with locale es-AR
When i use Angular numbe pipe with number 1000 the result is 1.000 with locale es-AR

## Expected behavior

Same as in Angular number pipe, 1000 in locale es-AR with translocoDecimal pipe to be 1.000

## Minimal reproduction of the problem with instructions
See at
https://stackblitz.com/github/santiagoilli/transloco-locale-issue

**Comment by itayod** [comment]
Hi @SantiagoIlli, 
Transloco's locale plugin is based on javascript's Intl API therefor there might be conflicts with Angular's behavior which we not going to fix.

Having said that, If you like you can modify the way Transloco transform numbers and dates using the newest `@ngneat/transloco-locale`'s version [API](https://netbasal.gitbook.io/transloco/plugins/locale-l10n#localization-transformer):

```ts
export class CustomNumberTransformer extends DefaultNumberTransformer {
  public transform(
      value: number | string,
      type: NumberTypes,
      locale: string,
      options: Intl.NumberFormatOptions
  ): string {
    if(locale === 'es-AR') {
      return // angular's number transformer.
    }
    return super.transform(value, type, locale, options);
  }
}

export const customTransformers = {
  provide: TRANSLOCO_NUMBER_TRANSFORMER,
  useClass: CustomNumberTransformer
}
```

**Comment by SantiagoIlli** [comment]
Hi @itayod  thanks for the reply! 

I'll try to use that approach to achieve a proper number format for spanish languages.

On the other hand, the javascript Intl API is being maintained ? I would like to report this issue in the proper repository. 

If the answer is no, that means that this is going to be a issue (with a work around, but still an issue) for undetermined time?

I realized that the problem it's also present in es-ES, so probably is in many (or in all)  spanish localizations too.

**Comment by itayod** [comment]
@SantiagoIlli yes, you might need to file an issue to the Intl API of javascript, but currently, we won't create a fix that on our side.
