### ISSUE TITLE
Error: Token InjectionToken PERSIST_TRANSLATIONS_LOADER is missing a ɵprov definition.

### ISSUE THREAD

**Issue by stijnvn** [ngneat/transloco#251]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

After adding the `TranslocoPersistTranslationsModule` to an Angular 9 application, it throws the following error:

```
Error: Token InjectionToken PERSIST_TRANSLATIONS_LOADER is missing a ɵprov definition.
```

## Expected behavior

It should also work with Angular 9

## Minimal reproduction of the problem with instructions

Add the `TranslocoPersistTranslationsModule` to `app.module.ts`

## Environment

<pre><code>
Angular version: 9.0.2

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by itayod** [comment]
Hi @stijnvn I couldn't reproduce it, could you upload a reproduction of this issue?

**Comment by shaharkazaz** [comment]
@stijnvn Feel free to reopen the issue and provide a reproduction 🙂 .
