### ISSUE TITLE
WARN transloco-persist-lang with peer dependencies

### ISSUE THREAD

**Issue by nsabourin** [ngneat/transloco#256]
I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

```
npm WARN @ngneat/transloco-persist-lang@1.0.1 requires a peer of @angular/common@^7.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngneat/transloco-persist-lang@1.0.1 requires a peer of @angular/core@^7.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngneat/transloco-persist-lang@1.0.1 requires a peer of @ngneat/transloco@^1.4.0 but none is installed. You must install peer dependencies yourself.

```

## Expected behavior

compatible plugin

## Minimal reproduction of the problem with instructions

`npm install @ngneat/transloco-persist-lang@1.0.1`

## What is the motivation / use case for changing the behavior?

Could eventually have issue with newer angular and transloco.

## Environment

<pre><code>
Angular version: 9.0.6

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 13.8.0  
- Platform: Windows

**Comment by itayod** [comment]
@nsabourin I have released a new version of `transloco-persist-lang` that fix that warning, you could upgrade to the newest version if you like :)
