### ISSUE TITLE
 Property 't' does not exist on type

### ISSUE THREAD

**Issue by gpeel** [ngneat/transloco#257]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>²

## Current behavior
with ng/cli 9.0.7
ng new mytestproject
add @ngneat/transloco

en.json
{
  "title": "titleEN",
}

NgModule not modified from generation and 'add' process

@Component({
  selector: 'app-root',
  template: `
    <div>{{t('title')}}}</div>
  `
})
export class AppComponent  {}

The compiler complains
    ERROR in src/app/app.component.ts:7:12 - error TS2339: Property 't' does not exist on type 'AppComponent'.
    
    7     <div>{{t('title')}}}</div>

**Comment by shaharkazaz** [comment]
@gpeel In order to use `t` in your template, this needs to be inside a transloco structural directive.
Try changing your template to this: `<div *transloco="let t">{{t('title')}}}</div>`.

**Comment by gpeel** [comment]
thanks, it work fine now

**Comment by shaharkazaz** [comment]
@gpeel you are welcome, please try our [gitter channel](https://gitter.im/ngneat-transloco/lobby) when you have a question 🙂
