### ISSUE TITLE
Unsupported syntax?

### ISSUE THREAD

**Issue by moniuch** [ngneat/transloco#26]
Maybe I am still too fresh, as this is my first hour with transloco, and I am still missing something but I tested the syntax options provided in README, against the following markup:

```html
<p transloco="title"></p>
<p [transloco]="title"></p>
<p>{{ 'title' | transloco}}</p>
<ng-container *transloco="let t">
  <p>{{ t.title }}</p>
</ng-container>
```

and I got the following result in WebStorm

![image](https://user-images.githubusercontent.com/681956/63349749-5612f000-c35c-11e9-9cee-df9e8345c89b.png)

Seems like the two upper options are not allowed.

**Comment by NetanelBasal** [comment]
Do you have a runtime error? If not, that's your IDE issue.

**Comment by moniuch** [comment]
OK thanks will forward it to them

**Comment by NetanelBasal** [comment]
Thanks.
