### ISSUE TITLE
Docs broken link

### ISSUE THREAD

**Issue by WLun001** [ngneat/transloco#268]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
https://netbasal.gitbook.io/transloco/comparison-to-other-libraries
The links for `Pluralization` and `Locale` are broken

**Comment by shaharkazaz** [comment]
@WLun001 You are viewing the old documentation site, see our [new docs](https://ngneat.github.io/transloco/docs/comparison)

**Comment by ChazUK** [comment]
@shaharkazaz So just to clarify is https://ngneat.github.io/transloco/docs/translation-api the official up to date documentation? As I've seen a lot of links to https://netbasal.gitbook.io/transloco/

**Comment by shaharkazaz** [comment]
@ChazUK ngneat.github.io/transloco is the correct documentation 🙂 
Where have you seen links to our old docs?

**Comment by ChazUK** [comment]
It's the second link on Google, and the top two articles also link to the old docs, one from April 2020.

<img width="869" alt="Screenshot 2020-08-10 at 14 08 36" src="https://user-images.githubusercontent.com/768108/89785944-0f8d4700-db13-11ea-842a-1faa386f08b8.png">

**Comment by shaharkazaz** [comment]
@ChazUK thanks for bringing it to my attention, I'll take care of it.

**Comment by Boosten** [comment]
@shaharkazaz the new docs do not mention anything about comparison anymore. So the link you previously shared does not work anymore: https://ngneat.github.io/transloco/docs/comparison

**Comment by shaharkazaz** [comment]
@Boosten We decided to remove this section 🙂
