### ISSUE TITLE
deprecated function in docs

### ISSUE THREAD

**Issue by Maxstgt** [ngneat/transloco#269]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I'm not sure if this `getTranslationObject` is still in the docs because of older versions? Because version `2.14.2` doenst have it anymore. Right?

## Expected behavior

If not part of the new version anymore, remove it.

## What is the motivation / use case for changing the behavior?

I really dont know... ;)

## Environment

Angular 9

 
For Tooling issues:
- Node version: 12
- Platform:  Mac

**Comment by shaharkazaz** [comment]
@Maxstgt Thanks you for submitting this, the function name was wrong 🙂 I [updated the docs](https://ngneat.github.io/transloco/docs/translation-api#translateobject) accordingly, the correct name is `translateObject`.
