### ISSUE TITLE
No provider for TranslocoService when using buildOptimizer

### ISSUE THREAD

**Issue by adrianriepl** [ngneat/transloco#270]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When I try to serve/build the app using the following flags/configuration:

```json
      "fileReplacements":[
         {
            "replace":"src/environments/environment.ts",
            "with":"src/environments/environment.staging.ts"
         }
      ],
      "optimization":false,
      "outputHashing":"all",
      "sourceMap":true,
      "extractCss":true,
      "namedChunks":false,
      "aot":true,
      "extractLicenses":true,
      "vendorChunk":false,
      "buildOptimizer":true
```

I get the following error:

`
ERROR NullInjectorError: StaticInjectorError(AppModule)[TranslocoPipe -> TranslocoService]:   
StaticInjectorError(Platform: core)[TranslocoPipe -> TranslocoService]: 
NullInjectorError: No provider for TranslocoService!
`

When I turn off `buildOptimizer` the error disappears. I inject `TranslocoService` into `AppComponent` and my `AppModule` looks like the following (removed all irrelevant imports):

```javascript

// Angular Modules
import { BrowserModule, Title } from '@angular/platform-browser';
import { HttpClientModule } from '@angular/common/http';
import { NgModule, LOCALE_ID, APP_INITIALIZER } from '@angular/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

// Routing Module, App Compononents & loaders
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { AccessDeniedPage } from './pages/access-denied/access-denied.page';
import { environment } from '@env/environment';
import { httpLoader } from '@app/loaders';

// Kendo Modules
import { IntlModule } from '@progress/kendo-angular-intl';
// Translations for Kendo components
import '@progress/kendo-angular-intl/locales/de/all';
import '@progress/kendo-angular-intl/locales/fr/all';
import '@progress/kendo-angular-intl/locales/it/all';

// 3rd Party Modules
import {
	TranslocoModule,
	TRANSLOCO_CONFIG,
	translocoConfig,
	TranslocoService,
	TRANSLOCO_LOADER
} from '@ngneat/transloco';

@NgModule({
	declarations: [ AppComponent, AccessDeniedPage ],
	imports: [
		// Angular Modules
		BrowserModule,
		HttpClientModule,
		BrowserAnimationsModule,

		// Routing Modules
		AppRoutingModule,

		// Kendo Modules
		IntlModule,

		// 3rd-Party Modules
		TranslocoModule,
	],
	providers: [
                {
			provide: LOCALE_ID,
			useFactory: (translocoService: TranslocoService) => {
				return translocoService.getActiveLang();
			},
			deps: [ TranslocoService ]
		},
		{
			provide: TRANSLOCO_CONFIG,
			useValue: translocoConfig({
				availableLangs: [ 'de', 'fr', 'it' ],
				prodMode: true,
				defaultLang: 'de',
				fallbackLang: 'de'
			})
		},
		// Loader for translations
		httpLoader,
	],
	bootstrap: [ AppComponent ]
})
export class AppModule {}
```

## Expected behavior

Expect TranslocoService to be working with `buildOptimizer`.

## Environment

<pre><code>
Angular version: 8.2.14
Transloco version: 2.13.3

Browser:
- [x] Chrome (desktop) version 80.0.3987.149
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.16.3 
- Platform:  Windows

</code></pre>

**Comment by shaharkazaz** [comment]
@adrianriepl can you try upgrading to v2.16.0?

**Comment by adrianriepl** [comment]
Upgraded to v2.16.0 and seems to be fixed now :smiley: Thank you!
