### ISSUE TITLE
Referencing other keys only works on outer keys in the global scope

### ISSUE THREAD

**Issue by devinvoss** [ngneat/transloco#274]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Referencing another key in a nested key doesn't work (pipe returns blank).
Referencing another key in a scoped file doesn't work (pipe returns blank).

Example demonstrated in StackBlitz: https://stackblitz.com/edit/ngneat-transloco-sjxkeq

The "some.nested.test" key will not fully render on the Home Page.
The "test" key will not render on the Admin Page (a scoped page)

## Expected behavior

Nested keys can reference other keys in the file (ideally any key in the file, not just other keys in the same nest).

Scoped definitions should be able to reference other keys in the way that the documentation reads.

## Minimal reproduction of the problem with instructions

Example demonstrated in StackBlitz: https://stackblitz.com/edit/ngneat-transloco-sjxkeq

## What is the motivation / use case for changing the behavior?

Documentation states this feature exists but doesn't state any limitations.

## Environment

<pre><code>
Angular version: 8.2.14

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ArielGueta** [comment]
It should be: 

```ts
"test": "Result2: {{some.nested.key}}"
```

**Comment by ArielGueta** [comment]
The second one I believe should be:
```ts
"test": "{{adminPage.title}}"
```

**Comment by devinvoss** [comment]
Both of the issues I was having resulted from not knowing that I needed to reference the scoped variable from within itself. Thank you @ArielGueta !

**Comment by shaharkazaz** [comment]
@ArielGueta Thanks for clarifying.
@devinvoss I updated the [Reference Other Keys](https://ngneat.github.io/transloco/docs/additional-functionality#reference-other-keys) section in the docs 👍
