### ISSUE TITLE
Not working on a local network dev server

### ISSUE THREAD

**Issue by mariusvn** [ngneat/transloco#275]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When launching developpement server on local network (`ng serve --host 0.0.0.0 --disableHostCheck`), tranloco tries to retrieve the language files on localhost and not the local network server.

![Transloco localhost request](https://i.imgur.com/s8lKmqx.png "Transolo localhost request")

## Expected behavior

Transloco should retrieve language files on server host enpoint.

## Minimal reproduction of the problem with instructions

Just launch `ng serve --host 0.0.0.0 --disableHostCheck` and access the developpement server from external device.

## What is the motivation / use case for changing the behavior?

Test the web app on mobile device.

## Environment

<pre><code>
Angular version: 9.1.0

Browser:
- [ ] Chrome (desktop) version XX
- [x] Chrome (Android) version 81.0.4044.117
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.16.1  
- Platform: Android 

Others:
- Server: Windows 10
- Client: Android 8.1.0
- IDE: Webstorm 2020.1

</code></pre>

**Comment by itayod** [comment]
Hi @mariusvn it is not related to `Transloco`, in order to load the translation with the above configuration you must fetch data from your IP or from `0.0.0.0` instead `localhost`.

**Comment by mariusvn** [comment]
Sorry, my bad ...
