### ISSUE TITLE
Migration does not work

### ISSUE THREAD

**Issue by muuvmuuv** [ngneat/transloco#277]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Using this command here `ng g @ngneat/transloco:migrate` from https://ngneat.github.io/transloco/docs/migration/ngx gives me this error:

```
❯ ng g @ngneat/transloco:migrate
An unhandled exception occurred: Collection "@ngneat/transloco" cannot be resolved.
See "/private/var/folders/yz/pntm5xh11mjb3ckzvf10ql180000gn/T/ng-z2aSrD/angular-errors.log" for further details.
```

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, for that you could use our [stackblitz example](https://stackblitz.com/edit/transloco-example)

## Environment

<pre><code>
Angular version: 9.1.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.16.1  
- Platform:  Mac latest 

Others:

</code></pre>

**Comment by shaharkazaz** [comment]
@muuvmuuv can you share the version of your main packages? (Angular, transloco, cli, etc)

**Comment by muuvmuuv** [comment]
@shaharkazaz updated the issue. Sorry I forgot to scroll down in the template.

**Comment by shaharkazaz** [comment]
Cool, what's your Transloco version?

**Comment by muuvmuuv** [comment]
Ohhh, I need to install the pkg to use the migration! I thought this is a one liner... so sorry. I got it running but when it hits "⠋ Step 5/5: Migrating spec" it fails because I haven't set up any tests yet and deleted all specs to prevent failurs.

**Comment by muuvmuuv** [comment]
Okay nice, just created an empty spec file and now it finished. Sorry again, corona stress hits me hard atm.

**Comment by shaharkazaz** [comment]
So you have an issue now that step 5 is failing when you don't have specs?
