### ISSUE TITLE
Transloco + Universal SSR + Firebase functions not showing HTML when we check the page source

### ISSUE THREAD

**Issue by jessemoon0** [ngneat/transloco#278]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Hi, I have been more than 2 weeks now dealing with different ways to make this work, so I have tried lots of things...

The problem is: When I have a decent-sized project, transloco works with Universal and SSR perfectly with `npm run build:ssr` + `npm run serve:ssr`, but when I set the project to be deployed to firebase `ng add @angular/fire` and `ng deploy`, it doesn't work properly, as we can't see any HTML that is enclosed in the `<ng-container *transloco="let text; read: 'HOME'">` (This works perfectly in prod of my machine).

Let me attach a picture when I right-click > View Page Source 

![Screen Shot 2020-04-30 at 8 49 49 PM](https://user-images.githubusercontent.com/13438524/80772449-cba6a100-8b24-11ea-94db-78e4b75b2caa.png)

*** Note: It works well with google cloud app engine, so a theory I have is that the latency of spinning up a function somehow makes it not work

So please by now, I would really appreciate the help.

## Expected behavior

- That when I add firebase: `ng add @angular/fire` and `ng deploy`, it works properly with SSR and we can see our HTML.
- It would also be nice to have more errors when for example

```
public getTranslation(lang: string) {
    return this.http.get<Translation>(`${environment.translocoUrl}/assets/i18n/${lang}.json`);
  }
```

if we don't have the correct URL, or even if transloco doesn't work for as expected for any reason.

- It would be nice to add a SSR case for getting the host URL instead of using `${environment.translocoUrl}`

## Minimal reproduction of the problem with instructions

- Create a project
- ng add @nguniversal/express-engine
- ng add @ngneat/transloco
- Create a project in firebase
- Create an app in firebase
- ng add @angular/fire 
- We should see the HTML of our code, not only the angular selectors (for SEO purposes).

## What is the motivation/use case for changing the behavior?

SSR allows us to see the HTML in the page when we do "View page source". This is Crucial to SEO and one of the main reasons 

## Environment

Production / Firebase functions

<pre><code>
Angular version: 9.1.4 (latest)

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 13  
- Platform:  Mac

Others:

</code></pre>

**Comment by shaharkazaz** [comment]
@jessemoon0 Seems like that Transloco is working as expected, so I'm not sure what's the issue here.
If you need assistance with Firebase, try asking on [gitter](https://gitter.im/ngneat-transloco/lobby?source=orgpage)/StackOverflow, but it seems like this issue is not related to Transloco.
