### ISSUE TITLE
Schematics : Ng-add translate-type option 'Typescript' deprecated

### ISSUE THREAD

**Issue by pedraldo** [ngneat/transloco#279]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
[X] Other... Please describe: Questions
</code></pre>

## Current behavior

We can read in schematics [documentation](github.com/ngneat/transloco/blob/master/schematics/README.md) that it's possible to set the `--translate-type` option to `'Typescript'`.  
I was telling me that Typescript files instead of "classic" JSON files could be interesting so I tried to launch `ng add @ngneat/transloco --translate-type Typescript`.  
Unfortunately, I discovered that JSON files was generated instead of ts files.  
I tried to launch the same command with quotes (`ng add @ngneat/transloco --translate-type 'Typescript'`) but the result is the same.

## Expected behavior

I was expecting that the `--translate-type` option of `ng add` schematic command generates `.ts` translation files instead of `.json`.  

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, for that you could use our [stackblitz example](https://stackblitz.com/edit/transloco-example)  

On a standard Angular project (testable with a fresh new project), install transloco (with npm for example) and launch :  
`ng add @ngneat/transloco --translate-type Typescript`

## What is the motivation / use case for changing the behavior?

I wondered why this option doesn't seem to work.  
I found that actually the `--translate-type` option is no longer useful because `.json` files will be generated in all cases.  

Generating `.ts` files was possible in the past, but this [commit](https://github.com/ngneat/transloco/commit/72a9c6c9a4d8e7ddce72497be113dc294caefb47) on the `schematics/src/ng-add/index.ts` file changed the game.  

Knowing all of this, I have few questions : 
- Why `--translate-type Typescript` option isn't "available" anymore ? 
- Does the schematics documentation have to be updated, or will the option be reintroduced in the future ?  

Once again, I think that `.ts`translation file could be interesting.  
It could allow us to break line and indent translations. I'm actually thinking about complex ICU / MessageFormat translation that we must write in a single line inside a JSON file, and sometime a line can be veeeeeery long 😉.
By the way if someone has a solution to this specific "problem" I'm interested ! 

## Environment

<pre><code>
Angular version: 9.1.2
Transloco version : 2.17.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.16.1
- Platform:  Mac

Others:

</code></pre>

I can share more packages and other configurations that I used but I don't think that it is necessary in that case. If needed I'll do it for sure !  
Thank you in advance for your answers.  
Cheers

**Comment by itayod** [comment]
Hi @pedraldo I have updated the docs accordingly, though using typescript for your translation files format is possible, it is not the standard way and might create some problems in certain cases.
