### ISSUE TITLE
Routes localization

### ISSUE THREAD

**Issue by bogusweb** [ngneat/transloco#28]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Expected behavior
Like this plugin https://github.com/Greentube/localize-router 

## What is the motivation / use case for changing the behavior?
The best i18n library for Angular 😍

**Comment by NetanelBasal** [comment]
I'm not sure what are the benefits of this library. Can you explain, please?

**Comment by bogusweb** [comment]
Its help for sites where u can add languages and translations in admin panel or get from rest.
Sometimes other languages can have different routes like `url.com/contact`/`url.com/en/contact`, for polish version `url.com/pl/kontakt` or spanish `url.com/es/contacto`. From route prefix, application can set language. Thanks to that u can share link to application with the correct language.

I'm not sure if this is some awesome feature, I suggest wait and see if anyone else would be interested

**Comment by Coly010** [comment]
I can see the benefit. I learned recently that if you want to truly support i18n you can't trust a user's browser locale, and should provide options of changing the user's locale.

In app, this could be a language drop-down.

However, from an SEO side, and of course marketing, you can tailor your site's URL based on where the Ad or Search Result is being displayed.

With the locale in the URL we can target the `https://mysite.com/es/home` to Spanish-speaking, ensuring that the site will be rendered using the `es` translations. These kinds of target audience options are available within Facebook Ads and Google AdWords.

It becomes even more useful if you are Spanish speaker in an English locale, as it means the app isn't picking up English locale from where you are based but rather giving you the app in the language you prefer.

**Comment by NetanelBasal** [comment]
@Coly010 so why not make it simple and add a query string with the required language?

`https://mysite.com/es/home?lang=es`

**Comment by Coly010** [comment]
@NetanelBasal That would be a perfectly good solution, however, where would you end up handling the logic to change the translation?

In the `ngOnInit()` of the `HomeComponent` by accessing the `RouteParams`? 
Would you have to do that for every page in your site that could be used for a marketing or search result URL?

You're advertising a job, `https://mysite.com/jobs/123?lang=es`
You've got a contact page that shows up in a search result, `https://mysite.com/contact?lang=es`

For each of these translations to be applied, does there need to be logic in each of those components to handle that translation?
If we can intercept it earlier, and have it handled in one place, all the better.

Also, gone are our vanity URLs.
`https://mysite.com/jobs/123?lang=es`
vs
`https://mysite.com/es/jobs/123`

Next, how would Angular's Router handle multiple route params should as above?

**Comment by NetanelBasal** [comment]
We can create a small library based on my suggestion that checks the `lang` query string, and based on it changes the active language.

**Comment by fxck** [comment]
> However, from an SEO side

this isn't really true, it has little no effects on seo

https://webmasters.stackexchange.com/a/85923

**Comment by itayod** [comment]
Thanks for your suggestion @bogusweb 

After reconsidering, we have decided that a library isn't really needed here since the implementaion isn't very complicated:

```typescript
  constructor(private route: ActivatedRoute, private translocoService: TranslocoService) { }

  ngOnInit() {
    this.route.queryParams
      .subscribe(params => {
        this.translocoService.setActiveLang(params.lang);
      });
  }
```

**Comment by ruizmarc** [comment]
In our project we localize all routes so they become more user friendly, easier to understand and even easier to memorize. It would be great to have route localization with this lib, not only a query param.

Here you have another example of library with route localization based on ngx-translate in which we are contributing to: https://github.com/gilsdav/ngx-translate-router

**Comment by shaharkazaz** [comment]
@ruizmarc You are welcome to open a PR and make it an official plugin 🙂

**Comment by ruizmarc** [comment]
We have spent a lot of time with ngx-translate and ngx-translate-router to make it work properly with all our requirements, I don't think I have time to do the same with this lib. Sorry about it. It was just a suggestion taking into account needs from projects like ours if you really want to become the reference localization library. If we ever use this lib in our project, I will find the time, but until then, I don't think I have time to do it and test it with your lib. Anyway, this lib looks promising, good job guys!

**Comment by alexbikazzan** [comment]
I think this definitely would be nice to have as a feature for the ones who run public sites with SSR.

Google recommends having different urls for each language of your page, for example by using the top-level domain `site.com, site.fr`, subdomain: `en.site.com, de.site.com` or subdirectories: `site.com/de`, but not by query params.

**Comment by gchronos** [comment]
+1
we also cannot refuse from using "/de" in the path
and without this feature, we can't use transloco 
but it's looks something that will be nice to use

**Comment by mohamedaarab1994** [comment]
Is this still an active thing? We are also looking for a way to implement this in our SSR Project.

**Comment by bgever** [comment]
This feature is a requirement for us. Our current implementation also uses https://github.com/gilsdav/ngx-translate-router that was suggested earlier, though ngx-translate doesn't support Transloco's neat lazy loaded scoping.

Keep up the great work! 👍

**Comment by itayod** [comment]
> Is this still an active thing? We are also looking for a way to implement this in our SSR Project.

It is, would you like to create a PR for this?

**Comment by bgever** [comment]
@itayod Could you reopen this issue as these features haven't been considered:

 - Prefixing URLs with a language code:  
    e.g. (default) `/page`, (English) `/en/page`, (Traditional Chinese, Hong Kong) `/zh-hk/page`.
 - Localizing URL segments:
   e.g. (English) `/en/page`, (Dutch) `/nl/pagina`.

**Comment by itayod** [comment]
Hi all,
 
We have discussed this issue within our team, and we have decided that we will not support this feature as an official library of Transloco.

For those who need this, you can create an external library (just like the one for ngx-translate), and we will assist you with whatever help you might need.

Thanks, and good luck.

**Comment by mfchan** [comment]
+1 we really need it

**Comment by SvenBudak** [comment]
Sry but this is insane.... this makes the whole package useless...

**Comment by d-koppenhagen** [comment]
I don’t think it will make the package useless. Probably it won’t fit for you but for others it does.

It‘s open source and you are free to create a package that will extend transloco or just use another lib that fits for you.

Keep in mind: it’s open source and you can either use it or not. And you can maybe request for a feature and try to contribute and get help from the community. But you should also respect a feature won’t be integrated- it’s not a must.

**Comment by daco** [comment]
Previous comment, calling the decision to leave this feature out "insane", is a bit harsh. However, I think the majority of the projects using this library need it. SEO is very important for most, and Google expects a different language either served from another domain, or from another prefix like domain/en/. You are also expected to point to the different language url's with an href lang element. Not doing this will result in less traffic from organic search results.

I'm still looking for the best solution for translation, and I would really like to use this package, but I need the url prefixing with an language code and serving from multiple domains.

Maybe this is something that is achievable this package. I already managed to setup my nginx to serve from multiple domains and language prefixes, using multiple index.html (index-en.html etc) files with a different base href value. So, if it just boils down to bootstrap this thing with different default values based on domain and prefix, than I guess it'll work.

Anyone any experience or thoughts about this? Thanks!

**Comment by JelleBruisten** [comment]
I small solution I came up with to combat this while there is no support for this feature would be to add a resolver to the routes:

```
{
    path : ':lang/a',
    component : AComponent,
    resolve: [LanguageGuard]
  },

  {
    path : ':lang/b',
    component : BComponent,
    resolve: [LanguageGuard]
  },
```

And then having the LanguageGuard class like this:

```
export class LanguageGuard implements Resolve<string> {

  constructor(private translocoService: TranslocoService) {}

  resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): string | Observable<string> | Promise<string> {
    const lang = route.params?.lang ?? this.translocoService.getDefaultLang();
    if(lang) {
      this.translocoService.setActiveLang(lang);
    }    
    return route.params.lang;
  }
  
}
```

This way it would change the language based on url, but seems like a hacky way todo this. Also for router links u would need to add active routerLink:

`<a [routerLink]="activeLanguage + '/a'">A</a>`

**Comment by penleychan** [comment]
I've ported @gilsdav/ngx-translate-router to work with transloco: https://github.com/penleychan/ngx-transloco-router
Demo app is in that repo to show case what's working.

Please keep in mind that I have not tested everything that @gilsdav/ngx-translate-router has to offer.

**Comment by danielehrhardt** [comment]
https://github.com/ngneat/transloco/discussions/491

**Comment by mihanc** [comment]
> I small solution I came up with to combat this while there is no support for this feature would be to add a resolver to the routes:
> 
> ```
> {
>     path : ':lang/a',
>     component : AComponent,
>     resolve: [LanguageGuard]
>   },
> 
>   {
>     path : ':lang/b',
>     component : BComponent,
>     resolve: [LanguageGuard]
>   },
> ```
> 
> And then having the LanguageGuard class like this:
> 
> ```
> export class LanguageGuard implements Resolve<string> {
> 
>   constructor(private translocoService: TranslocoService) {}
> 
>   resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): string | Observable<string> | Promise<string> {
>     const lang = route.params?.lang ?? this.translocoService.getDefaultLang();
>     if(lang) {
>       this.translocoService.setActiveLang(lang);
>     }    
>     return route.params.lang;
>   }
>   
> }
> ```
> 
> This way it would change the language based on url, but seems like a hacky way todo this. Also for router links u would need to add active routerLink:
> 
> `<a [routerLink]="activeLanguage + '/a'">A</a>`

Is this solution still the best?
