### ISSUE TITLE
DatePipe option 'weekDay'  doesn't provide the weekday.

### ISSUE THREAD

**Issue by danyuep** [ngneat/transloco#281]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
This is the first ever issue I report. Maybe I'm just simply missing something obvious.

Following line doesn't result in any compiling errors or anything, however the Date is returned, rather than the weekday ('5/3/2020').
console.warn(this.service.localizeDate(new Date(), 'en-US', { weekDay: 'long' })); 

Interesting note: While still serving, when I change the option to "weekday" (lower case D), a compilation error occurs but the weekday is returned as I would have expected it as 'Sunday'.

 error TS2345: Argument of type '{ weekday: string; }' is not assignable to parameter of type 'DateFormatOptions'.

## Minimal reproduction of the problem with instructions

this.service.localizeDate(new Date(), 'en-US', { weekDay: 'long' })
and
this.service.localizeDate(new Date(), 'en-US', { weekday: 'long' })

## What is the motivation / use case for changing the behavior?

Being able to retrieve the weekday for a date depending on the active locale.

## Environment

<pre><code>
Angular version: 9
Latest Ionic Framework

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by itayod** [comment]
Hi @danyuep seems that was a typing issue :) I have fixed that and released a new version.
Thanks for rising that up

**Comment by danyuep** [comment]
Yeah it's working. Good job, thank you :)
