### ISSUE TITLE
routerLink into translated string

### ISSUE THREAD

**Issue by davidecampello** [ngneat/transloco#283]
Hi, is it possible to include a link (with routerLink) into a translated string?

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Putting a string with <a href="..."> into the json translated string, binded with innerHTML is working, but is it possible to use the routerLink? 
Thanks

**Comment by ArielGueta** [comment]
`[routerLink]="t('key')"`

**Comment by davidecampello** [comment]
I'm sorry but I've put it badly.
What I would like to do is something like this inside assets/i18n/en.json:
`
 {
 "text": "text <a routerLink='/link'>with link</a>"
 }
`

**Comment by shaharkazaz** [comment]
@davidecampello for questions and assistance please try our [gitter room](https://gitter.im/ngneat-transloco/lobby?source=orgpage).
You can't do it using while AOT compilation, but there are 2 alternatives:
- Transform your component into a web component using `@angular/elements` and use the HTML tag in your translation.
- Separate your translation into 2 parts and insert the desired component between.

I've also added this to our [faq page](https://ngneat.github.io/transloco/docs/faq/#is-it-possible-to-use-an-angular-component-inside-my-translation-string).
