### ISSUE TITLE
Nested Module usage is not clear

### ISSUE THREAD

**Issue by gethari** [ngneat/transloco#285]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

My application is very large and it has 2-3 layers of nested modules. I'm trying to maintain a separate `i18n` folder for each module and load `json` using `inlineLoaders` on each of the modules.

Even though I have the json in each of the module's root placed under `i18n` folder, its saying `Unable to load fallback language` or `missing translation` which indicates me the json is not loaded properly. But I'm not sure how to proceed.

## Minimal reproduction of the problem with instructions

Here is somewhat similar [stackblitz](https://stackblitz.com/edit/ngneat-transloco-nndjgf) with nested modules and I've tried to use it on the nested modules and its not working.

I think I don't find this clearly in the docs or am i doing something wrong, which am not able to figure it out.

### Some Questions which I have!

* If I'm using inline loaders in each of the feature modules? Should there be a root loader next to `app.module` ?
* Which is the recommended approach for large scale apps ? Going full blown with all json with separated folders under `assets/feature` or each feature will have separate `i18n` folders with `json` files lying in root folder of `i18n`

Thanks
Hari

## Environment

<pre><code>
Angular version: 8.2.14

Package version : 2.17.1

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.3.1  
- Platform: Windows 

Others:

</code></pre>

**Comment by itayod** [comment]
@gethari I am closing this issue, for now, we will continue to discuss it in our gitter channel.

**Comment by timhecker** [comment]
Hi @gethari I have your same problem with inline loaders and the error `Missing translation for....`. I found your [example repo](https://github.com/gethari/nestedModules-transloco/tree/master/src/app) and my problem is similar, without nested modules. This is my folders structure:

<img width="373" alt="Schermata 2020-07-08 alle 17 00 38" src="https://user-images.githubusercontent.com/3533765/86935342-02a8bc80-c13d-11ea-9e0c-eb7a93ff8061.png">

When I was working with only one feature module, everything worked. Problems come when I've used inline loaders into other feature modules. Now I see only strings:

<img width="651" alt="Schermata 2020-07-08 alle 17 06 26" src="https://user-images.githubusercontent.com/3533765/86935702-6b903480-c13d-11ea-98a0-cdfcf1554f2b.png">

 
Let me know please if you solved in some way. 
Thanks

**Comment by JohanHeyvaert** [comment]
Hello,

I have the same problem/question. We have an Nx project with many modules and sub modules. When using inline loaders, the translations work for only one of the modules. If we remove the transloco scope provider for the module with working translations then it starts working for an other module (but each time just for one module).

When adding a nested module in the [demo nx project](https://github.com/NetanelBasal/transloco-with-nx-libs) (referred to by https://ngneat.github.io/transloco/docs/inline-loaders) then the same problem occurs: only the translations of the submodule work, the translations of the main module (TranslocoLibBModule in this case) stop working. 

Could you please extend that demo project to show how inline loading should be used with nested modules? Thank you in advance!

**Comment by henryruhs** [comment]
It took me a while to figure out this solution, thanks Johan for pointing it out! As `TRANSLOCO_SCOPE` of a shared library will be overriden inside another feature library, there is no point to configure the scope in the shared library. For that reason I create a tiny utility that can be used in each component of the shared library.

I used another (in my opinion cleaner) approach for the loader, you can still use the factory pattern from the official docs.

**shared.provider.ts**

```typescriot
import { Provider } from '@angular/core';
import { TRANSLOCO_SCOPE } from '@ngneat/transloco';

export const translocoProvider : Provider =
{
	provide: TRANSLOCO_SCOPE,
	useValue:
	{
		scope: 'shared',
		loader:
		{
			en: () => import('libs/frontend/shared/src/assets/i18n/en.json'),
			de: () => import('libs/frontend/shared/src/assets/i18n/de.json'),
			mk: () => import('libs/frontend/shared/src/assets/i18n/mk.json')
		}
	}
};

```

**example.component.ts**

```typescriot
import { Component } from '@angular/core';
import { TranslocoService } from '@ngneat/transloco';
import { translocoProvider } from '../../shared.provider';

@Component(
{
	selector: 'shared-example',
	templateUrl: './example.component.html',
	styleUrls:
	[
		'./example.component.scss'
	],
	providers:
	[
		translocoProvider
	]
})
export class ExampleComponent
{
}
```

This should be part of the docs in a "handle nested / shared modules" section. @gethari

**Comment by jesuscc98** [comment]
Any progress on this issue?

Im trying to use transloco in a dynamic form, that receives an attribute to know where should It fetch the translations.

This is an static example of the approach that I am trying to achieve, the translation file `i18n/demand-planning/mock-engine/es.json` is loading correctly.

```jsx
<ng-container *ngIf="i18nLabels === true; else defaultLabel">
    <label *transloco="let t; scope: 'demand-planning/mock-engine'" class="label col-md-3 form-control-label">
        {{ t('demandPlanningMockEngine.expirationDate') }}
    </label>
</ng-container>
```

the first thing Ive been toying with is the key inside my `t` function, my research lead me to that string, but I also have tried with `demand-planning.mock-engine.expirationDate`,
`demandPlanningMockEngine.expirationDate`,

I would be great to expand the docs and detail the nested modules usage.
The only workaround is to use the load function in my component?
