### ISSUE TITLE
schematics ng-add run as externalSchematic throws error "TypeError: Cannot read property 'projectType' of undefined" because projects in angular.json are not read

### ISSUE THREAD

**Issue by vankeer** [ngneat/transloco#294]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I am trying to run the `ng-add` schematic in one of my schematics:

```
externalSchematic('@ngneat/transloco', 'ng-add', {
  // passing my config here...
        langs: languages.join(', '),
        path: 'assets/',
      }),
```

When I run it, I get the following error:

```
TypeError: Cannot read property 'projectType' of undefined
    at /Users/laurens/git/sandbox/node_modules/@ngneat/transloco/schematics/ng-add/index.js:91:31
```

So, this line is failing: https://github.com/ngneat/transloco/blob/master/schematics/src/ng-add/index.ts#L122
Because there are no projects found: https://github.com/ngneat/transloco/blob/master/schematics/src/utils/projects.ts#L31
If I put a `console.log(config)` here, I do indeed see the projects are missing: https://github.com/ngneat/transloco/blob/master/schematics/src/utils/projects.ts#L18

```console.log result
{
	"$schema": "./node_modules/@angular/cli/lib/config/schema.json",
	"version": 2,
	"newProjectRoot": "projects",
	"projects": {},
	"defaultProject": "sandbox"
}
```

However, my angular.json has projects, it's just a default config generated by the CLI:

```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "sandbox": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/sandbox",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "aot": true,
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb",
                  "maximumError": "10kb"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "sandbox:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "sandbox:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "sandbox:build"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "tsconfig.app.json",
              "tsconfig.spec.json",
              "e2e/tsconfig.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "sandbox:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "sandbox:serve:production"
            }
          }
        },
        "cypress-run": {
          "builder": "@briebug/cypress-schematic:cypress",
          "options": {
            "devServerTarget": "sandbox:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "sandbox:serve:production"
            }
          }
        },
        "cypress-open": {
          "builder": "@briebug/cypress-schematic:cypress",
          "options": {
            "devServerTarget": "sandbox:serve",
            "watch": true,
            "headless": false
          },
          "configurations": {
            "production": {
              "devServerTarget": "sandbox:serve:production"
            }
          }
        }
      }
    }
  },
  "defaultProject": "sandbox"
}
```

Why does it not read out the projects?

## Expected behavior

I expect it to run the ng-add schematic

## Minimal reproduction of the problem with instructions

See above description. Simply run the @ngneat/transloco:ng-add schematic using the `externalSchematic` command in a custom schematic, in an Angular app.

## What is the motivation / use case for changing the behavior?

Running the Transloco schematic from schematics.

## Environment

<pre><code>
Angular version: 9.1.7
 
For Tooling issues:
- Node version: 12.16.3
- Platform: Mac

Others:
    "@angular-devkit/build-angular": "~0.901.6",
    "@angular-devkit/schematics": "^9.1.7",
    "@schematics/angular": "^9.1.7",
</code></pre>

**Comment by itayod** [comment]
@vankeer could you upload a reproduction repo?

**Comment by vankeer** [comment]
My mistake: in the specific project I was working on, there was an obscure utility function that read out the angular.json file and removed projects from the object. This issue can be closed.

**Comment by victorcruz86** [comment]
worked for me by adding the following in angular.json

```
 "extensions": {
     "projectType": "application"
 },
```

like

```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "sandbox": {
      "projectType": "application",
      "extensions": {
        "projectType": "application"
      },
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      }
     ...
    }
  }
}
```

**Comment by tarlepp** [comment]
I'm having this same issue and in my `angular.json` I have defined that `projectType` what should I do?
```bash
node@node:/app$ ng add @ngneat/transloco
ℹ Using package manager: yarn
✔ Found compatible package version: @ngneat/transloco@4.1.1.
✔ Package information loaded.

The package @ngneat/transloco@4.1.1 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
? 🌍 Which languages do you need? en, fi
? 🚀 Are you working with server side rendering? No
Cannot read properties of undefined (reading 'projectType')
node@node:/app$ 
```
![image](https://user-images.githubusercontent.com/595561/181382791-e178b59b-1692-4cd3-99b8-45ba23a33624.png)

**Comment by BruneXX** [comment]
Same issue here 👍

**Comment by BruneXX** [comment]
Found a solution, something similar sometimes happens for components generation and you need to set the project using `--project={your-project-name}`

So the full solution will be to execute:
`ng add @ngneat/transloco --project={your-project-name}`

**Comment by tarlepp** [comment]
> Found a solution, something similar sometimes happens for components generation and you need to set the project using `--project={your-project-name}`
> 
> So the full solution will be: `ng add @ngneat/transloco --project={your-project-name}`

Oh, I need to try that one after my summer vacation - thanks for sharing that! Should there be some documentation about this?

**Comment by BruneXX** [comment]
Hi @tarlepp currently **ngneat** has an open PR to integrate a fix for that, so I think that will be sooner than later and you'll not need to care about that anymore. 
That issue arise because Angular v14 has removed the **defaultProject** from the angular.json configuration file.
You can see that here: https://github.com/angular/angular-cli/issues/23470

**Comment by sergiohidekiono** [comment]
> Found a solution, something similar sometimes happens for components generation and you need to set the project using `--project={your-project-name}`
> 
> So the full solution will be: `ng add @ngneat/transloco --project={your-project-name}`

Save me alot! Thanks
