### ISSUE TITLE
transloco key manager does not detects scopes correctly

### ISSUE THREAD

**Issue by stijnvn** [ngneat/transloco#295]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The key manager detects `TRANSLATION_SCOPE_KEY` instead of `myTranslationScopeKey` while parsing the module definition below. 

```
const TRANSLATION_SCOPE _KEY = 'myTranslationScopeKey';

@NgModule({
  imports: [CommonModule, TranslocoModule],
  providers: [
    {
      provide: TRANSLOCO_SCOPE,
      useValue: {
        scope: TRANSLATION_SCOPE_KEY,
        loader: scopeLoader((language, root) => import(`./${root}/${language}.json`))
      }
    }
  ]
})
export class MyFeatureModule {}
```

## Expected behavior

The key manager detects `myTranslationScopeKey` while parsing the module definition below. 

## Minimal reproduction of the problem with instructions

Run `transloco-keys-manager extract`

## What is the motivation / use case for changing the behavior?

In my application the scope key is a constant in a separate file which is imported in different places (the feature module, a transloco testing module...)

## Environment

<pre><code>
Angular version: 9.0.2

**Comment by shaharkazaz** [comment]
@stijnvn please submit this issue in the [keys manager repo](https://github.com/ngneat/transloco-keys-manager);
