### ISSUE TITLE
Transloco - Testing with Spectator

### ISSUE THREAD

**Issue by Kamieniu** [ngneat/transloco#297]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
transloco-root.module.ts
```
import { NgModule } from '@angular/core';
import {
  TRANSLOCO_CONFIG,
  TRANSLOCO_LOADER,
  translocoConfig,
  TranslocoModule,
} from '@ngneat/transloco';

import { TranslocoService } from '@core/services';
import { environment } from '@env/environment';

@NgModule({
  exports: [TranslocoModule],
  providers: [
    {
      provide: TRANSLOCO_CONFIG,
      useValue: translocoConfig({
        availableLangs: ['en'],
        defaultLang: 'en',
        reRenderOnLangChange: true,
        prodMode: environment.production,
      }),
    },
    { provide: TRANSLOCO_LOADER, useClass: TranslocoService },
  ],
})
export class TranslocoRootModule {}
```

transloco-root.ts
```
import { TranslocoConfig, TranslocoTestingModule } from '@ngneat/transloco';

export function getTranslocoModule(config: Partial<TranslocoConfig> = {}) {
  return TranslocoTestingModule.withLangs(
    {},
    {
      availableLangs: ['en', 'es'],
      defaultLang: 'en',
      ...config,
    },
  );
}
```

My Test File

```
describe('SignInFormComponent', () => {
  let spectator: Spectator<SignInFormComponent>;
  const createComponent = createComponentFactory({
    component: SignInFormComponent,
    mocks: [SignInService],
    imports: [
      ......
      getTranslocoModule(),
      .......
    ],
  });

  beforeEach(() => (spectator = createComponent()));

  it('should create', () => {
    expect(spectator).toBeTruthy();
  });
});
```

Getting:

```
Unexpected value 'TranslocoTestingModule' imported by the module 'DynamicTestModule'. Please add an @NgModule annotation.
```

OR

```
Error: Importing TranslocoModule which does not have a ɵmod property
```

## Expected behavior
It should pass the test

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, for that you could use our [stackblitz example](https://stackblitz.com/edit/transloco-example)

## Environment

```
    "@angular/animations": "~9.1.9",
    "@angular/cdk": "^9.2.4",
    "@angular/common": "~9.1.9",
    "@angular/compiler": "~9.1.9",
    "@angular/core": "~9.1.9",
    "@angular/forms": "~9.1.9",
    "@angular/material": "^9.2.4",
    "@angular/platform-browser": "~9.1.9",
    "@angular/platform-browser-dynamic": "~9.1.9",
    "@angular/router": "~9.1.9",
    "@angular/service-worker": "~9.1.9",
    "@ngneat/transloco": "^2.17.2",
    "@ngxs/router-plugin": "^3.6.2",
    "@ngxs/store": "^3.6.2",
    "file-saver": "^2.0.2",
    "ftp-deploy": "^2.3.7",
    "moment": "^2.26.0",
    "ng-inline-svg": "^10.1.0",
    "normalize.css": "^8.0.1",
    "rfdc": "^1.1.4",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
```

<pre><code>
Angular version: 9.1.9

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v14.4.0
- Platform:  Mac

Others:

</code></pre>

**Comment by Kamieniu** [comment]
https://www.loom.com/share/689a8b951f1143ffa1b84b721ca84c90

**Comment by itayod** [comment]
@Kamieniu could you create a minimal reproduction lib on github?

**Comment by micahwood** [comment]
I was having the same issue and wiped out my node_modules folder, ran `npm i` again and it worked after that. Thinking it may have been an issue with ngcc step the first time I installed it. Hopefully that fixes it for you as well.

**Comment by shaharkazaz** [comment]
@Kamieniu Any update on the reproduction? did you try what @micahwood suggested? 🙂

**Comment by shaharkazaz** [comment]
@Kamieniu I'm closing this for now. Please feel free to reopen if this still occurs.
If you do reopen, please provide a reproduction 🙂

**Comment by developer239** [comment]
I can confirm that reinstalling node modules works. Running `ngcc` might be OK too.

**Comment by Olgagr** [comment]
I had the same problem. I reinstalled node_modules with `npm ci` and it helped.
