### ISSUE TITLE
Issue when using full stop in translate service value

### ISSUE THREAD

**Issue by zzakir** [ngneat/transloco#298]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
`this.translocoService.translate('An email was sent to your email address. Please check your mail box.') `

Extracted value in json file:

"'An email was sent to your email address": {
    " Please check your mail box": {
      "'": ""
    }
  }

When ever I try to translate a string with full stop in it, the service thinks it is an object.

## Expected behavior
Extracted value in json value should be :

"'An email was sent to your email address. Please check your mail box.": ""

The service should parse it as a full sentence instead of an object.

## Environment

<pre><code>
Angular version: 9.1.11

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 14.3.0
- Platform:  Mac

Others:

</code></pre>

**Comment by itayod** [comment]
Hi @zzakir I am not sure what do you mean here, could you please create a stackblitz example and show us your use case?

**Comment by itayod** [comment]
@zzakir I am sorry but what you wish is not possible, please find another solution.

**Comment by zzakir** [comment]
@itayod So do you mean that we cannot translate a sentence using this library if it has a full stop in it?

**Comment by itayod** [comment]
@zzakir, of course, you can...
you can translate a sentence like that:
```json
{
  "someKey": "my long sentence. with points."
}
```
and then you can translate like this:
```ts
  this.translocoService.translate('someKey'). // will be: "my long sentence. with points."
```

**Comment by zzakir** [comment]
Ah alright. Now I get it. Thank you very much for your help.
