### ISSUE TITLE
Generic type 'ModuleWithProviders<T>' requires 1 type argument(s)

### ISSUE THREAD

**Issue by HHGAG** [ngneat/transloco#299]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Build quits with 

> ERROR in node_modules/@ngneat/transloco/lib/transloco-testing.module.d.ts:12:87 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).
> 
> 12     static withLangs(langs: HashMap<Translation>, config?: Partial<TranslocoConfig>): ModuleWithProviders;
> ~~~~~~~~~~~~~~~~~~~
> node_modules/@ngneat/transloco-locale/lib/transloco-locale.module.d.ts:9:50 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).
> 
> 9     static init(config?: TranslocoLocaleConfig): ModuleWithProviders;
> ~~~~~~~~~~~~~~~~~~~
> node_modules/@nguniversal/module-map-ngfactory-loader/src/module-map-loader.module.d.ts:25:43 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).
> 
> 25     static withMap(moduleMap: ModuleMap): ModuleWithProviders;

## Expected behavior

Run through build process...

## Environment

<pre><code>
Angular version: 10.0.0

 
For Tooling issues:
- Node version: 10.19.0  
- Platform:  Linux

Others:
Works until Angular version: 8.2.14

</code></pre>

**Comment by HHGAG** [comment]
Seems to be this breaking change: 

https://medium.com/better-programming/angular-10-new-features-dbc779061dc8#cfe7

**Comment by itayod** [comment]
Hi @HHGAG,
Thank you for letting us notice, I have released a new version of `Transloco`, `Transloco-Locale` and the other plugins that were affected by this breaking change.
Could you please try to update the versions and see it works now?

**Comment by HHGAG** [comment]
Hi @itayod,

seems to be fixed. Thnx for the quick bugfix.
