### ISSUE TITLE
Support translation references in message-format customFormatters

### ISSUE THREAD

**Issue by tommueller** [ngneat/transloco#300]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I added message-format support as described in the docs: https://ngneat.github.io/transloco/docs/plugins/message-format
I also added a custom formatter as described in the very end of the aforementioned docs. _Sadly the docs do not have any clues on how to use the customFormatter in the JSON files. Took me quite some time to figure out how to use it so far._

## Expected behavior

I love the feature of referencing other translations within a translation:
```
{
  "home": "home english",
  "fromList": "from {{admin.home}}"
}
```
Since we also use transloco to adapt our app to different wording depending on the customers, we have something like a keyword table, which are reused in other parts of the app:
```
{
  "KEYWORDS": {
    "USER": "User"
  },
  "USERPAGE_TITLE": "{{ KEYWORDS.USER }} page",
  "USER_COUNT": "The page has {{ value }} {{ KEYWORDS.USER }}(s)"
}
```
Depending on the position of the reusage, I would need the word to be starting with a capital or lowercase letter. Messageformat's customFormatter seems perfect for this, but as far as I was able to use it, only works with variables. I would like to avoid to always add the KEYWORD from the template like this: `{{ 'USERPAGE_TITLE' | transloco: { user: { 'KEYWORDS.USER' | transloco } }}`, which technically works, but is horrible for the dev experience ...

## Environment

<pre><code>
Angular version: 9.1.0

</code></pre>

**Comment by itayod** [comment]
Hi @tommueller I am not sure that we want it as part of the core library code, but as you mentioned you have the ability to create a custom formatter, which I think is the best solution for your case...
Why didn't it work for you? what were the difficulties?

**Comment by tommueller** [comment]
We use references within the translation file a lot (see the initial post for an example.

Now when I use this combined with message-format's pluralization it works fine, i.e. this works perfectly:

```
{ "DISCOVER": "{value, plural, =0 { No {{ KEYWORDS.USER }} to discover } one { Discover 1 {{ KEYWORDS.USER }} } other { Discover # {{ KEYWORDS.USERS }} } }" }
```

The problem is, that throughout the translation file, we will sometimes need the value of KEYWORDS.USER with a capital first letter, and sometimes in all lowercase. So I added a customFormatter, i.e.:

```
customFormatters: { capitalize: v => v[0].toUpperCase() + v.slice(1); ) }
```
```
{ "EXAMPLE": "Custom format { example, capitalize }" }
```

This works fine, when using with passed variables: `t('EXAMPLE', { example: 'hello' })`, but not with references like this:
```
{
  "KEYWORDS.USER": "user", 
  "EXAMPLE": "Custom format { {{KEYWORDS.USER}}, capitalize }" }
```
This results in `Cannot read property 'toUpperCase' of undefined`

I hope my issue has become more clear now. Ideally it would even be possible to nest it, so that this would also be possible:
```
{ "DISCOVER": "{value, plural, =0 { No { {{ KEYWORDS.USER }}, capitalize } to discover } one { Discover 1 { {{ KEYWORDS.USER }}, capitalize } } other { Discover # { {{ KEYWORDS.USERS }}, capitalize } }" }
```

**Comment by itayod** [comment]
@tommueller I got your problem, but as I said I would suggest you try to create your own custom formatter for that. Did you try doing that?

**Comment by tommueller** [comment]
@itayod well I honestly do not have any idea on how I would start on that. As far as I understood this so far I did create a custom formatter, but it comes with the limitation of only working with passed variables and not with translation references.

I am happy to try this, but I sincerely don't know how.

**Comment by itayod** [comment]
@tommueller I recommend you take a look at the [message format transpiler](https://github.com/ngneat/transloco/blob/master/projects/ngneat/transloco-messageformat/src/lib/messageformat.transpiler.ts) as an example and start from there (maybe try to extend it and add your logic on top of it...). 

Currently, I don't see any change we need to make in this library in order to support that as it seems like you have all the API you need to achieve that on your own and therefore I am going to close this Issue.

If you do need any change of the current API feel free to reopen this issue or ask on our [gitter](https://gitter.im/ngneat-transloco/lobby) channel for support.

**Comment by Leemonn** [comment]
Hello, any news about this feature? It's needed
