### ISSUE TITLE
documentation up to date

### ISSUE THREAD

**Issue by stefanomiccoli** [ngneat/transloco#302]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I just started having a look to the lib but following the getting started docs it seems to me that the docs are not aligned.

## Expected behavior

**Usage of schematics**
Following the docs I run `yarn run ng add @ngneat/transloco --project=<my project name>` but the code does not generate `transloco-root.module.ts`  as per the doc

**Module configuration**
[Docs](https://ngneat.github.io/transloco/docs/config-options) mention that config options includes `availableLangs` prop.
This is not the case looking at the code of `transloco.config.d.ts`.

## Minimal reproduction of the problem with instructions

1. `yarn run ng add @ngneat/transloco --project=<my project name>` but the code does not generate `transloco-root.module.ts`  as per the docs
2. expect file `transloco-root.module.ts` to be created but does not exist.

## Environment

<pre><code>
Angular version: 10.0.2
Transloco version: 1.1.1
</code></pre>

**Comment by itayod** [comment]
Hi @stefanomiccoli I see that you are using an old version, could you update to the latest version and try again?

**Comment by stefanomiccoli** [comment]
Hi & thanks for the quick reply!

Now that I notice it is indeed a quite old version... However, shouldn't the schematics take care by itself of using the latest version?

Im not at the dev pc now, but will try asap tomorrow ;)

**Comment by shaharkazaz** [comment]
@stefanomiccoli There was an issue with the peer dependency versions that cause the cli to install an older version.
Should be ok now (I released v`2.17.4`), I would recommend re-running the `ng add ` 😄
