### ISSUE TITLE
bug(version): ng add @ngneat/transloco installs version 1.1.1

### ISSUE THREAD

**Issue by AmitMY** [ngneat/transloco#304]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

`ng add @ngneat/transloco` installs version 1.1.1

```
ng new project
cd project
ng add @ngneat/transloco
npm i @ngneat/transloco-messageformat
ng serve # will error
```

uninstalling and reinstalling both packages

**Comment by shaharkazaz** [comment]
@AmitMY Fixed in `v2.17.4` 😃
