### ISSUE TITLE
Angular 10 for transloco-persist-translations dependency

### ISSUE THREAD

**Issue by C0ZEN** [ngneat/transloco#305]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The latest version `1.0.2` has a dependency to `@angular/core` as `>=4.3.0 <10.0.0`.

## Expected behavior

Make it compatible to Angular 10 if this is possible (is it just not updated yet to support Angular 10 or is it already supported but just not updated with the dependencies?

## Minimal reproduction of the problem with instructions

`ng update @ngneat/transloco-persist-translations`

## What is the motivation / use case for changing the behavior?

The migration to Angular 10 should be done without error.

## Environment

<pre><code>
Angular version: 10.0.2
</code></pre>

**Comment by itayod** [comment]
Hi @C0ZEN it is already fixed in the last release, please update to the latest version and it should be fine 😀

**Comment by C0ZEN** [comment]
I just saw that indeed the version `1.0.3` release 30 minutes after your message fix this.

**Comment by shaharkazaz** [comment]
@C0ZEN I released this fix for Transloco main lib yesterday and for the plugins today, @itayod knew I was releasing it 😊
