### ISSUE TITLE
bug(version): ng g @ngneat/transloco:keys-manager installs @ngneat/transloco-keys-manager@1.3.2

### ISSUE THREAD

**Issue by stefanomiccoli** [ngneat/transloco#306]
It's pretty much on the same page of #304 , that identifies the bug that I didnt identify in my #302, hopefully it will be handled in a better way for the next major release of angular

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
`ng g @ngneat/transloco:keys-manager` adds devDependency @ngneat/transloco-keys-manager@version 1.3.2

```
function installKeysManager(host: Tree, context: SchematicContext) {
  addPackageToPackageJson(host, 'devDependencies', 'ngx-build-plus', '^9.0.2');
  addPackageToPackageJson(host, 'devDependencies', '@ngneat/transloco-keys-manager', '^1.0.0');
  context.addTask(new NodePackageInstallTask());
}
```

## Expected behavior

install @ngneat/transloco-keys-manager@2.2.1

**Comment by itayod** [comment]
@stefanomiccoli that's wasn't the same as #304 that was a different and unrelated issue. Anyway, we have changed the script so it will always install the latest version now...
Please upgrade to the latest Transloco's version it should be fixed there.

**Comment by stefanomiccoli** [comment]
Hi Itayod. I may have not explained myself in the best way and apologies if I seemed mean. Only thing I wanted to point out was that both schematics had hardcoded references to old versions, either for the core or the keys-manager packages.

This time I proceeded to update manually, I guess next time the fix will come in hand.

Thanks again for the effort and the very convenient module!
