### ISSUE TITLE
Copyright notice missing

### ISSUE THREAD

**Issue by wolfganggallo** [ngneat/transloco#307]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[x] Other... Please describe:
</code></pre>

## Current behavior

No copyright notice is given in your license text. Since the MIT license requires the preservation of the copyright notice at distribution, you are making it hard to impossible to use your library legally in Germany where copyright can not be waivered. I'm not a lawyer, this is just what they tell me ;-)

## Expected behavior

A copyright notice is given in your license text. For example "Copyright 2020 Netanel Basal, Shahar Kazaz, Itay Oded and contributors". Maybe this link helps: https://www.disclaimergenerator.net/copyright-notices/

## Minimal reproduction of the problem with instructions

See https://github.com/ngneat/transloco/blob/master/LICENSE

## What is the motivation / use case for changing the behavior?

A big company's compliance department is refusing to allow the use of an application using your library because your copyright notice is missing.

**Comment by ChazUK** [comment]
Please add a license 🙏
