### ISSUE TITLE
[Documentation Request] - Currency Pipe

### ISSUE THREAD

**Issue by SvenBudak** [ngneat/transloco#309]
I checked the documentation about the currency pipe: https://netbasal.gitbook.io/transloco/plugins/locale-l10n#currency-pipe but i dont really understand how to use it... I installed latest of `transloco-locale` (1.3.1) and i tryed to import it to my `shared.module`:

```js
import {CommonModule} from '@angular/common';
import {NgModule} from '@angular/core';
import {RouterModule} from "@angular/router";
import {FormsModule, ReactiveFormsModule} from '@angular/forms';
import {HeaderComponent} from './components/header/header.component';
import {TranslocoRootModule} from "../transloco-root.module";
import {LangToFlagPipe} from './pipes/lang-to-flag.pipe';
import {HttpClientModule} from "@angular/common/http";
import {SplideComponent} from './components/splide/splide.component';
import {TranslocoLocaleModule} from '@ngneat/transloco-locale';

// Import Modules here:
const sharedModules = [
    CommonModule,
    HttpClientModule,
    FormsModule,
    ReactiveFormsModule,
    TranslocoRootModule,
    TranslocoLocaleModule,
];

// Declare Components here:
const sharedComponents = [
    HeaderComponent,
];

// Declare Pipes here:
const sharedPipes = [
    LangToFlagPipe
];

@NgModule({
    imports: [
        RouterModule,
        sharedModules
    ],
    declarations: [
        sharedComponents,
        sharedPipes,
        SplideComponent
    ],
    exports: [
        sharedModules,
        sharedComponents,
        sharedPipes
    ]
})
export class SharedModule {
}
```

The first strange thing was that `TranslocoLocaleModule` dont autocomplete the import `import {TranslocoLocaleModule} from '@ngneat/transloco-locale';` I never saw before that this is not working in my IDE...

So i added it manually. But then the import is strange highlighted without any description why.

Anyway i just tryed the pipe with: `{{ 47165.21 | translocoDate }}` but i get `translocoDate > unresolved variable`

and in frontend:

```
core.js:4073 ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(AppModule)[Overlay -> Overlay -> Overlay]: 
  NullInjectorError: No provider for Overlay!
NullInjectorError: R3InjectorError(AppModule)[Overlay -> Overlay -> Overlay]: 
  NullInjectorError: No provider for Overlay!
```

Ps.: i also tryed with `TranslocoLocaleModule.init()` same problem...

Is the documentation maybe not complete?

**Comment by itayod** [comment]
@SvenBudak could you create a small reproduction on stackblitz?

**Comment by SvenBudak** [comment]
I dont get it... i tryed this 10 times last week. now i just do the same and it works...
But one last question to this... 

```
{{ 47165.21| translocoCurrency: 'symbol' : { minimumFractionDigits: 0 } }}
```

When i set `minimumFractionDigits: 0` i expected that he remove the cents totally.
So that i get only `47,165` as output. But he still output me `47.165,21`
Is this what the creator of this pipe expected?

**Comment by itayod** [comment]
@SvenBudak the pipe works by javascript's [intl api](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat) so you can check over there.
For your case, I think the problem is you are using `minimumFractionDigits` instead of `maximumFractionDigits`.
