### ISSUE TITLE
Transloco Locale License

### ISSUE THREAD

**Issue by ChazUK** [ngneat/transloco#310]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x] Other... Please describe:
</code></pre>

## Current behavior

Transloco Locale package does not have a license associated.

## Expected behavior

Add a license similar to Transloco main package https://github.com/ngneat/transloco/blob/master/LICENSE

**Comment by AnttiApina** [comment]
The `package.json` is also missing the license property field.

Lack of licensing details might actually make your code **not** open-source:
http://opensource.stackexchange.com/q/1720/775

**Comment by shaharkazaz** [comment]
@AnttiApina We are looking into the licenses 😃
