### ISSUE TITLE
Transloco not working in IE11

### ISSUE THREAD

**Issue by SuhasParameshwara** [ngneat/transloco#313]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have used transloco in my Angular Project and it works fine in Google Chrome. But when I load it in IE11, it throws me 

`SCRIPT5018: Unexpected quantifier`
`vendor.js (110222,53)`

I just went to that line of code and I found out there's a regex expression.

`var transpiled = value.replace(/\[\[\s*(?<functionName>\w+)\((?<args>.*)\)\s*]]/g, (/**`

I just googled the issue and it said that the characters should be properly escaped. I think here all the characters are properly escaped I guess. Please check and verify it from your end.

REF: [Stackoverflow](https://stackoverflow.com/questions/4923652/why-regexp-generates-an-error-of-unexpected-quantifier-on-ie8)

## Expected behavior

ng-neat transloco should load properly in IE11.

## Minimal reproduction of the problem with instructions

If you try to load transloco in IE11, I think probably you should be able to reproduce this issue

## Environment

<pre><code>
Angular version: 8.2.14
Transloco version: 2.17.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ X ] IE version XX
- [ ] Edge version XX
 

</code></pre>

**Comment by shaharkazaz** [comment]
@SuhasParameshwara should be fixed in v2.18.3 😄

**Comment by SuhasParameshwara** [comment]
@shaharkazaz Thanks for the quick fix 👍
