### ISSUE TITLE
Transloco MessageFormat Error: Localisation function not found for locale

### ISSUE THREAD

**Issue by aerialist7** [ngneat/transloco#316]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

We use "@ngneat/transloco": "2.18.3" with "@ngneat/transloco-messageformat": "1.2.3"
We faced with issue that "transloco-messageformat" works wrong with locale named "default".

How we can fix it?

An error:
```
ERROR Error: Localisation function not found for locale "default"
    at w (messageformat.js:1)
    at new t (messageformat.js:1)
    at mfFactory (ngneat-transloco-messageformat.js:27)
    at MessageFormatTranspiler.setLocale (ngneat-transloco-messageformat.js:87)
    at MessageFormatTranspiler.onLangChanged (ngneat-transloco-messageformat.js:80)
    at TranslocoService.setActiveLang (ngneat-transloco.js:830)
    at app-localization.service.ts:24
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Object.onInvoke (core.js:27147)
    at ZoneDelegate.invoke (zone-evergreen.js:363)
```

## Expected behavior

"transloco-messageformat" should works correctly with any locale.

## Minimal reproduction of the problem with instructions

Sample: https://github.com/aerialist7/transloco-bug-polygon
Run `ng serve` and open browser console on `http://localhost:4200/`

- `app-localization.service.ts` contains language loading logic
- `assets/l10n.json` - contains translations
- `assets/user.json` - contains user language data

## Environment

<pre><code>
Angular version: 10.0.5

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.16.1
- Platform: Windows

**Comment by aerialist7** [comment]
P.S. It's strange, but if I change "default" to "en" all works!

**Comment by itayod** [comment]
@aerialist7 I see that the `"default"` is coming from your `AppLocalizationService` from the `languagePreloader` function so this bug isn't related to this library
