### ISSUE TITLE
ng-add schematic throws an error with default import

### ISSUE THREAD

**Issue by Edouardbozon** [ngneat/transloco#32]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Hi, when I run the installation schematic `ng-add` on my existing project I get an un-relevant error : 

```
Cannot read property 'forEach' of undefined
```

By doing some research I've found that default imports in my `app.module.ts` are causing this issue. When I remove these default imports the schematics works well.

## Expected behavior

Supports of default imports for `ng-add` schematic.

## Minimal reproduction of the problem with instructions

Just add a default import in the `app.module.ts` like : 

```
import something from './my-module';
import { NgModule } from '@angular/core';
```

**Comment by itayod** [comment]
@Edouardbozon Hi, I bumped a version with a fix, could you please try again now?

**Comment by Edouardbozon** [comment]
@itayod It's still not working with `1.1.2` :confused:

**Comment by Edouardbozon** [comment]
Also if I remove default imports I'm getting an error related to the newly added `ssr` property : 

```
ssr is not defined
```

Even if I use defaults values.

**Comment by itayod** [comment]
@Edouardbozon My bad, I didn't build the schematics I will publish a new version asap

**Comment by itayod** [comment]
@Edouardbozon I released a new version, I tested it on a tester project and should be working now :)

**Comment by Edouardbozon** [comment]
Fixed, thanks for the reactivity :zap: !
