### ISSUE TITLE
*transloco="let t; else showLoader"

### ISSUE THREAD

**Issue by bjornharvold** [ngneat/transloco#320]
## I'm submitting a...

<pre><code>
[x] Feature request
</code></pre>

## Current behavior
Sometimes, it takes a while for a lazy loaded modal with lazy loaded JSON to display. When the component defined in the route wraps the component with a 

`<ng-container *transloco="let t">rest of data here</ng-container> `

it can add to the wait time users experience.

## What is the motivation / use case for changing the behavior?
Improved UX

**Comment by shaharkazaz** [comment]
@bjornharvold have you tried using the [loading template](https://ngneat.github.io/transloco/docs/loading-template/)?

**Comment by bjornharvold** [comment]
Fantastic! Was looking through your docs last night but could not find that link. THANK YOU.
