### ISSUE TITLE
Specify start and end parameter value instead of having to overwrite the transpiler

### ISSUE THREAD

**Issue by erikmom** [ngneat/transloco#323]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

In our application we use a mixture of frameworks (Java, Angular) and all of these frameworks read from the same message bundle. Unfortunately these frameworks read the message bundle in a different way regarding the parameters.

An example value in our message bundle : "Failed to delete {0}"

Note the single curly brackets, while transloco expects double curly brackets by default.

To workaround this we have made a custom transpiler, but the only thing that is changed in comparison with the default transpiler is replacing the double curly brackets with single curly brackets.

## Expected behavior

It would be nice if we could just specify a start and end parameter value, instead of overwriting the default transpiler with a custom transpiler.

## What is the motivation / use case for changing the behavior?

Less code to maintain and less likely that things break while upgrading to newer versions of transloco, e.g. if something changes in the default transpiler.

**Comment by shaharkazaz** [comment]
@erikmom Would you like to create a PR for it? 😄

**Comment by shaharkazaz** [comment]
Thanks @Waterstraal for the PR! realease in `transloco v2.19.0` & `transloco-messageformat v1.3.0`
