### ISSUE TITLE
After page reload, translate API does not load 

### ISSUE THREAD

**Issue by guiworks** [ngneat/transloco#331]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When I make the navigation by menu and enter in a component with translations by pipe or API translate, all translations works fine. But when I reload the page, only api translates by (transloco service), doesn't work anymore. Is this normal? Should I do something to recover the transloco module or subscribe? 

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version 84.0.522.61

**Comment by guiworks** [comment]
Well, the translocoServices only works when I navigate by route. But if for some reason I refreshs/reloads/f5 the page, the translations from TranslocoService API disapears. 

All root module has the Transloco Module and app module has your TranslocoRootModule, it should be works as pipe translations work well.

**Comment by itayod** [comment]
@guiworks it seems like you are having an asynchronous issue... which method from the service do you use? could you post your code here?

**Comment by guiworks** [comment]
@itayod Yes, sure.

transloco-root.module.ts (app root directory)
![image](https://user-images.githubusercontent.com/29649474/92113255-6a8a2500-edc5-11ea-859c-cec8d03d192f.png)

app.module.ts
![image](https://user-images.githubusercontent.com/29649474/92113309-81307c00-edc5-11ea-9eeb-e5e9670a9921.png)

features.module.ts (module of all components)
![image](https://user-images.githubusercontent.com/29649474/92113363-94dbe280-edc5-11ea-991a-0d720c14cefa.png)

**Comment by itayod** [comment]
And what about the service...?

**Comment by guiworks** [comment]
> And what about the service...?

locality-list.component.ts (component using transloco)
![image](https://user-images.githubusercontent.com/29649474/92147010-e8175a80-edf0-11ea-8df3-398ccfdef716.png)

using
![image](https://user-images.githubusercontent.com/29649474/92147176-1a28bc80-edf1-11ea-95c5-202f83891311.png)

**Comment by itayod** [comment]
Looks like you are using the `translate` method which is working synchronously while your translation is loading asynchronously,
In that case you should use the `select` method instead which return an observable of the translation.

**Comment by guiworks** [comment]
Ok, just to clarify... 
This uses `this.translocoService.translate('newLocality')` would change to this.translocoService.selectTranslate('newLocality'), right?

Obs: Would be selectTranslate, right?

**Comment by guiworks** [comment]
Now I understood. 

I need create a custom function to load the json before components when the page reload.

**Comment by guiworks** [comment]
Is there some default to recover the translate before initialize the component? Looks like the transloco don't recommended nothing to do, then I wanna to know.

> Looks like you are using the `translate` method which is working synchronously while your translation is loading asynchronously,
> In that case you should use the `select` method instead which return an observable of the translation.

**Comment by guiworks** [comment]
Solved. Thank you for attention.
