### ISSUE TITLE
Can't install inside a package.

### ISSUE THREAD

**Issue by marcobuschini** [ngneat/transloco#333]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Cannot install in packages.

## Expected behavior
It should install also in packages.

## Minimal reproduction of the problem with instructions

Using my test repository at https://github.com/marcobuschini/parking-widget if I issue an `ng add @ngneat/transloco` I end up with:

```
Installing packages for tooling via npm.
Installed packages for tooling via npm.
? 🌍 Which languages do you need? en, it
? 🚀 Are you working with server side rendering? No
Specified module path projects/widget/src/app does not exist
```

And I cannot do anything about that because I am developing a reusable library package, and not an application.

## What is the motivation / use case for changing the behavior?
I want to use this on a reusable package and not on a monorepo app with packages inside the app.

## Environment

<pre><code>
Angular version: 9.1.2

Browser:
- I didn't get that far ;-)
 
For Tooling issues:
- Node version: v12.18.3
- Platform: Linux

Others:

</code></pre>

**Comment by itayod** [comment]
@marcobuschini did you try using the `--project` and `--module` flags?
see in [docs](https://ngneat.github.io/transloco/docs/schematics#options)

**Comment by marcobuschini** [comment]
@itayod I will try that as soon as I get back from the holidays in two weeks. Anyway, that trick is not mentioned in the docs at https://ngneat.github.io/transloco/docs/installation.

**Comment by itayod** [comment]
I am closing this issue, let me know if it doesnt work for you...
