### ISSUE TITLE
Docs: selectTranslationObject() should have been selectTranslateObject()

### ISSUE THREAD

**Issue by michalstanko** [ngneat/transloco#337]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Docs incorrectly mention `selectTranslationObject()`

## Expected behavior

Docs should mention `selectTranslateObject()`

## Minimal reproduction of the problem with instructions

Go to [docs](https://ngneat.github.io/transloco/docs/translation-api#selecttranslationobject) and read the `selectTranslationObject()` header

**Comment by shaharkazaz** [comment]
@michalstanko Thanks, I'll take care of it 🙂
