### ISSUE TITLE
[Feature Request] - getCurrentCurrency

### ISSUE THREAD

**Issue by SvenBudak** [ngneat/transloco#339]
Hi. I cant find any way to get just the current currency name or symbol.
At this moment i use `{{0| translocoCurrency: 'code' }}` and use `text-indent: -24px` to remove the 0
a function that returns the currency code / symbol / name would be very helpfull.

best regards.

PS.: I solved it by creating a pipe:

import { Pipe, PipeTransform } from '@angular/core';

````javascript
@Pipe({
  name: 'stringToCurrency'
})
export class StringToCurrencyPipe implements PipeTransform {

  transform(value: string): string {
    return value.replace(/[\d\s\,\.]/g, '');
  }

}
````

Then: `{{(0 | translocoCurrency: 'code') | stringToCurrency }}`

Bit dirty and i hope for a better solution.

**Comment by itayod** [comment]
Hi, sorry for the late feedback, feel free to create a PR for that :)
