### ISSUE TITLE
It should treat `zh-Hans`, `zh-Hant` as valid BCP47 language tags

### ISSUE THREAD

**Issue by szhong-becls** [ngneat/transloco#341]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The current BCP47 language tag validation function treats `zh-Hans`, `zh-Hant`, etc. as invalid language tags.

https://github.com/ngneat/transloco/blob/c1f620879070fd7c4749e01ade53f77b978860ba/projects/ngneat/transloco-locale/src/lib/helpers.ts#L13-L15

## Expected behavior

It should treat `zh-Hans`, `zh-Hant`, etc as valid language tags. These locale ids are supported by Angular: https://github.com/angular/angular/tree/master/packages/common/locales

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, for that you could use our [stackblitz example](https://stackblitz.com/edit/transloco-example)

## What is the motivation / use case for changing the behavior?

My project is going to support Chinese, and want to use the latest language tags (locale ids). So use `zh-Hans` instead of `zh-CN`, and `zh-Hant` instead of `zh-TW`.

## Environment

N/A

**Comment by itayod** [comment]
Hi @szhong-becls it should be fixed in the latest version, could you please upgrade and validate that it works for you?

**Comment by szhong-becls** [comment]
@itayod Thanks for adding this feature. It works well.
