### ISSUE TITLE
Lazy load do not found, only read base folder

### ISSUE THREAD

**Issue by ODH003** [ngneat/transloco#342]
Hi team 

I have a little problem, i use Angular 10 and have multiple lazy modules but when I want to use transloco component I cant use it.  My lazy modules always read the main languajes but not the new folders and files for it.

Here is my package

`{
    "name": "inlandnet",
    "version": "0.0.0",
    "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "build": "ng build",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e"
    },
    "private": true,
    "dependencies": {
        "@agm/core": "3.0.0-beta.0",
        "@angular/animations": "^10.1.1",
        "@angular/cdk": "^10.2.0",
        "@angular/common": "^10.1.1",
        "@angular/compiler": "^10.1.1",
        "@angular/core": "^10.1.1",
        "@angular/fire": "^6.0.2",
        "@angular/forms": "^10.1.1",
        "@angular/material": "^10.2.0",
        "@angular/platform-browser": "^10.1.1",
        "@angular/platform-browser-dynamic": "^10.1.1",
        "@angular/router": "^10.1.1",
        "@ng-bootstrap/ng-bootstrap": "^7.0.0",
        "@ng-select/ng-select": "^5.0.1",
        "@ngneat/transloco": "^2.19.1",
        "@types/file-saver": "^2.0.1",
        "@types/googlemaps": "^3.39.13",
        "@types/html2canvas": "0.0.35",
        "agm-direction": "^0.8.6",
        "angular-google-charts": "^1.1.6",
        "angular-tinymce": "^6.0.0",
        "angularx-qrcode": "^10.0.10",
        "chart.js": "^2.9.3",
        "classlist.js": "^1.1.20150312",
        "compass-mixins": "^0.12.10",
        "core-js": "^3.6.5",
        "file-saver": "^2.0.2",
        "firebase": "^7.20.0",
        "html2canvas": "1.0.0-rc.7",
        "jspdf": "^2.1.1",
        "location-picker": "^1.1.1",
        "moment": "^2.27.0",
        "moment-timezone": "^0.5.31",
        "ng2-charts": "^2.4.1",
        "ng2-dragula": "^2.1.1",
        "ng2-pdf-viewer": "^6.3.2",
        "ng2-validation": "^4.2.0",
        "ng5-slider": "^1.2.4",
        "ngx-avatar": "^4.0.0",
        "ngx-chips": "^2.1.0",
        "ngx-currency": "^2.5.1",
        "ngx-device-detector": "^2.0.0",
        "ngx-mask": "^10.0.1",
        "ngx-tags-input": "^2.0.1",
        "primeicons": "^4.0.0",
        "primeng": "^10.0.0",
        "rxjs": "^6.6.3",
        "tinymce": "^5.4.2",
        "travel-marker": "^0.13.0",
        "web-animations-js": "^2.3.2",
        "xlsx": "^0.16.7",
        "zone.js": "^0.11.1"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "^0.1001.1",
        "@angular/cli": "^10.1.1",
        "@angular/compiler-cli": "^10.1.1",
        "@angular/language-service": "^10.1.1",
        "@types/jasmine": "^3.5.14",
        "@types/jasminewd2": "^2.0.8",
        "@types/node": "^12.12.58",
        "codelyzer": "^6.0.0",
        "jasmine-core": "~3.6.0",
        "jasmine-spec-reporter": "~5.0.2",
        "karma": "~5.2.2",
        "karma-chrome-launcher": "~3.1.0",
        "karma-coverage-istanbul-reporter": "~3.0.3",
        "karma-jasmine": "~4.0.1",
        "karma-jasmine-html-reporter": "^1.5.4",
        "protractor": "^7.0.0",
        "ts-node": "~9.0.0",
        "tslint": "~6.1.3",
        "typescript": "~4.0.2",
        "webpack": "^4.44.1",
        "webpack-dev-middleware": "^3.7.2",
        "webpack-dev-server": "^3.11.0",
        "webpack-hot-middleware": "^2.25.0"
    }
}

My transloco root module is configured as the webpage

my structure is , the main module is inlo.module.ts, the lazy module is ind.module.ts

![image](https://user-images.githubusercontent.com/48140216/93003364-bc3c5900-f503-11ea-8ef3-d06baef4260b.png)

![image](https://user-images.githubusercontent.com/48140216/93003575-7f716180-f505-11ea-8707-0db2fdf3486b.png)

in ind.module.ts I have this configuration:

![image](https://user-images.githubusercontent.com/48140216/93003391-eb52ca80-f503-11ea-9199-fe3fedeaa2d6.png)

the i18n folders is like 

![image](https://user-images.githubusercontent.com/48140216/93003402-045b7b80-f504-11ea-9eaf-19cb169c2fe1.png)

but when i want to use in my components lazy modules only use the i18n/en.json files not i18n/inland/en.json

I put the log in my TranslocoHttpLoader

![image](https://user-images.githubusercontent.com/48140216/93003430-3ec51880-f504-11ea-99c2-0d9d41819c32.png)

in console read all the files but in lazy module do not use it.

![image](https://user-images.githubusercontent.com/48140216/93003440-543a4280-f504-11ea-842c-e9c8303076f4.png)

In the lazy component i use it

![image](https://user-images.githubusercontent.com/48140216/93003494-d32f7b00-f504-11ea-817b-27e5d0dd2eb1.png)

but do not read

![image](https://user-images.githubusercontent.com/48140216/93003513-fb1ede80-f504-11ea-9710-054f33e08ddc.png)

**Comment by dabbid** [comment]
As far as I can read, it seems that you don't use the `inland` namespace in your `ind.nav.html`, i.e. `{{tnsa('maintest')}}` should be `{{tnsa('inland.maintest')}}`

**Comment by ODH003** [comment]
Hi @dabbid  that's right, the problem was it, thank you for your support.
