### ISSUE TITLE
Development time packages are potentially marked as production packages

### ISSUE THREAD

**Issue by antpyykk** [ngneat/transloco#343]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

We are performing a license collection in our project, which crawls through all of our production (e.g. "dependencies") packages and their subdependencies. Couple of collected libraries originate from transloco packages, which only seem to be relevant during development time.

**parse-json**
```
yarn why v1.22.5
[1/4] Why do we have the module "parse-json"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "parse-json@5.0.0"
info Reasons this module exists
   - "@ngneat#transloco#@ngneat#transloco-utils#cosmiconfig" depends on it
   - Hoisted from "@ngneat#transloco#@ngneat#transloco-utils#cosmiconfig#parse-json"
```

**has-flag**
```
yarn why v1.22.5
[1/4] Why do we have the module "has-flag"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "has-flag@3.0.0"
info Reasons this module exists
   - "@ngneat#transloco#ora#chalk#supports-color" depends on it
   - Hoisted from "@ngneat#transloco#ora#chalk#supports-color#has-flag"
```

## Expected behavior

Some Transloco packages should be marked as `devDependencies` as they are not used during browser runtime. 
- **cosmiconfig** package is used to load package.json files
- **ora** package showcases a fancy loading spinner in terminal

Or are these packages added under "dependencies", for publishing reason?

## Environment

**Installed transloco packages**

- "@ngneat/transloco-locale@1.3.0"
- "@ngneat/transloco-utils@1.1.1"
- "@ngneat/transloco@2.17.3"
 
- Node version: v12.9.1
- yarn v1.22.5

**Comment by itayod** [comment]
Could you please be more specific and tell us which packages you think should be `devDependencies`?

**Comment by itayod** [comment]
@antpyykk I have checked about the packages you mentioned, those packages used as dependencies for Transloco's schematics and needed for publishing the package.
