### ISSUE TITLE
Path defined in a library's inline loader no more functional when library is used in an ivy project

### ISSUE THREAD

**Issue by dabbid** [ngneat/transloco#346]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I've got an Angular 8 library packaged with ng-packagr, that embeds its own translation file, copied in `dist/my-npm-scope/my-lib/assets/i18n/` folder, then published on an private repo. Now if I use this library in an Angular 10 project compiled with view engine, everything works fine, but if I enable ivy compilation, then my lib gets compiled in a `/__ivy_ngcc__/fesm2015` folder, and that additional `__ivy_ngcc__` folder breaks the path defined in my lib's transloco inline loader (i.e. I've got a `../assets/i18n/en.json` path which works with view engine, while I should have `../../assets/i18n/en.json` with ivy)

## Expected behavior

A solution that would make things work both for view engine and ivy compilation.

**Comment by itayod** [comment]
@dabbid is it still relevant?

**Comment by shaharkazaz** [comment]
Please reopen if this is still relevant and provide a valid reproduction or demo so we can understand this issue better.
