### ISSUE TITLE
Transloco with MatSortModule (material)

### ISSUE THREAD

**Issue by M-Blobby** [ngneat/transloco#351]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I'm using angular material table with the matSort. When my table is inside the directive transloco, the sort doesn't work (no effect when I click on the arrow) :
```html
<div *transloco="let t">
  <h1>{{ t("hello") }}</h1>

  <table mat-table [dataSource]="dataSource" matSort class="mat-elevation-z8">
    <!-- Position Column -->
    <ng-container matColumnDef="position">
      <th mat-header-cell *matHeaderCellDef mat-sort-header>No.</th>
      <td mat-cell *matCellDef="let element">{{ element.position }}</td>
    </ng-container>
  </table>
</div>
```

When my table is out of *transloco, the sort works :
```html
<div *transloco="let t">
  <h1>{{ t("hello") }}</h1>
</div>

<table mat-table [dataSource]="dataSource" matSort class="mat-elevation-z8">
    <!-- Position Column -->
    <ng-container matColumnDef="position">
      <th mat-header-cell *matHeaderCellDef mat-sort-header>No.</th>
      <td mat-cell *matCellDef="let element">{{ element.position }}</td>
    </ng-container>
</table>
```

## Expected behavior

Use transloco with mat-table and mat-sort for be able to translate my table headers.
I suppose the problem is on transloco side, but I may be wrong and it's on material side (or I'm missing something else ...).

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/transloco-material-table?file=src/app/app.component.html

## Environment

<pre><code>
Angular version: 10.0.1 - 10.1.3

Browser:
- [x] Chrome (desktop) version 85.0.4183.121
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 73.0.1
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version 85.0.564.51
 
For Tooling issues:
- Node version: v12.18.3
- Platform:  Windows

</code></pre>

**Comment by itayod** [comment]
Hi, @M-Blobby looking at your case, seems like you have asynchronous problem, pay attention that in your `afterViewInit` method `this.sort` is `undefinded`.
This is due to the translation didn't finish to load and therefor your view is not up in `AfterViewInit`.

this problem can be resolved in many way... one of them would be replacing
```ts
  @ViewChild(MatSort) sort: MatSort;
```  
with this
```ts
  @ViewChild(MatSort) set sort(sort: MatSort) {
    this.dataSource.sort = sort;
  };
```
