### ISSUE TITLE
How to lazy load TranslocoLocaleModule

### ISSUE THREAD

**Issue by alexdabast** [ngneat/transloco#353]
Hi I have a question on how to use TranslocoLocaleModule in lazy loaded modules ?
The documentation do not provide any information about that.

Should TranslocoLocaleModule be imported in each lazy loaded modules with his init function ? `TranslocoLocaleModule.init()`

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
No documentation about on how to load the TranslocoLocaleModule in a lazy loaded module

## Expected behavior
The documentation should explain how to load this TranslocoLocaleModule

## Minimal reproduction of the problem with instructions
N/A

## What is the motivation / use case for changing the behavior?

I would like to use TranslocoLocaleModule in a ionic project with lazy loaded modules

## Environment
N/A

**Comment by itayod** [comment]
@alexdabast `TranslocoLocaleModule` provides you with locale pipes, as mention at the docs, basically just like in every module you will need to import wherever you need to use those pipes...

The `init` is a configuration method to initial those providers therefor it needs to be called once when you provide you configuration settings.
