### ISSUE TITLE
Inline loader doesn't load translation when pipe is passed to content projection

### ISSUE THREAD

**Issue by artaommahe** [ngneat/transloco#355]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Passing `transloco` pipe usage as content projection to other component with `transloco` pipe usage, when both components use inline loaders, leads to no translation for th first one

## Expected behavior

Both translation work

## Minimal reproduction of the problem with instructions

Demo https://stackblitz.com/edit/transloco-inline-loaders-content-projection?file=src%2Fapp%2Fapp.component.html

- app component has a translation for the `app.text` key
- hello component has a translation for the `hello.text` key
- both components load translations inline via providing `TRANSLOCO_SCOPE` token and use `transloco` pipe to translate
- app's text is passed to hello component's content projection
- no translation for `app.text`
- uncomment `<!-- {{ 'app.text' | transloco }} -->` in `app.component.html` and both translation works well

## What is the motivation / use case for changing the behavior?

It should work ¯\\\_(ツ)\_/¯

## Environment

Stackblitz

<pre><code>
Angular version: 10.1.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by artaommahe** [comment]
Furthermore where is even an issue with passing translation via input.
Same example, but using input instead of content projection
```html
<hello [title]="'app.text' | transloco"></hello>
```
No translation for `app.text` 😶

https://stackblitz.com/edit/transloco-inline-loaders-input?file=src/app/app.component.html

**Comment by shaharkazaz** [comment]
@artaommahe in your `hello.component` change the `providers` to `viewProviders`.

**Comment by artaommahe** [comment]
@shaharkazaz O_o never saw this thing in the wild.. thx. Looks like this should be added to the inline loaders docs page to avoid further issues like this one

**Comment by shaharkazaz** [comment]
@artaommahe I'll add a reference for it in the FAQ or the inline loaders docs when I have the time.
