### ISSUE TITLE
MessageFormatTranspiler.transpile takes a lot of time

### ISSUE THREAD

**Issue by k3nsei** [ngneat/transloco#358]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

`MessageFormatTranspiler.transpile` method takes a lot of time almost 3ms.

![Zrzut ekranu 2020-10-05 o 11 31 34](https://user-images.githubusercontent.com/190422/95187073-0646f080-07cb-11eb-855b-44c1aac18d36.png)

![Zrzut ekranu 2020-10-6 o 12 38 43](https://user-images.githubusercontent.com/190422/95191351-efa39800-07d0-11eb-9b43-a36518349e5f.png)

## Expected behavior

Messages can be pre-transpiled when translations are set or loaded. Then generated closure can be memoized. To not parse them with every rerender.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/transloco-example-izuqre?file=src/app/app.component.ts

## What is the motivation / use case for changing the behavior?

Better performance

## Environment

<pre><code>
Angular version: 6.1.10

Browser:
- [x] Chrome (desktop) version 85
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.22.0  
- Platform:  Mac 

Others:

</code></pre>

**Comment by itayod** [comment]
Hi, I hope I could get to it soon as I am pretty busy these days...
In the mean time you are welcome to create a pr for it.

**Comment by k3nsei** [comment]
@itayod If I manage to find time, I will definitely try to improve it by myself.
