### ISSUE TITLE
Reference Plural Translations in Keys

### ISSUE THREAD

**Issue by ChazUK** [ngneat/transloco#359]
Is it possible to to use plurals inside of translation files?

https://ngneat.github.io/transloco/docs/additional-functionality#reference-other-keys + https://ngneat.github.io/transloco/docs/plugins/message-format#usage

**Comment by shaharkazaz** [comment]
@ChazUK Yes, you can, here is an example:

#### `en.json`
```json
{
  "test": "My {{mySelectRule}}",
  "mySelectRule": "{myVar, select, val1 {Value 1} val2 {Value 2} other {Other Value}}"
}
```

#### `Template`
```
<h1>{{ 'test' | transloco:{myVar: 'val2'} }}</h1>
```

#### Output
```
My Value 2
```

**Comment by Brechard** [comment]
Hi @shaharkazaz I have tried as you suggested but it does not work, I have created a stackblitz with the exact same code you provide, just copy paste. I have also tried sending a message in gitter but nobody is saying anything 
https://ngneat-transloco-esgpbz.stackblitz.io/

**Comment by shaharkazaz** [comment]
@Brechard Can you provide the edit link?

**Comment by ChazUK** [comment]
@shaharkazaz https://stackblitz.com/edit/ngneat-transloco-esgpbz

**Comment by shaharkazaz** [comment]
@ChazUK @Brechard The `@ngneat/transloco-messageformat` lib isn't event installed.

**Comment by ChazUK** [comment]
@shaharkazaz Don't shoot the messenger! ✋ 🤚

I did however forget to thank you for the original solution! Thank you :)
