### ISSUE TITLE
Avoid scope name while using transloco pipe in library

### ISSUE THREAD

**Issue by BVSureshBabu** [ngneat/transloco#363]
Hi,

I am migrating my app from 'ngx-translate' to 'transloco'. Followed the below link and placed translation files in the library. 

https://github.com/NetanelBasal/transloco-with-nx-libs

And ended up with one issue that scope name to be added before to all keys placed in the library `{{scopeName.key|transloco}}`.

Please help me with avoiding scope name to be added for all keys in the library.

```typescript
import { Component, Inject, OnInit } from '@angular/core';
import { TranslocoService, TRANSLOCO_SCOPE } from '@ngneat/transloco';

@Component({
  selector: 'transloco-with-libs-a',
  template: `
    <ng-container >
      <p *transloco="let t; read:'compA'">where am I? {{ t('gpsa') }}</p>
    </ng-container>
    {{'compA.gpsa'|transloco}}  \\\\\\\\\\\\\\\\\\\\  **How to avoid this scope name while using transloco pipe**
  `
})
export class LocationAComponent implements OnInit {

  msg="User added successfully";

  constructor(private translocoService: TranslocoService,  @Inject(TRANSLOCO_SCOPE) private scope) {}

  ngOnInit() {

    this.translocoService.selectTranslate('gpsa',{},this.scope).subscribe(result => {
      console.log("Translation is   ",result);
    })

    this.translocoService.selectTranslate('gps').subscribe(result => {
      console.log("GPS  Translation is   ",result);
    })

  }
}
```

Thanks,
Suresh

**Comment by shaharkazaz** [comment]
@BVSureshBabu I need you to further explain what you mean by:

> one issue that scope name to be added before to all keys placed in the library

I'm not sure I understand what's the issue.
Can you please give an example of the expected behavior and current behavior? 🙂

**Comment by BVSureshBabu** [comment]
@shaharkazaz Thanks for reply.

In this below example if I use transloco directive, I can avoid scope name by using read.
But if I use transloco pipe, every time need to use scope name before the key. Is there any way to avoid scope name before all keys while using transloco pipe. 


import { Component, Inject, OnInit } from '@angular/core';
import { TranslocoService, TRANSLOCO_SCOPE } from '@ngneat/transloco';

@Component({
  selector: 'transloco-with-libs-a',
  template: `
    <ng-container >
      <p *transloco="let t; read:'compA'">where am I? {{ t('gpsa') }}</p>
    </ng-container>
    **{{'compA.gpsa'|transloco}}  \\\\\\\\\\\\\\\\\\\\  **How to avoid this scope name while using transloco pipe**
    {{'compA.string1'|transloco}}
    {{'compA.string2'|transloco}}**
  `
})
export class LocationAComponent implements OnInit {

  msg="User added successfully";

  constructor(private translocoService: TranslocoService,  @Inject(TRANSLOCO_SCOPE) private scope) {}

  ngOnInit() {

    this.translocoService.selectTranslate('gpsa',{},this.scope).subscribe(result => {
      console.log("Translation is   ",result);
    })

    this.translocoService.selectTranslate('gps').subscribe(result => {
      console.log("GPS  Translation is   ",result);
    })

  }
}

Thanks,
Suresh

**Comment by shaharkazaz** [comment]
@BVSureshBabu the scope name is part of the key, therefore you can't avoid writing it when using the pipe.
The structural directive's read input does the prefixing for you.
In the example you provided, why use the pipe? why aren't all your translations from the same scope under the structural directive? 
```html
    <ng-container *transloco="let t; read:'compA'">
      <p>where am I? {{ t('gpsa') }}</p>
      {{ t('string1') }}
    </ng-container>
```

**Comment by shaharkazaz** [comment]
@BVSureshBabu did you get the chance to see my comment? did it help you get the solution you were looking for? 🙂

**Comment by BVSureshBabu** [comment]
@shaharkazaz  Sorry for the delay in reply.

Thanks for your suggestion. I am looking to avoid scope name while using transloco pipe instead of directive.

**Comment by shaharkazaz** [comment]
@BVSureshBabu, unfortunately, there isn't a way since it's part of the translation key 🙂
