### ISSUE TITLE
sample application is down

### ISSUE THREAD

**Issue by StanevichIvan** [ngneat/transloco#365]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

https://transloco.netlify.app/home is broken.
![image](https://user-images.githubusercontent.com/20155344/97274074-31aa8180-1845-11eb-8ee5-75399f94bff5.png)

## Expected behavior

As a developer I would like to see sample app by navigation thought the docs link.  

## Minimal reproduction of the problem with instructions

* Open https://github.com/ngneat/transloco
* Click on the link 👉 Checkout the sample application

Result: server return 404
Expected result: site is working

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [X] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by shaharkazaz** [comment]
@StanevichIvan Thanks for that! the link was pointing to the old sample app, the current app is [inside the docs site](https://ngneat.github.io/transloco/sampleApp).
I'll update 👍
