### ISSUE TITLE
Add module loader library to documentation

### ISSUE THREAD

**Issue by larscom** [ngneat/transloco#37]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## What is the motivation / use case for changing the behavior?

I've ported a library (from ngx-translate) to transloco, its my own library for loading mutliple translations via http. Would love to see it in the transloco documentation :smiley:

Library: https://github.com/larscom/transloco-module-loader

Working demo: https://stackblitz.com/edit/transloco-module-loader

**Comment by shaharkazaz** [comment]
Nice! would you like to make it an official plugin for transloco? 😃

**Comment by NetanelBasal** [comment]
@larscom thanks for your work. I think that your functionality is already provided out of the box in Transloco (with lazy scoping). Can you verify it from this [comment](https://github.com/ngneat/transloco/issues/24#issuecomment-524056486), please?

**Comment by larscom** [comment]
@NetanelBasal i think you are right! Great work :smiley:

**Comment by NetanelBasal** [comment]
@larscom We really do appreciate the effort, and we'll add you to the contributors' list. We'd love to see more of you in the future 💯.

**Comment by larscom** [comment]
> @larscom We really do appreciate the effort, and we'll add you to the contributors' list. We'd love to see more of you in the future .

Thanks alot! appreciated.
