### ISSUE TITLE
When i used queryParams I cant load translation file

### ISSUE THREAD

**Issue by muhammadsamir11** [ngneat/transloco#371]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, for that you could use our [stackblitz example](https://stackblitz.com/edit/transloco-example)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by shaharkazaz** [comment]
@muhammadsamir11 This issue is lacking a lot of information.
Please follow the issue template and provide a reproduction and more information about the current behavior, the expected one, and the versions of the packages.

**Comment by shaharkazaz** [comment]
@muhammadsamir11 I'm closing this for now. 
Feel free to reopen if the issue still exists and please provide more information and a reproduction 🙂
