### ISSUE TITLE
How to escape template variable parser in JSON

### ISSUE THREAD

**Issue by ChazUK** [ngneat/transloco#372]
I'm trying to store a regular expression in one of the language JSON files.

The expression is a simple date format which may change between different regions eg `/^\d{2}[/]\d{2}[/]\d{4}$/`.
This works fine when creating a new RegExp object `new RegExp(/^\d{2}[/]\d{2}[/]\d{4}$/)` and when working with it as a string the backslashes need to be escaped which then becomes `new RegExp('^\\d{2}[/]\\d{2}[/]\\d{4}$')`.

Adding this into the the JSON file

```
{
  "pattern": "^\\d{2}[/]\\d{2}[/]\\d{4}$",
}
```

When console logging this translation `console.log(translate('scope.pattern'));` it outputs

```
^\dundefined[/]\dundefined[/]\dundefined$
```

I'm guessing that `{2}` is trying to be replaced with a variable. Is it possible to escape these characters correctly?

**Comment by shaharkazaz** [comment]
@ChazUK Seems like it's [working as expected](interpolation) since the default interpolation's start and end markings are `{{` & `}}`.
Any chance you changed the markings in your config?

**Comment by ChazUK** [comment]
I'm confused, if the interpolation markings are `{{  }}` then why is it trying to run it on the single `{ }` in my case?

**Comment by shaharkazaz** [comment]
@ChazUK IDK, have you seen the working example I added? 
Create a reproduction in stackblitz so we can try an tackle this 🙂

**Comment by ChazUK** [comment]
@shaharkazaz will do, the first link in your response is to a search of the github issues for "author:interpolation" I don't know if that was intentional.

**Comment by ChazUK** [comment]
I've found the issue, it's the use of `formatjs` in `TranslocoMessageFormatModule`, there's an issue here https://github.com/formatjs/formatjs/issues/1182. I'll close this ticket and see if I can follow up there.

Thanks

**Comment by shaharkazaz** [comment]
@ChazUK I updated the link anyways 👍
