### ISSUE TITLE
@ViewChild() not working in the scope of the *transloco directive

### ISSUE THREAD

**Issue by bojidaryovchev** [ngneat/transloco#375]
https://stackblitz.com/edit/angular-ivy-tpnv2n?file=src%2Fapp%2Fapp.component.ts

check out the console, trying to access a view child inside an element with the *transloco directive on it yields undefined

**Comment by shaharkazaz** [comment]
@bojidaryovchev The transloco structural directive has an async operation in its internals which is fetching the translations.
So the contents of the directive won't be available in the `ngAfterViewInit` method.
The simplest way you can gain access to the element on render is by making the `ViewChild` a setter.
This is no different than any other structural directive, it will only set the template once the content is ready, [see the demo](https://stackblitz.com/edit/angular-ivy-vovl3z?file=src%2Fapp%2Fapp.component.ts).

**Comment by itayod** [comment]
@bojidaryovchev did you understand your problem? can we close this?

**Comment by shaharkazaz** [comment]
@bojidaryovchev The answer to this question is now part of our [faq](https://ngneat.github.io/transloco/docs/faq#why-does-querying-an-element-inside-the-transloco-directive-using-viewchild-not-working) as it was raised before.

If you have more questions, feel free to send a message in our [gitter lobby](https://gitter.im/ngneat-transloco/lobby), there are members of our community who can help you out. I'm there also of course 🙂
