### ISSUE TITLE
selectTranslate emits only the first time the active language is changed

### ISSUE THREAD

**Issue by micobarac** [ngneat/transloco#378]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

`selectTranslate` **emits only the first time the active language is changed**.

## Expected behavior

Docs say: `selectTranslate` **will emit each time the active language is changed**.

## Minimal reproduction of the problem with instructions

I installed @ngneat/transloco with:

`ng add @ngneat/transloco`

This installed some old version `1.1.1` instead of the latest `2.19.2`?!

`this.translocoService.selectTranslate('hello').subscribe((value) => console.log(value));`

**This event fires only once, on page load, but with empty result.**

My language file is simple:

```json
{
  "hello": "Hello"
}
```
The console output says the language file was loaded successfully:

`ngneat-transloco.js:508  🍻 Translation Load Success: en`

Any subsequent language changes are ignored.

## What is the motivation / use case for changing the behavior?

**Getting the translation asynchronously on every language change**

## Environment

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 11.0.3
Node: 14.15.0
OS: darwin x64

Angular: 11.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.3
@angular-devkit/build-angular   0.1100.3
@angular-devkit/core            11.0.3
@angular-devkit/schematics      11.0.3
@angular/cdk                    11.0.1
@angular/flex-layout            11.0.0-beta.33
@angular/material               11.0.1
@schematics/angular             11.0.3
@schematics/update              0.1100.3
rxjs                            6.6.3
typescript                      4.0.5</code></pre>

**Comment by micobarac** [comment]
The right issue here is why the `ng add @ngneat/transloco` installs ancient version `"@ngneat/transloco": "1.1.1"`?

**Comment by shaharkazaz** [comment]
@micobarac hey, I believe it's because the peer dependency of transloco isn't updated to Angular 11, so the cli goes to the first matching version that does.
This will be fixed once we update, should be in the next few days.

**Comment by micobarac** [comment]
This was the issue with the previous Angular versions also. The only workaround was to manually install the latest dependency and then run the schematics.

**Comment by shaharkazaz** [comment]
@micobarac This will be resolved via #379. after I release a new version it should work as expected.

**Comment by shaharkazaz** [comment]
@micobarac would be great if you can retry now and verify 🙂

**Comment by micobarac** [comment]
@shaharkazaz I created a brand new Angular project.

`ng add @ngneat/transloco` added the correct version `"@ngneat/transloco": "^2.19.3"` to `package.json`.

It's ok now. Thanks. :D
