### ISSUE TITLE
Failure when considering Transloco for use in an exisitng project

### ISSUE THREAD

**Issue by marcobuschini** [ngneat/transloco#384]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

During tests (Jest, without spectator) strings are not translated and keys are used instead. For example 'MY_KEY' stays as 'MY_KEY' instead of getting the value 'This is a key'. It works when run.

## Expected behavior

Proper substitution of kyes with translated strings.

## Minimal reproduction of the problem with instructions

It's a project of 20000 lines of code I am migrating to transloco. Well, considering migrating.

## What is the motivation/use case for changing the behavior?

I need to test the code during the commit (husky hooks).

## Environment

<pre><code>
Angular CLI: 10.2.0

Browser:
- [x] None, it's a Jest issue.
 
For Tooling issues:
 - Node: 12.4.0
 - OS: win32 x64
</code></pre>

**Comment by shaharkazaz** [comment]
@marcobuschini sounds like #250, this should be fixed in the next version.

**Comment by marcobuschini** [comment]
@shaharkazaz thanks, I will check the next version, then. When it should be available?

**Comment by shaharkazaz** [comment]
@marcobuschini in the next couple of days 🙂

**Comment by shaharkazaz** [comment]
@marcobuschini Can you please verify this is resolved in v2.20.0? (make sure you use the `preloadLangs` if that fits your case)

**Comment by marcobuschini** [comment]
@shaharkazaz as soon as I start working on it again next week I will check.

**Comment by marcobuschini** [comment]
@shaharkazaz the problem persists.

**Comment by shaharkazaz** [comment]
@marcobuschini I see, please provide a small reproduction so we can better understand the issue 🙂 .

**Comment by marcobuschini** [comment]
@shaharkazaz on a small project everything tests as expected.
