### ISSUE TITLE
TypeError: Invalid option : timeStyle

### ISSUE THREAD

**Issue by RemyAlves** [ngneat/transloco#386]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Can't use the 'timeStyle' option with the translocoDate pipe, it fail with an error message, but only on the new version of Chrome (87), both on mobile and desktop. Chrome 81 still works fine. Seems like the new version of firefox have the same issue.
Example: {{ date | translocoDate: { dateStyle: 'medium', timeStyle: 'short' } }}

Error message:
core.js:5882 ERROR TypeError: Invalid option : timeStyle
    at Date.toLocaleDateString (<anonymous>)
    at localizeDate (ngneat-transloco-locale.js:46)
    at DefaultDateTransformer.transform (ngneat-transloco-locale.js:834)
    at TranslocoLocaleService.localizeDate (ngneat-transloco-locale.js:922)
    at TranslocoDatePipe.transform (ngneat-transloco-locale.js:1158)
    at Module.ɵɵpipeBind2 (core.js:36667)
    at DesanitizedMessageComponent_Template (desanitized-message.component.html:7)
    at executeTemplate (core.js:11937)
    at refreshView (core.js:11784)
    at refreshComponent (core.js:13224)

## Expected behavior

It should properly convert the date with the option entered.

## Minimal reproduction of the problem with instructions

Open this link: https://stackblitz.com/edit/transloco-example-p581h3?file=src%2Fapp%2Fon-push%2Fon-push.component.html
On Chrome 87 it will not work, but on Chrome 81 it will display correctly the time...

## Environment

<pre><code>
Angular version: 9.0.6

Browser:
- [x] Chrome (desktop) version 87
- [x] Chrome (Android) version 87
- [ ] Chrome (iOS) version XX
- [x] Firefox
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by itayod** [comment]
@RemyAlves would you like to create a pr that fixes that?

**Comment by RemyAlves** [comment]
Well, I can try, but I'm not sure how to proceed to test it out.
Never really got the time to contribute to an open source project of such.

**Comment by RemyAlves** [comment]
Never mind, it's been fixed in the last update of the library. My mistake, I through I updated it.
The thing that threw me off also is the stackbliz not being on the latest version of the library, reproducing the error.
Sorry about all of that...

**Comment by RemyAlves** [comment]
The issue was with `date.toLocaleDateString` being replaced with `new Intl.DateTimeFormat().format` in new browsers.
