### ISSUE TITLE
Translations dont appear in production

### ISSUE THREAD

**Issue by YazaWainakh** [ngneat/transloco#387]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Translations dont appear in production while they appear perfectly correct in dev. Only the translation keys appear in production.

## Expected behavior

Translations to work in production

## Minimal reproduction of the problem with instructions

I have followed the tutorial [here](https://lokalise.com/blog/angular-localization-with-transloco/) to install and add Transloco to the project.

`transloco-root.module.ts`
```
import { HttpClient } from '@angular/common/http'
import { Injectable, NgModule } from '@angular/core'
import { environment } from '@environments/environment'
import {
  Translation,
  translocoConfig,
  TranslocoLoader,
  TranslocoModule,
  TRANSLOCO_CONFIG,
  TRANSLOCO_LOADER,
} from '@ngneat/transloco'
import { Observable } from 'rxjs'

@Injectable({ providedIn: 'root' })
export class TranslocoHttpLoader implements TranslocoLoader {
  constructor(private http: HttpClient) {}

  getTranslation(lang: string): Observable<Translation> {
    return this.http.get<Translation>(`/assets/i18n/${lang}.json`)
  }
}

@NgModule({
  exports: [TranslocoModule],
  providers: [
    {
      provide: TRANSLOCO_CONFIG,
      useValue: translocoConfig({
        availableLangs: ['en', 'de'],
        fallbackLang: 'en',
        defaultLang: 'en',
        missingHandler: {
          useFallbackTranslation: true,
        },
        // Remove this option if your application doesn't support changing language in runtime.
        reRenderOnLangChange: true,
        prodMode: environment.production,
        flatten: {
          aot: environment.production,
        },
      }),
    },
    { provide: TRANSLOCO_LOADER, useClass: TranslocoHttpLoader },
  ],
})
export class TranslocoRootModule {}
```

`transloco-testing.module.ts`

```
import de from '@assets/i18n/de.json'
import en from '@assets/i18n/en.json'
import { TranslocoConfig, TranslocoTestingModule } from '@ngneat/transloco'

export function getTranslocoTestingModule(config: Partial<TranslocoConfig> = {}): TranslocoTestingModule {
  return TranslocoTestingModule.withLangs(
    { en, de },
    {
      availableLangs: ['en', 'de'],
      defaultLang: 'en',
      fallbackLang: 'de',
      reRenderOnLangChange: true,
      ...config,
    },
  )
}

```

The part of `config.yml` which builds the review:
```
build_review:
    executor: node-lts
    steps:
      - attach_current_workspace
      - run:
          name: Create production build
          command: npm run build -- --prod
      - persist_to_workspace:
          root: *workspace_location
          paths:
            - ./ng/dist
```

## Environment
<pre><code>
Transloco version: 2.20.0
Angular version: 10.0.2
 
For Tooling issues:
- Node version: 14.15.1
- Platform:  linux x64

Others:
Angular CLI: 10.0.1

</code></pre>

**Comment by itayod** [comment]
@YazaWainakh please use our [gitter channel](https://gitter.im/ngneat-transloco/lobby) for support.

p.s.
I suggest you take a look at official guides in our [docs site](https://ngneat.github.io/transloco/) for tutorials.

**Comment by shaharkazaz** [comment]
@hgschwibbe Why comment on a closed issue from 3 years ago? If you have an issue, you are welcome to:

1. Refer to the [official docs](https://ngneat.github.io/transloco/)
2. Open a [discussion](https://github.com/ngneat/transloco/discussions) and request help
3. If you are sure/think this is an issue with the library itself you are welcome to open a PR and help improve this open-source.

PS: advising developers to use a library that is in [maintenance mode](https://github.com/ngx-translate/core/issues/783), IMO is a bad call and shouldn't be part of your comment.

**Comment by shaharkazaz** [comment]
Transloco has a large number of users (~100k weekly downloads ATM), and if there was a concrete issue with it in production it would have been raised by now.

> Sorry, you forget, but Google does not.

I'm not sure what that means or what's your point.

> This comment is for all the users facing the same problem. It's for the developers who need a solution.

You haven't provided any relevant solution.
If I have issues with **this** library, telling someone to use another isn't much of a solution.

Some developers have specific configurations and may require assistance, that's what a community is for and there are a lot of channels where they can find the help they need, starting with our very maintained and detailed docs.

Everyone should use the best solution for them, and if that's ngx-translate/core for you, go ahead.
