### ISSUE TITLE
Use environment in transloco.config.js 

### ISSUE THREAD

**Issue by pookdeveloper** [ngneat/transloco#388]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X] Support request
[ ] Other... Please describe:
</code></pre>

How I can set the property langs of **transloco.config.js** with my environment file

```
module.exports = {
  rootTranslationsPath: 'assets/i18n',
  langs: ['es-ES', 'en'],
  keysManager: {}
};
```

Something like that:
```
module.exports = {
  rootTranslationsPath: 'assets/i18n',
  langs: environment.langs,
  keysManager: {}
};
```

Thanks

**Comment by shaharkazaz** [comment]
@pookdeveloper requiring the file didn't work?

**Comment by pookdeveloper** [comment]
No because is js file, dont work  with import o required

**Comment by itayod** [comment]
@pookdeveloper it doesn't make a lot of sense doing that since these files have completely different purposes.

Having said that, you can try to make those files sync... one way to do so is by creating some kind of script that updates those files accordingly.

**Comment by krzyhan** [comment]
You can read `environment` (i.e. in a service) and then update using `setAvailableLangs()`

https://ngneat.github.io/transloco/docs/language-api/#setavailablelangs

**Comment by itayod** [comment]
@pookdeveloper did you figure this out?

**Comment by shaharkazaz** [comment]
@pookdeveloper did you manage to figure out a solution here?

**Comment by pookdeveloper** [comment]
> @pookdeveloper did you manage to figure out a solution here?

No sorry 😔

**Comment by shaharkazaz** [comment]
This isn't something we can support and it doesn't relate to our library. Try to use a third-party tool like `.env`
