### ISSUE TITLE
ng add should support libraries

### ISSUE THREAD

**Issue by burkeallen** [ngneat/transloco#39]
## I'm submitting a Bug Report

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
**[ X ] Bug report**  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

when initiating

`ng add @ngneat/transloco`

and answering the 1st 3 prompts using the defaults.  The install fails, generating the following error

Specified module path projects/communal/src/app/app does not exist

our repository has multiple projects in it and I am attempting to add this to a common "communal" library that will be shared with the multiple projects

If I attempt to put in a path the same error is generated

## Expected behavior

Provide a more descriptive error so a person getting the error knows how to correct their mistake.

## Minimal reproduction of the problem with instructions

`ng add @ngneat/transloco`

and answering the 1st 3 prompts using the defaults. 

## Environment

<pre><code>
Angular CLI: 8.1.2
Node: 10.9.0
OS: win32 x64
Angular: 8.1.2

**Comment by itayod** [comment]
@burkeallen could you please explain what's the issue?

**Comment by itayod** [comment]
@burkeallen does "communal" projectType is "application" or "library"?

**Comment by itayod** [comment]
I will add support for libraries, in the meantime, you could install transloco using npm:
`npm install @ngneat/transloco` :)

**Comment by itayod** [comment]
@burkeallen, I released a new version with the fix for library :)
You could use it by passing the project name and the module name:

`ng add @ngneat/transloco --project communal --module {YOUR_ROOT_MODULE}`

Please let us know if it works for you.
