### ISSUE TITLE
Breaking out of the `read` scope

### ISSUE THREAD

**Issue by Spielboerg** [ngneat/transloco#391]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## What is the motivation / use case for changing the behavior?

I often use the `read` input because all translations of the page are grouped in one property, as in the example from the docs (https://ngneat.github.io/transloco/docs/translation-in-the-template#utilizing-the-read-input):

`en.json`:
```json
{
  "foo": "Foo",
  "bar": "Bar",
  "dashboard": {
    "title": "Dashboard Title",
    "desc": "Dashboard Desc"
  }
}
```
`home.component.html`:
```html
<ng-container *transloco="let t; read: 'dashboard'">
  <h1>{{ t('title') }}</h1>
  <p>{{ t('desc')</p>
</ng-container>
```

But sometimes I need a translation of another property which is not in the nested property, e.g. `foo`. Currently there is as far as I know no way to get translations from another key that is not in the nested property. In this case I have to remove the `read` input and add the key to each translation.

It would be great to disable/break out of the nested property for one single translation. Proposals:

```html
<ng-container *transloco="let t; read: 'dashboard'">
  <p>{{ t('title') }}</p>

  <!-- Starting with a dot to indicate that the read input should be ignored -->
  <p>{{ t('.foo') }}</p>

  <!-- Navigation like in a file system -->
  <p>{{ t('/foo') }}</p>
  <p>{{ t('../foo') }}</p> <!-- "Navigating" to the parent property -->

  <!-- Additional option parameter -->
  <p>{{ t('foo', { someParam: 'someValue' }, { read: '' } ) }}</p>
  <p>{{ t('foo', {}, { read: 'general' } ) }}</p>
  <p>{{ t('foo', null, { read: 'dashboard.someNestedKey' } ) }}</p>

  <p>{{ t('foo', { someParam: 'someValue' }, { ignoreRead: true } ) }}</p>
  <p>{{ t('foo', {}, { ignoreRead: true } ) }}</p>
  <p>{{ t('foo', null, { ignoreRead: true } ) }}</p>
</ng-container>
```

I like the `.foo` version the most because of its simplicity, but maybe someone has a better idea for the syntax.

**Comment by shaharkazaz** [comment]
@Spielboerg if you want to get a translation of the structural directive's scope you can use the transloco pipe:
```html
<ng-container *transloco="let t; read: 'dashboard'">
  <h1>{{ t('title') }}</h1>
  <p>{{ t('desc')</p>
  <button>{{ 'general.ok' | transloco }}</button>
</ng-container>
```
If you have many translations that need to "break" then maybe the read property isn't a good fit there.

**Comment by Spielboerg** [comment]
Hm, ok then I will switch to the pipe in these cases. I would have preferred to use only the read directive as recommended, but in my cases it will do the job.
