### ISSUE TITLE
Change currency format

### ISSUE THREAD

**Issue by YazaWainakh** [ngneat/transloco#392]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I want to change the currency formatting related to a language. e.g. when the language is EN I still want the currency formatter to use the German DE format. I managed to change the currency symbol but not the format. 

E.g. 
language: English
Text appears as `€217.00` 

language: German
Text appears as `217,00 €`  --> symbol on the right which is what I want

Any idea how to achieve that?
Here are the transloco-locale providers:
```

const globalFormatConfig = {
  date: {
    dateStyle: 'long',
    timeStyle: 'long',
  },
  currency: {
    minimumFractionDigits: 2,
  },
}

const localeConfig = {
  global: globalFormatConfig,
}

const langToLocaleMapping = {
  en: 'en-US',
  de: 'de-DE',
}

const defaultLocale = {
  en: 'en-US',
}

const localeToCurrencyMapping = {
  'en-US': 'EUR',
  'de-DE': 'EUR',
}

const translocoLocaleProviders = {
      provide: LOCALE_LANG_MAPPING,
      useValue: langToLocaleMapping,
    },
    {
      provide: LOCALE_DEFAULT_LOCALE,
      useValue: defaultLocale,
    },
    {
      provide: LOCALE_CONFIG,
      useValue: localeConfig,
    },
    {
      provide: LOCALE_CURRENCY_MAPPING,
      useValue: localeToCurrencyMapping,
    },
    {
      provide: TRANSLOCO_DATE_TRANSFORMER,
      useClass: DefaultDateTransformer,
    },
    {
      provide: TRANSLOCO_NUMBER_TRANSFORMER,
      useClass: DefaultNumberTransformer,
    },]
```
## Environment

<pre><code>
Angular version: 10
</code></pre>

**Comment by itayod** [comment]
@YazaWainakh you can pass the locale hardcodedly to the pipe as a parameter, did you try that?

**Comment by YazaWainakh** [comment]
@itayod can you please write an example, I am not sure I follow.

**Comment by itayod** [comment]
@YazaWainakh sorry, I have been very busy the past days...
I think it would be best if you can create some stackblitz example so I can work on and get you back with a working solution

**Comment by shaharkazaz** [comment]
@YazaWainakh You think you can provide an example as @itayod requested? 😃

**Comment by YazaWainakh** [comment]
This issue has become of less priority at the moment, I will close the issue for now and maybe reopen it once I have a stackblitz example. thanks.
