### ISSUE TITLE
What is the proper way of importing transloco module?

### ISSUE THREAD

**Issue by shravansofts** [ngneat/transloco#393]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x ] Support request
[ ] Other... Please describe:
</code></pre>

## Expected behavior
As part of transloco installation: https://ngneat.github.io/transloco/docs/installation transloco-root.module.ts will be created and imported in the app module.
If I have a shared module and is being imported in the lazy loaded feature module. I need to import translocoModule in shared module to use the transloco pipe/services in lazy loaded module.
Is this correct way of doing or am I missing anything.

Do we have forRoot(), forChild() functions?

Just want to know right way of importing module without duplication.

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, for that you could use our [stackblitz example](https://stackblitz.com/edit/transloco-example)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by itayod** [comment]
@shravansofts please move this question into the [discussion](https://github.com/ngneat/transloco/discussions) or [gitter channel](https://gitter.im/ngneat-transloco/lobby?source=orgpage)
