### ISSUE TITLE
Multiple fallback Languages

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/transloco#40]
Add support for multiple fallbacks `defaultLang: ['en', '..', '..']`

**Comment by NetanelBasal** [comment]
Create `TRANSLOCO_FALLBACK_STRATEGY` which implement a `handle(failedLang: string): string[]` method, and should return an array of fallback langs.

Note: if the user passes `defaultLang` in the config, use this as `['en']`. If they want a custom strategy they need to ignore this option. (don't forget to remove the `defaultLang: 'en'` from the config.

**Comment by shaharkazaz** [comment]
@NetanelBasal we don't want to keep en as a default lang? Do we want to make a default handler?
