### ISSUE TITLE
Bug: `selectTranslate` should not assume return type is string and should support nested properties when using MessageFormatTranspiler

### ISSUE THREAD

**Issue by fxck** [ngneat/transloco#40]
See https://stackblitz.com/edit/angular-rvacre?file=src%2Fapp%2Fapp.component.ts

Given this translation object

```
{
  foo: {
    bar: 'baz'
  }
}
```

and doing:

```
this._t.selectTranslate('foo').subscribe(console.log);
```

It:

1. assumes return type will be string, which in this case it is not
2. crashes with `Uncaught TypeError: message is not a function` when using `MessageFormatTranspiler`

It would be great if `selectTranslate` could accept generic type with the default of `string | Translation`, would be useful for [typed translations](https://github.com/ngneat/transloco/issues/38#issuecomment-525309127).

**Comment by NetanelBasal** [comment]
I'm not sure what you expect to get when passing an object. Can you elaborate?

**Comment by fxck** [comment]
See that stackblitz (and its console) with messageformat disabled

https://stackblitz.com/edit/angular-aernrh?file=src/app/app.component.ts

you get back translated object

```typescript
{
  bar: 'baz'
}
```

which is what I would expect, but the indicated return type of `selectTranslate` is `Observable<string>`, that is one thing.. the other is that it throw error with messageformat transpiler.

**Comment by NetanelBasal** [comment]
@blackmjck I'm not sure what you mean. You can do it with Transloco:

```ts
this.translate.selectTranslate('APP.GRID').subscribe(i18n => {
 ...
});

**Comment by fxck** [comment]
How about that string type thing @NetanelBasal? So @blackmjck wouldn't have to override the type..

**Comment by fxck** [comment]
Oh, nevermind, apparently it already has a generic type

```
selectTranslate<T = string | Translation | string[]>
```

great.
