### ISSUE TITLE
Karma Unit Test: String is not being translated in service file when method is called from the spec file

### ISSUE THREAD

**Issue by dharemsj** [ngneat/transloco#400]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[x] Other... Please describe:  
</code></pre>

## Current behavior

String is not being translated in service file when method is called from the spec file to get coverage. I am using this code in component and spec files 

## stoargeUtil.service.ts
<pre><code>
import {TranslocoService} from "@ngneat/transloco";

 export class StorageUtilService {
 
  constructor(private transloco: TranslocoService) { }

   public getFormattedCapacity(val: number): string {
        let result: string = "";      
            if (val >= 1024) {
                result = (val / 1024).toFixed(2) + " " + this.transloco.translate('kilobyte');
            }      
        return result;
    }
}
</code></pre>

## stoargeUtil.service.spec.ts
<pre><code>   
import { TestBed, waitForAsync } from '@angular/core/testing'; 
import { StorageUtilService } from './storageUtil.service';
import {TranslocoService, TranslocoTestingModule} from "@ngneat/transloco";
import {getTranslocoModule} from "~services/transloco-module.spec";

describe('StorageUtilService', () => {
    let service: StorageUtilService;

    beforeEach(waitForAsync(() => {
        TestBed.configureTestingModule({
            imports: [               
                TranslocoTestingModule,
                getTranslocoModule()
            ],
            providers: [StorageUtilService,               
                TranslocoService
            ]
        });
        service = TestBed.inject(StorageUtilService);
    }));

    it('should be created', waitForAsync(() => {
        const service: StorageUtilService = TestBed.inject(StorageUtilService);
        expect(service).toBeTruthy();
    }));
   
    it("Should return a response 1.00 KB when getFormattedCapacity method is called", () => {
        let value = service.getFormattedCapacity(1024);
        expect(value).toBe("1.00 KB");
    }); 

});

</code></pre>

## transloco-module.spec.ts
<pre><code>
import { TranslocoTestingModule, TranslocoTestingOptions } from '@ngneat/transloco';
import en from '../../assets/i18n/en-US.json';
import ja from '../../assets/i18n/ja-JP.json';
import cn from '../../assets/i18n/zh-CN.json';

export function getTranslocoModule(options: TranslocoTestingOptions = {}) {
    return TranslocoTestingModule.forRoot({
        langs: { en, ja, cn },
        translocoConfig: {
            availableLangs: ['en', 'ja', 'cn'],
            defaultLang: 'en',
        }
    });
}
</code></pre>

## en-US.json 
<pre><code>
{
  "kilobyte": "KB",
}
</code></pre>

## Output (On Running **ng test** Command)
<pre><code>
  Error: Expected '1.00 kilobyte' to be '1.00 KB'.
            at <Jasmine>
            at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/src/app/services/storageUtil.service.spec.ts:35:23)
            at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:364:1)
            at ProxyZoneSpec.push.QpwO.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:292:1)
Chrome Headless 85.0.4183.83 (Windows 10): Executed 1 of 62 (1 FAILED) (0 secs / 0.182 secs)
Chrome Headless 85.0.4183.83 (Windows 10) StorageutilService Should return capacity in terms of KB when call method getFormattedCapacity FAILED
        Error: Expected '1.00 kilobyte' to be '1.00 KB'.
            at <Jasmine>
            at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/src/app/services/storageUtil.service.spec.ts:35:23)
            at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:364:1)
Chrome Headless 85.0.4183.83 (Windows 10): Executed 2 of 62 (1 FAILED) (skipped 60) (0.353 secs / 0.195 secs)
</code></pre>

## Expected behavior
Transloco should translate the passed string i.e "kilobyte" in storageUtil service file and result should be 1 KB not 1 kilobyte.

## Minimal reproduction of the problem with instructions

1. Copy service and  spec file code in sample project.
2. add @ngneat/transloco package, their dependencies and transloco module given above at root level
3. add en-US json file and copy json code given above.
4. run "ng test" command from project folder.

## Environment
<pre><code>
Angular version: 10.2.0
Typescript: 4.0.5
@ngneat/transloco: 2.20.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v12.13.0
- Platform:  Windows
</code></pre>

**Comment by marianturchyn** [comment]
Hi, today I had the same issue. My solution is to wait until translates will be loaded. 
```
TestBed.configureTestingModule({
	imports: [
		getTranslocoModule(),
	],
	providers: [
		TranslocoService
	]
}).compileComponents()
.then(async() => {
	fixture = TestBed.createComponent(TestComponent);
	Page = new Pages(fixture);
	
	await TestBed.get(TranslocoService).selectTranslation().pipe(take(1)).toPromise(); // <-- here
});
```

**Comment by shaharkazaz** [comment]
@marianturchyn @dharemsj In the testing module configuration set the `preloadLangs` property to `true`.
I'll update the docs so this property appears as true in the example.
LMK if this resolved your issue.

**Comment by dharemsj** [comment]
@shaharkazaz Thanks a lot, it worked. string is being translated while running ng test, I am getting expected result. Thanks.
