### ISSUE TITLE
After build project with ionic build --prod i18n files return error 404

### ISSUE THREAD

**Issue by RobertoRVieira** [ngneat/transloco#404]
After build project with ionic build --prod i18n files return error 404. 
During the tests running with ng run app:serve, for example, the project work fine.
The correct path is localhost/www/assets/i18n/ json files.

![image](https://user-images.githubusercontent.com/39014807/108255990-b6464600-713b-11eb-9aeb-f7683119c2d3.png)

Node version 
v14.15.0

Plataform
Windows

Angular CLI: 10.2.0
Node: 14.15.0
OS: win32 x64

Angular: 10.0.2
... animations, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.0
@angular-devkit/build-angular   0.1002.0
@angular-devkit/core            10.1.7
@angular-devkit/schematics      10.1.7
@angular/cdk                    10.0.1
@angular/cli                    10.2.0
@angular/common                 10.0.3
@angular/localize               11.2.0
@angular/material               10.0.1
@angular/platform-server        10.2.2
@angular/service-worker         10.2.2
@schematics/angular             10.1.7
@schematics/update              0.1002.0
rxjs                            6.6.0
typescript                      3.9.6

**Comment by shaharkazaz** [comment]
@RobertoRVieira can you please share a reproduction repo?

**Comment by shaharkazaz** [comment]
@RobertoRVieira if this is still relevant please provide a reproduction 🙂

**Comment by seanwu1105** [comment]
@shaharkazaz [This project](https://github.com/seanwu1105/moment-pwa) has the same problem, it can be reproduced by the open the static [GitHub page](https://seanwu1105.github.io/moment-pwa). Although the i18n translation is correctly shown, the console still reporting error 404 on `https://seanwu1105.github.io/moment-pwa/assets/i18n/en.json`. It seems the translation files have not been loaded on the first time.

**Comment by shaharkazaz** [comment]
@RobertoRVieira Reopen with a reproduction please if this is still relevant.
