### ISSUE TITLE
Firefox displays translocoDate: { dateStyle: 'full' } format as dd.mm.yyyy

### ISSUE THREAD

**Issue by Gamewalker** [ngneat/transloco#409]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Chrome: Donnerstag, 11. März 2021
Firefox: 11.3.2021

## Expected behavior
Firefox should display the date in format: Donnerstag, 11. März 2021

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/transloco-example-tgnng2?file=src%2Fapp%2Fon-push%2Fon-push.component.html

## Environment

<pre><code>

tested with Angular version: 6, 10 and 11

Browser:
- [x] Chrome (desktop) Version 80.0.3987.87 (right date format)
- [x] Chrome (Android) version XX (right date format)
- [ ] Chrome (iOS) version XX
- [x] Firefox version 72.0.2 (wrong date format)
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version Version 89.0.774.45 (right date format)
 
</code></pre>

**Comment by shaharkazaz** [comment]
@Gamewalker Transloco uses the built-in `Intl` object, you are using Firefox v72, yet the `dateStyle` option is supported from v79+ see the [Intl browser compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat#browser_compatibility) for more information.

Tested and working as expected in a newer version of Firefox.
