### ISSUE TITLE
feature: structural directive could get nested property 

### ISSUE THREAD

**Issue by fxck** [ngneat/transloco#41]
Given this translation file

```
{
  dashboard: {
    projectsTitle: 'Projects',
    projectsDesc: 'Lorem ipsum.'
  }
}
```

when you do this:

```html
<ng-container *transloco="let t">

</ng-container>
```

..using shared strategy you get the whole object.

So you have to do `{{ t.dashboard.projectsTitle }}` and `{{ t.dashboard.projectsDesc }}` etc., it would be nice if you could do something like this 

```html
<ng-container *transloco="let t; read: 'dashboard'">
  <h1>{{ t.projectsTitle }}</h1>
  <p>{{ t.projectsDesc }}</p>
</ng-container>
```

..if it were only "dashboard" it wouldn't be that bad, but in my case it's `@zerops/zerops/pages/dashboard` (unique id of the lazy loaded module, used for various other things, ngrx state etc.), so 

```html
<ng-container *transloco="let t; read: featureKey;">
  <h1>{{ t.projectsTitle }}</h1>
  <p>{{ t.projectsDesc }}</p>
</ng-container>
```

would be much nicer than

```html
<ng-container *transloco="let t; read: featureKey;">
  <h1>{{ t[featureKey].projectsTitle }}</h1>
  <p>{{ t[featureKey].projectsDesc }}</p>
</ng-container>
```

**Comment by NetanelBasal** [comment]
That's nice, but it will limit you to use only keys from this specific scope.
