### ISSUE TITLE
Feature: Support `defaultCurrency`

### ISSUE THREAD

**Issue by seravifer** [ngneat/transloco#419]
### Is your feature request related to a problem? Please describe.
I need to change the default currency of the whole app. Our application only supports EUR even if the user connects from the US. It's a bit cumbersome to have to force it on all pipes and services or map everything in `localeToCurrencyMapping`.

### Describe the solution you'd like
I would like to be able to pass a value in the module configuration as the default.

### Describe alternatives you've considered
Currently I have a large mapping to force all locales to `EUR`. Also, the file `locale-currency.ts` is not exported by the library and if I add `localeToCurrencyMapping` it does not combine them. In this way I have to rewrite the entire file and not modify what interests me.

### Current behavior
```typescript
    TranslocoLocaleModule.init({
      defaultLocale: 'es-ES',
      langToLocaleMapping: {
        en: 'en-US', // We support English lang
        es: 'es-ES'
      },
      localeToCurrencyMapping: {
        'en-US': 'EUR',
        'es-ES': 'EUR',
        'ca-ES': 'EUR', // I need to rewrite this again
        'eu-ES': 'EUR',
        'gl-ES': 'EUR',
      }
    })
```

### Expected behavior
```typescript
    TranslocoLocaleModule.init({
      defaultLocale: 'es-ES',
      langToLocaleMapping: {
        en: 'en-US',
        es: 'es-ES'
      },
      defaultCurrency: 'EUR'
    })
```

### Contribution
I want to make a pull request for this feature:
Yes! 🚀

**Comment by itayod** [comment]
@seravifer would you like to create a pr for that?
