### ISSUE TITLE
Feature: Translator-friendly plural rules

### ISSUE THREAD

**Issue by AndiBat** [ngneat/transloco#420]
### Problem
We are using plural rules in the JSON in our app, such as:
`"myPluralRule": "{myCount, plural, =0 {no results} one {1 result} other {# results}}"`
However, we need to translate these into 27 other languages and, although we've tried to explain precisely, the translators are having difficulty understanding what to do.

### Preferred solution
Communication to the translators would be much simpler if the sections within the inner curly brackets referenced separate translations. Something like:
```
"myPluralRule": "{myCount, plural, =0 {@no_results} one {@one_result} other {@many_results}}",
"no_results": "No results",
"one_result": "1 result",
"many_results": "# results",
```
As well making it easier for the translators it would make it more straightforward for us to automate the preparation of the strings for translation.

**Comment by shaharkazaz** [comment]
@AndiBat Have you seen [reference other keys](https://ngneat.github.io/transloco/docs/additional-functionality/#reference-other-keys) section in the docs?

**Comment by AndiBat** [comment]
Hi Sharhar

Thanks for the pointer, but I couldn’t get it to work.

I tried…

  "profile": {
    "zero_credentials": "0 Credentials",
    "one_credentials": "1 Credential",
    "other_credentials": "# Credentials",
    "credentials_plural_count_test": "{count, plural, =0 {{{zero_credentials}}} one {{{one_credentials}}} other {{{other_credentials}}}}"
  }

…and …

  "profile": {
    "zero_credentials": "0 Credentials",
    "one_credentials": "1 Credential",
    "other_credentials": "# Credentials",
    "credentials_plural_count_test": "{count, plural, =0 {{zero_credentials}} one {{one_credentials}} other {{other_credentials}}}”
  }

…and …

  "profile": {
    "zero_credentials": "0 Credentials",
    "one_credentials": "1 Credential",
    "other_credentials": "# Credentials",
    "credentials_plural_count_test": "{count, plural, =0 {{{profile.zero_credentials}}} one {{profile.{one_credentials}}} other {{{profile.other_credentials}}}}"
  }

…and …

  "profile": {
    "zero_credentials": "0 Credentials",
    "one_credentials": "1 Credential",
    "other_credentials": "# Credentials",
    "credentials_plural_count_test": "{count, plural, =0 {{profile.zero_credentials}} one {{profile.{one_credentials}}} other {{profile.other_credentials}}}”
  }

All crashed silently 🙁

What am I doing wrong?

Cheers

Andrew

**Comment by shaharkazaz** [comment]
@AndiBat This is working as expected. Not sure what your use case is, maybe these translations are part of a scope and you are missing the prefix? 
I've tried it on our playground you can clone and try it yourself (clone this repo to run it)

I've added the following to the `assets/i18n/transpilers/messageformat/en.json`:
```json
{
"messageFormat": "The {gender, select, male {boy named {{mf.testKey}} won his} female {girl named {{mf.testKey}} won her} other {person named {{mf.testKey}} won their}} race - English",
"testKey": "🤡",
}
```
**Note** that the keys are prefixed with `mf` as this is the scope's alias.

And the result:
![image](https://user-images.githubusercontent.com/17194830/113470642-d9188980-945f-11eb-9773-d7946dffb542.png)


If you need further assistance please use our [gitter channel](https://gitter.im/ngneat-transloco/lobby?source=orgpage) or [github discussions](https://github.com/ngneat/transloco/discussions) 🙂
