### ISSUE TITLE
Bug: ios device > currencyDisplay > RangeError

### ISSUE THREAD

**Issue by KirstenStake** [ngneat/transloco#439]
### Current behavior

I am using the localizeNumber() endpoint with the config options of 
```
      return this._translocoLocaleService.localizeNumber(value, 'currency', currentLocale, {
        currency: currencyCode,
        currencyDisplay: 'narrowSymbol',
        maximumFractionDigits: decimals
      }).replace(/\s/g, '');
```
In the browser and on android everything is working correctly, on IOS device I am getting the error
`RangeError: currencyDisplay must be either "code", "symbol", or "name"`

This is **only** happening on IOS

### Expected behavior
Allow IOS to also use the currencyDisplay of 'narrowSymbol' in order to not show the characters before the symbol (same as symbol-narrow from other translations)

### Screenshots
![Screen Shot 2021-05-13 at 5 28 35 pm](https://user-images.githubusercontent.com/70495867/118093346-a70c2700-b410-11eb-9098-0e7a8fb1343d.png)

### Environment
    "@ngneat/transloco": "^2.20.1",
    "@ngneat/transloco-locale": "^1.4.0"

Angular CLI: 11.2.11
Node: 14.15.4
OS: darwin x64

Angular: 11.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.11
@angular-devkit/build-angular   0.1102.11
@angular-devkit/core            11.2.5
@angular-devkit/schematics      11.2.5
@angular/cli                    11.2.11
@schematics/angular             11.2.5
@schematics/update              0.1102.11
rxjs                            6.6.7
typescript                      4.1.5

### Additional context
Using Ionic 5, Capacitor, Angular frameworks.

**Comment by shaharkazaz** [comment]
@KirstenStake  Transloco uses the built-in Intl object, the`currencyDisplay` option doesn't support the `narrowSymbol` value on IOS devices see the [Intl compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat#browser_compatibility) for more information.

Since this isn't the first time that compatibility issue is raised so I think I'll clarify that we rely on the native Intl object in the docs.

**Comment by KirstenStake** [comment]
Thank you for your quick reply.
