### ISSUE TITLE
Bug: Property 'selectTranslateObject' does not exist on type 'TranslocoService' 

### ISSUE THREAD

**Issue by Christoph1972** [ngneat/transloco#444]
### Current behavior
Error message: `Property 'selectTranslateObject' does not exist on type 'TranslocoService' in home.ts` while rebuilding the StackBlitz demo.

### Minimal reproduction of the problem with instructions
```
export class HomeComponent implements OnInit {

  constructor(private service: TranslocoService) {}

  ngOnInit() {
    this.service.selectTranslate("some.nested.key").subscribe(console.log);
    this.service
      .selectTranslate("params", { value: "Transloco" })
      .subscribe(console.log);
    this.service.selectTranslateObject("some.nested").subscribe(console.log);//<--selectTranslateObject is underlined
  }
}
```

### Environment
<pre><code>- Transloco version: @ngneat/transloco": "^1.1.1"
- Angular version: 12.01
</code></pre>

For Tooling issues:
<pre><code>
- Node version: 14.17
- Platform:   Windows
</code></pre>

Hello,

I’m new in Transloco and also quite new in Angular. Yesterday I rebuild the demo app from StackBiltz (https://stackblitz.com/edit/ngneat-transloco) with angular 11, it worked verry well. Today I updated to the newest stable version of node.js and also to Angular 12. Now I can’t rebuild the demo app. I got the error message: `Property 'selectTranslateObject' does not exist on type 'TranslocoService'` in home.ts
When I use the yesterdays demo app of mine, which contains local Angular 11 it still works. Is this a bug, or is the demo app on StackBlitz not up to date?

What can I do to fix this problem? 

Kind Regards
Christoph

**Comment by shaharkazaz** [comment]
@Christoph1972 I have a feeling that an old version of Transloco was installed because of a peer dependency mismatch with Angular v12.
As you stated you are using v1.1.1, the current version is v2.21.0.
Please update to the latest version and LMK 🙂

**Comment by Christoph1972** [comment]
After installing the newest version of node and angular and creating a new project it works as expected. Now I have to look how to fix it in my current project. Thanks a lot so far!

**Comment by Christoph1972** [comment]
After installing the newest version of node and angular and creating a new project it works as expected. Thanks a lot so far!
