### ISSUE TITLE
Bug: No translation when  Angular web components loads first time in prod

### ISSUE THREAD

**Issue by lippomano** [ngneat/transloco#445]
### Current behavior
I am using pipe transloco in my Angular 12 web component, but when I load the app the first time in production I don't see the translation, if I refresh or if I serve the app in dev it works.
The translation file is loaded remotely.

### Expected behavior
I think that pipe transloco can automatically translate the key when the translation file is loaded (tried also with directive)

### Minimal reproduction of the problem with instructions

Provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, for that you could use our [stackblitz example](https://stackblitz.com/edit/transloco-example)

### Transloco config
```
export class TranslocoHttpLoader implements TranslocoLoader {
    constructor(private http: HttpClient) {
    }

    getTranslation(lang: string) {
        return this.http.get<Translation>(`${environment.i18n}${lang}.json`);
    }
}

   @NgModule({
    exports: [TranslocoModule],
    providers: [
        {
            provide: TRANSLOCO_CONFIG,
            useValue: translocoConfig({
                availableLangs: ['it', 'en'],
                defaultLang: getBrowserLang(),
                // Remove this option if your application doesn't support changing language in runtime.
                //  reRenderOnLangChange: true,
                prodMode: environment.production,
            })
        },
        {provide: TRANSLOCO_LOADER, useClass: TranslocoHttpLoader}
```

### Environment
<pre><code>- Transloco version: 2.2
- Angular version: 12.0.1
</code></pre>

For Tooling issues:
<pre><code>
- Node version: 14 
- Platform:  Windows 
</code></pre>

### Browser:
- [ X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [X ] Edge version XX

**Comment by shaharkazaz** [comment]
@lippomano please provide a small reproduction so I can further explore the issue 🙂

**Comment by lippomano** [comment]
I think you can close it, I try to rebuild my component from 0, and now all works well, I don't know what's happened.
