### ISSUE TITLE
Bug: Not working with Angular 12?

### ISSUE THREAD

**Issue by Christoph1972** [ngneat/transloco#447]
### Current behavior
A simple translation case fires an error.
 
```
<div *transloco="let t">
  <p>{{ t('title') }}</p> 
</div>
```

Error message:    `ERROR TypeError: t_r1 is not a function`

[EDIT]
This works:
`<span>{{ 'title' | transloco }}</span>`
and this to:
`<span transloco="title"></span>`

this not:
```
<div *transloco="let t">
  <p>{{ t('title') }}</p> 
</div>
```

### Expected behavior
A working translation

### Minimal reproduction of the problem with instructions

https://github.com/Christoph1972/transloco-demo

### Environment
<pre><code>- Transloco version: 1.1.1
- Angular version: 12.0.1
</code></pre>

For Tooling issues:
<pre><code>
- Node version: 14.17.0
- Platform:  Windows
</code></pre>

### Browser:
- [ ] Chrome (desktop) version 90.0.4430.212 
- [ ] Firefox version 88.0.1

### Additional context
It’s not possible to run a simple translation. I’m verry interested to use Transloco, but in my opinion it’s not possible to work with it. Please can someone have a look into it?

**Comment by shaharkazaz** [comment]
@Christoph1972 Hey!
I've cloned your repo and it seems like you are using an old implementation.
Now when adding Transloco (via schematics) a new `transloco-root.module` is created, you can see it [here](https://ngneat.github.io/transloco/docs/installation).

You were missing the `availableLangs` property in your config, once I added `availableLangs: ['en']` everything was working as expected 👍

**Comment by Christoph1972** [comment]
After installing the newest version of node and angular and creating a new project it works as expected. Thanks a lot so far!
