### ISSUE TITLE
translate attribute

### ISSUE THREAD

**Issue by ewok-janitor** [ngneat/transloco#45]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

Can we get documentation on how to translate an attribute?

Example from angular docs:
<code>
<img [src]="logo" i18n-title title="Angular logo" />
</code>

**Comment by NetanelBasal** [comment]
Added to the docs:

```html
<span [attr.alt]="'hello' | transloco">Attribute</span>
<span [title]="'hello' | transloco">Property</span>
```
