### ISSUE TITLE
[Question]: Reference object of keys

### ISSUE THREAD

**Issue by cthrax** [ngneat/transloco#453]
Hello, I'm very recently migrating over from ngx-translate and something we used a lot in that library was references to other keys and in some cases, a whole object of keys. It seems like that is not working in transloco, but maybe we need to be doing something differently.

As an example of what I mean:
```
{
   'app': {
       'scope1': {
           'features': {
               'feature1': 'value1',
               'feature2': 'value2'
           }
       },
       'scope2': {
          'features': '{{app.scope1.features}}'
       }
   }
}
```

Thanks in advance!

**Comment by shaharkazaz** [comment]
@cthrax What would you expect in such a case?

**Comment by cthrax** [comment]
@shaharkazaz Sure! I should have mentioned that. So I would expect that translating the key "app.scope2.features.feature1" I get the value "value1". Right now I'm getting the untranslated key.
