### ISSUE TITLE
Bug: transloco-validator reports JSON comments

### ISSUE THREAD

**Issue by muuvmuuv** [ngneat/transloco#455]
### Current behavior

Unexpected token / in JSON at position 1892

### Expected behavior

Comments are valid in JSON. Sometimes it is recognized by an additional "c" after the json extension name ".jsonc" but not always.

### Minimal reproduction of the problem with instructions

Provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, for that you could use our [stackblitz example](https://stackblitz.com/edit/transloco-example)

### Environment
<pre><code>- Transloco version: X.Y.Z
- Angular version: X.Y.Z
</code></pre>

For Tooling issues:
<pre><code>
- Node version: XX  
- Platform:  
</code></pre>

### Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

### Contribution
I would like to make a pull request for this feature:
[x] Yes! 🚀 (If nobody else is faster)
[ ] Maybe next time

**Comment by muuvmuuv** [comment]
Oh, I missed a part where HTTPClientModule isn't compatible with comments as well... idk what to do now honestly. We have a lot of multiline comments which I do not want to insert into `"feature.comment": "..."`. 

Any ideas?

**Comment by muuvmuuv** [comment]
OK I found a way to fix the validator but sadly the optimizer cannot remove those:

```jsonc
  "features.comment.01": "------------------------------------------------", // not removed
  "features.comment.02": "------ Feature related translations below ------", // not removed
  "features.comment.03": "------------------------------------------------", // not removed
  "analysis_group": {
    "comment": "Filter component analysis group", // removed
```

_Will edit the title_

**Comment by shaharkazaz** [comment]
We'll close this issue in favour of #456
