### ISSUE TITLE
Bug: Transloco fails to translate when language inside scope contains '-'

### ISSUE THREAD

**Issue by gabriel-gn** [ngneat/transloco#457]
### Current behavior
I want to translate a key using the `selectTranslate()` method and `pt-BR` language. My current code is the following:
```
this.t.selectTranslate(`${metadata['title']}`, {}, {scope: '.metadata'}).pipe(
      take(1)
    ).subscribe(translated => {
      console.log(translated);
      this.updateTitle(translated);
    });
```
My folder structure is the following: `assets/i18n/.metadata` -> `en.json, pt-BR.json`
When the language is set to 'en', it works perfectly.
When language is set to 'pt-BR', it gives me the error: `ERROR TypeError: Cannot read property '0' of undefined`

I have tried to change `{scope: '.metadata'}` to `{scope: '.metadata/en'}` and it worked ok. When I switched languages, it still translated to english. 

When i changed `{scope: '.metadata'}` to `{scope: '.metadata/pt-BR'}` I had the same errors.

### Expected behavior
Using the `selectTranslate()` method with scope param and its value containing "-" character translating as intended.

### Minimal reproduction of the problem with instructions

Code above.

### Screenshots
below scrrenshot when first language loaded is "pt-BR", then I switched to "en", then "pt-BR", "en", and so on
![image](https://user-images.githubusercontent.com/30876329/121297644-056ddd80-c8c9-11eb-92be-b5b3fb474fe3.png)

### Transloco config
Transloco module:
```
@NgModule({
  exports: [TranslocoModule],
  providers: [
    {
      provide: TRANSLOCO_CONFIG,
      useValue: translocoConfig({
        availableLangs: ['en', 'pt-BR'],
        defaultLang: 'pt-BR',
        // fallbackLang: 'en',
        reRenderOnLangChange: true, // Remove this option if your application doesn't support changing language in runtime.
        prodMode: environment.production,
      })
    },
    {provide: TRANSLOCO_LOADER, useClass: TranslocoHttpLoader}
  ]
})
```

### Environment
<pre><code>- Transloco version: 2.21.0
- Angular version: 11.0.3
</code></pre>

For Tooling issues:
<pre><code>
- Node version: 12.18.3  
- Platform:  Mac 
</code></pre>

### Browser:
- [X] Chrome (desktop) version XX
- [X] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

### Additional context
I have had the same behaviour ocourring when using scope folders with `-` character on it, but I could overcome it providing scope and alias on my components.
Now that I need to use transloco on a service, I don't know how to overcome it.

### Contribution
I would like to make a pull request for this feature:
[ ] Yes! 🚀
[X] Maybe next time

**Comment by itayod** [comment]
Hi @gabriel-gn please read this [section](https://ngneat.github.io/transloco/docs/scope-configuration#scopes-namespace) in the docs.

**Comment by gabriel-gn** [comment]
@itayod thanks for the link of the section in the docs, but it didn't solve my issue.
I created a module for my service providing TRANSLOCO_SCOPE with values and imported it on `app.module.ts`, but the method `selectTranslate()` on the service does not inherit correctly the scope provided. (although it works fine when using for component modules)

Is there any workaround I should try when using translate api on a service?

**Comment by gabriel-gn** [comment]
Managed to solve it.
My "pt-BR" translation had a `,` on the end of the json file. Sorry for taking your time, and congratulations on the awesome library! Keep it up!
