### ISSUE TITLE
Bug: Transloco Locale Compilation error - Angular 12

### ISSUE THREAD

**Issue by FlorianCostamagna** [ngneat/transloco#465]
### Current behavior
Couldn't use Transloco and Transloco Locale at the same time in Angular 12

### Expected behavior
After installing Transloco-locale npm package using : npm i @ngneat/transloco-locale
I imported the TranslocoLocaleModule in my app.module.ts using : TranslocoLocaleModule.init() within my imports.
I recompiled my projet and I got these errors : 

./node_modules/@ngneat/transloco-locale/__ivy_ngcc__/fesm2015/ngneat-transloco-locale.js:39:19-27 - Error: export 'toNumber' (imported as 'toNumber') was not found in '@ngneat/transloco' (possible exports: DefaultFallbackStrategy, DefaultTranspiler, MessageFormatTranspiler, TRANSLOCO_CONFIG, TRANSLOCO_FALLBACK_STRATEGY, TRANSLOCO_INTERCEPTOR, TRANSLOCO_LANG, TRANSLOCO_LOADER, TRANSLOCO_LOADING_TEMPLATE, TRANSLOCO_SCOPE, TRANSLOCO_TRANSPILER, TemplateHandler, TestingLoader, TranslocoDirective, TranslocoModule, TranslocoParamsPipe, TranslocoPipe, TranslocoService, TranslocoTestingModule, defaultConfig, defaultProviders, translate, ɵa, ɵb, ɵd, ɵe)

./node_modules/@ngneat/transloco-locale/__ivy_ngcc__/fesm2015/ngneat-transloco-locale.js:1122:12-17 - Error: export 'isNil' (imported as 'isNil') was not found in '@ngneat/transloco' (possible exports: DefaultFallbackStrategy, DefaultTranspiler, MessageFormatTranspiler, TRANSLOCO_CONFIG, TRANSLOCO_FALLBACK_STRATEGY, TRANSLOCO_INTERCEPTOR, TRANSLOCO_LANG, TRANSLOCO_LOADER, TRANSLOCO_LOADING_TEMPLATE, TRANSLOCO_SCOPE, TRANSLOCO_TRANSPILER, TemplateHandler, TestingLoader, TranslocoDirective, TranslocoModule, TranslocoParamsPipe, TranslocoPipe, TranslocoService, TranslocoTestingModule, defaultConfig, defaultProviders, translate, ɵa, ɵb, ɵd, ɵe)

./node_modules/@ngneat/transloco-locale/__ivy_ngcc__/fesm2015/ngneat-transloco-locale.js:1191:12-17 - Error: export 'isNil' (imported as 'isNil') was not found in '@ngneat/transloco' (possible exports: DefaultFallbackStrategy, DefaultTranspiler, MessageFormatTranspiler, TRANSLOCO_CONFIG, TRANSLOCO_FALLBACK_STRATEGY, TRANSLOCO_INTERCEPTOR, TRANSLOCO_LANG, TRANSLOCO_LOADER, TRANSLOCO_LOADING_TEMPLATE, TRANSLOCO_SCOPE, TRANSLOCO_TRANSPILER, TemplateHandler, TestingLoader, TranslocoDirective, TranslocoModule, TranslocoParamsPipe, TranslocoPipe, TranslocoService, TranslocoTestingModule, defaultConfig, defaultProviders, translate, ɵa, ɵb, ɵd, ɵe)

./node_modules/@ngneat/transloco-locale/__ivy_ngcc__/fesm2015/ngneat-transloco-locale.js:1253:12-17 - Error: export 'isNil' (imported as 'isNil') was not found in '@ngneat/transloco' (possible exports: DefaultFallbackStrategy, DefaultTranspiler, MessageFormatTranspiler, TRANSLOCO_CONFIG, TRANSLOCO_FALLBACK_STRATEGY, TRANSLOCO_INTERCEPTOR, TRANSLOCO_LANG, TRANSLOCO_LOADER, TRANSLOCO_LOADING_TEMPLATE, TRANSLOCO_SCOPE, TRANSLOCO_TRANSPILER, TemplateHandler, TestingLoader, TranslocoDirective, TranslocoModule, TranslocoParamsPipe, TranslocoPipe, TranslocoService, TranslocoTestingModule, defaultConfig, defaultProviders, translate, ɵa, ɵb, ɵd, ɵe)

./node_modules/@ngneat/transloco-locale/__ivy_ngcc__/fesm2015/ngneat-transloco-locale.js:1317:12-17 - Error: export 'isNil' (imported as 'isNil') was not found in '@ngneat/transloco' (possible exports: DefaultFallbackStrategy, DefaultTranspiler, MessageFormatTranspiler, TRANSLOCO_CONFIG, TRANSLOCO_FALLBACK_STRATEGY, TRANSLOCO_INTERCEPTOR, TRANSLOCO_LANG, TRANSLOCO_LOADER, TRANSLOCO_LOADING_TEMPLATE, TRANSLOCO_SCOPE, TRANSLOCO_TRANSPILER, TemplateHandler, TestingLoader, TranslocoDirective, TranslocoModule, TranslocoParamsPipe, TranslocoPipe, TranslocoService, TranslocoTestingModule, defaultConfig, defaultProviders, translate, ɵa, ɵb, ɵd, ɵe)

### Minimal reproduction of the problem with instructions

* npm install Transloco
* npm install Transloco Locale
* import both in the app.module.ts 
* Observe the errors explained above

### Transloco config
{
      provide: TRANSLOCO_CONFIG,
      useValue: {
        listenToLangChange: true,
        defaultLang: 'en',
        fallbackLang: 'en',
        prodMode: true,
      } as TranslocoConfig,
    },

### Environment
<pre><code>- Transloco version: 1.1.0
 Transloco locale version: 1.4.0
- Angular version: 12.0.0
</code></pre>

For Tooling issues:
<pre><code>
- Node version: 14.16.1
- npm version : 7.12.0
- Platform:  Mac
</code></pre>

### Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

### Contribution
I would like to make a pull request for this feature:
[ ] Yes! 🚀
[ ] Maybe next time

**Comment by shaharkazaz** [comment]
Looks like you installed an old version of Transloco (1.1.0). Can you please try to install the latest version?

**Comment by shaharkazaz** [comment]
@FlorianCostamagna did you try installing the latest version?
