### ISSUE TITLE
migrate not working well with NG12 Nx12 RxJS7

### ISSUE THREAD

**Issue by pegaltier** [ngneat/transloco#483]
### Current behavior
Angular 12 with Nx workspace 12 and RxJS7 and @ngx-translate. After running ng g @ngneat/transloco:migrate

1. I enter the 2 inputs from & path in the command prompt and I get a first error message probably because the schematics between Nx and Angular is slighty different: Property 'from' does not match the schema. 'NgxTranslate' should be one of [object Object],[object Object].
2. I found an alternative to execute the command correctly by passing the 2 inputs directly in the command: ng generate @ngneat/transloco:migrate --path=./ --from=NgxTranslate
3. I get another error because transloco is still using RxJS 6.3.3 and using the 'rxjs/internal-compatibility' functions: Package subpath './internal-compatibility' is not defined by "exports" in .../node_modules/rxjs/package.json
4. I downgrade to RxJS 6.3.3 (npm i rxjs@6.3.3) and run again the migrate command and it works: ng generate @ngneat/transloco:migrate --path=./ --from=NgxTranslate

### Expected behavior
1. transloco works well with Nx workspace so I don't get any schematics error when using the prompt
2. transloco support RxJS7 so I don't have to downgrade RxJS when doing the migration.

### Environment
<pre><code>
- Transloco version: 2.22.0
- Angular version: 12.0.4
- Nx version: 12.5.0
- RxJS version: 7.1.0
</code></pre>

For Tooling issues:
<pre><code>
- Node version: v12.20.1
- Platform:  Mac
</code></pre>

**Comment by shaharkazaz** [comment]
@pegaltier would you like to create a PR for it?

**Comment by shaharkazaz** [comment]
@pegaltier v3 will be out very soon with **a lot** of infra upgrades, and I think this process might be smoother in that version.
Is there a way you can re-test this with v3? 🙂

**Comment by shaharkazaz** [comment]
I believe the issues here are resolved in v3+.
Closing due to lack of communication on the issue.
