### ISSUE TITLE
Bug: Playground does not work

### ISSUE THREAD

**Issue by danielehrhardt** [ngneat/transloco#486]
### Current behavior
your playground does not work: 
https://stackblitz.com/edit/ngneat-transloco
click on english or spanish

### Expected behavior
the language should change to english

### Browser:
- [ X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by mkubdev** [comment]
Hello,

There is two json file :
*  `assets/i18n/es.json` :
```json
{
  "hello": "Hola",
  "params": "Hello {{value}} spanish",
  "some": {
    "nested": {
      "key": "nested key spanish"
    }
  }
}
```
*  `assets/i18n/en.json` :
```json
{
  "hello": "Hello",
  "params": "Hello {{value}} english",
  "some": {
    "nested": {
      "key": "nested key english"
    }
  }
}
```

And this is the template :
```html
<ng-container *transloco="let t">
	<h1>{{ t('hello') }}</h1>
        <p>{{ t('some.nested.key') }}</p>
	<p>{{ t('params', { value: 'Transloco'}) }}</p>
</ng-container>
```

1. `<h1>{{ t('hello') }}</h1>`  loading the `hello` key of both .json file on language change : "Hola" or "Helo"
2. `<p>{{ t('some.nested.key') }}</p>` loading the `some.nested.key` of both .json file : "nested key spanish" or "nested key english"
3. `<p>{{ t('params', { value: 'Transloco'}) }}</p>` loading the `params` key of both .json file :  "Hello {{value}} spanish" or "Hello {{value}} english"

## Conclusion

The Playground work as excpected 😃

**Comment by danielehrhardt** [comment]
> Hello @danielehrhardt,
> 
> There is two json file :
> 
> * `assets/i18n/es.json` :
> 
> ```json
> {
>   "hello": "Hola",
>   "params": "Hello {{value}} spanish",
>   "some": {
>     "nested": {
>       "key": "nested key spanish"
>     }
>   }
> }
> ```
> 
> * `assets/i18n/en.json` :
> 
> ```json
> {
>   "hello": "Hello",
>   "params": "Hello {{value}} english",
>   "some": {
>     "nested": {
>       "key": "nested key english"
>     }
>   }
> }
> ```
> 
> And this is the template :
> 
> ```
> <ng-container *transloco="let t">
> 	<h1>{{ t('hello') }}</h1>
>         <p>{{ t('some.nested.key') }}</p>
> 	<p>{{ t('params', { value: 'Transloco'}) }}</p>
> </ng-container>
> ```
> 
> 1. `<h1>{{ t('hello') }}</h1>`  loading the `hello` key of both .json file on language change : "Hola" or "Helo"
> 2. `<p>{{ t('some.nested.key') }}</p>` loading the `some.nested.key` of both .json file : "nested key spanish" or "nested key english"
> 3. `<p>{{ t('params', { value: 'Transloco'}) }}</p>` loading the `params` key of both .json file :  "Hello {{value}} spanish" or "Hello {{value}} english"
> 
> ## Conclusion
> The Playground work as excpected 😃

I was a issue with my browser sorry 🙈
