### ISSUE TITLE
Bug: adding Transloco in Nx monorepo results in property projectType not readable

### ISSUE THREAD

**Issue by mattgek** [ngneat/transloco#500]
### Current behavior
When running **ng add @ngneat/transloco** and a Nx monorepo with a set of languages and no server rendering, an error is thrown stating **Cannot read property projectType of undefined**. The operation is canceled after that.

### Expected behavior
When running **ng add @ngneat/transloco** and a Nx monorepo with a set of languages and no server rendering, the operation should be successful and a set of files should be created for all the libs/apps which require it.

### Minimal reproduction of the problem with instructions
1. open a monorepo project with standar Angular i18n translation enabled
2. at the root of the project run **ng add @ngneat/transloco**
3. provide a set of languages
4. set the server side rendering to **NO**

### Screenshots
![Screen Shot 2021-09-15 at 11 27 12](https://user-images.githubusercontent.com/17617446/133409192-72e6a2f4-a6dc-440b-a9e5-06f9bbf9b8a6.png)

### Transloco config
No configuration yet. This is the first setup step

### Environment
<pre><code>- Transloco version: ^2.23.2
- Angular version: ^12.2.2
- Nx angular version: ^12.7.2
</code></pre>

For Tooling issues:
<pre><code>
- Node version: v16.1.0
- Platform:  Mac
</code></pre>

**Comment by mattgek** [comment]
project issues

**Comment by shaharkazaz** [comment]
@mattgek Can you please share what was the issue so others might benefit? 🙂

**Comment by mattgek** [comment]
The issue is actually this one https://github.com/ngneat/transloco/issues/504
