### ISSUE TITLE
Bug: selectTranslate() with forkJoin()

### ISSUE THREAD

**Issue by william-fargues** [ngneat/transloco#502]
### Current behavior
I'm trying to use _**selectTranslate()**_ in a _**forkJoin()**_ but when I log the result I got nothing.

### Expected behavior
Having the translated strings.

### Minimal reproduction of the problem with instructions

In the constructor of my Service I'm calling this code and nothing is logged :

```
forkJoin([
      this.transloco.selectTranslate('hello'), 
      this.transloco.selectTranslate('world'), 
    ]).subscribe(resp => console.log(resp))
```

If I do this instead, I have the logs :

```
forkJoin([
     of('hello'), 
     of('world'), 
    ]).subscribe(resp => console.log(resp))
```

### Environment
"@ngneat/transloco": "~1.8.0",
"@angular/core": "~12.0.0",

**Comment by shaharkazaz** [comment]
@william-fargues See [`forkJoin`](https://www.learnrxjs.io/learn-rxjs/operators/combination/forkjoin):

> When all observables complete, emit the last emitted value from each.

The selectTranslate doesn't complete, if you want to get the values you should use [`combineLatest`](https://www.learnrxjs.io/learn-rxjs/operators/combination/combinelatest) instead.
