### ISSUE TITLE
Angular Universal errors: failed loading: GET "http://localhost:4200/assets/i18n/en.json"

### ISSUE THREAD

**Issue by mpricu** [ngneat/transloco#507]
I created a new angular project using Angular 12.2.7 with the latest Angular Universal package @nguniversal/express-engine@12.1.0.
I installed the Transloco package with the command "ng add @ngneat/transloco" and I accepted the default options, including " Are you working with server side rendering? Yes".
Compiling and running the new Angular project revealed a small error: "Error: Can't resolve '..environmentsenvironment' in..." in the transloco-root,module.ts file because of the back slash in the path:
"import { environment } from '..\environments\environment';".
Replacing the backslash with a normal slash fixed the problem.
A new compiling showed the error:
"ERROR Error: When using the default fallback, a fallback language must be provided in the config!"
I fixed it adding " fallbackLang: 'en'," in the transloco-root,module.ts file.
But when I modified the files en.json and es.json with any line and running the commands "npm run build:ssr" and "npm run serve:ssr", I received the following errors:
XHR failed loading: GET "http://localhost:4200/assets/i18n/en.json".
XHR failed loading: GET "http://localhost:4200/assets/i18n/es.json".
I expected to be abe to load these files and be able to run an Angular project with the Transloco package.

**Comment by josencv** [comment]
I'm interested in this as well, since we are considering using this library in our project, which has SSR with angular 12 as well 👀

**Comment by shaharkazaz** [comment]
@mpricu @josencv As far as I know there should be issues with SSR, can you please provide a reproduction? it would be great if you could re-open this issue using our new issues template, they will instruct you on what information is needed to help me understand the issue 🙂

**Comment by shaharkazaz** [comment]
@mpricu @josencv Is this still relevant? can you provide the information?

**Comment by shaharkazaz** [comment]
@josencv @mpricu Feel free to reopen this with more information.
