### ISSUE TITLE
Bug: ansi-regex is vulnerable to Inefficient Regular Expression Complexity

### ISSUE THREAD

**Issue by madhurahuja** [ngneat/transloco#509]
### Current behavior
The code pipeline runs npm audit and throws the aforementioned error and prevents me from proceeding further to deploy on ECS. The current child dependency is 4.1.0 but the expected patched version is 6.0.1 || 5.0.1

Even though the vulnerability is low, the security team may not agree to budge on it.

### Expected behavior
It would be great if the library can patch child dependencies viz. ora, replace-in-file

### Minimal reproduction of the problem with instructions

Run npm audit on @ngneat/transloco@2.23.3

### Environment
<pre><code>- Transloco version: 2.23.3
- Angular version: 12.2.3

### Contribution
I would like to make a pull request for this feature:
[ ] Yes! 🚀
[x] Maybe next time

**Comment by shaharkazaz** [comment]
@madhurahuja There is a major upgrade about to release the upgrades all of these, will be fixed in v3

**Comment by madhurahuja** [comment]
> @madhurahuja There is a major upgrade about to release the upgrades all of these, will be fixed in v3

Thank you for your response @shaharkazaz is there a tentative time when v3 release is planned?

**Comment by shaharkazaz** [comment]
@madhurahuja When I get the chance to release it 🙂  no estimated date, hopefully soon, it's 97% done.

**Comment by madhurahuja** [comment]
@shaharkazaz Good to hear! Thank you much :)

**Comment by shaharkazaz** [comment]
@madhurahuja released v3, LMK if that works for you 😄

**Comment by madhurahuja** [comment]
Thank you so much for so quick turnaround 👍 Let me check and get back to you!

**Comment by CameronJThomas** [comment]
Would it be possible to resolve this vulnerability as a minor patch for 2.x also? V3 appears to depend on Angular 12, but Angular 10 and 11 are still in LTS so this will catch a lot of people out who haven't yet had a chance to upgrade (my team included!)

**Comment by shaharkazaz** [comment]
@CameronJThomas You are welcome to open a PR to the v2 branch 🙂

**Comment by CameronJThomas** [comment]
Thanks! Have raised a PR per above 😄

**Comment by shaharkazaz** [comment]
@CameronJThomas Try @ngneat/transloco@2.23.4

**Comment by CameronJThomas** [comment]
Thanks for the quick turnaround! I can confirm this is now passing audit so this issue can be closed 🙂
