### ISSUE TITLE
Chore: migrate to standalone project configuration

### ISSUE THREAD

**Issue by edbzn** [ngneat/transloco#511]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Which Transloco package(s) will this feature affect?

Don't know / other

### Is your feature request related to a problem? Please describe

Hi, 

You should consider migrating to standalone project configs. It will reduce the conflicts in workspace definition and improve maintainability: 

```
nx generate @nrwl/workspace:convert-to-nx-project --all
```

### Describe alternatives you've considered

```markdown
Keep Angular.json format v1.
```

### Describe alternatives you've considered

N/A

### Additional context

You could find additional information here: https://blog.nrwl.io/per-project-configuration-storybook-support-for-angular-12-auto-refresh-for-dependency-graph-and-bcd2d1e06658

### I would like to make a pull request for this feature

Yes 🚀

**Comment by NetanelBasal** [comment]
Go for it.

**Comment by shaharkazaz** [comment]
We are using the standalone configurations 😄
