### ISSUE TITLE
Bug(schematics): ng add broken in v.3

### ISSUE THREAD

**Issue by strigefleur** [ngneat/transloco#516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Schematics

### Is this a regression?

Yes

### Current behavior

According to [installation steps](https://ngneat.github.io/transloco/docs/installation) I run `ng add @ngneat/transloco` on a pretty new Angular project.
Now I get only the package installed and error saying
```
[error] Error: Collection "...\\node_modules\\@ngneat\\transloco\\schematics\\collection.json" cannot be resolved.
```

### Expected behavior

`ng add @ngneat/transloco` command should get me complete boilerplate code and package installed.

### Please provide a link to a minimal reproduction of the bug

#

### Please provide the environment you discovered this bug in

```markdown
Transloco: 3.0.2
Angular: 12.2.9
Node: 14.17.6
Package Manager: 7.22.0
OS: Windows_NT x64 10.22000.194
```

### I would like to make a pull request for this bug

No

**Comment by shaharkazaz** [comment]
@strigefleur @gn-sky Please try v3.0.4 and LMK if it works for you 🙂

**Comment by shaharkazaz** [comment]
@seravifer Can you share some env details? (OS, node version, etc)

**Comment by shaharkazaz** [comment]
@strigefleur fixed in v3.0.6

**Comment by PuffPastry** [comment]
I've just encountered this error

@ngneat/transloco 3.2.0
@angular/core: 13.2.0

node v14.19.0
on Windows 10

**Comment by fvoska** [comment]
This is broken again for me on v3.2.0.

![Screenshot 2022-03-29 at 11 55 35](https://user-images.githubusercontent.com/3170728/160586023-28d8fd26-8881-4531-8acc-2f46de6ac38b.png)

I can see there is no `src` folder in transloco in node_modules that is needed when resolving collection.json:

![image](https://user-images.githubusercontent.com/3170728/160585680-937035d0-14b9-4429-92f2-89a56a9893e5.png)
