### ISSUE TITLE
translation files not found when running on Firefox

### ISSUE THREAD

**Issue by Code202** [ngneat/transloco#520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Don't know / other

### Is this a regression?

No

### Current behavior

Running my app on chrome works fine but on Firefox, I am getting the following error:
`Error while trying to load "en" TypeError: value is null`

### Expected behavior

Translation works fine

### Please provide a link to a minimal reproduction of the bug

,

### Please provide the environment you discovered this bug in

```markdown
Transloco: 2.23.4
Angular: 12.2.0
Node: none
Package Manager: 
OS: Linux (ubuntu distro)
```

### Browser

```markdown
Firefox: 93.0
```

### I would like to make a pull request for this bug

No

**Comment by shaharkazaz** [comment]
@Code202 Feel free to reopen when a providing a minimal reproduction of the issue.
