### ISSUE TITLE
Bug(selectTranslation): It is not returning an object for nested keys

### ISSUE THREAD

**Issue by Leemonn** [ngneat/transloco#527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Transloco

### Is this a regression?

No

### Current behavior

assets/i18n/admin-page/en.json
```
{
  "title": "Admin Page English",
  "nested": {
    "hello": "hello",
    "world": "world"
  }
}
```

selectTranslation('admin-page') returns:
```
{
    "title": "Admin Page English",
    "nested.hello": "hello",
    "nested.world": "world"
}
```

### Expected behavior

assets/i18n/admin-page/en.json
```
{
  "title": "Admin Page English",
  "nested": {
    "hello": "hello",
    "world": "world"
  }
}
```

selectTranslation('admin-page') should return:
```
{
  "title": "Admin Page English",
  "nested": {
    "hello": "hello",
    "world": "world"
  }
}
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/ngneat-transloco-gt9vdw?file=src%2Fapp%2Fservice%2Ftest.service.ts

### Additional context

In the current behavior you need to access the object like this `object['nested.hello']`.
It should be `object.nested.hello` instead.

### I would like to make a pull request for this bug

No

**Comment by shaharkazaz** [comment]
@Leemonn That's just how transloco works, for optimization purposes all the translations are flattened.
What's your use case? why use nested objects? 
You can use [flat](https://www.npmjs.com/package/flat) to unflatten your object.

**Comment by Leemonn** [comment]
> @Leemonn That's just how transloco works, for optimization purposes all the translations are flattened. What's your use case? why use nested objects? You can use [flat](https://www.npmjs.com/package/flat) to unflatten your object.

Thank you, that solves my problem I thought it was a bug
