### ISSUE TITLE
Shared scope does not check existing translations before loading

### ISSUE THREAD

**Issue by ewok-janitor** [ngneat/transloco#53]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

With `scopeStrategy` set to `shared`, you can load a root translation file such as this:

<pre><code>
{
    "rootpageheader": "welcome",
    "subcomponent": {
        "header": "child",
    }
}
</code></pre>

In a separate component, setting the scope to `subcomponent` like this:
<pre><code>
        {
            provide: TRANSLOCO_SCOPE,
            useValue: "subcomponent",
        },
</code></pre>

Will bypass checking the existing translation, and will instead fire a call to the `TranslocoLoader`.  With the default `httploader` from the docs, this fires an unnecessary xhr call.

## Expected behavior

Existing translation scopes should be checked before loading more

## What is the motivation / use case for changing the behavior?

Scoped translations are useful.  However, when using the key-as-value pattern AND scoped translations, you can no longer have attribute translations like this:

```
<div transloco="Username to display:"></div>
```

the only option is to use `TRANSLOCO_SCOPE`, which forces an (unnecessary) load

**Comment by shaharkazaz** [comment]
@ewok-janitor I'm not sure how `subcomponent` key got to the translation file, can you please explain? 
Do you have a key with the same name as the scope?

**Comment by fxck** [comment]
I have a feeling he's mistaking `scope` with `read`.

**Comment by ewok-janitor** [comment]
Yes- the `read` and `scope` ideas are muddled somewhat.  They seem like aspects of the the same concept.

The concept is that there is one huge translation tree, broken up by properties.  In the `read` pattern, all of these properties are available in local memory.  In the `scope` pattern, it requires an xhr to populate.


Let me try to explain what I am trying to accomplish, and then you can tell me where I have gone wrong :)

I am writing a library (call it the `lib` library).  This library will ship translations with it.  We are hoping that consumers (`consumer`) will concatenation our translations with theirs.  This is so that there will only be one initial xhr for translations.  We'll need to namespace the `lib` strings so that there are no collisions.  I had anticipated using the `shared` strategy, like in your documentation

The singular file will look something like:
<pre><code>
{
    "consumer": {
         "welcome" : "welcome"
     }
    "lib": {
        "library_string": "library_string",
    }
}
</code></pre>

All good so far.  I can use the `read` concept like in your example.

```
<ng-container *transloco="let t; read: 'lib'">
  <h1>{{ t.library_string}}</h1>
</ng-container>
```

However, this pattern prevents the use of keys as value.  By that I mean, NOT using aliases for the strings.  You use the actual string.  For example,
```
 <li><span transloco="This is the actual english string"></span></li>
```

For this, the translation file would need to be:

<pre><code>
{
    "lib": {
        "This is the actual english string": "This is the actual english string",
    }
}
</code></pre>

When you do it this way, you can use an automated extraction process, and create all of the i18n files automatically.  The developers never have to worry about translations files, its all part of the build automation.

So, the real question: **How do I use the `read` concept without specifying the prefix in every string?**

I can get very close to this with the use of `TRANSLOCO_SCOPE`.  This only issue is that a separate scope requires a second call to the loader.

In order to get this effect WITHOUT a second xhr, I can load the full combined translation file in the initial call to the `TRANSLOCO_LOADER`.  Then, in subsequent calls to my custom `TRANSLOCO_LOADER`, I just return one part of the copy I already have.  But, this seems like it would be really useful to have in the framework.

**Comment by NetanelBasal** [comment]
Let's make it clear for a second. Lazy loading scopes and the `read` property are not related.

You can use `read` without a lazy load. So, for example, if your translation file includes the following keys:

```json
{
  "general": {
     "OK": "",
     "submit": ""
   }
}
```

You can set the context to be the `general` object:

```html
<ng-container *transloco="let t; read: 'general'">
  <h1>{{ t.OK }}</h1>
  <h1>{{ t.submit }}</h1>
</ng-container>
```

When you use the `scope` feature, Transloco will lazily load it, and merge it under the scope name into the current language.

Back to your example, if your file looks like this:

```json
{
  "lib": {
     "This is the actual english string": "This is the actual english string",
  }
}
```

It doesn't matter if it's a lazy load scope or a static key, you have to use it following the JS rules:

```html
<ng-container *transloco="let t; read: 'lib'">
  <h1>{{ t['This is the actual english string'] }}</h1>
</ng-container>
```

Btw, we're working on a CLI tool that will help you with the development process extracts all the keys, and creates the files for you.

**Comment by ewok-janitor** [comment]
gotcha, thanks for the explanation
