### ISSUE TITLE
Feature(messageformat): include a lightweight option

### ISSUE THREAD

**Issue by AmitMY** [ngneat/transloco#535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) will this feature affect?

MessageFormat

### Is your feature request related to a problem? Please describe

When compiled for production, my entire bundle is 900kb, out of them, 79kb are `@messageformat/core`.

### Describe the solution you'd like

I would like to use **simple** find and replace formatting, without having 150kb in my bundle.

Given the following i18n string: 
> "{val} is the value"

I want to be able to specify `val` for an easy find and replace. No need for the entire functionality of `messageformat`

### Describe alternatives you've considered

```markdown
`('path.to.translation' | transloco).replace('{val}', val)`
```

### Describe alternatives you've considered

Going to Angular i18n, but that looks very bad

### Additional context

My repository is https://github.com/sign-language-processing/sign-translate

### I would like to make a pull request for this feature

No

**Comment by shaharkazaz** [comment]
@AmitMY Not sure how this relates to the messageformat lib, you just want to [use params](https://ngneat.github.io/transloco/docs/translation-in-the-template/#pipe).

**Comment by shaharkazaz** [comment]
@AmitMY Does my previous comment resolves your issue?

**Comment by shaharkazaz** [comment]
@AmitMY You're welcome?
