### ISSUE TITLE
Preload Module doesn't work at all, because the service is never instantiated

### ISSUE THREAD

**Issue by andi0b** [ngneat/transloco#551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Preload Langs

### Is this a regression?

Yes 

(probably, it can't work like it is implemented now, and I guess it used to work...?)

### Current behavior

The preload module doesn't preload anything, because it only registers the service, but it never gets constructed.

Just registerig a service to Angular DI, doesn't mean in gets constructed. At least in Angular 13.

### Expected behavior

Instantiate the preload service to fetch the languages. If you add this code to app.component.ts it works:

```ts
  constructor(injector:Injector) {

    // construct transloco preload service, horrible hack to get it working, can't directly request it, because it is not exported
    const x = TranslocoPreloadLangsModule.forRoot(["1"])
    const token = (x as any).providers[0]
    injector.get(token)

  }
```

### Please provide a link to a minimal reproduction of the bug

sorry

### Transloco Config

```markdown
import {HttpClient} from '@angular/common/http';
import {
  TRANSLOCO_LOADER,
  Translation,
  TranslocoLoader,
  TRANSLOCO_CONFIG,
  translocoConfig,
  TranslocoModule
} from '@ngneat/transloco';
import {Injectable, NgModule} from '@angular/core';
import {environment} from '../../environments/environment';
import {TranslocoPreloadLangsModule} from "@ngneat/transloco-preload-langs";

@Injectable({providedIn: 'root'})
export class TranslocoHttpLoader implements TranslocoLoader {
  constructor(private http: HttpClient) {
  }

  getTranslation(lang: string) {
    return this.http.get<Translation>(`/i18n/${lang}.json?v=${environment.appVersion}`);
  }
}



@NgModule({
  imports: [
    TranslocoPreloadLangsModule.forRoot(['en', 'de', 'register/de', 'register/en']),
  ],
  exports: [TranslocoModule],
  providers: [
    {
      provide: TRANSLOCO_CONFIG,
      useValue: translocoConfig({
        availableLangs: ['de', 'en'],
        defaultLang: 'de',
        reRenderOnLangChange: true,
        fallbackLang: 'de',
        prodMode: environment.production,
      })
    },
    {provide: TRANSLOCO_LOADER, useClass: TranslocoHttpLoader}
  ]
})
export class TranslocoRootModule {
}
```

### Please provide the environment you discovered this bug in

```markdown
Transloco: 3.2.0
Angular: 13.2.0
Node: v16.14.0
Package Manager: NPM 8.3.1
OS: Windows
```

### Browser

```markdown
Chrome 99
Firefox 98
it doesn't really matter
```

### Additional context

The bug is somewhere here:

https://github.com/ngneat/transloco/tree/master/libs/transloco-preload-langs/src/lib

### I would like to make a pull request for this bug

No

**Comment by shaharkazaz** [comment]
@andi0b should be ok in v4.0.1, LMK if it works as expected 👍

**Comment by andi0b** [comment]
@shaharkazaz yes it works, thanks for the support! 👍
