### ISSUE TITLE
Bug(scope): Data path "" must NOT have additional properties(inlineLoader) when generating a new scope

### ISSUE THREAD

**Issue by PavelTurkish** [ngneat/transloco#558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Transloco

### Is this a regression?

No

### Current behavior

When I run `ng g @ngneat/transloco:scope my-scope` I get :

> Node.js version v17.3.0 detected.
> Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/releases/.
> Schematic input does not validate against the Schema: {"name":"my-scope","project":"my-project","langs":["en"],"translateType":"JSON","routing":false,"routingScope":"Child","flat":false,"commonModule":true,"lintFix":false}
> Errors:
> 
>   Data path "" must NOT have additional properties(inlineLoader)

### Expected behavior

I hoped to generate a new scope.

### Please provide a link to a minimal reproduction of the bug

-

### Transloco Config

```markdown
module.exports = {
  rootTranslationsPath: 'src/assets/i18n/',
  langs: ['en'],
  keysManager: {}
};
```

### Please provide the environment you discovered this bug in

```markdown
Transloco: 4.0.0
Angular: 13.3.2
Node: 17.3.0
Package Manager: 8.3.0
OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
```

### I would like to make a pull request for this bug

No

**Comment by DenisFilipic** [comment]
+1

**Comment by ghaschel** [comment]
+1
