### ISSUE TITLE
Using Preload plugin

### ISSUE THREAD

**Issue by nartc** [ngneat/transloco#56]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
![image](https://user-images.githubusercontent.com/25516557/64201153-98a3f480-ce53-11e9-89b0-3476340179d1.png)
I can't seem to import `TranslocoPreloadLangsModule`.

## Expected behavior
Be able to import and use `TranslocoPreloadLangsModule`

## Minimal reproduction of the problem with instructions
1. Install `@ngneat/transloco-preload-langs`
2. Can't seem to import and use `TranslocoPreloadLangsModule`

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, for that you could use our [stackblitz example](https://stackblitz.com/edit/transloco-example)

## Environment

<pre><code>
Angular version: 8.2.4

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.6
- Platform:  MacOSX

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
It is fixed in 1.0.1. Thanks for the report.
