### ISSUE TITLE
Feature(transpiler): Add translation key to transpile method

### ISSUE THREAD

**Issue by jacksonopp** [ngneat/transloco#568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) will this feature affect?

Transloco

### Is your feature request related to a problem? Please describe

We are migrating our applications from a custom translation solution to using transloco. In our applications, we store some translations that need to be swapped out for other translations occasionally. 

For example, I have an application that is used by two different clients, BarCorp and BazInc. Both companies host some help documentation about our application, but specific to their usecases. We store urls to those help docs in our translations, which usually looks something like this:

```json
{
  "helpurl": "help.mydefaultcompany.com/en",
  "helpurl.BARCORP": "help.barcorp.com/en",
  "helpurl.BAZINC": "www.bazinc.net/helpdocs/en",
  "viewHelp": "View help documentation"
}
```

In the template, we'd like to do something like
```html
<a [href]="t('helpurl')" >{{ t('viewHelp') }}</a>
```
and swap out the URL appropriately based on the client. The client could change dynamically in some instances.

### Describe the solution you'd like

I think that it could be very useful if the `transpile` method of the `TranslocoTranspiler` interface had the key as a parameter so that a custom transpiler can perform actions based on the key, such as the ones described above. No implementation changes would be needed for the default transpiler, or any of the other built in transpilers.

### Describe alternatives you've considered

```markdown
Our first approach was to use the TranslocoInterceptor, but since this client could change dynamically after translations have been loaded, I don't think its quite the right option. 

Our second approach was to look at the transpiler. We loop through all of the values in the `translation` parameter and compare their values against the `value` parameter in order to get the original key. We then create a new key with the original plus the suffix and return the value from the `translation` param that has that key. This ends up being pretty brittle, and doesn't have great performance.
```

### Additional context

I have forked transloco and added this feature, so I would like to make a PR that adds this as a feature. I'm fairly new to open source contributing, so I may be missing some things that you are looking for in a PR.

### I would like to make a pull request for this feature

Yes 🚀

**Comment by SplitThePotCyrus** [comment]
What's the status of this? I have the exact same issue

**Comment by jacksonopp** [comment]
@SplitThePotCyrus hopefully this will get merged soon. I've updated my fork to main, and pending everything passing it *should* get merged.

Also tagging @davidcraig5 who was working on a project with me that would benefit from this feature
