### ISSUE TITLE
[Discussion] Memoized translated values

### ISSUE THREAD

**Issue by nartc** [ngneat/transloco#57]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[x] Other... Please describe: Discussion
</code></pre>

Hi guys,

I'm just wondering if it's worth it to have "already translated keys" to be memoized. The motivation is when we render a list of items and there are some text on the items are repeated. For example:

<img width="1389" alt="Screen Shot 2019-09-03 at 11 06 17 PM" src="https://user-images.githubusercontent.com/25516557/64225120-a67f6700-ce9f-11e9-9579-f12606f72213.png">

As you can see the `TimeZone` on each card item can be duplicated. And I am doing:
```html
{{t.timeZone | translocoParams: {timeZone: location.timeZone} }}
```

I think it would be beneficial to have these "potential duplicated translated values" to be memoized. Just an idea. 

Cache key can be: `key + lang + scope + Object.keys(params).join('delimeter')` ?

What do you guys think? I do understand the trade-offs of having to implement a Cache to have memoized data but the question is "is it worth it?"

**Comment by shaharkazaz** [comment]
@nartc Thanks for the suggestion! 💪 
The translation operation isn't that expensive and it's not worth all the memory we will have to use for keeping everything.
Also, checking the params will make it almost the same as the original operation 🙂
