### ISSUE TITLE
Bug(scope): pre-commit is wrong

### ISSUE THREAD

**Issue by alvipeo** [ngneat/transloco#584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Don't know / other

### Is this a regression?

No

### Current behavior

The current version of pre-commit.js will catch this diff with a *removed* `.only()` as an invalid case:
```
-test.describe.only("Confirm on form leave", () => {
+test.describe("Confirm on form leave", () => {
    test("noChanges - should not ask", async ({ page }) => {
       await page.goto("/companies/add");
```
and will output the file containing the removal as an obstacle for commit.

### Expected behavior

commit should be valid

### Please provide a link to a minimal reproduction of the bug

see the behavior desc

### Please provide the environment you discovered this bug in

```markdown
Transloco: 
Angular: 
Node: 
Package Manager: 
OS:
```

### Additional context

Here's what I came up with:

```
/** Map of forbidden words and their match regex */
const words = {
   debugger: { matcher: "(debugger);?", extension: fileExtensions.ts },
   fit: { matcher: "\\s*fit\\(", extension: fileExtensions.spec },
   // \+\S+\.skip\(
   ".skip": { matcher: "\\+\\S+\\.skip\\(", extension: fileExtensions.spec },
   // \+\S+\.only\(
   ".only": { matcher: "\\+\\S+\\.only\\(", extension: fileExtensions.spec },
   fdescribe: { matcher: "\\s*fdescribe\\(", extension: fileExtensions.spec }
};
```

I only changed it for `skip` and `only`.

### I would like to make a pull request for this bug

No

**Comment by shaharkazaz** [comment]
@alvipeo The pre-commit.js is an internal script, I'm guessing you copied the logic for your own use.
The idea is to prevent at addition of these keywords, if you have them already in you committed code than just skip this check once to allow the removal.

Closing since this isn't part of the library and is working fine for my internal use-cases.
