### ISSUE TITLE
Feature(utils): Check unused translation keys

### ISSUE THREAD

**Issue by pumano** [ngneat/transloco#585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) will this feature affect?

Don't know / other

### Is your feature request related to a problem? Please describe

Common not resolved problem in large scale projects is - continuous support of translation keys. 

Features changed, but keys rarely deleted from `.json` files. 

### Describe the solution you'd like

Would love to see some console command for checking that keys from some language json file is exist inside project.

Just need to check that key is exist inside project and works as expected. And show list of unused translation keys when command finished.

It give possibility to maintain translation keys effectively, and possible to add checks in CI/CD pipeline for better quality.

### Describe alternatives you've considered

```markdown
mostly manually check keys inside IDE and it's not efficient
```

### I would like to make a pull request for this feature

No

**Comment by AbdealiJK** [comment]
Currently I delete the the entire JSON file and regenerate it. And then take the keys and do a diff with my existing JSON to find missing paramters.
Would be great if there is a simple util which can do this for me !

**Comment by zstundys** [comment]
Checkout https://github.com/ngneat/transloco-keys-manager -- it does exactly the thing you look for ;)

**Comment by pumano** [comment]
@zstundys thank you, I will check it soon

**Comment by shaharkazaz** [comment]
@zstundys Thanks for referencing.
@pumano Closing this. feel free to interact with the keys-manager repo if needed.
