### ISSUE TITLE
Bug(Tests): Testfile not launching in ESM mode

### ISSUE THREAD

**Issue by jnain** [ngneat/transloco#587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Transloco, Scoped Libs

### Is this a regression?

No

### Current behavior

I am using this minimum repro repository I've made (see in the dedicated area underneath)
So it's using Angular 14, Transloco, Spectator (it's pretty much all, and it's the stack i'm using in my real project so I kinda need this stack to work 🙏 )

When I launch the test from the root directory with  
`node --experimental-vm-modules --no-warnings node_modules/jest/bin/jest.js -c=projects/ticketing-lib-ui-library/jest.config.mjs --no-cache`
I get this error :
![image](https://user-images.githubusercontent.com/4598542/183382606-70fba78f-010c-4cfe-a239-97a785fed8c7.png)

After a bit of search, I found that when I change the import of 'flat' in the file node_modules\@ngneat\transloco\fesm2020\ngneat-transloco.mjs

from this: 

`import { unflatten as unflatten$1, flatten as flatten$1 } from 'flat';`

to this:

`import * as flat from 'flat';
const unflatten$1 = flat.unflatten;
const flatten$1 = flat.flatten;`

I get another error after launching the tests:

![image](https://user-images.githubusercontent.com/4598542/183383028-51ff7ff1-33ce-4cac-ad87-af1efa59b7d5.png)

### Expected behavior

I expect the test to pass as it is only a "should init" test.

### Please provide a link to a minimal reproduction of the bug

https://github.com/jnain/minimum-transloco-spectator-repro

### Transloco Config

```markdown
Not relevant and can be found in the repo (but not sure it is complete as I removed a lot of my project)
```

### Please provide the environment you discovered this bug in

```markdown
Transloco: ~4.1.1
Angular: ^14.1.0
Node: v16.16.0
Package Manager: npm 8.11.0
OS: Windows
```

### Browser

```markdown
Jest test framework
```

### I would like to make a pull request for this bug

If you really help me for this I can but as it is touching to your exported types, I'm not sure I can help...

**Comment by jnain** [comment]
Hello there ! 

After a loooot of digging in transloco code, trying to change this and that to help my app to test properly, I had a revelation : Why would there be a problem with the code if the app is running correctly?

So I began to look deeper into the testing conf and I found the answer to my problem.

As I am using the new ESM features, I had 2 issues :
* my ts-jest conf was set to `isolatedModules: true` unfortunately. Here is my final ts-jest conf :
`'ts-jest': {
      ...ngPreset.defaultsESM.globals['ts-jest'],
      tsconfig: '<rootDir>/tsconfig.spec.json',
      isolatedModules: false
    }`
* my tsconfig.spec was also not really good ; I now have to include all ts files for my tests and not only the .spec.ts :
`"include": ["src/**/*.ts"]`

**Comment by jnain** [comment]
Hello ! 

In fact I need to change some things in your lib in order to continue to use it...
I am making a PR now, but there are things that I can't do alone.

I manage to make a change in the way you use 'flat' library by moving you tsconfig a little bit ; but the transloco-schematics project is now broken when I try to build it...

I can't see why and I don't understand the error message...

Please have a look at my PR 🙏

**Comment by jnain** [comment]
I seem to have fix this problem in my PR, I would like to have some news about all of this please...

**Comment by jnain** [comment]
The only way I found was to build a local transloco with the changes made in my [PR](https://github.com/ngneat/transloco/pull/597) ; ATM I am using this version in my production application... 

This is not perfect as I am closed for any updates in transloco but it does the job for now...

**Comment by angelnikolov** [comment]
@jnain Yeah thinking of doing the same. Thanks man! Really helpful!

**Comment by shaharkazaz** [comment]
Closing this via [7657b3de](https://github.com/ngneat/transloco/commit/7657b3de185b011bd35f815436da759aae33fc26), feel free to reopen if not fixed
