### ISSUE TITLE
Install schematic is not following sourceRoot for assets path

### ISSUE THREAD

**Issue by Edouardbozon** [ngneat/transloco#59]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Hi, 

I'm using the Nx monorepo style and when running the install schematic, the assets path is not taking my `sourceRoot` from angular.json file. 

It results in creating the i18n directory in the wrong place : `src/assets/i18n` instead of `apps/my-app/src/assets/i18n` in my case.

## Expected behavior

Following the `sourceRoot` when creating the translations directory.

## What is the motivation / use case for changing the behavior?

Improve support of monorepo.

**Comment by itayod** [comment]
@Edouardbozon What path did you enter in the 3rd question (✍ Which folder will contain the translation files?)?

**Comment by Edouardbozon** [comment]
@itayod I entered the default value `src/assets/i18n`. It confused me because I expected this path to be relative to my application directory `apps/my-app`, not the project root. Just like others files added by the schematic.

**Comment by itayod** [comment]
@Edouardbozon thanks for your input, we decided to remove this question, as `asstes/i18n` it's pretty much the standard library for the translation files, and install it under the correct relative path.

I still left the option to set a different path that will also be relative to the project using `-path` flag :)
