### ISSUE TITLE
Add specs

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/transloco#6]

**Comment by itayod** [comment]
I will add jest now, and start with some specs...
make sure to update so we won't work on same files :P

**Comment by shaharkazaz** [comment]
@itayod Hey, we are working with [spectator](https://github.com/NetanelBasal/spectator) and I started writing the spec for the directive.
Let me know once you finished setting up jest 🙂

**Comment by itayod** [comment]
@shaharkazaz cool :) never tried your spectator, I am looking forward to trying that.

**Comment by shaharkazaz** [comment]
@NetanelBasal @itayod which specs do we still need to write?

**Comment by itayod** [comment]
@shaharkazaz did we test `transloco.pipe`?

**Comment by shaharkazaz** [comment]
@itayod yep, and the service is in PR now

**Comment by itayod** [comment]
great, so I think we're done with the unit tests for now :).
we can maybe add coverage report to our ci, and also create a badge for it in the `readme.md` file. but let's open another issue for it

**Comment by NetanelBasal** [comment]
@shaharkazaz you can run the coverage and see. There are few lines worth testing, as the runtime flag. We can go for 100% easily. 🥇
