### ISSUE TITLE
Bug(transloco-scoped-libs): --skip-gitignore flag is not respected in watch mode

### ISSUE THREAD

**Issue by joonashak** [ngneat/transloco#604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Scoped Libs

### Is this a regression?

No

### Current behavior

When running `transloco-scoped-libs` with the `--watch` and `--skip-gitignore` flags, `.gitignore` is amended upon chances to watched files.

You can test this in the provided repository, instructions are in `README.md`.

### Expected behavior

`transloco-scoped-libs` should either respect the `--skip-gitignore` in conjunction with the `--watch` flag as it does without the `--watch` flag, or explicitly throw, informing the user that and invalid flag was passed to the program. Preferably the former, as not having the `--skip-gitignore` functionality in watch mode pretty much renders it moot when not running in watch mode.

### Please provide a link to a minimal reproduction of the bug

https://github.com/joonashak/transloco-scope-libs-bug-repro

### Please provide the environment you discovered this bug in

```markdown
Transloco: 4.1.1
Angular: 13.3.0
Node: 16.14.0
Package Manager: npm@8.3.1
OS: macOS 12.6
```

### Browser

```markdown
Not relevant.
```

### I would like to make a pull request for this bug

Yes 🚀
See #605

**Comment by shaharkazaz** [comment]
Released in v5.0.1
