### ISSUE TITLE
List of browser languages

### ISSUE THREAD

**Issue by playpirates** [ngneat/transloco#61]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

getBrowserLang() and getBrowserCultureLang() returns only the first language in the list.

## Expected behavior

There should be methods which returns the complete lists of configured languages.

## What is the motivation / use case for changing the behavior?

The user's native language is German, but he also knows Spanish.
The user has multiple configured languages in browser in order [German, Spanish].
The app supports English and Spanish languages.

Because there is no German translation, English is selected as fallback instead of Spanish, even if the user knows Spanish.

**Comment by itayod** [comment]
@playpirates thanks for your input,

There is no point to add it to our API. You can accomplish that by using the browser's `navigator.languages` API, but consider that it is **not fully browser supported**.

![](https://user-images.githubusercontent.com/6719615/64323466-3bcc4980-cfcd-11e9-9ae8-cb7a7155edf8.jpeg)
