### ISSUE TITLE
Feature(TranslocoModule): Support for Standalone Applications

### ISSUE THREAD

**Issue by tutkli** [ngneat/transloco#614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) will this feature affect?

Transloco

### Is your feature request related to a problem? Please describe

As for now, trying to install Transloco in a standalone application with no modules does not work.

Steps to reproduce:

1. Create a standalone application without ngModules (Angular v14 or v15)
2. Try to add Transloco `ng add @ngneat/transloco --project your-project-name`
3. Installation will fail with error `Specified module path src/app does not exist`

```bash
ng add @ngneat/transloco --project your-project-name
Skipping installation: Package already installed
? 🌍 Which languages do you need? en, es
? 🚀 Are you working with server side rendering? No
Specified module path src/app does not exist
```

Additionally, it is required to import the entire TranslocoModule in every standalone component for it to work.

### Describe the solution you'd like

Add suport to Standalone Applications, importing the TranslocoModule in main.ts bootstrapApplication imports.
Additionally, it would be nice if we could import Translocos' directives and pipes directly in the components instead of the whole module.

### Describe alternatives you've considered

```markdown
Manually import the TranslocoModule
```

### I would like to make a pull request for this feature

No

**Comment by kfern** [comment]
@shaharkazaz Do you have any plans to implement this functionality? Without this it is not possible to use Transloco in new projects

**Comment by tutkli** [comment]
@kfern It is possible to use Transloco if you create the transloco module manually. But it would be nice to have a standalone API since it looks like Angular it's moving to that direction.

**Comment by shaharkazaz** [comment]
@kfern as @tutkli said this shouldn't block you in any way.
@tutkli Don't have an ETA on this, I'll try to prioritize for our sponsor 😃

**Comment by kfern** [comment]
Thank you @tutkli @shaharkazaz. I'll try to create the transloco module manually

**Comment by Legiew** [comment]
Hey,
has someone got it working?
I am trying to add transloco to a freshly created nx workspace (angular and a few angular libs). The app builds but on page load I got the following error:
```
ERROR NullInjectorError: R3InjectorError(Standalone[_s])[o -> o -> InjectionToken TRANSLOCO_TRANSPILER -> InjectionToken TRANSLOCO_TRANSPILER]: 
  NullInjectorError: No provider for InjectionToken TRANSLOCO_TRANSPILER!
```

What I did so far:
- copied the code for TranslocoRootModule and TranslocoHttpLoader from the docs
- imported it in the standalone AppComponent or in bootstrapApplication > providers
- I always get the error above twice in the console

What am I missing?

**Comment by Legiew** [comment]
`importProvidersFrom` around the module was missing thanks.

**Comment by zsmatrix62** [comment]
Thanks, importProvidersForm actually works.

**Comment by tutkli** [comment]
Here is a [Stackblitz Demo](https://stackblitz.com/edit/angular-ivy-vrpbhe) for anyone interested.

**Comment by guzmanoj** [comment]
You could simply define a function that returns all the providers, thus no need to create a `TranslocoRootModule`
```

import {
  TRANSLOCO_CONFIG,
  TRANSLOCO_LOADER,
  translocoConfig,
  TranslocoModule,
} from '@ngneat/transloco';
import { DEFAULT_LANGUAGE, LANGUAGES } from './i18n-configuration';
import {
  EnvironmentProviders,
  importProvidersFrom,
  makeEnvironmentProviders,
} from '@angular/core';
import { TranslationLoaderService } from './translation-loader.service';

export const provideRootTranslocoConfig = (): EnvironmentProviders => {
  return makeEnvironmentProviders([
    importProvidersFrom(TranslocoModule),
    {
      provide: TRANSLOCO_CONFIG,
      useValue: translocoConfig({
        availableLangs: LANGUAGES,
        defaultLang: DEFAULT_LANGUAGE,
        reRenderOnLangChange: false,
        prodMode: true,
      }),
    },
    {
      provide: TRANSLOCO_LOADER,
      useClass: TranslationLoaderService,
    },
  ]);
};

```

The magic occurs in the  `importProvidersFrom(TranslocoModule)`

Then just use the function in your main.ts

```
bootstrapApplication(AppComponent, {
  providers: [
    provideRouter(appRoutes, withEnabledBlockingInitialNavigation()),
    provideHttpClient(),
    provideRootTranslocoConfig(),
  ],
}).catch((err) => console.error(err));
```

In the future, the library could export a similar function, and we (consumers) can wrap it with our custom providers or maybe the function will allow some sort of configuration similar to provideRouter() or provideHttpClient() functions from Angular.

**Comment by alexfriesen** [comment]
This Code works quite well for me:

```ts
import {
  defaultProviders,
  TRANSLOCO_CONFIG,
  TRANSLOCO_LOADER,
  TRANSLOCO_SCOPE,
  translocoConfig,
  TranslocoConfig,
  TranslocoLoader,
  TranslocoScope,
} from '@ngneat/transloco';

type TranslocoOptions = {
  config?: Partial<TranslocoConfig>;
  loader?: Type<TranslocoLoader>;
};

export function provideTransloco(options: TranslocoOptions) {
  const providers: Provider[] = [...defaultProviders];

  if (options.config) {
    providers.push({
      provide: TRANSLOCO_CONFIG,
      useValue: translocoConfig(options.config),
    });
  }

  if (options.loader) {
    providers.push({ provide: TRANSLOCO_LOADER, useClass: options.loader });
  }

  return makeEnvironmentProviders(providers);
}

export function provideTranslocoScope(scope: TranslocoScope) {
  return makeEnvironmentProviders([
    {
      provide: TRANSLOCO_SCOPE,
      useValue: scope,
    },
  ]);
}
```

`importProvidersFrom(TranslocoModule)` would just extract `defaultProviders` from the module  so I use it directly.

Another approach could be to split it up in separate functions like: `provideTransloco`, `provideTranslocoLoader`, `provideTranslocoConfig`

**Comment by tleveque23** [comment]
And what about lazy loading? Is anybody found a solution to us it when having a full standalone project?
It seems to not make sens since there is no module, but with a standalone project you still can lazy load components by route.

**Comment by tleveque23** [comment]
> And what about lazy loading? Is anybody found a solution to us it when having a full standalone project?
> It seems to not make sens since there is no module, but with a standalone project you still can lazy load components by route.

I will answer to myself! Look at the stackblitz exemple! It is already there! https://stackblitz.com/edit/angular-ivy-vrpbhe
Just use 
providers: [{ provide: TRANSLOCO_SCOPE, useValue: 'lazy' }]
In the route

**Comment by MickL** [comment]
Arent standalone apps already supported as described here? https://ngneat.github.io/transloco/docs/getting-started/installation/#standalone-setup

In this case I wonder why this issue is still open or is there more stuff missing?

**Comment by shaharkazaz** [comment]
v5 is now standalone and compatible with Angular v16. 
I'll update the docs when I get the chance.

**Comment by alfredo-perez-lc** [comment]
@shaharkazaz is this still an issue? I  can see the following error when using it with Standalone and Lazy Loading

```sh
ERROR NullInjectorError: R3InjectorError(Standalone[RoleManagement])[TranslocoService -> TranslocoService -> TranslocoService -> InjectionToken TRANSLOCO_TRANSPILER -> InjectionToken TRANSLOCO_TRANSPILER]
```

**Comment by shaharkazaz** [comment]
@alfredo-perez-lc Not as far as I know. Make sure you are using the correct provider functions.
If you are still having problems open an issue **with a reproduction link**.

**Comment by shaharkazaz** [comment]
@nhhockeyplayer like my previous comment to @alfredo-perez-lc, I'm unaware that this is still an issue, you can open a new  issue **with a reproduction link.**

**Comment by nhhockeyplayer** [comment]
nope
after haggling with the docs
issues in play for 2 yrs
and then assessing the entire codebase and who crafted it
Im bailing

this library was crafted by javascript callback functional programmers with javascript habits that cannot be broken
and the end result is a pile of creator functions thrown at the wall that are stuck 

javascript is short cut like react and unfit for commercial applications
it does not survive change
and costly and painful
let alone unreadable

checkout typegoose... beautiful diamond grade set of generics destroyed by javascript hands manifesting more issues

these KINDS of developers I have witnessed sink entire corporations into chapter 11 hailing and claiming to the closure

but all it amounts is one liner whiz bang code statements
then the one liner becomes a one liner with 2 whiz bang functions short-cutted into the one line
then the one liner becomes 3 purpose short-cuts in one line
soon we have multiple lines of code that each perform 3 or more things and interdependent across in and around
and it grows limited, goes brittle and fails to change or adapt

and this is what happens when a javascripter who has no concept of natural world object oriented design training and chooses to live by functions/callbacks/transient-grifting-properties-on-objects with who knows what inside for logic the addiction is anything can be short-cutted and one-lined they are unreadable when plastered everywhere and its found its way into some of the most best elite frameworks 

but an entire group of humans worldwide continue to program like this when javascript is unfit

these are the javascripters in europe like the ones who condemned NgRX with akita

some nice javasacript products exist but under the hood is harrowing and limited it cant survive change without pain and cost

maybe its fun throwing creator functions at the wall

Im dis-impressed for giving transloco my time and it looks to be a political clique like react and facebook

what impressed me is ngx-translate
- simple
- turnkey
- modeled the right way using observables
- it don't throw a plethora of functions at the wall 
- corral them for primitive procedural legs of execution

this library has my sympathy

I chose to remove transloco from all my code today
all it took was that one runtime error for translocoservice failed injectoreror that no one on the web has yet to solve
and I have mor eimportant things to do

ciao

**Comment by wall-street-dev** [comment]
> nope after haggling with the docs issues in play for 2 yrs and then assessing the entire codebase and who crafted it Im bailing
> 
> this library was crafted by javascript callback functional programmers with javascript habits that cannot be broken and the end result is a pile of creator functions thrown at the wall that are stuck
> 
> javascript is short cut like react and unfit for commercial applications it does not survive change and costly and painful let alone unreadable
> 
> checkout typegoose... beautiful diamond grade set of generics destroyed by javascript hands manifesting more issues
> 
> these KINDS of developers I have witnessed sink entire corporations into chapter 11 hailing and claiming to the closure
> 
> but all it amounts is one liner whiz bang code statements then the one liner becomes a one liner with 2 whiz bang functions short-cutted into the one line then the one liner becomes 3 purpose short-cuts in one line soon we have multiple lines of code that each perform 3 or more things and interdependent across in and around and it grows limited, goes brittle and fails to change or adapt
> 
> and this is what happens when a javascripter who has no concept of natural world object oriented design training and chooses to live by functions/callbacks/transient-grifting-properties-on-objects with who knows what inside for logic the addiction is anything can be short-cutted and one-lined they are unreadable when plastered everywhere and its found its way into some of the most best elite frameworks
> 
> but an entire group of humans worldwide continue to program like this when javascript is unfit
> 
> these are the javascripters in europe like the ones who condemned NgRX with akita
> 
> some nice javasacript products exist but under the hood is harrowing and limited it cant survive change without pain and cost
> 
> maybe its fun throwing creator functions at the wall
> 
> Im dis-impressed for giving transloco my time and it looks to be a political clique like react and facebook
> 
> what impressed me is ngx-translate
> 
> * simple
> * turnkey
> * modeled the right way using observables
> * it don't throw a plethora of functions at the wall
> * nor corral them for primitive procedural legs of execution
> 
> I chose to remove transloco from all my code today all it took was that one runtime error for translocoservice failed injectoreror that no one on the web has yet to solve and I have more important things to do
> 
> ciao

Who hurt you?

**Comment by nhhockeyplayer** [comment]
ha ha  : )
you beat me to the punch

some folks are more focused on beauty and elegance
we don't care about taking over the world
its a gift

**Comment by nhhockeyplayer** [comment]
sorry I inxulted your library
Im still going with ngx-translate
