### ISSUE TITLE
Add Locale Support 

### ISSUE THREAD

**Issue by philjones88** [ngneat/transloco#62]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

No way to change LOCALE_ID based on language selected in transloco so that pipes such a Date etc update.

## Expected behavior

Have some pipes like found in https://github.com/robisim74/angular-l10n

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, for that you could use our [stackblitz example](https://stackblitz.com/edit/transloco-example)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by itayod** [comment]
Hi @philjones88, thanks for your suggestion.

We will provide an external module that will include support for locales pipes (e.g. date format & currency) as part of Transloco.

**Comment by itayod** [comment]
Hi @armanozak, thanks for the suggestion.
I already implement it using the native JS API, and will release it next week.

**Comment by NetanelBasal** [comment]
@philjones88 we're almost there. @itayod will fix the PR comments, and we'll release the library. 

We would love to get your feedback before the release. Here's the [README](https://github.com/ngneat/transloco/blob/86f490433fb31371e32adefffe607815618b6c13/projects/ngneat/transloco-locale/README.md) file.

CC @armanozak.

**Comment by armanozak** [comment]
@itayod did an amazing job. Can't wait to give it a try. I've put a few comments. Hopefully useful ones... 🤞

**Comment by TmrdShnb** [comment]
‫في الجمعة، 13 سبتمبر 2019 في 12:25 ص تمت كتابة ما يلي بواسطة ‪Levent
Arman Özak‬‏ <‪notifications@github.com‬‏>:‬
