### ISSUE TITLE
Bug(migrate, v2):  Cannot find module 'fs-extra'

### ISSUE THREAD

**Issue by fowl2** [ngneat/transloco#623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Schematics

### Is this a regression?

Unknown

### Current behavior

I'm trying to run `@ngneat/transloco:migrate` on and Angular 7 project. It seems that if the project doesn't already include `fs-extra`, the migration will fail:

```
>npm run -- ng g @ngneat/transloco:migrate  

> ng "g" "@ngneat/transloco:migrate"

? ✍ Which library did you use? Angular
? ✍ Which folder will contain the translation files? ./src/app
Cannot find module 'fs-extra'
```

### Expected behavior

migration runs :)

### Please provide a link to a minimal reproduction of the bug

N/A

### Transloco Config

```markdown
None yet :)
```

### Please provide the environment you discovered this bug in

```markdown
Transloco: 2.23.5
Angular: 7.2.16
Node: node@v10.24.1
Package Manager: npm@6.14.12
OS: Windows_NT 10.0.19044
```

### Browser

```markdown
N/A
```

### Additional context

Fix seems to be `npm install fs-extra@^8.1.0`. 

The current version isn't compatilbie with the node version required for Angular 7.

I found 8.1 from:

https://github.com/ngneat/transloco/blob/4d51bd9594da17ca6626352d8938b8a1be1126f4/schematics/package.json#L18

Not sure why it's not being picked up when installing transloco.

### I would like to make a pull request for this bug

If I knew the fix I would.

**Comment by shaharkazaz** [comment]
@fowl2 we use fs-extra v9.1.0 which requires node v10+ so why do you need to install v8.1.0? 🤔 
I'll take a look but anyway a fix won't be released for Transloco v2 since we are currently on v4.

**Comment by fowl2** [comment]
I used the version of fs-extras from the package file I linked as it seemed likely this would be the correct version and the current version isn't supported by the version of node that's supported by the version of angular I'm using. I'm using V2 for the same reason.

**Comment by shaharkazaz** [comment]
@fowl2 Yes I understand that you are using V2 because of Angular 7. 
What I'm saying it that `fs-extra@9.1.0` supports node 10+ which is the version you have.

Anyways, I'm glad you managed to migrate, I'll add a fix for new users and Transloco v4.

BTW did the migration went as expected?
