### ISSUE TITLE
Unable to use translation service programmatically

### ISSUE THREAD

**Issue by t0nyak** [ngneat/transloco#63]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Translation programmatically is not working at all.

## Expected behavior

Being able to translate somehow in the component.

## Minimal reproduction of the problem with instructions

1) Inject transloco service in the component where I want to use it
2) Call `translate()` method with the exact string to the value to be translated like this: `this.service.translate('section.subsection.value')`
3) It returns nothing

No matter if I inject the service using `constructor(private service: TranslocoService) {}` or I directly import `translate()` function. Both of them do nothing.

I know the path to the value in the translation files is correct, since it works using the template approach.

By the way, I'm not providing a stackblitz demo since I've not been able even to reproduce the transloco-example in the stackblitz. Is the project and the demo still being supported?

## Environment

<pre><code>
Angular version: 8.0.1

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.16.0  
- Platform: Mac 

Others:

</code></pre>

**Comment by itayod** [comment]
Hi @t0nyak,

Your problem is that the translation files did not successfully load yet when you tried to use the `tranlate` method.

**From the docs**:
"Note that in order to safely use this method, you are responsible for ensuring that the translation files have been successfully loaded by the time it's called. If you aren't sure, you can use the `selectTranslate()` method instead"

**Comment by gs-mhashir** [comment]
how to load the translation files before calling any method

**Comment by sysmat** [comment]
> Note that in order to safely use this method, you are responsible for ensuring that the translation files have been successfully loaded by the time it's called.

is this possible ? If not translate method should be removed

**Comment by shaharkazaz** [comment]
@sysmat @gs-mhashir I recommended [reading the docs](https://ngneat.github.io/transloco/docs/translation-api#translate).
