### ISSUE TITLE
Bug(dependency): Could not resolve dependency: peer fs-extra@"^9.1.0" from @ngneat/transloco@4.2.4

### ISSUE THREAD

**Issue by PeterHewat** [ngneat/transloco#630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Transloco

### Is this a regression?

Yes

### Current behavior

Trying to update from @ngneat/transloco 4.2.2 to 4.2.4 I get the following issue:
```shell
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: ps-ui@0.0.0
npm ERR! Found: fs-extra@11.1.0
npm ERR! node_modules/fs-extra
npm ERR!   dev fs-extra@"^11.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer fs-extra@"^9.1.0" from @ngneat/transloco@4.2.4
```
I have `"fs-extra": "^11.1.0"` in my devDependencies but since @shaharkazaz pushed https://github.com/ngneat/transloco/commit/581dda1c4955ffa68f43ee0bfdef3ef2afc9f698 it requieres an older version of fs-extra

### Expected behavior

Updating @ngneat/transloco to latest version should work fine with latest version of fs-extra

### Please provide a link to a minimal reproduction of the bug, if you won't provide a link the issue won't be handled.

not relevant

### Transloco Config

```markdown
not relevant
```

### Please provide the environment you discovered this bug in

```markdown
Transloco: 4.2.4
Angular: 15.1.5
Node: 18.12.1
Package Manager: npm
OS: MacOS 13.2.1
```

### Browser

```markdown
not relevant
```

### I would like to make a pull request for this bug

Yes 🚀

**Comment by shaharkazaz** [comment]
You want to make the fix or I'll push it? 😊

**Comment by PeterHewat** [comment]
I'm doing it as we speak ;-)
