### ISSUE TITLE
Bug(MessageFormat): delay of a change

### ISSUE THREAD

**Issue by ben12** [ngneat/transloco#633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

MessageFormat

### Is this a regression?

Yes

### Current behavior

When the active language changes, the message format delays a change.

![image](https://user-images.githubusercontent.com/6554486/222105775-789ebf73-fc18-485f-8dc8-0a31ae030ad3.png)
![image](https://user-images.githubusercontent.com/6554486/222105894-3712b6ce-cd11-4e20-91d0-6c6ffeece038.png)

### Expected behavior

When the active language changes, the message format use the active lang.

![image](https://user-images.githubusercontent.com/6554486/222106705-dc7a26da-4679-4b32-a9f0-2306d6bdcf5d.png)
![image](https://user-images.githubusercontent.com/6554486/222106778-a7159ae9-5d20-41df-962d-8d1a2b963888.png)

### Please provide a link to a minimal reproduction of the bug, if you won't provide a link the issue won't be handled.

https://stackblitz.com/edit/angular-3mqfvo?file=src/app.component.ts

### Please provide the environment you discovered this bug in

```markdown
Transloco: 4.2.5
Transloco-messageformat: 4.1.0
Angular: 15.0.0
```

### Additional context

A workaround is to call `this.translocoTranspiler.onLangChanged(lang)` before `this.translocoService.setActiveLang(lang)`

### I would like to make a pull request for this bug

Yes

**Comment by shaharkazaz** [comment]
Released in v4.2.6, thanks for the PR
