### ISSUE TITLE
Can't get Transloco Persist Translations to work

### ISSUE THREAD

**Issue by philjones88** [ngneat/transloco#64]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I've followed the instructions on setting up Transloco Persist Translations in my AppModule like:

```
        TranslocoModule,
        TranslocoPersistLangModule.init({
            storage: {
                provide: TRANSLOCO_PERSIST_LANG_STORAGE,
                useValue: cookiesStorage()
            },
            storageKey: 'locale'
        }),
        TranslocoPersistTranslationsModule.init({
            loader: HttpLoader,
            storage: {
              provide: PERSIST_TRANSLATIONS_STORAGE,
              useValue: localStorage
            },
            ttl: 86400,
            storageKey: 'translations'
          })
```

And it compiles / runs.

Nothing is persisted.

I added breakpoints in the Firefox dev tools but it's not hitting them.

<img width="590" alt="image" src="https://user-images.githubusercontent.com/677167/64362217-0859e100-d006-11e9-8858-b399479a26fb.png">

Can you not use Transloco Persist Lang and Transloco Persist Translations at the same time maybe?

## Expected behavior

It to persist to local storage

## Minimal reproduction of the problem with instructions

See current behaviour

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version 69
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.16.3
- Platform:  Mac
- Angular: 8.0.3
- Transloco: 1.7.2
- Transloco Persist Lang: 1.0.1
- Transloco Persist Translations: 1.0.0

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
My guess is that you didn't remove the default loader:

```ts
providers: [
  translocoLoader <==== remove this
]
```

**Comment by NetanelBasal** [comment]
I added this note to the README file. Feel free to close the issue if it solves your problem.

**Comment by NetanelBasal** [comment]
You can see a working example here: https://github.com/NetanelBasal/transloco-plugins-playground

**Comment by philjones88** [comment]
@NetanelBasal 	you are exactly right, feel like a numpty!
