### ISSUE TITLE
Bug(docs): Unable to load docs (ERR_SSL_PROTOCOL_ERROR)

### ISSUE THREAD

**Issue by Chifilly** [ngneat/transloco#643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Don't know / other

### Is this a regression?

Yes

### Current behavior

Trying to access the docs site in Chrome results in the following error:

```
This site can’t provide a secure connection
ngneat.github.io sent an invalid response.
ERR_SSL_PROTOCOL_ERROR
```

and in Firefox it just times out.

### Expected behavior

The docs site is accessible

### Please provide a link to a minimal reproduction of the bug, if you won't provide a link the issue won't be handled.

https://ngneat.github.io/transloco/

### Please provide the environment you discovered this bug in

```markdown
OS: KDE Neon 5.27
```

### Browser

```markdown
Chrome Desktop Version 111.0.5563.110
Firefox Desktop Version 111.0.1
```

### I would like to make a pull request for this bug

No

**Comment by shaharkazaz** [comment]
Do you have some sort of firewall set up? We are using GH pages for the docs nothing special.

I can access it without any problems, I'll need more info to understand what's going on

**Comment by Chifilly** [comment]
Not that I know of, but I'll try and provide as much info as I can, just let me know what you need.

I noticed that it seems to work with Brave browser, but neither Chrome nor Firefox on Desktop, and on mobile I tried 4 browsers (Chrome, Firefox, Brave and Kiwi) and they all either time out or give the same `ERR_SSL_PROTOCOL_ERROR` error.

I also don't have any issues with other GitHub Pages, either using a custom domain or `.github.io`.

However, if I disable WiFi on mobile I can access it fine on all browsers, so it seems to be the router or my ISP. But I don't understand why it would work with Brave on Desktop but not Chrome or Firefox if it's a router/ISP level issue.

**Comment by shaharkazaz** [comment]
Thanks for the info! We need to take the time to understand because something similar opened in Elf as well

**Comment by paslavsky** [comment]
➕ Same for me

**Comment by shaharkazaz** [comment]
I really have no clues on this 😞 
I'll try updating the docs libs. Once updated, I'll update here and you can LMK if it worked.
If the issue still presists, I need one of you who has this issue to help investigate.

**Comment by shaharkazaz** [comment]
I tried to deploy an updated version. can you please try it?

**Comment by ruimmserrano** [comment]
after a few refreshes, is working now

**Comment by shaharkazaz** [comment]
@paslavsky @Chifilly Can you please also verify?

**Comment by paslavsky** [comment]
😕 Unfortunately, I see the same error page with the error code `ERR_SSL_PROTOCOL_ERROR`. 
I can suspect the issue is with the HTTPS certificate for your domain. You may need to regenerate the certificate.

**Comment by shaharkazaz** [comment]
@paslavsky Seems like it resolved a [similar issue in Elf](https://github.com/ngneat/elf/issues/450#event-9209110410) as well.
It's all managed by GH and built by docusaurus so TBH I think there's nothing I can do besides what's done.

**Comment by paslavsky** [comment]
📣📣📣**Update**: I cleaned the cache at my router, and it helps. Maybe it will be enough to reboot the router.

**Comment by Chifilly** [comment]
It seems to be fixed for me too
