### ISSUE TITLE
Feature(scope): Missing handler: passing TranslocoService 

### ISSUE THREAD

**Issue by f-aubert** [ngneat/transloco#645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) will this feature affect?

Transloco

### Is your feature request related to a problem? Please describe

I'm currently implementing a Missing Handler. 

### Describe the solution you'd like

In the handle method, I'd like to access the active and available languages from the TranslocoService, so passing the service as argument to the handle method (ngx-translate does it) seems a clean and easy solution. 

### Describe alternatives you've considered

```markdown
Note: injecting TranslocoService in Missing handler results in circular DI!
```

### I would like to make a pull request for this feature

Yes 🚀

**Comment by f-aubert** [comment]
It would also allow the missing value to be added using setTranslation

**Comment by shaharkazaz** [comment]
You can inject the service via the Injector. See a [similar issue](https://github.com/ngneat/transloco/issues/555).
I might change the API in a newer version of the lib

**Comment by f-aubert** [comment]
Thanks for pointing me the other issue as well as the injector workaround. Great Lib! Great Author!
