### ISSUE TITLE
Feature(Support): Angular 16 RC unsupported

### ISSUE THREAD

**Issue by LuigiDC** [ngneat/transloco#646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) will this feature affect?

Transloco

### Is your feature request related to a problem? Please describe

Is it possible to get an Transloco RC for the actual Angular 16 RC?

### Describe the solution you'd like

Support for Angular 16 (RC).

### Describe alternatives you've considered

```markdown
Manually tried to install the actual release through
npm i @ngneat/transloco --legacy-peer-deps
with Angular 16 but getting http interception errors in the application at the end.
```

### I would like to make a pull request for this feature

No

**Comment by liesahead** [comment]
Angular 16 is out, so this issue is more important now.

**Comment by anikets43** [comment]
@NetanelBasal @shaharkazaz Can we please get this PR merged?

**Comment by liesahead** [comment]
Actually, that's quite bad support for such library.. Risky to choose it for long-term projects.

**Comment by shaharkazaz** [comment]
@liesahead You are welcome not to use it.
Comments like these make you wonder why I even spend my free time on OS projects.

**Comment by liesahead** [comment]
@shaharkazaz , sorry if it was too harsh, I’m just sad recently because many OS libraries we use just became inactive and now we have to migrate many of them.

**Comment by dfa1234** [comment]
@shaharkazaz at least he didn't gave you due date like it happen to me frequently :) 

Please consider allowing to choose freely the angular version, here what I propose:
https://github.com/ngneat/transloco/pull/668
NPM sem-versionning is weird all the times, ">13.0.0" will be interpreted as "14 and greater will be not allowed"

תודה, חבריה

**Comment by liesahead** [comment]
@shaharkazaz , thanks a lot for the update! 😄
