### ISSUE TITLE
Bug(scope): NPM audit fails 

### ISSUE THREAD

**Issue by lechu1985** [ngneat/transloco#648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Transloco

### Is this a regression?

No

### Current behavior

NPM  audit started throwing exceptions and suggests an outdated package.

```
yaml  <2.2.2
Severity: moderate
Uncaught Exception in yaml - https://github.com/advisories/GHSA-f9xv-q969-pqx4
fix available via `npm audit fix --force`
Will install @ngneat/transloco@2.23.5, which is a breaking change
node_modules/yaml
  cosmiconfig  6.0.0 - [7][URL redacted]).1.0
  Depends on vulnerable versions of yaml
  node_modules/cosmiconfig
    @ngneat/transloco-utils  >=1.1.0
    Depends on vulnerable versions of cosmiconfig
    node_modules/@ngneat/transloco-utils
      @ngneat/transloco  >=3.0.0
      Depends on vulnerable versions of @ngneat/transloco-utils
      node_modules/@ngneat/transloco
      ```

### Expected behavior

npm audit should not fail :)
I think the `cosmiconfig` should be upgraded to 8.1.3 (a major update)

### Please provide a link to a minimal reproduction of the bug, if you won't provide a link the issue won't be handled.

https://github.com/ngneat/transloco - and run `npm audit` :D 

### Please provide the environment you discovered this bug in

```markdown
Transloco: 4.2.6
Angular: 14.2.5
Node: 16.3.1
Package Manager: npm
OS: wsl
```

### I would like to make a pull request for this bug

No

**Comment by angelaman** [comment]
Raised a PR in hope to fix this: https://github.com/ngneat/transloco/pull/651

**Comment by shaharkazaz** [comment]
Released a new version, LMK if the issue is fixed

**Comment by shaharkazaz** [comment]
Please reopen if this is still relevant.
