### ISSUE TITLE
Feature(typing): Typing for InjectionToken

### ISSUE THREAD

**Issue by AbdealiLoKo** [ngneat/transloco#658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) will this feature affect?

Transloco

### Is your feature request related to a problem? Please describe

I was trying to use the `inject()` function for DI and realized that `private parser = inject(TRANSLOCO_TRANSPILER)` gave me a type as `unknown`

On checking - I noticed that some of the `InjectionToken()`s in transloco do not mention a type. Would be nice to have a type.

A quick search on github shows the following don't have types
 - TRANSLOCO_LOADER
 - TRANSLOCO_PERSIST_LANG_STORAGE
 - TRANSLOCO_INTERCEPTOR
 - TRANSLOCO_TRANSPILER
 - TRANSLOCO_MISSING_HANDLER

### Describe the solution you'd like

Let's add types for InjectionTokens :)

### Describe alternatives you've considered

```markdown
I could override types: `private parser = inject(TRANSLOCO_TRANSPILER) as TranslocoTranspiler;`
```

### I would like to make a pull request for this feature

Yes 🚀

**Comment by shaharkazaz** [comment]
@AbdealiLoKo you are more than welcome to open a PR
