### ISSUE TITLE
Bug(messageformat): does not properly escape the characters `{}`

### ISSUE THREAD

**Issue by dzolotarova** [ngneat/transloco#665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

MessageFormat

### Is this a regression?

Yes

### Current behavior

My translation contains some text in {}. But transloco thinks it is a variable and tries to set the value.
 
For example, my translation:
`Some text {not_a_variable} some text`

It is rendered as
`Some text undefined some text`

### Expected behavior

It is rendered as
`Some text {not_a_variable} some text`

I think a possible solution is to add https://github.com/messageformat/messageformat/tree/main/packages/convert

### Please provide a link to a minimal reproduction of the bug, if you won't provide a link the issue won't be handled.

https://codesandbox.io/s/ngneat-transloco-forked-4yc2vp?file=/src/app/transpilers/transpilers.component.html

### Please provide the environment you discovered this bug in

```markdown
Transloco: 2.23.5
Angular: 14.2.7
Node: 16.13.2
Package Manager: 8.3.0
OS: macOS
```

### Browser

```markdown
Chrome (desktop) version 114.0.5735.133
```

### Additional context

I think a possible solution is to add https://github.com/messageformat/messageformat/tree/main/packages/convert

### I would like to make a pull request for this bug

Yes

**Comment by dzolotarova** [comment]
Seems I found another solution because https://github.com/messageformat/messageformat/tree/main/packages/convert is outdated.

Please check PR https://github.com/ngneat/transloco/pull/666

**Comment by EricPoul** [comment]
Hi @NetanelBasal, I see that lately, you have had no time to check opened PRs. We have to use `{some_test}` in our translations and it causes bags. Could someone have time to check a PR that @dzolotarova made?

**Comment by NetanelBasal** [comment]
Sure. @shaharkazaz can you please take care?

**Comment by ben12** [comment]
Single brace `{}` is handled by messageformat (when enabled), you must use the messageformat escape character which is quote:

So translation:
`Some text '{not_a_variable}' some text`
is rendered as
`Some text {not_a_variable} some text`

**Comment by NetanelBasal** [comment]
@EricPoul does @ben12 answer helps?

**Comment by EricPoul** [comment]
@ben12 thank you! I've been digging in `MessageFormat.escape` docs and never scroll the main docs page till the end😄.
@NetanelBasal it does. I guess we can close the issue and the pr.
