### ISSUE TITLE
Bug(scope): Upgrade to v5 asks for @ngneat/transloco-utils

### ISSUE THREAD

**Issue by bjornharvold** [ngneat/transloco#674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Transloco, Don't know / other

### Is this a regression?

Yes

### Current behavior

When I try to upgrade from 4.3.0 to 5.0.0 and run `yarn`, it asks me about which version of @ngneat/transloco-utils I want to use. When I manually add @ngneat/transloco-utils to package.json, yarn still asks me which version I would like to use. 

<img width="291" alt="Screenshot 2023-07-31 at 09 07 29" src="https://github.com/ngneat/transloco/assets/641791/613ce99e-914c-4675-98bc-2dc5069150a7">

<img width="868" alt="Screenshot 2023-07-31 at 09 07 05" src="https://github.com/ngneat/transloco/assets/641791/5f698a51-cf29-44db-805b-78c40f5ee217">

This happens when I try to replicate in sandbox:
<img width="1478" alt="Screenshot 2023-07-31 at 09 13 33" src="https://github.com/ngneat/transloco/assets/641791/8b86246b-e372-426a-a68b-5fd91b3eb0ef">

Comes up every time I run yarn:
```
warning Lockfile has incorrect entry for "@ngneat/transloco-utils@^4.0.0". Ignoring it.
Couldn't find any versions for "@ngneat/transloco-utils" that matches "^4.0.0"
? Please choose a version of "@ngneat/transloco-utils" from this list: (Use arrow keys)
❯ 5.0.0 

```

### Expected behavior

Running yarn should just download the new version of transloco.

### Please provide a link to a minimal reproduction of the bug, if you won't provide a link the issue won't be handled.

Unable to download 5.0.0 into sandbox to replicate

### Please provide the environment you discovered this bug in

```markdown
Transloco: 5.0.0
Angular: 16.1.7
Node: 18.16.x
Package Manager: Yarn
OS: Mac
```

### I would like to make a pull request for this bug

Yes

https://github.com/ngneat/transloco/pull/675

**Comment by shaharkazaz** [comment]
Thanks, Released in v 5.0.1
