### ISSUE TITLE
JetBrains WebStorm incompatibility

### ISSUE THREAD

**Issue by Newbie012** [ngneat/transloco#68]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

WebStorm doesn't know what type is `t` which results in IDE errors:

![869021a257e0cd476ff995c9c17cc55b](https://user-images.githubusercontent.com/10504365/64434494-571c7f00-d0c9-11e9-984c-fb01c7a3adeb.png)

![image](https://user-images.githubusercontent.com/10504365/64434527-656a9b00-d0c9-11e9-9bfb-a6bf57d2765f.png)

## Expected behavior

WebStorm should treat `t` as any object without showing these IDE warnings/errors.

## Minimal reproduction of the problem with instructions

1. Create an Angular app with transloco.
2. Write the code above.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.11.0
- Platform:  Windows
Others:

IDE: JetBrains Webstorm

</code></pre>

**Comment by itayod** [comment]
Hi @Newbie012,

Unfortunately, structural directives typing will only be supported after Ivy.
In the meantime, you can open this issue to Webstorm.
