### ISSUE TITLE
Feature(config): 'whitelist' for all strings that aren't translation keys.

### ISSUE THREAD

**Issue by marfrede** [ngneat/transloco#690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) will this feature affect?

Transloco

### Is your feature request related to a problem? Please describe

From an API we get some string properties which either can be
- an already translated label OR
- a transloco key.

The Frontend has to handle this. Right now our solution is to just pass every string to transloco. 

Unfortunately this leads to runtime errors (as long as `missingHandler.logMissingKeys: true`).
But turning `logMissingKeys` off is not a great solution for this.

### Describe the solution you'd like

This could be fixed if:
- instead of true/false for `logMissingKeys` a whitelist can be given 😍
- the whitelist will contain **all allowed strings** known that don't need to be translated / aren't transloco keys
- these whitelisted strings will **just wander through transloco** like they do already now, but **without any console warnings**

### Describe alternatives you've considered

- First alternative coming to mind is to disable `missingHandler.logMissingKeys` which has downsides for when a key is really just missing. 😕
- Second option would be to accept an console which is full of errors. This would lead to further problems in production mode though. 😕
- Third option would be to create a wrapper to all transloco functions and apply a whitelist ourselves. This would rip out transloc, inhibiting to use all the cool transloco features (using the directive, the service, etc.) 😕

### I would like to make a pull request for this feature

Yes 🚀

**Comment by shaharkazaz** [comment]
Why not provide a custom [missing handler](https://ngneat.github.io/transloco/docs/hack#missing-handler)?

**Comment by shaharkazaz** [comment]
@marfrede As far as I understand, you can resolve your issue using a custom missing handler.
You are welcome to reopen if this doesn't resolve your issue for some reason 👍
