### ISSUE TITLE
Bug(transloco-schematics): split schematic doesn't update subfolders

### ISSUE THREAD

**Issue by Zaroymi** [ngneat/transloco#695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Schematics

### Is this a regression?

No

### Current behavior

Root dictionary json 
```json
{
  "deal": {
     "someFIeld1": "string",
     "actions": {
        "action1": "string" 
     } 
  }
}
```

Out folder structure
/assets/i18n/
```
en.json
/deal
--> en.json
--> /actions
----> en.json
```

Command `ng generate @ngneat/transloco:split` updates only root en.json and deal/en.json, but doesn't update /deal/actions/en.json

### Expected behavior

It should update all subfolders

### Please provide a link to a minimal reproduction of the bug, if you won't provide a link the issue won't be handled.

https://codesandbox.io/p/sandbox/ngneat-transloco-forked-4snlch?welcome=true

### Please provide the environment you discovered this bug in

```markdown
Transloco: 4.2.2 / 5.0.6
Angular: 15.1.0 / 16
Node: 16 / 18
Package Manager: npm / yarn
OS:
```

### I would like to make a pull request for this bug

Yes 🚀
#696

**Comment by shaharkazaz** [comment]
Thanks! I'll take a look as soon as I get the chance 👍
