### ISSUE TITLE
FEATURE REQUEST: Support numbers in pipe attributes

### ISSUE THREAD

**Issue by bjornharvold** [ngneat/transloco#70]
## I'm submitting a...
<pre><code>
[X] Feature request
</code></pre>

ngx-translate support numbers when translating something like this:
`{{ 'alert' | transloco: { value: dynamic } }}`

This currently fails if I do an 'ng build' while passing it a number. transloco only accepts strings.

ERROR MESSAGE:
ERROR in ./src/app/subscription.component.html(144,104): Type 'number' is not assignable to type 'string'.

**Comment by NetanelBasal** [comment]
Can you share the error, please?

**Comment by bjornharvold** [comment]
Updated

**Comment by NetanelBasal** [comment]
Try the latest version.
