### ISSUE TITLE
Bug(migrate): some `ngx-translate` `translate` pipe usages are not recognized

### ISSUE THREAD

**Issue by hakimio** [ngneat/transloco#701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Transloco

### Is this a regression?

No

### Current behavior

Following syntax is not recognized by migrate script:
```html
<app-pdf-report
    [title]="'Google Ads ' + ('pdf-report.report' | translate)"
>
```

### Expected behavior

The syntax should be recognized and `| translate` should be replaced with `| transloco`.

### Please provide a link to a minimal reproduction of the bug, if you won't provide a link the issue won't be handled.

https://codesandbox.io/s/ngneat-transloco-kn52hs

### Please provide the environment you discovered this bug in

```markdown
Transloco: 5.0.7
Angular: 16
Node: 18
Package Manager: yarn v1
OS: Windows 10
```

### Additional context

There is also another minor debatable issue. The migrate script replaces `TranslateModule` with `TranslocoModule` even in case where just `TranslocoPipe` import would be a better choice.

### I would like to make a pull request for this bug

No

**Comment by shaharkazaz** [comment]
@hakimio You are welcome to open an improvement PR.
Regarding the import, this script was written before standalone was even a thing, so this is a nice optimization to have.

**Comment by hakimio** [comment]
@shaharkazaz I am trying to understand the following regex for `pipeInBinding`:
`\]=('|")\s*([^}\r\n]*?\|)\s*(translate)\s*(?::\s*{[^}\r\n]+})?\s*(\s*\|[\s\r\t\n]*\w*)*\s*\1`

- Why do you need to match `|` character second time once (after matching `translate`)? Shouldn't it be matched zero to unlimited times (`\|*` instead of `\|`)?

What do you think about the following regex:
`\]=('|")\s*([^}\r\n]*?\|)\s*(translate)\s*(?::\s*{[^}\r\n]+})?\s*(\s*\|*[\s\r\t\n\)]*\w*)*\s*\1`
Matches `[title]="'Google Ads ' + ('pdf-report.report' | translate)"`

diff: https://github.com/ngneat/transloco/assets/768105/4db573d7-0130-41f9-827a-7d056d6448ac

**Comment by hakimio** [comment]
If you want to have something like [pipe extractor](https://github.com/ngneat/transloco-keys-manager/blob/master/src/keys-builder/template/pipe.extractor.ts) that would add a lot of extra code and I don't really want to go that route. I am only willing to make a small PR.
If you are ok with keeping regex, I could add a test to make sure updated regex matches all the cases you wanted to cover with your original regex.
