### ISSUE TITLE
Feature(typing): Export TranslocoOptions type

### ISSUE THREAD

**Issue by scurk1415** [ngneat/transloco#709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) will this feature affect?

Transloco

### Is your feature request related to a problem? Please describe

I would like to have the TranslocoOptions in a separate file, to not clutter the providers/module. With the module approach its not such a big problem as you create a separate module which you import in the AppModule, but with standalone the config takes too much space in the app.config.ts file.

Something like this:

```typescript
export const appConfig: ApplicationConfig = {
  providers: [
    provideTransloco(importedConfigObject)
  ]
};
```

### Describe the solution you'd like

```typescript
export type TranslocoOptions = {
    config: PartialTranslocoConfig;
    loader?: Type<TranslocoLoader>;
};
```

### Describe alternatives you've considered

```markdown
I think the described solution is acceptable
```

### I would like to make a pull request for this feature

No

**Comment by greenjellygit** [comment]
@scurk1415 If you would like to be able to use the `TranslocoOptions` type, you can get it using TypeScript based on the parameters of the `provideTransloco` method.

```
type TranslocoOptions = Parameters<typeof provideTransloco>[0]

const myConfig: TranslocoOptions = {
   config: {},
   loader: TranslocoHttpLoader
}
```

**Comment by shaharkazaz** [comment]
I'll export the options, but @greenjellygit's solution is a valid and clean one, you can use it.
