### ISSUE TITLE
Bug(scope): Can not acccess view child of element wrapped inside transloco directive

### ISSUE THREAD

**Issue by laradvil** [ngneat/transloco#721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Transloco

### Is this a regression?

Yes

### Current behavior

```html
    <div *transloco="let t; read: 'navbar.menu'">
      <a
        #serviceBtnView
        id="testBtn"
        routerLink="/services"
        routerLinkActive="text-primary-500 font-semibold">
        XX
        <i class="material-icons">
          {{ !serviceMenuOpened() ? "expand_more": "expand_less" }}
        </i>
      </a>
    </div>
```

```typescript
@ViewChild('serviceBtnView', { static: true })
serviceBtn?: ElementRef<HTMLElement>;

ngAfterViewInit(): void {
  console.log(serviceBtn?.nativeElement); // undefined
  console.warn(document.querySelector("#testBtn") // undefined
}

```

### Expected behavior

- should not be undefined
- If I was wrong, then how to access that element ?

After I remove transloco directive, it works just fine, all logs not undefined.

```html
    <div>
      <a
        #serviceBtnView
        id="testBtn"
        routerLink="/services"
        routerLinkActive="text-primary-500 font-semibold">
        XX
        <i class="material-icons">
          {{ !serviceMenuOpened() ? "expand_more": "expand_less" }}
        </i>
      </a>
    </div>
```

```html
    <ng-container>
      <a
        #serviceBtnView
        id="testBtn"
        routerLink="/services"
        routerLinkActive="text-primary-500 font-semibold">
        XX
        <i class="material-icons">
          {{ !serviceMenuOpened() ? "expand_more": "expand_less" }}
        </i>
      </a>
    </ng-container>
```

Both of these above works just fine

### Please provide a link to a minimal reproduction of the bug, if you won't provide a link the issue won't be handled.

https://codesandbox.io/s/ngneat-transloco-forked-tk4nhg?file=/src/app/lazy-scope-alias/lazy-scope-alias.component.ts

### Please provide the environment you discovered this bug in

```markdown
Transloco: 
Angular: 
Node: 
Package Manager: 
OS:
```

### Browser

```markdown
Chrome
```

### I would like to make a pull request for this bug

Yes 🚀

**Comment by mackelito** [comment]
I have the exact same problem.. If I move "<ng-container *transloco="let t">" to not wrap the element then it works..

**Comment by shaharkazaz** [comment]
Read the [FAQ](https://ngneat.github.io/transloco/docs/faq#why-does-querying-an-element-inside-the-transloco-directive-using-viewchild-not-working) section in the docs.

Next time try to search the docs before opening an issue, here is the result of searching "viewChild":
<img width="691" alt="image" src="https://github.com/ngneat/transloco/assets/17194830/26daaa33-03d1-4be8-a5a9-8a7c771e75e8">
