### ISSUE TITLE
Docs for unit tests, broken links

### ISSUE THREAD

**Issue by mackelito** [ngneat/transloco#730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) will this feature affect?

Transloco

### Is your feature request related to a problem? Please describe

https://ngneat.github.io/transloco/docs/unit-testing
The example's links to files that does no longer exists..

Eg:
https://github.com/ngneat/transloco/blob/master/apps/transloco-playground/src/app/on-push/on-push.component.spec.ts

### Describe alternatives you've considered

```markdown
link broken
```

### I would like to make a pull request for this feature

Yes 🚀

**Comment by shaharkazaz** [comment]
Thanks, you are welcome to open a PR 👍

**Comment by mackelito** [comment]
I guess the spec files has been removed for a reson?

**Comment by shaharkazaz** [comment]
I honestly don't remember, maybe a location change. I'd check git 🙂
