### ISSUE TITLE
Transloco has a problem loading json files when requests are passed through an HttpInterceptor

### ISSUE THREAD

**Issue by omarAjmi** [ngneat/transloco#74]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

i have transloco working perfectly, but when adding an HttpInterceptor, and explicitly passing through transloco requests, it returns a this error:

![image](https://user-images.githubusercontent.com/25843962/64635143-489ed200-d3ff-11e9-8e52-888edff444c2.png)

## Expected behavior

i want my interceptor to ignore the transloco request, which it does but something is going wrong.
here is a snapshot of the interceptor ignoring the transloco requests:

![Capture](https://user-images.githubusercontent.com/25843962/64635385-d7abea00-d3ff-11e9-923f-e4ff208faf09.PNG)

## transloco configurations:
loader: http
files: JSON
location: /assets/i18n/*

## Minimal reproduction of the problem with instructions

nothing special really, it works fine, but it has a problem with interceptors, am i doing something wrong?!

## Environment

<pre><code>
Angular version: 8.0.1

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by NetanelBasal** [comment]
You missed the return.

**Comment by omarAjmi** [comment]
yep just figured it out, silly me!!! thanks anyway
