### ISSUE TITLE
Config option to disable console logging

### ISSUE THREAD

**Issue by blackmjck** [ngneat/transloco#75]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Things like preload success/fail, missing translation handler calls, etc. all trigger console output when run.

## Expected behavior

It would be awesome if a config option existed to disable console output, particularly when in a testing scenario, to avoid clogging the log output.

It might also help avoid errors like `11 09 2019 11:54:48.476:ERROR [karma-server]: Error: Invalid character (�) in string: HeadlessChrome 0.0.0 (Mac OS X 10.14.6) LOG: '%c 🍻 Translation Load Success: en', 'background: #fff; color: hotpink;'`, which would be a bonus. :-)

**Comment by NetanelBasal** [comment]
Set `config.prodMode` to `true`.

**Comment by NetanelBasal** [comment]
I will make it the default for `TranslocoTestingModule` in the next release.

**Comment by NetanelBasal** [comment]
Released v1.7.7 with this change.
