### ISSUE TITLE
Bug(scope): Scoping doesn't work in routes loaded with loadChildren

### ISSUE THREAD

**Issue by CitrusyAlmond** [ngneat/transloco#776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Transloco

### Is this a regression?

Yes

### Current behavior

The function provideTranslocoScope only applies the scopes assigned to the parent element. It doesn't seem to work either in the lazy loaded route file nor the child component's Type Decorator.

This is a screenshot of the main routes file.
![image](https://github.com/jsverse/transloco/assets/173900104/9f18deca-8e28-4cbd-bddd-06a3eaec3dfd)

This is a screenshot of the child routes file.
![image](https://github.com/jsverse/transloco/assets/173900104/74b018b5-a240-42b8-9f2b-9c0186605523)

When using this._transloco.getTranslation(), it only shows the translations from the language.json file as well as those from the scope assigned in the parent element.

![image](https://github.com/jsverse/transloco/assets/173900104/a2274105-9819-42c6-ad78-09d3902aeae9)

### Expected behavior

The function provideTranslocoScope to not also apply the scopes assigned to it in the main routes file, but also those imported using the loadChildren function.

### Please provide a link to a minimal reproduction of the bug, if you won't provide a link the issue won't be handled.

https://codesandbox.io/s/tmt5zn

### Please provide the environment you discovered this bug in

```markdown
Transloco: 
Angular: 
Node: 
Package Manager: 
OS:
```

### I would like to make a pull request for this bug

No

**Comment by shaharkazaz** [comment]
The issue with your reproduction is that you are not triggering a load for the `lazy` translation set.
When you use the transloco pipe in the main template, he triggers a load for the scoped translation. that's why we see that the translations for main are loading while the lazy ones are missing.

**Comment by CitrusyAlmond** [comment]
You are absolutely right, the use of the transloco pipe was dowloading the translation file, which could be read by the child component.

That said, after removing the template translation I find myself unable to use the provided scope without directly referencing it in the selectTranslate function, most likely due to a lack of understanding of the explanations given.

With a routes file such as this.
![image](https://github.com/jsverse/transloco/assets/173900104/645c48fc-927f-46a8-860f-fd7afff7b3d9)

I encounter myself in this situation.
![image](https://github.com/jsverse/transloco/assets/173900104/cd112efe-fa28-48a6-9d71-1859edaf6f9e)

I apologize if my question might seem stupid, but I'm failing to come up with the solution to the issue.
