### ISSUE TITLE
Get translation asynchronously

### ISSUE THREAD

**Issue by Newbie012** [ngneat/transloco#78]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ X ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When I inject TranslocoService in my service and then immediately want to fetch the results (i.e, fetch in the constructor) I get empty results. I guess it happens because of the translation is yet to be ready.

So it leaves me with two alternatives:

1. Preload the translation (which isn't a viable solution for every app).
2. Delay the request for translation (but you can't know exactly when it'll be ready).

## Expected behavior

I suggest that Transloco should have a method that indicates if the translation is read, or to make a method that gets the translation as a promise (resolved when the translation is ready).

In `ngx-translate` I simply used `this.translate.get` for async.

## Minimal reproduction of the problem with instructions

1. Create a new angular app
2. Add Transloco
3. Try to translate inside a service constructor.

## What is the motivation / use case for changing the behavior?

Using the translation outside of the view after a service has been initialized.

## Environment

<pre><code>
Angular version: 8.2.5

Browser:
- [X] Chrome (desktop) version 74
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by itayod** [comment]
Hi @Newbie012, 
Did you try to use the `select` method?
```ts
// Translate specific key
this.service.selectTranslate('hello').subscribe(value => ...);
// Load and returns the provided language
this.service.selectTranslation('es').subscribe(translation => ...);
```

**Comment by Newbie012** [comment]
Actually yes. Much better now =)
