### ISSUE TITLE
Issue on ng add => Unexpected token } in JSON

### ISSUE THREAD

**Issue by mickz18** [ngneat/transloco#80]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

ng add @ngneat/transloco --verbose
Skipping installation: Package already installed
? 🌍 Which languages do you need? en, es
? 🚀 Are you working with server side rendering? No
Unexpected token } in JSON at position 1033

## Expected behavior
working 

## Environment

<pre><code>
Angular CLI: 8.3.4
Node: 11.15.0
OS: linux x64
Angular: 8.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.4
@angular-devkit/build-angular     0.803.4
@angular-devkit/build-optimizer   0.803.4
@angular-devkit/build-webpack     0.803.4
@angular-devkit/core              7.3.7
@angular-devkit/schematics        7.3.7
@angular/cdk                      8.2.0
@angular/cli                      8.3.4
@angular/flex-layout              8.0.0-beta.26
@angular/material                 8.2.0
@ngtools/webpack                  8.3.4
@schematics/angular               8.3.4
@schematics/update                0.803.4
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2

@ngx-translate/core": "^11.0.1"

</code></pre>

This must be because of my code base, have you any clue how I can found the file causing the issue or A way to investigate more ? Thanks

**Comment by itayod** [comment]
@mickz18 could you send me a repo with a reproduction of the issue?

**Comment by NetanelBasal** [comment]
Check your `angular.json` file. My guess is that you have an invalid comma.

**Comment by mickz18** [comment]
Thanks a lot, indeed error in angular.json was loking for line number and not postion.

**Comment by ahaneef29** [comment]
@hmica & @NetanelBasal Thanks a lot.
