### ISSUE TITLE
Add angular-l10n to comparison table

### ISSUE THREAD

**Issue by IlCallo** [ngneat/transloco#81]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

There is a beautiful comparison table, but `angular-l10n` is missing.
`angular-l10n` was probably the best i18n library for Angular before Transloco, so a comparison with it would be really interesting.
I see someone already asked for it into #13 

## Expected behavior

Add `angular-l10n` to the table.

## What is the motivation / use case for changing the behavior?

Clarity, documentation, help devs to choose what fits them best.

**Comment by NetanelBasal** [comment]
I updated the [table](
https://github.com/ngneat/transloco/#comparison-to-other-libraries). Let me know if there are any mistakes, and I will update. Thanks.

**Comment by IlCallo** [comment]
Perfect, thank you!
There are some things wrong:
- `listenToLangChange`: `angular-l10n` provide `LocaleService` to listen and react to locale changes
-  `Multiple Languages Simultaneously`: pretty much every goodies of `angular-l10n` accept an optional `lang` to use instead of the default one. I'm just not sure about directives :thinking:
- `Hackable`: while not hackable as `transloco`, `angular-l10n` allow to hack some pieces of its configuration as needed (missing value management, storage strategy, custom translation provider, etc)
- `Ivy support`: actually it supports Ivy, it doesn't support it only when using in combination with AOT (does Transloco work with AOT? It's not specified anywhere), but that's an [Angular core problem](https://github.com/angular/angular/issues/31495)
- `Additional Functionality`: `angular-l10n` have a ton of additional features, for example SEO optimization, translations lazy loading, locale detection via Accept-Language header, value validation locale-based, etc etc. You can probably pot some of those into `transloco`

I think there's more, but this is what I know from personal usage and docs reading

**Comment by NetanelBasal** [comment]
Hi, couple of notes:

- `listenToLangChange` - Read in the [docs](https://github.com/ngneat/transloco/#config-options) what it means, please.
- `Multiple Languages Simultaneously` - and you can use it in the template?
- `Hackable` - not the same, but I will think of something
- `Ivy support` - "it doesn't support it only when using in combination with AOT", so it doesn't support Ivy. Everyone uses AOT.
- `Additional Functionality` - I will remove it from the table as it's too general.

**Comment by NetanelBasal** [comment]
@IlCallo you're welcome to submit a PR for any additional functionality you want.

**Comment by IlCallo** [comment]
* `listenToLangChange` - I read it, but maybe I'm missing something... Aren't we talking of reacting to language changes and the ability of changing that language at runtime? Because `angular-l10n` allow both of those things. [It exposes](https://robisim74.github.io/angular-l10n/spec/api/#ilocaleservice) a Subject which emits every time language changes and a method to change it programmatically.
* `Multiple Languages Simultaneously` - Yes, all [pipes](https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#pure-pipes) have a `lang` parameter. Cannot remember if it works with the directive too or not, on docs is not specified.
* `Hackable` - of course you are much more advanced on this point, maybe an half check mark will do? :P  
* `Ivy support` - well, it doesn't support it _when using decorators_, so it actually supports Ivy except that use case. You don't support getting current language via decorator, so saying that Ivy isn't supported on that project because it isn't supported when using a feature you don't have doesn't seem really fair to me. Also, in a year and half of usage of that package I *never* had to use decorators: pipes, directives and services are just much more used. So maybe it can be a check mark with a side note?

**Comment by NetanelBasal** [comment]
- You should reread it. Anyway, this bullet is confusing. I removed it.
- Tell me what I'm missing because it doesn't seem to [work](https://stackblitz.com/edit/angular-l10n-7yy2by):
```html
<h3>{{ 'changeCountry' | translate: 'en' }}</h3>
<h3>{{ 'changeCountry' | translate: 'it' }}</h3>
```
- Added partially support.
- It's all over the docs, so I guessed this is the main use-case. I will update the table.

> You don't support getting current language via a decorator
We don't need to support it. It's work out of the box in Transloco without this boilerplate code.

**Comment by IlCallo** [comment]
* `listenToLangChange` - Ok, I got it now, you meant the optimization due to unsubscribing. I understood it while you were writing and edited previous comment at the same time you add the new comment.
* `Multiple Languages Simultaneously` - I was pretty sure I used it somewhere (I don't have access to that codebase anymore) but I guess I was wrong, sorry :sweat: 
* `Ivy support` - I think you updated the wrong bullet in the README (`Pipe` works with AOT, it's `Pipe` + `AOT` + `Ivy` which doesn't)

> We don't need to support it. It's work out of the box in Transloco without this boilerplate code.

Not wanna pick a fight here, and you are right about the "works out of the box" thing, but the boilerplate in `angular-l10n` is needed to keep the pipe pure, while you decided to go by the inpure pipe road.

Not saying it's wrong but it degrades performance, so you probably should add a disclaimer on the documentation.
`angular-l10n` used impure pipes too, then [decided](https://github.com/robisim74/angular-l10n/issues/33) to move to pure pipes and add the boilerplate, to avoid performance issues.

But maybe you found a way to avoid impure pipe performance degradation or you already studied the problem and noticed the performance impact isn't so high even with a lot of pipes used around, in that case sorry to bother :)

**Comment by NetanelBasal** [comment]
Our solution is a structural directive.

**Comment by NetanelBasal** [comment]
I will stop this discussion here. It becomes to be a discussion of who's better, and I don't like it. It's your decision whether to use `angular-l10n` or any other solution. We appreciate every library and think that's good.

If there are more mistakes in the table, I will update. Thanks.

**Comment by IlCallo** [comment]
I think I couldn't explain myself good enough: mine where just suggestions plus some context, not attacks to the library or saying which one is best (in my opinion, `transloco` is the best right now).

Anyway, the table is now correct, original issue is solved: keep on the great work! :)

**Comment by rala72** [comment]
Is it possible to add the current comparison table again somewhere?
I saw a link for the table in the last comment of #13, but I think it might not be up-to-date.
