### ISSUE TITLE
The pipe 'translocoDate' could not be found

### ISSUE THREAD

**Issue by philjones88** [ngneat/transloco#83]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I've setup transloco-locale as per the instructions along side my existing transloco logic as per https://github.com/ngneat/transloco/tree/master/projects/ngneat/transloco-locale

But when I swap the `date` Angular pipe to `translocoDate` I get:

```
ERROR Error: Uncaught (in promise): Error: Template parse errors:
The pipe 'translocoDate' could not be found ("mp.name }}</h5>
                    <small>{{ 'manage.download-logs.dumps.created' | transloco }}{{ [ERROR ->]dump.dateCreated | translocoDate : { dateStyle: 'medium' } }} Size: {{ dump.size }}</small>
         "): ng:///ManageModule/LogsComponent.html@72:84
```

This is inside a lazy loaded module.

If I add this to my app component html it works perfectly and I can see it be awesome and swap the date formatting when going between US/GB!

`{{ now | translocoDate: { dateStyle: 'long' } }}`

## Expected behavior

Should work in lazy loaded modules

## Minimal reproduction of the problem with instructions

See above

## Environment

<pre><code>
Angular version: 8.0.3
Transloco: 1.7.9
Transloco-locale: 1.0.0
Transloco-persist-lang: 1.0.1

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.16.3
- Platform:  MacOS

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
You need to import `TranslocoLocaleModule` in each module you're using it.

**Comment by philjones88** [comment]
@NetanelBasal 	thanks, just wondering why I haven't had to do that with the main `TranslocoModule` ?

**Comment by NetanelBasal** [comment]
You need to. This is Angular requirements.

**Comment by philjones88** [comment]
Not quite sure how I had it working without importing `TranslocoModule` into my lazy loaded children modules but... this isn't a real issue. Closing.
