### ISSUE TITLE
Allow fallback language for missing values

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/transloco#84]
Example: If I use Spanish, and one of the keys is missing, I want to display the English version of it.

**Comment by Edouardbozon** [comment]
@NetanelBasal I would be happy to pick this.

**Comment by NetanelBasal** [comment]
Go ahead 😀.

**Comment by Edouardbozon** [comment]
@NetanelBasal In your point of view is it better to add this behavior directly in the `translate` method of `TranslocoService` or delegate this to the `MissingTranslationHandler` ?

**Comment by NetanelBasal** [comment]
@Edouardbozon what's the status of the issue?

**Comment by Edouardbozon** [comment]
@NetanelBasal I have something working, I have to add tests now. I will push it soon to get feedback.
