### ISSUE TITLE
[QUESTION] ngx-translate addLangs equivalent

### ISSUE THREAD

**Issue by dertuerke** [ngneat/transloco#85]
Hi,
what is the equivalent for the ngx-translate `addLangs`?
Or how i can add it?

**Comment by shaharkazaz** [comment]
@dertuerke Hi!
Currently, we don't have an equivalent, but we have no problem adding one.
Can you please explain what is the use case? 🙂

**Comment by shaharkazaz** [comment]
@dertuerke Feel free to continue this

**Comment by dertuerke** [comment]
@shaharkazaz Hi, we are currently considering whether we need this function at all. So the ticket could be closed for now. If we have decided and still need the function, I would write it in the ticket.

**Comment by shaharkazaz** [comment]
@dertuerke cool, closing 🙂

**Comment by AyushiSingh14399** [comment]
> Hi, what is the equivalent for the ngx-translate `addLangs`? Or how i can add it?

did you find it?

**Comment by shaharkazaz** [comment]
@AyushiSingh14399 Can you please explain what is the use case? 🙂
