### ISSUE TITLE
Transloco Message Format Plugin documentation bug

### ISSUE THREAD

**Issue by PeterHewat** [ngneat/transloco#88]
## I'm submitting a documentation bug

If you follow the documentation to add the messageformat plugin here:
https://github.com/ngneat/transloco/tree/master/projects/ngneat/transloco-messageformat
You get an error stating that TranslocoMessageFormatModule can not be found inside @ngneat/transloco-messageformat

If you follow the documentation here:
https://www.npmjs.com/package/@ngneat/transloco-messageformat
Everything works fine.

**Comment by itayod** [comment]
The documentation from the github, is for a future version that still not have been published yet.

Please stick with this documentation for now:
with https://www.npmjs.com/package/@ngneat/transloco-messageformat

We will release a new version this Sunday :)

**Comment by PeterHewat** [comment]
Excellent, thank you. Closing this issue.

**Comment by PeterHewat** [comment]
Hello again,
I updated @ngneat/transloco-messageformat from 1.0.0 to 1.1.0 and tried setting it up the new way (using TranslocoMessageFormatModule.init()) but I get the following error:
Property 'init' does not exist on type 'typeof MessageFormatTranspiler'.ts(2339)

**Comment by itayod** [comment]
Hi @PeterHewat I can't reproduce this error, I think it might be cache...

Could you try deleting you `node_modules` folder and reinstall?

If it keeps happening, could you please create stackblitz reproduction?

**Comment by PeterHewat** [comment]
Hi @itayod,
I'm sorry, false alarm... I started over making sure to follow the documentation and everything works fine. 
https://stackblitz.com/edit/angular-mjlabx?file=src%2Fapp%2Fapp.module.ts
Closing the issue again ;-)
