### ISSUE TITLE
[QUESTION] Library-Monorepo problem

### ISSUE THREAD

**Issue by mailok** [ngneat/transloco#9]
Thank you very much for this project, it is very good.

I have a question, how could I use Transloco in a library, and use that library in an application that also uses Transoloco?

This library can be lazy loaded or it can be loaded normally. I wish it could work for both cases.
Of course, this use case is a common when you use Monorepo in your company.

**Comment by shaharkazaz** [comment]
Hey, 

let's discuss this in our [gitter channel](https://gitter.im/ngneat-transloco/lobby#).
