### ISSUE TITLE
Can't get ElementRef when parent has *transloco directive

### ISSUE THREAD

**Issue by Newbie012** [ngneat/transloco#92]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Given the following template:

```
<section id="about" *transloco="let t; read: 'about'">
  <div class="container">
    <mat-card class="mat-elevation-z12" #card></mat-card>
  </div>
</section>
```

I can't access `#card`:

```
@ViewChild('card', { static: false }) card: ElementRef;
```

logging `this.card` in `ngAfterViewInit` will result in undefined.

## Expected behavior

`@ViewChild` should find the desired component.

## Minimal reproduction of the problem with instructions

1. `ng new`
2. install transloco
3. `ng g c about`
4. paste the following component:

```
import { AfterViewInit, Component, ElementRef, ViewChild } from '@angular/core';

@Component({
  selector: 'app-about',
  template: `
    <div #test></div>
    <section id="about" *transloco="let t; read: 'about'">
      <div class="container">
        <div class="mat-elevation-z12" #card></div>
      </div>
    </section>
  `,
})
export class AboutComponent implements AfterViewInit {

  @ViewChild('card', { static: false }) card: ElementRef;
  @ViewChild('test', { static: false }) test: ElementRef;

  ngAfterViewInit(): void {
    console.log('test', this.test, 'works');
    console.log('card', this.card, 'doesn\'t work');
  }

}

```

## Environment

<pre><code>
Angular version: 8.2.5

Browser:
- [X] Chrome (desktop) version 74
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.11  
- Platform:  win32 x64

Others:

</code></pre>

**Comment by shaharkazaz** [comment]
@Newbie012 This is not a bug.
You are using the structural directive, which in the first time initializes after the translation loading is done, this is why your view init before the directive does.
you have 3 ways to resolve this:
1. Use the pipe or directive.
2. Add a setter to the `ViewChild` so you will know when did the structural directive load.
3. listen to `translationLoadSuccess ` event and then you know that the card element is available to use.

**Comment by harishajdarevic** [comment]
@shaharkazaz ViewChild setter doesn't work.
