### ISSUE TITLE
Feature request: component level scope alias

### ISSUE THREAD

**Issue by zufarzhan** [ngneat/transloco#97]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently in order to specify alias for component scope translations you have to do it in main APP module's TRANSLOCO_CONFIG object. This means that every time you add or remove component with it's own scope, you have to keep in mind that you have to update another file, which has nothing to do with component itself.

## Expected behavior

What I propose, is to be able to define scope alias on component level. We think it will make the whole process much easier and will avoid repetitions in the code.

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, for that you could use our [stackblitz example](https://stackblitz.com/edit/transloco-example)

## What is the motivation / use case for changing the behavior?

Right now we keep translation files in the same folder with components, each component has its own translation files - to keep components as self contained as possible. So it would be much easier to specify scope alias within component itself rather than going to APP module every time you create/remove a component.

And in general we think it will be much easier, not only in our case.

I've implemented the test version of this feature which is backwards compatible.
Please have a look at: https://github.com/zufarzhan/transloco/tree/feat/scope-alias

Let me know what you think about this feature, and maybe I should finish it and make a PR?

P.S. Another thing I noticed: when you specify scope on module level, then specify scope on component level which is part of the module, you get error if you try using translations from module scope level. So maybe it's better to mention it in the doc or maybe handle it somehow in the code?

## Environment

<pre><code>
Angular version: 7.2.0

Browser:
- [x] Chrome (desktop) version 76
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.16.1  
- Platform:  MacOS 10.14.6 

Others:

</code></pre>

**Comment by shaharkazaz** [comment]
@zufarzhan Would you like to open a PR for it?

**Comment by zufarzhan** [comment]
@shaharkazaz sure, will do it a bit later :)

**Comment by shaharkazaz** [comment]
Added in #100 published in v2.1.0, @zufarzhan thanks 🎉

**Comment by dereklin** [comment]
@zufarzhan I am new to transloco.  I saw your notes that "... [you] keep translation files in the same folder with components".  I want to do the same.  I haven't found any examples on this.  I read through the docs and I saw your stackbliz example.  I don't see where a i18n folder is inside a component folder.  Do you have any examples you can share to show how this is done?

**Comment by zufarzhan** [comment]
@dereklin the way we stored translation files was not connected specifically to Transloco. You can use such method with any translation library. We just stored lang json files in each component folder, and then moved them to "translations" folder of the library using webpack. You can check it [here.](https://github.com/ngneat/transloco/issues/121#issuecomment-540476147)

**Comment by dereklin** [comment]
@zufarzhan I see.  Thanks for sharing!
