### ISSUE TITLE
Xliff format support.

### ISSUE THREAD

**Issue by uxohotteixo** [ngneat/transloco#99]
It is possible to install xliff format translation files in the transloco or convert current translations to transloco json format?

**Comment by itayod** [comment]
Hi @uxohotteixo 
It could simply be done by creating a loader that loads the xliff format and convert it to json:

```ts
   return this.http.get<Translation>(`/assets/i18n/${langPath}.xliff`).pipe(map(xliff => {
      return xliff2js(xliff);
    }))
```

This is a repository that you could use to achieve that:
https://github.com/locize/xliff

**Comment by NetanelBasal** [comment]
Here's a complete working example:

```ts
import { HttpClient } from '@angular/common/http';
import { Translation, TRANSLOCO_LOADER, TranslocoLoader } from '@ngneat/transloco';
import { Injectable } from '@angular/core';
import { environment } from '../environments/environment';
import xliff from "xliff/xliff12ToJs";
import { map } from 'rxjs/operators';

@Injectable({ providedIn: 'root' })
export class HttpLoader implements TranslocoLoader {
  constructor(private http: HttpClient) { }

  getTranslation(langPath: string) {
    return this.http.get(`/assets/i18n/${langPath}.xlf`, { responseType: 'text' as 'text' }).pipe(
      map((translation) => {
        const toJSON = xliff(translation);
        return toTranslationFormat(toJSON);
      }));
  }
}

function toTranslationFormat(json) {
  const obj = json.resources.transloco;
  return Object.keys(obj).reduce((acc, key) => {
    acc[key] = obj[key].target;
    return acc;
  }, {});
}

export const translocoLoader = { provide: TRANSLOCO_LOADER, useClass: HttpLoader };
```

The translation files:
```xlf
<?xml version="1.0" encoding="UTF-8" ?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="en" datatype="plaintext" original="transloco">
    <body>
      <trans-unit id="title">
        <source>Hello Transloco!</source>
        <target>Bonjour Transloco!</target>
      </trans-unit>
    </body>
  </file>
</xliff>
```

**Comment by eluchsinger** [comment]
@NetanelBasal this approach seems to not be working anymore. Could you please give us an updated version?

**Comment by shaharkazaz** [comment]
@eluchsinger can you please share what's not working? 
Everything is completely customizable, make the changes needed to make your code work 🙂

**Comment by eluchsinger** [comment]
@shaharkazaz it's kind of difficult to say what's not working because the example does not really contain a lot of information 😊. Maybe, I can explain it better on gitter, if you're there. 

Basically it starts with finding out what library was used for the example, then guessing what version of that library it was, because it looks like `xliff(translation);` is asynchronous (and I can't even import it like in this example).

I've got it to extract the id's now, but I still get a `Missing translation for ...` error in the console.

**Comment by shaharkazaz** [comment]
@eluchsinger sounds like some adjustments are needed to the example code posted by Netanel.
This isn't related to Transloco and There is already a good reference here for implementing this loader.
Would be great if you share the result here once done so others might stumble upon it, we might even add it as a recipe 🙂

**Comment by bleful** [comment]
@eluchsinger Did you solve the problem and could you share the solution with us?

**Comment by eluchsinger** [comment]
@bleful sorry, I decided to use a different library.

**Comment by konrado** [comment]
@bleful this works for me (xliff 2.0):
```
import xliff2js from 'xliff/esm/xliff2js';
import { from } from 'rxjs';
import { map, switchMap } from 'rxjs/operators';
...
return this.http.get(`/assets/i18n/${lang}.xliff`, { responseType: 'text' as 'text' }).pipe(
    switchMap(translation => from(xliff2js(translation))),
    map(json => this.toTranslationFormat(json))
);
```

**Comment by shaharkazaz** [comment]
I updated the recipe 👍
